### ISSUE TITLE
Leading spaces should be trimmed

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#10]
Additionally, the full_syn widget is not trimming off the leading spaces. Screenshot attached (leading space in top synonym.PNG).

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
I don't see this attachment leading space in top synonym.PNG. 
Can you please provide the screen shot so I can validate the fix? 
Thanks,
Reza

**Comment by bdionne** [comment]
sorry I don't have it. I must have put in the wrong url.

The description is clear I think, leading spaces need to be trimmed when editing.

**Comment by rmehri** [comment]
Based on the fix description, this fix has been retested good.  Please see attached screen shot for more detail. 
Thanks,
Reza
![leading space](https://cloud.githubusercontent.com/assets/8367102/21113170/83ab1902-c076-11e6-875c-1d1615d32ea1.png)
