### ISSUE TITLE
Protege Tag-107- ReportWriter- Mismatch Count on Total Generated Report  

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#101]
Steps to reproduce:

1) Log in to server 
2) Connect to "ncit-owl2-v3" project.
3) Select the class "Organ" 
4) Select ReportWriter tab and start the report
5)You'll see the generated report indicates 296 out 301 completed.
Please see attach snapshot for more details. 

Thanks,
Reza
![protege tag 107-reportwriter](https://cloud.githubusercontent.com/assets/8367102/20821439/747ef430-b810-11e6-8e5b-49f521d06e9d.png)

**Comment by bdionne** [comment]
nice catch, sometimes a class has multiple parents, the report writer was counting wrong. This is [fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.1.3) in the newest edittab plugin so if you check plugins and update you can verify the fix

**Comment by rmehri** [comment]
This fix has been successfully retested. Used updated Tag-107 "nci-edit-tab-0.1.3-SNAPSHOT.jar"  
This ticket can be closed. See attached snapshot for more detail.
Thanks,
Reza
![reportwriter_tag107_fixed](https://cloud.githubusercontent.com/assets/8367102/20899820/ff5f5d10-baf9-11e6-92bd-96201e2df9af.png)
