### ISSUE TITLE
Protege5-Tag 107-Clone- A Class with the Same Name Saves as Duplicate

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#102]
Steps to reproduce:
1) Log in to server
2) Connect to "ncit-owl2-v3" project.
3) Select a protein family class
4) Select Clone and "create a new class" popup displays
5) Enter the same class name and you'll see the warning message that says the entity is already exists  
6) Ignore and press OK then you can save it.
Please see attach snapshost for more details.
Thanks,
Reza

![class-duplicate-1](https://cloud.githubusercontent.com/assets/8367102/20839396/70a21116-b87a-11e6-8934-4b802169b6b2.png)
![class-duplicate-2](https://cloud.githubusercontent.com/assets/8367102/20839402/73f5eebe-b87a-11e6-8afc-81a95f7f3ee4.png)

**Comment by bdionne** [comment]
This is not a bug, the `Preferred Name` is not necessarily unique. It's discouraged but allowed. I don't think it happens too often but it's the reason we always use the `IRI` to identify a class.

**Comment by NCIEVS** [comment]
I've copied the documentation page from the [NCI wiki](https://wiki.nci.nih.gov/display/Protege/NCI+Extensions+to+Protege) (compiled for Protege 3.x) to the github [wiki](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege) for nci-protege5.  

We can update the nci-protege 5 documentation page as we go along.

Will add a documentation label and close.
