### ISSUE TITLE
Protege5-Tag 107-Lucene Search- Query Type 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#103]
Hi,
Some search properties do not have the latest query types. 
As an example: 
1.	Property= “Definition Reviewer Name”
2.	Query Types= “Starts with -token”, “ends with”, “exact match-token”
3.	Missing query type for step 1: “exact match-string”   
I am wondering if the latest query types should apply to all or most properties or selective ones.
Can you please elaborate more on details so QA can validate them? Please see attached snapshot for more details.

Thanks,
Reza

![query types](https://cloud.githubusercontent.com/assets/8367102/20852696/25df973a-b8b5-11e6-8d6b-2fb6c1737922.png)

**Comment by bdionne** [comment]
correct, these query types are only used when searching for classes using `rdfs:label`

**Comment by NCIEVS** [comment]
a wiki [page](https://github.com/NCIEVS/nci-protege5/wiki/properties-searched-by-the-various-query-types) has been created to document the fields.  Will label as documentation and close.
