### ISSUE TITLE
read-only and read-write access per tab by role

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#105]
Will create a wiki page with the information.

**Comment by NCIEVS** [comment]
@bdionne, when you have a chance, can you take a peek at the wiki [page](https://github.com/NCIEVS/nci-protege5/wiki/editability-of-tabs-per-role)?  I think I got all of them, but we probably want to touch base.

**Comment by bdionne** [comment]
look reasonable, not sure how useful individuals is, maybe we should leave that out completely.

I think we also should leave out classes, it's already included in the Entities tab and it just adds more confusion as it's close to EditTab.

We need to be careful as the protege editing semantics is much different from NCI's approach

**Comment by bdionne** [comment]
We also need to figure out how to convey [this information](https://github.com/NCIEVS/nci-protege5/wiki/editability-of-tabs-per-role) at login time, perhaps adding to the server configuration?

**Comment by bdionne** [comment]
this is now implemented in [nci-0.111](https://github.com/NCIEVS/nci-protege5/releases), with the exception of support for guest

**Comment by rmehri** [comment]
Hi Bob,
I have retested this issue using tag-116.  I compared the current application tabs roles against the "edit ability of tabs per role" document, and noticed the following discrepancies:  


Expected:  Workflow-Modeler (In document)

1)	Active Ontology => “R” 
2)	Classes => tbd
3)	Data Properties => tbd
4)	Individuals by => “R”

Expected:  Workflow-Manager (In document)

1)	Classes => tbd
2)	Data Properties => tbd
3)	Individuals by => “RW”
****************************************************
Actual:  Workflow-Modeler (In application)

1)	Active Ontology => “RW” 
2)	Classes => “Greyed out”
3)	Data Properties => “Greyed out”
4)	Individuals by => “R”

Actual:  Workflow-Manager (In application)

1)	Classes => “Greyed out”
2)	Data Properties => “Greyed out”
3)	Individuals by => “Greyed out”

Please see attached screen shot for more details. 

![user roles](https://cloud.githubusercontent.com/assets/8367102/21910245/26d6876c-d8e9-11e6-9de9-8268a44bc11e.png)

Thanks,
Reza

**Comment by bdionne** [comment]
That WIKI page is a bit out of date. It's largely correct but we are not using any of the `Individuals` tabs or views. I'm not sure sure why you see panes greyed out. It could be:

 - the user you are logged in as doesn't have the proper permissions, but a previous login did

 - you just have stale preferences on the machine from previous installs

You might try resetting the tabs to default state

**Comment by rmehri** [comment]
Hi, thanks for your feedback! I have reset the selected tab to default state and retested, and I see the same greyed out tabs as I reported previously.  By the way, I have used the following logins:

1) Modeler and Manager roles:  (eric and alice) https://nciws-d699-v.nci.nih.gov:9090
2) Modeler and Manager roles:  (reza and alice) http://localhost:8080 

Please see attached zip file to play the video for more details and  let me know your thoughts.

[Protege_Tabs_Role.zip](https://github.com/NCIEVS/nci-protege5/files/712024/Protege_Tabs_Role.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
I think the issue is likely your config file

**Comment by rmehri** [comment]
Thanks and we'll do that.
Reza

**Comment by rmehri** [comment]
Hi, 
I have retested this issue using tag-118, edittab-0.3.5 and see the same greyed out tabs as I reported previously.  I have used the following for testing;

1.Modeler and Manager roles: (eric and alice) https://nciws-d699-v.nci.nih.gov:9090
2.Modeler and Manager roles: (reza and alice) http://localhost:8080
Please see attached zip file for the video to play for more detail:

[Protege_Tabs_Role_Tag118.zip](https://github.com/NCIEVS/nci-protege5/files/750880/Protege_Tabs_Role_Tag118.zip)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
This issue has been retested using tag-122, editab-04.5 and the same greyed out tabs. According to edit ability of tabs per role  "https://github.com/NCIEVS/nci-protege5/wiki/editability-of-tabs-per-role", the "Individuals by class" tab should be enabled for modeler "R" and manager "RW".  But this is not the case. Please attached screen shots for more details.

![tab access roles-modeler](https://cloud.githubusercontent.com/assets/8367102/23074174/070ea49e-f506-11e6-85d5-73fb944b2c94.png)
![tab access roles-manager](https://cloud.githubusercontent.com/assets/8367102/23074179/08a636aa-f506-11e6-9fc4-00551fc688db.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Hi @rmehri - see my comment above in this thread. We don't use the individuals tab

**Comment by rmehri** [comment]
Hi,
Thanks, based on your feedback, this issue can be closed for now.  
*Note: we will add the latest edit ability tabs per role to this issue when the WIKI page is updated.
Reza
