### ISSUE TITLE
P5-Tag 107- Preferences-User Details -Not Showing Correct System User

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#106]
Steps to reproduce:
1.Log in to server "https://nciws-d699-v.nci.nih.gov:9090"  user =eric 
2.Connect to "ncit-owl2-v3" project.
3.Select "preferences / User details.
4.The user details shows my network username: "mehrig" instead of the actual user "eric".  
Shouldn’t user details show the user the name of the actual of user who is logged into server?
Please see attached snapshots for more details and let me know your thoughts.

![user deatails_username](https://cloud.githubusercontent.com/assets/8367102/20901506/e20a6bea-bb00-11e6-85af-d737645e4643.png)
![user deatails_username-2](https://cloud.githubusercontent.com/assets/8367102/20901513/e6a3f5f4-bb00-11e6-8e04-21b1d33e89c6.png)

Thanks,
Reza

**Comment by bdionne** [comment]
not sure, Protégé was designed for a single user. That user you see in preferences is also used to determine where to store the preferences that persist across sessions.

we'll probably revisit when we address #89 and #90 

If you look at the server menu you can see the user logged in to the server
