### ISSUE TITLE
filtering searches in lucene query tab

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#107]
need the ability to set and persist (per instance, #89 and #90) the query type for the filtered search (at the bottom of the resultset panel).

**Comment by hahndane** [comment]
This attachment compares the protege-1.5.1 and protege5 Configure Lucene Query options window.

[Options for filtering search.pptx](https://github.com/NCIEVS/nci-protege5/files/699801/Options.for.filtering.search.pptx)

**Comment by bdionne** [comment]
This still needs some requirements work, to fully understand the implications of filtering using different criteria form the original search.

.eg. what should be the impact on original results set? If the user filters then does an export, should the export be based on the filtered set?

**Comment by NCIEVS** [comment]
Yes, if the resultset gets filtered, then the export would be based on the filtered set.

**Comment by NCIEVS** [comment]
from [TQ]:
Not sure if this was still on the radar to be fixed, but the search results are not yet acting correctly. 
If you look at the snap, there ae 85 matches, if you look at the text output, there are 421 values. I believe this is because it hasn’t cleared the previous search from its cache.
If you click on the Clear button and redo the search and output parameters, it does not change the results.
In order to get the correct results, you must log out and back into Protégé.

**Comment by NCIEVS** [comment]
Followup to the above, from [TQ]:
Just to clarify… it will export the correct properties or attributes you request, but possibly not on the correct set of terms if you have done more than one query in succession.

**Comment by bdionne** [comment]
This is really a separate issue (#306)

**Comment by bdionne** [comment]
[fixed in 1.0.7](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.7)

**Comment by rmehri** [comment]
Hi,
This fix has been retested using latest tag nci-1.008, nci-edit tab-0.6.5, Lucerne search 1.0.7, on my local server 8080 and QA server "https://nciws-q791-v.nci.nih.gov:9090".
Please see attached screenshots for more details.


![issue-107-filtering1](https://user-images.githubusercontent.com/8367102/28242379-1909dbc8-6978-11e7-8444-3e7190c36e38.png)
![issue-107-filtering2](https://user-images.githubusercontent.com/8367102/28242382-191187e2-6978-11e7-9d55-353c4c34f11b.png)
![issue-107-filtering3](https://user-images.githubusercontent.com/8367102/28242381-19101c04-6978-11e7-81ea-708ca9bfb037.png)
![issue-107-filtering4](https://user-images.githubusercontent.com/8367102/28242383-1913d42a-6978-11e7-85ff-45ada7b5d0b1.png)
![issue-107-filtering5](https://user-images.githubusercontent.com/8367102/28242380-190c542a-6978-11e7-94e0-88924a844f68.png)
![issue-107-filtering6](https://user-images.githubusercontent.com/8367102/28242384-19150cfa-6978-11e7-9f60-4af0e4e51ed3.png)
![issue-107-filtering7](https://user-images.githubusercontent.com/8367102/28242385-1929b218-6978-11e7-9483-c1b51d4fbe2b.png)

Thanks,
Reza
