### ISSUE TITLE
cannot clear the Report Writer screen without exiting

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#110]
for the time being, workaround exists, e.g. drag a new concept to the panel.

**Comment by bdionne** [comment]
@singhik - sorry, this was sitting in the QA bucket but I forgot to change the milestone.

**Comment by singhik** [comment]
QA has verified the ReportWriter Screen 'Clear' button being Functional per below screen prints :: 

ReportWriter Screen with configuration data :: 

![image](https://user-images.githubusercontent.com/36314371/40800563-b8f0feac-64de-11e8-937c-90e001917ec3.png)

ReportWriter Screen data is cleared by clicking 'Clear' button and without Exiting ::

![image](https://user-images.githubusercontent.com/36314371/40800631-ebcd1270-64de-11e8-9e6f-6cc30553d6a2.png)
