### ISSUE TITLE
cannot clear Merge panel if you put the wrong concept in it

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#111]
Feedback:  "If you put the wrong concept into a pane in the Merge, you cannot Clear it out. If you come back in the same session it is still there. You have to Exit and log back in."

The Clear button is enabled once you drag a second concept (serves as a workaround).  Feature request is to enable the Clear button as soon as the first concept is dragged in.

**Comment by bdionne** [comment]
This is already fixed in the newest. As soon as any class is dropped in there the clear button is enabled

**Comment by rmehri** [comment]
This issue has been successfully retested in tag-109.  This issue can be closed.
Please see attached snapshot for more detail.
Thanks, 
Reza

![issue-111-tag109_fixed](https://cloud.githubusercontent.com/assets/8367102/20935539/279f0678-bbad-11e6-8956-dee837457e3c.png)
