### ISSUE TITLE
need to be able to find IRIs more easily to write batch edit files.

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#112]
There are several options at this time, but there is agreement that finding these IRIs needs to be easier.  Under investigation for v1 release.

**Comment by NCIEVS** [comment]
one possible option:
"Could the headers on the tables include the identifier (IRI) that is used in the batch in parentheses.  For example Term Type (term-group or the “code” when we move to code-based)"

**Comment by bdionne** [comment]
Not sure I follow, headers on what tables?

**Comment by NCIEVS** [comment]
In this one option, it would be the column headers in the complex property tables.

**Comment by NCIEVS** [comment]
Another option that TQ suggested was to provide list of properties and their fragment identifiers.

**Comment by bdionne** [comment]
oh, sure, that would be simple to implement but might make the headers read poorly. We can try it and see how it looks to modelers

**Comment by bdionne** [comment]
add a new tab in `EditTab` that provides a simple mapping as a table, mapping labels to `IRI`s and `IRI` fragments

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

A new tab displays the IRIs, fragments, and labels for all properties

**Comment by rmehri** [comment]
The fix has been retested using tag-112, verified that the newly added "BatchEditIRIs" tab under NCI Edit Tab is active and functional. Please see attached snapshot for more detail.

Thanks,
Reza   

![new_batchedit tab](https://cloud.githubusercontent.com/assets/8367102/21326504/fd19c23e-c5f8-11e6-8faf-3ac244925b0a.png)
