### ISSUE TITLE
Tag109-Lucene Search-Property-"Label & End With" Not Retuning Specific Search Results

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#113]
Steps to reproduce:
1) Launch server and client protege5
2) Use Eric user and Login to "https://nciws-d699-v.nci.nih.gov:9090"
3) In Add Basic Query use the following search criteria:
Property = label
 Query Type =End with
 Value = "e"
4) Click Search link and search results not specific. 
Please see attached snapshot for more details.
Thanks,
Reza

![search _label_ends with_tag109](https://cloud.githubusercontent.com/assets/8367102/20954093/3b21a7ce-bc06-11e6-88ac-0dc3320ddb94.png)

**Comment by bdionne** [comment]
I think this is as expected. `ends with` is searching over tokens, notice that each of your results ha s a token that ends with "e"

I could see if possibly we could do an `ends-with-string` similar to `starts-with-string` but I'd have to check

**Comment by NCIEVS** [comment]
Let's sit on this one until we know its importance.

**Comment by bdionne** [comment]
works as intended
