### ISSUE TITLE
P5-Tag-109-Edit Tab-Definition - Invalid Value

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#115]
The invalid value for definition can be saved, 
Please see attached Snapshots for more details. 

Thanks,
Reza

![tag-109-invalid property value-1](https://cloud.githubusercontent.com/assets/8367102/20999246/477b0e26-bce1-11e6-8275-1f3c7c350c23.png)
![tag-109-invalid property value-2](https://cloud.githubusercontent.com/assets/8367102/20999255/4f0aaa0c-bce1-11e6-898e-97c74219328b.png)

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
This fix has been successfully retested and verified using tag-112.
Please see attached snapshots for more detail.
Thanks, 
Reza

![definition- invalid value-1](https://cloud.githubusercontent.com/assets/8367102/21366447/df304d68-c6c7-11e6-97de-4511229991eb.png)
![definition- invalid value-2](https://cloud.githubusercontent.com/assets/8367102/21366496/0a2583c6-c6c8-11e6-99a9-3e50ed9b1175.png)
