### ISSUE TITLE
visibility of retired concepts

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#117]
Even though a concept may have been retired (owl:deprecated), we should be able to bring it up in the edit tab to examine the data it was associated with (e.g. old parents, old roles, definition).  Currently this is not possible but there is a workaround (bring it up in the "merge" tree panel).

**Comment by bdionne** [comment]
I deliberately disabled this since the user is not allowed to edit. Once we have the read only tabs I can bring this back

**Comment by bdionne** [comment]
A first [draft](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.6) of a new read only tab is available now, for review. It only shows classes that are retired.

**Comment by rmehri** [comment]
Hi Bob, 
Based on your comment 12 days ago, which new read only tab are you referring to? Please let me know. 
Meanwhile, I have retested this fix using tag-115.  Please see attached screen shots for more details. 

Thanks,
Reza
![retire_visibility](https://cloud.githubusercontent.com/assets/8367102/21617167/dde46426-d1b2-11e6-9391-a0f8df056a44.png)
![new tab_retire](https://cloud.githubusercontent.com/assets/8367102/21617383/d7515c3a-d1b3-11e6-938a-45d13607731d.png)

**Comment by bdionne** [comment]
There is a new "read only class" tab:

<img width="1019" alt="screen shot 2017-01-03 at 1 51 52 pm" src="https://cloud.githubusercontent.com/assets/31741/21619032/eb084d58-d1bb-11e6-8fa4-1d4309c5135b.png">

That becomes visible, but in read only mode, when you select a class that is retired:

<img width="1016" alt="screen shot 2017-01-03 at 1 52 10 pm" src="https://cloud.githubusercontent.com/assets/31741/21619053/01866966-d1bc-11e6-9a74-8388e94d5ced.png">

If you're missing that tab, and you have the newest jar file, then try the usual `reset selected tab to default state` under the windows menu.

**Comment by rmehri** [comment]
It has been verified.   
Thanks, Reza

![readonlyclass](https://cloud.githubusercontent.com/assets/8367102/21620193/28beefda-d1c1-11e6-98d0-64944adefd6c.png)

**Comment by rmehri** [comment]
I am adding the screen shot that shows the description of retired concept under ReadOnlyClass tab. 
Thanks,
Reza
![readonlyclass](https://cloud.githubusercontent.com/assets/8367102/21621473/2cc7b4bc-d1c7-11e6-9ba9-7d56ac156503.png)

**Comment by bdionne** [comment]
@NCIEVS - this seems to work for me, and it should make no difference whether it's a newly retired class or existing one. When a retired class is selected the new tab should come into focus and be populated with a read only version of the retired class:

<img width="1023" alt="screen shot 2017-01-04 at 11 59 12 am" src="https://cloud.githubusercontent.com/assets/31741/21653248/26b2f4a8-d27e-11e6-83cb-dc49f0c55c65.png">

Did you try the usual `reset the default state...` ? 

Otherwise I'll have to check your content. The test I use is whether the class is a subclass of the retired root, which should work regardless of when it was retired

**Comment by NCIEVS** [comment]
Yes, I tried the reset to the default state, and that didn't make a difference the behavior was the same, the ReadOnlyClass tab was not populated, but the Edit tab was, and the concept was editable in the Edit tab.  So I gather this is not a config issue then.  OK, yes, try the NCIt, see if it's a content difference.

**Comment by NCIEVS** [comment]
Interestingly, if I look at "foo" over here, the editor switches to the ReadOnlyClass tab whick picks up the retired concept and displays it fine.  However, the retired concepts are still editable in the Edit tab.

**Comment by rmehri** [comment]
Yes, I used eric login and NCIt project and that didn't show the contents of retired concept under ReadOnlyClass tab either.  I have reset to the default state in my previous and current tests as well. 
Please see attached screen shots for retired and preretired as well.
Thanks,
Reza

![untitled-1](https://cloud.githubusercontent.com/assets/8367102/21658629/5cee4376-d295-11e6-8b7f-89f5d331114a.png)
![untitled-2](https://cloud.githubusercontent.com/assets/8367102/21658640/64f8c668-d295-11e6-84cd-a64cdd9d387f.png)
![untitled-3](https://cloud.githubusercontent.com/assets/8367102/21658649/6d25f568-d295-11e6-85ba-ae4e8d2bf4b2.png)
![untitled-4](https://cloud.githubusercontent.com/assets/8367102/21658669/7b6d0c2e-d295-11e6-8536-931c040bfb01.png)

**Comment by rmehri** [comment]
Hi Bob,
I have used the following scenarios to validated fix:
1) Used eric login for ncit ==> retired concept content displayed
2) Used eric login for foo> retired concept content Not displayed ==?
3) My local project==> retired concept content displayed
Please let me know your thoughts. 
Thanks,
Reza

**Comment by bdionne** [comment]
I"m not sure I understand the question?

FIY, I don't think Foo is reliably configured anymore unless your local copy has been updated. `SmallBase` will produce better results

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! For steps 1&2, I have used server address: https://nciws-d699-v.nci.nih.gov:9090, login: eric.  I also updated my previous note as well.  In this case, based on your latest feedback and my test results, this ticket can be closed. 

Reza
