### ISSUE TITLE
reversal of pre-merge and pre-retire by editors prior to the final approval by workflow manager

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#118]
placeholder, it is not known if it's required at this time.

**Comment by bdionne** [comment]
The code that checks for the switch assumes the codes are of the form "prefix-xxxx-suffix" where the config may have removed the delimiter.

**Comment by bdionne** [comment]
oops, wrong ticket, I was confusing this with the code swapping in merge

**Comment by NCIEVS** [comment]
Reversing the pre-merge & pre-retire would require the modeler at this time to go through Revision History.  No "simple" undo mechanism in place.  Since this hasn't been requested by the editors, will close ticket.
