### ISSUE TITLE
P5-Tag 109- Lucene Search- "Definition Reviewer Name & Contains" Not Returning Search Results 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#119]
Steps to reproduce:
1.Launch protege server and client
2.Log into the Server.
3. Search for "Definition Reviewer Name" not returning any results using three character or more of name
  a) Query Type= Contains 
  b) Value = r==> 55461 matches   
  c) Value = re==> 35319 matches  
  c) Value = rez ==> 0 match. 
Please see attached screen shots for more details.
Thanks,
Reza

![definition reviewer name-1](https://cloud.githubusercontent.com/assets/8367102/21027655/d7f5d804-bd5f-11e6-98b8-89f0ff39bb4f.png)
![definition reviewer name_contains_search](https://cloud.githubusercontent.com/assets/8367102/21027694/0cce1ad2-bd60-11e6-9575-6fd8c989bebf.png)

**Comment by NCIEVS** [comment]
I'm not seeing this issue.  Could you reindex?

**Comment by bdionne** [comment]
this seems to work, perhaps this is dated, 109 was some time ago. 

please reopen if the issue is reproducible

**Comment by rmehri** [comment]
Hi Bob,
I have retested this issue using tag-120, edit tab-0.4.2. The problem still persists.  
https://github.com/NCIEVS/nci-protege5/issues/195
Thanks,
Reza

**Comment by bdionne** [comment]
? - How does this relate to #195 ?

**Comment by rmehri** [comment]
Hi Bob,
I used the same search criteria, which returned number of records.  This works fine.  But the associated “Definition Reviewer Name” to the returned records cannot verified since the value of “Definition Reviewer Name” field is missing (Blank). As per tracking purpose, I will remain this ticket open so I can retest it when this ticket https://github.com/NCIEVS/nci-protege5/issues/195 is fixed. 

![nci edit tab -definition reviewer name](https://cloud.githubusercontent.com/assets/8367102/22986341/2f2f2cd4-f379-11e6-9b36-0ad60cbfffb6.png)
![lucen4 search -test result](https://cloud.githubusercontent.com/assets/8367102/22986344/303095f0-f379-11e6-8071-bc4701a2af32.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - I see, I misunderstood your comment, so this ticket is fine

**Comment by rmehri** [comment]
This issue has been retested and verified using tag-121, nci-edit-0.4.4. 
Please see attached snap shots for more detail.

![lucene_search](https://cloud.githubusercontent.com/assets/8367102/23041729/e49cdeb4-f463-11e6-8878-07009e559978.png)
![lucene_search1](https://cloud.githubusercontent.com/assets/8367102/23041730/e7b61f16-f463-11e6-8f72-42177714d826.png)

Thanks,
Reza
