### ISSUE TITLE
No way to edit property values whose types are enums

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#12]
Not sure how to add Semantic Type values; the Data Properties tab appears to have a list of acceptable values for this property but they are not displayed when you add the property. If you don’t fill the property, the GUI doesn’t warn you that it will save the empty property.

**Comment by bdionne** [comment]
I think this one is for Protege

**Comment by rwynne** [comment]
@bdionne 

I think I've found the preferred steps to do so using P5 beta-24.  

After loading the NCIt Prototype OWL2 file:

Select 'Entities' tab -> 'Datatypes' tab -> Select an enum class such as "Concept_Status-enum" -> in the 'Datatype Definitions' panel select 'Edit' and enter the value in 'Datarange Expression' tab.  In the comma delimited map, in double quotes enter the  (e.g., "foo") -> Click 'OK'

Screenshot attached (please let me know if it doesn't attach properly).

![editingp5b24-enums](https://cloud.githubusercontent.com/assets/6089714/18758060/6893a5cc-80c4-11e6-9149-c265dc410070.gif)

**Comment by bdionne** [comment]
Rob, thanks, but the issue is when one wants to add a property assertion to a class, and the properties value is one of those enum types, not editing the type itself.

**Comment by rwynne** [comment]
Yes, you're correct.  I read your initial issue incorrectly (without thoroughly reading Matthew's follow-up).

The closest I can get to adding an -enum value is selecting the -enum concept itself as an annotation.  There is no simple way to select a value from the 'Data range expression's after this is done.

**Comment by bdionne** [comment]
[added to protege](https://github.com/protegeproject/protege/issues/532)

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
Hi, 
Can you please share your use case to verify this fix? 

Thanks,
Reza

**Comment by rmehri** [comment]
Leave a comment
