### ISSUE TITLE
need to be able to set the starting code from the server config file

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#121]
The numeric portion of the code is kept in a file that we won't have access to in production.  There will be occasions when the code sequence needs to be reset and it would be better to do it through the gui rather than have the systems group go and edit the file.  It does have a workaround, so it can slip.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

There is a new sample server script that can be used to set the sequence. The server can be running while this is performed

**Comment by rmehri** [comment]
I already addressed my question about regarding  setseq.sh file as a note in github. Thanks

**Comment by bdionne** [comment]
From Reza:

Hi, 
Should we run this file "./setseq.sh"  separately or leave this file alone? Or just update genecode file to setup the initial value? Please clarify. Thanks!

The purpose of the script is to update the seed code that the code generator uses. It needs to be at least as great as anything in the ontology you are using

**Comment by bdionne** [comment]
The purpose of the script is to update the seed code that the code generator uses. It needs to be at least as great as anything in the ontology you are using

**Comment by rmehri** [comment]
Based on development's comment, this ticket can be closed. This was tested before,
