### ISSUE TITLE
Tag-110-Creating a New OWL Class Without Name Can be Saved

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#122]
The user can create a new OWL class Without name .  Please see attached zip file for the video clip to play. 
Regards,
Reza
[No Name.zip](https://github.com/NCIEVS/nci-protege5/files/643005/No.Name.zip)

**Comment by bdionne** [comment]
what steps did you take to reproduce?

**Comment by rmehri** [comment]
Great and thanks
-Reza

**Comment by bdionne** [comment]
fixed in [nci-edit-tab-0.2.0](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.0)

**Comment by rmehri** [comment]
This fix has been retested and verified.  Please see attached screen for more detail.
Thanks,
Reza

![create child class_no name](https://cloud.githubusercontent.com/assets/8367102/21689176/870466ce-d33d-11e6-8835-4192d25d8560.png)
