### ISSUE TITLE
P5-Tag110- Window-Tab- Not All Tabs Available  

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#123]
I have tested several scenarios and noticed that not all window/tabs are available with Admin to add to protégé GUI page.  Here are some of the scenarios: 

Testing Users Roles for Tabs only: 
1) reza => Administrator
a. Two tabs (NCI Edit Tab & Lucene Search Tab) enabled. 
b. Tabs menu indicates greyed out
2) alice=>WorkFlow Manager 
The following tabs are showing available:
a.	Active Ontology
b.	Entities
c.	Object Properties
d.	 Annotation Properties
e.	NCI Edit Tab
f.	Lucene Search Tab
g.	Revision History
3) mike=> WorkFlow Modeler
a. Two tabs (NCI Edit Tab & Lucene Search Tab) enabled. 
4) root=>sysadmin
a. Two tabs (NCI Edit Tab & Lucene Search Tab) enabled. 
b. Tabs menu indicates greyed out
5) The following tabs are not showing available:
a.	classes
b.	Data Properties
c.	Individuals by Class
d.	NCI Edit Tab
e.	Lucene Search Tab
f.	Server administration (This tab gets available when login to the port 8081”

 Please see attached zip file for the video clip to play for more details.         
 Thanks,
 Reza

[Wndow-Tabs Not Available.zip](https://github.com/NCIEVS/nci-protege5/files/643396/Wndow-Tabs.Not.Available.zip)

**Comment by bdionne** [comment]
Yes, this pretty much as [intended](https://github.com/NCIEVS/nci-protege5/wiki/editability-of-tabs-per-role), though the read-only aspect is not yet complete

**Comment by rmehri** [comment]
Based on the development's comment "wontfix" this ticket can be closed.
