### ISSUE TITLE
Batch edit not using PT for FULL_SYN Term Group

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#127]
From Terri: 

I’m having trouble batch editing in some subsets and an editor note, but I did one manually, and all I can see is the code- will you add the preferred term, as this is not helpful at all.
 
Also, I loaded a bunch of concepts in alice, and under Coping Skills, you will see that they were assigned a Term group of SY. Should be PT. Now, when I went to cadd another SY, I got the error message that there could be only one PT, so you cannot do anything until you assign a PT. At first, it would not let me change a PT, but now I can, so cannot replicate the steps that wouldn’t let me change the PT. this is pretty important.

**Comment by NCIEVS** [comment]
The second item is not an issue.  This was a configuration item, I set the default to SY, just have to set it to PT.

The first item I don't follow; the screenshot in the email thread does show a preferred term.

**Comment by NCIEVS** [comment]
OK, the first item is related to the second item.  It's not the preferred term being referred to here, but rather the full_syn NCI/PT.  This will get "fixed" on setting the default to PT on the term-group-enum.  Will close this ticket with wonfix.
