### ISSUE TITLE
Tag-110-NCI Edit Tab-Missing "ComplexEdit, Retire, ReportWriter tabs"  

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#128]
When using the same tag110 on different Windows7 workstation, the NCI Edit tab shows missing 
 "ComplexEdit, Retire, ReportWriter tabs" . 
Please see attached zip file to play the video for more details.

Thanks,
Reza

[No Retire or Report Writer.zip](https://github.com/NCIEVS/nci-protege5/files/649479/No.Retire.or.Report.Writer.zip)

**Comment by NCIEVS** [comment]
@rmehri please click on "Window -> Reset selected tab to default state" and follow up from there.

**Comment by rmehri** [comment]
Ok, we tried and it worked. Thanks!

I am wondering what could cause of it..
Thanks,
Reza

**Comment by bdionne** [comment]
Closing this, there seems to be nothing to do here? Please reopen if there's an issue.

@rmehri - protege store the state of the GUI, layouts, user preferences, etc.. on the user's local machine. Sometimes as the code is changing that state is no longer compatible and you see strange results like panels missing. Gilberto's suggestion is always the first thing to try when you see something amiss.

**Comment by rmehri** [comment]
Sure and I agree that this ticket should be closed.  
Thank you for your feedback!
Reza
