### ISSUE TITLE
Issue with Report Writer

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#129]
From Garret:

[editor note endo.txt](https://github.com/NCIEVS/nci-protege5/files/651599/editor.note.endo.txt)
Report generated from LQT. Field delimiter = “|”, property value delimiter = “tab”. Output is in one continuous string. Unable to paste into text editor due to line length. Previously, there was a break at the end of the query for each class. Looks like the information is in the file in a way that I can parse it so as to be useful, but presently I cannot edit the file for the aforementioned reason. Suggestions?

**Comment by NCIEVS** [comment]
This seems to be an EOL/windows issue, as the "single line" output is evident in Notepad but not in other text editors that know how to deal with CR vs CRLF vs LF.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

**Comment by rmehri** [comment]
Hi Bob, 

Based on the description of this issue, I have retested this fix in tag-118, edittab-0.3.3 on Windows 7. 
Please see attached zip file for the exported reports in .csv and .txt for more details. 

[lucene-export1.zip](https://github.com/NCIEVS/nci-protege5/files/739634/lucene-export1.zip)

Thanks,
Reza
