### ISSUE TITLE
Warn user when leaving edit panel before saving

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#13]
Need a warning when moving away from unsaved changes in a concept. Also, the Save button doesn’t get highlighted when there are changes made.

**Comment by NCIEVS** [comment]
Concept is flagged as "(editing)" in the tree widget.  Some issues with the refresh of "(retired)" being tracked [elsewhere](https://github.com/NCIEVS/nci-protege5/issues/82).  Labeling this one as ready for QA & v1 release.
