### ISSUE TITLE
include class fragment identifier in a visible place

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#131]
Related to #66, can be included in a third text field of the same #66 enhancement.  The text box for the fragment identifier can have the label "IRI-Fragment" (suggestions for other labels welcome).

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
This fix has been tested and verified using tag-112. 
Please see attached screen shot for more detail.
Thanks,
Reza

![iri fragment](https://cloud.githubusercontent.com/assets/8367102/21369898/2ed4fa94-c6d7-11e6-9fdd-4c2e2195a793.png)
