### ISSUE TITLE
Tag-111- Report Writer - LQT Export Completion Remains with A Question

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#132]
Steps to reproduce:
1.Log into the localhost 8080 as Workflow Modeler
2.Use a class "Activity"
3.Go to Report Writer
4.Configure export LQT for all these properties “Definition, Alt Definition, Full_SYN “with their table names.
5.Do export the report write.  
6. In application/ Report Writer Activity page, you'll notice the report writer finished successfully but at the end the following message displays: Exported file: How To Add The Name? 
Please see attached screen shot for more detail.

Thanks,
Reza
![lqt-report](https://cloud.githubusercontent.com/assets/8367102/21240512/a711fca2-c2d9-11e6-9cfd-42b79e8b2607.png)

**Comment by bdionne** [comment]
this looks like an initialization error, will investigate

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.0)

**Comment by rmehri** [comment]
This fix has been retested verified using tag-115.  Please see attached screen shot for more detail.
Thanks,
Reza

![untitled](https://cloud.githubusercontent.com/assets/8367102/21618497/2bee1184-d1b9-11e6-9cff-4c1942a067cc.png)
