### ISSUE TITLE
Tag-111- By Code- Unable to Create A Class Using ProjectByCode

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#133]
Steps to reproduce:
1. Log into the localhost 8080 as Workflow Modeler
2. Select ProjectBaseByCode
3. Select NCI Edit Tab
4. Select "Edit" link/ Create Child from top browser
5. Enter a class name in Create a New OWL Class menu
6. Click Ok and then you'll notice the java error. 
 Please see attached screen shot and log file for more detail.

Thanks,
Reza
![tag111-project by code](https://cloud.githubusercontent.com/assets/8367102/21242684/77291a66-c2e3-11e6-86b5-513db89c94f8.png)
[Tag-111-Unable to create a class.txt](https://github.com/NCIEVS/nci-protege5/files/655869/Tag-111-Unable.to.create.a.class.txt)

**Comment by bdionne** [comment]
@rmehri -- I'm pretty sure you're trying to open a template project. Is this a project you built?

**Comment by bdionne** [comment]
closing this. @rmehri - just ping me on Skype if you can't get the server to generate codes and I'll step you through fixing it
