### ISSUE TITLE
Is it the case that only admins can create new children of owl:Thing?

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#134]
Oh yea I think this is a bug

**Comment by rmehri** [comment]
Hi Bob, 
I am adding the screen shot to this ticket. Please see attachment for more detail.

Thank you for your great feedback!
Reza

![child of owl thing](https://cloud.githubusercontent.com/assets/8367102/21278552/da2ece8c-c3a9-11e6-9fe0-efb57496dd1d.jpg)

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.2)

**Comment by rmehri** [comment]
This fix  has been retested and verified using tag-116.  Used  manager and modeler logins.
Thanks,
Reza
![create child of owl-thing-manager](https://cloud.githubusercontent.com/assets/8367102/21868434/b9f8b1d8-d820-11e6-8f7d-2f56932abea5.png)
![create child of owl-thing-modeler](https://cloud.githubusercontent.com/assets/8367102/21868436/bc5f1be2-d820-11e6-9baf-c62fd9f03001.png)
