### ISSUE TITLE
Tag-112-System Administration-Unable to Remove a User 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#136]
Steps to reproduce:
1) Launch server and client 
2) Log into local host http://localhost:8081  ==>" Server Admin"
3) Use "Bob"
4) Select the users and remove their assigned projects in  "access control policy " 
5) Try to remove the users  and go Jason Serialization and save and exit the application 
6) Repeat steps 1 through 3 and you'll see the users not removed and they still exist.
Please attached zip file to play the video.

Thanks,
Reza

[Server_Admin_Unable to Remove User.zip](https://github.com/NCIEVS/nci-protege5/files/661670/Server_Admin_Unable.to.Remove.User.zip)

**Comment by NCIEVS** [comment]
This is probably a refresh issue.  future enhancement.  Also, the data in the json display panel stops displaying.

**Comment by bdionne** [comment]
@singhik - this needs triage, but is very low priority

**Comment by singhik** [comment]
@bdionne : Sure, will park this ticket for now .
