### ISSUE TITLE
Tag-112-Create Child Class-Full_SYN “No_Default” Values is displayed 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#139]
Tag-112-Create Child Class-Full_SYN “No_Default” is displayed for term type and term source.

Steps to reproduce:
 1.Launch server and client
 2.Log into local host http://localhost:8080
 3.Use "Reza" Work Flow Modeler
 4.Select NCI Edit Tab
 5.Create a new OWL Class save it then
 6. You'll see the Full_SYN “No_Default” is displayed for term type and term source.
 Please attached zip file to play the video.

Thanks,
 Reza

[Full Syn No Default Text.zip](https://github.com/NCIEVS/nci-protege5/files/661886/Full.Syn.No.Default.Text.zip)

**Comment by bdionne** [comment]
This is a data issue, you need to add defaults annotations on the complex property qualifiers

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! By the way, I am adding the following to this ticket as well, if that makes any difference to the resolution: 

Note:
When Select  the Full_SYN property from step#6 and press edit, you'll see the value= BDA Testing Values for child and term source = ACC and Term Type= AB and click Ok, then you'll received  warning message: One and only one PT with source NCI is allowed.

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - This is a data issue, you need to fix the ontology you are working with and it will go away.

The warning about only one NCI/PT FULL_SYN is correct

**Comment by rmehri** [comment]
Based on the development's comment and also wontfix status, this ticket can be closed.
Thanks,
Reza
