### ISSUE TITLE
Revision diff panel throws exceptions on empty properties

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#141]
When a change to a class involves logic, adding roles, .eg., the `LogDiff` method throws exceptions as it assumes all changes involve properties

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.113)

**Comment by rmehri** [comment]
Hi Bob, 
I have retested this fix by adding empty properties and changing properties for a few classes, which I did not see any errors in Revision history.  Would you have any specific use cases that I can extend my testing for this issue?
Thanks,
Reza

**Comment by bdionne** [comment]
I don't, the commits throwing the exceptions were legacy and I don't recall how they were created

**Comment by rmehri** [comment]
Hi Bob, 
Thanks! Based your comment, this fix cannot be verified by QA. 
Reza

**Comment by bdionne** [comment]
Thanks @rmehri , I'll go ahead and close this then since I opened it. As mentioned above the issue occurs when changes involve logic, and I'm no longer able to reproduce it. Feel free to reopen if it happens again,
