### ISSUE TITLE
batch edit - validation of enumerated properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#143]
annotation properties with an enumerated range should be validated in a batch edit to have a value within the range.

This should apply to annotation properties that are asserted on a class (e.g.  semantic_type) as well as annotations on annotation values (e.g. a term-group annotation on a full_syn property).

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.6)

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using tag-123, edittab-0.4.6. 
Please attached screen shot and input and output batch files for more details.
Used local server (8080)

![full_syn](https://cloud.githubusercontent.com/assets/8367102/23187346/73c539c2-f858-11e6-8be7-49fd2b133821.png)
[batch_edit2.txt](https://github.com/NCIEVS/nci-protege5/files/791654/batch_edit2.txt)
[batch_edit2-out.txt](https://github.com/NCIEVS/nci-protege5/files/791655/batch_edit2-out.txt)

Thanks,
Reza
