### ISSUE TITLE
Check batch files for bad characters

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#144]
Would be good to find a way to make sure that a batch file matches the batch type.   It would reduce the possibility of error during a batch job.

**Comment by bdionne** [comment]
you could create a convention based on the input file extension, which the software would enforce

**Comment by NCIEVS** [comment]
This won't be as crucial with dedicated tool support, but the tool itself could add metadata in a header for a simple check by protege when reading a file.

**Comment by NCIEVS** [comment]
The title change reflects a narrowing in scope.

**Comment by bdionne** [comment]
make sure all characters in the batch files are valid UTF-8

**Comment by NCIEVS** [comment]
Map of sanctioned unicode -> allowed-ascii has been posted [here](https://github.com/NCIEVS/ops-data-conversion/blob/master/LVG_Config/symbolMap.data).  Any additional characters that need to be disallowed in the future would be entered into this map.  Only the first two columns need to be processed (unicode & allowed-ascii), the last two are informational (rendered unicode, unicode name).

**Comment by bdionne** [comment]
upon reflection I don't think we need a separate plugin for this, rather we can just add the file to the edittab plugin. When the file changes, the plugin will need to be updated, version number bumped, etc.. in either case so it seems no harm to have it part of edittab.

Seem reasonable?

**Comment by NCIEVS** [comment]
Agreed.  Separately, we need to document where in git the map resides so we can keep it updated.

**Comment by bdionne** [comment]
This is the same issue we fixed in #330 - but was mislabeled as the 2.1 release. Moving to 2.3 so that we double check the fix then

**Comment by singhik** [comment]
@NCIEVS @bdionne : Hi , Please confirm the scope of coverage for this Requirement, in sense of validation , will using a batch file for Batch_Type 'LOAD'  having few of the listed/allowed ASCII Characters like ( ", / , ! , ^, ~ , % , * )  with Loading being successful, will suffice ?

**Comment by singhik** [comment]
@NCIEVS @bdionne :  Hi, I have tested a Batch Type Load with few ASCII Characters but they did not get converted to respective UTF-8 charcters and got uploaded with ASCII chars only . Please find below the screen prints : 

EmDash(—) , did not convert to - 
RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK(») , did not convert to "
DIVISION SIGN (÷)  , did not convert to /

Input File ::

![image](https://user-images.githubusercontent.com/36314371/38324965-b3cf5e42-380f-11e8-9701-778f37fea76f.png)

Uploaded successfully  without conversion :: 

![image](https://user-images.githubusercontent.com/36314371/38325002-c9e849d2-380f-11e8-9923-20a4e7f82ec5.png)

**Comment by bdionne** [comment]
this is missing code, it's fixed in [nci-edit-tab-0.8.0](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.8.0)

**Comment by singhik** [comment]
@NCIEVS ::  Hi Gilberto ,  QA has verified  Chars to Mapped Ascii conversion using Boundary Value Analysis , in which , I have Tested 10 Characters to Ascii conversion via Batch Type 'LOAD', The conversion did happen successfully for those 10 characters . Please share your valuable insight  if this will suffice the coverage for this issue? 
Attached are the screen print document ...

[Issue 144.docx](https://github.com/NCIEVS/nci-protege5/files/1881368/Issue.144.docx)

**Comment by NCIEVS** [comment]
@singhik, Hi Itendra, yes, this suffices for coverage.  You can close as fixed.

One last note, this map covers conversions the unicode->unicode_in_the_ascii_range.  We still have to do something separately about non-unicode, specifically non-utf8, being present in the batch files, see #376.

**Comment by singhik** [comment]
Closing this ticket w.r.t Unicode to Unicode in ascii range conversion, as validated by QA per above .
Ticket #376 is scoped for 2.4.0 Milestone for non-Unicode(non-utf8) conversion ..
