### ISSUE TITLE
batch edit - logging false errors

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#145]
The batch jobs register errors even when the batch succeeds.  (I'm wondering if there's an innocuous warning/error that is being bubbled up to the batch processor.)  The note below is typical of what has been seen recently.

"Just to let you know that I processed Editor Notes successfully on old and new concepts, but the console read Failed for each instance, but the last line said 28 of 28 successful."

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.6)

**Comment by rmehri** [comment]
Hi,
This issue will be retested in the next build.  But is there any specific input file for this issue?
 
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using tag-123, edit tab-0.4.6
Used local server (8080)
Two input files "without typo and with typo)
Please see attached batch files for more details.

[RMv6-Def-Quals4-Typo.txt](https://github.com/NCIEVS/nci-protege5/files/791455/RMv6-Def-Quals4-Typo.txt)
[RMv6-Def-Quals4-Typo-Out.txt](https://github.com/NCIEVS/nci-protege5/files/791457/RMv6-Def-Quals4-Typo-Out.txt)
[RMv6-Def-Quals4-Good.txt](https://github.com/NCIEVS/nci-protege5/files/791456/RMv6-Def-Quals4-Good.txt)

[RMv6-Def-Quals4-Typo-Out.txt](https://github.com/NCIEVS/nci-protege5/files/791458/RMv6-Def-Quals4-Typo-Out.txt)

Thanks,
Reza
