### ISSUE TITLE
performance of property editing widget is slow

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#146]
The widget to add or edit a property is very slow to come up.  Very often the user clicks multiple times on the + because there's no feedback either.  If edits are done accidentally in the various editing guis that come up, it is possible that multiple properties get added (e.g. a typo won't score as a duplicate and will go in).  The performance needs to be increased, but also bringing up multiple windows should be prevented.  This might be for Stanford.

**Comment by NCIEVS** [comment]
Aiming for V1 release, but can be set to future release based on effort & timeline constraints.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

Tabs that are not used in the annotations property editor are removed. When the editor comes up the focus should be on the tab with the corresponding type. 

It should come up within a second or so

**Comment by rmehri** [comment]
Hi,
Based on this issue and fix descriptions and "edit ability of tabs per role" in GitHub,  I have retested and verified this fix using tag-118, edittab-03.4. 
Used: WorkFlow -Modeler & WorkFlow-Manager
OS=Windows7
Please see attached screenshots for more details.

![annotation properties tab-modeler](https://cloud.githubusercontent.com/assets/8367102/22571459/d078e50a-e96d-11e6-9d79-2f3e51f26ae8.png)
![annotation properties tab-manager](https://cloud.githubusercontent.com/assets/8367102/22571466/d3925276-e96d-11e6-8a2b-0e214c0085c9.png)

Thanks,
Reza
