### ISSUE TITLE
Tag-113-Server Administration-Creating A User But Not Displays In Current Session

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#147]
Steps to reproduce:
 1.Launch server and client
 2.Log into local host http://localhost:8081
 3.Use "Bob"  Server Admin
 4. Create first user as Work Flow Modeler and save it. 
 5. Create the second user and press ok and save it but you cannot see the second user is created on the current session. But
6. Logout and log back into sever administration and then you'll see the second user is created. 
Please attached zip file to play the video clip for more detail.
Thanks,
Reza
 
[User_Not Showing.zip](https://github.com/NCIEVS/nci-protege5/files/667509/User_Not.Showing.zip)

**Comment by rmehri** [comment]
Hi, 
I have experienced with the same issue while creating users in using tag-121 .  Please attached video clip for more details.

[Sever Admin_Creating User Not Showing.zip](https://github.com/NCIEVS/nci-protege5/files/781457/Sever.Admin_Creating.User.Not.Showing.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri 

I can't reproduce this using the steps above in the ticket. If you have some other scenario I can try please enumerate the steps and I will try. 

As I mentioned previously, I think this is a far lower priority issue than the ones in the QA bucket.

**Comment by rmehri** [comment]
Hi,  
I have noticed the same behavior while creating the users for tag-123.  Please see attached zip file for video clip to play for more details.

[Sever Admin_User Creation_Tag 123.zip](https://github.com/NCIEVS/nci-protege5/files/784195/Sever.Admin_User.Creation_Tag.123.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - there's nothing in tag `nci-0.123` that addresses this so I'm not surprised. 

I started a new project for the next release and moved this ticket as well as all the other in the `Future Release` milestone.

**Comment by rmehri** [comment]
Hi, 
Thanks for your feedback,
Reza
