### ISSUE TITLE
validation of IRIs on batch edits

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#148]
The batch processor freezes protege if it encounters a non-existent IRI to process.  This happened during a re-treeing test batch edit.  The batch processor should validate the IRIs &/or deal with any exceptions thrown attempting to access the IRI's object.

**Comment by bdionne** [comment]
[v6.NewParent.txt](https://github.com/NCIEVS/nci-protege5/files/670031/v6.NewParent.txt)

**Comment by bdionne** [comment]
[v4.CryingConceptsLoad.txt](https://github.com/NCIEVS/nci-protege5/files/670040/v4.CryingConceptsLoad.txt)

**Comment by bdionne** [comment]
I tried a couple of different scenarios with these files and nothing causes a hanging. The first file, `v4.CryingConceptsLoad.txt` specifies a set of new concepts, all children of `Ceremony`. It loads fine and creates the new classes, The second file, `v6.NewParent.txt` then doesn't do anything as none of the codes specified are found. They are just the preferred names of the classes created. Even if that file used the right codes, the classes are already treed under `Ceremony`


[teri_edit.txt](https://github.com/NCIEVS/nci-protege5/files/670670/teri_edit.txt)

**Comment by bdionne** [comment]
we can reopen if this happens again
