### ISSUE TITLE
Modeler feedback on clone, etc..

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#149]
I went on to revise the new concept from the clone process (ARHGAP32 Gene C250055) and found several issues.
 
This new concept had 2 NCI PT, the one I assigned and the one from the cloned concept. This should not be how the Clone process works, the new concept in a Clone should never maintain the PT of the existing concept as a PT. In our current protégé, the PT of the cloned concept ends up as a SY in the new concept. This is a problem, if I hadn’t gone back to edit the concept, the new concept would have been published with 2 NCI PT because the existing PT should not have been copied as a PT into the new concept and I couldn’t edit the concepts in the Copy panel. I should not have been able to Save the new concept while it had 2 NCI PT. (This lack of editing in the Complex Edit tab will be a problem for Splits as well because the Save can occur when 2 PT are present.)
 
Additionally, I got the following message after opening one of the SY, changing the value and hitting OK.I could not edit any other FULL_SYN for C250055 until I removed one of the PT. (In our current protégé the editor gets a similar message only when trying to Save a concept with multiple FULL_SYN NCI PT.) Note: I was able to edit the DEF without removing a PT. Additionally, the GUI walked back through the window to edit the property and I had to hit cancel to get back to what I was doing. This part is an annoyance because, if the PTs are not at the top of the FULL_SYN table and you are working from top to bottom (as was the case for this new concept), the editor will need to jump around to complete the editing and could lose track of what they haven’t modified.
 
Also, the control of domains and ranges of restrictions are not being enforced. I was able to add Gene_Product_Plays_Role_In_Biological_Process some 'Neural Development' to my new gene concept and I was able to Save the inconsistent role.
 
Additionally, clicking on a role changed the focus of the Edit panel to the self-defining concept for that role without prompting me that I had not saved the concept I was editing.
 
Finally, the (editing…) label still persists after saving a concept.

All of the work below was done in ncit-owl2-v3 with the 12_19_2016 snapshot. I was cloning ARHGAP5 Gene code C97279 to create a new concept ARHGAP32 Gene. I don’t know if I have pointed out some of the workflow differences here before but here is what I saw.
 
 In protege5 (p5) the editor is not prompted to add a definition for the new clone. (This is the current workflow, because the clone should not have the same definition as the existing term.)

You cannot edit the cloned concept until you save. If you hit the edit button on the DEF in the clone, the editor can change the text but the OK button is greyed out. Here is a picture.

Once you hit save the two concepts are purged from the copy panes. Then the editor needs to edit the concepts separately. The current prod workflow allows modification of both concepts in the copy pane.

As far as I can tell, we have completely lost the ability to edit two concepts at once. I copy roles from one existing concept to another ALL THE TIME. 

Here is a use case: I am updating the DEF for proteins that already exist in the Gene Product branch and updating the modeling for the proteins and the related genes at the same time. (We have increased the number of Biochemical Pathways that can be used in the restrictions Gene_Is_Element_In_Pathway and Gene_Product_Is_Element_In_Pathway, so I focus a lot of energy on adding these.) So often I am copying restrictions between the gene or wt_Allele and protein concepts (and then editing the restriction to reflect the proper domain) or between related protein concepts (there is overlapping relationships in protein families) to make the modeling of these concepts consistent. Creating multiple roles in each concept takes a lot of time but the copy/paste function in the current Copy tab is much quicker mostly because you don’t have to find the filler values using a query each time.

Not just in the clone panel, if you hit the button to edit a property more than once, multiple windows open. It is easy to make this mistake because the edit window opens slowly. So two things here, the button should only respond to the first click and it would be nice if the edit window opened more quickly (we editors tend to be an impatient lot).

Also not in the clone panel, I used the Lucene Search Tab to find the concept I cloned (ARHGAP5 Gene code C97279) and double-clicked on it to have the hierarchy focus on that concept so I could clone it. The search I had done was FULL_SYN contains ARHGAP. But after I finished cloning and saving and was not editing any concept, I went back to the Lucene_Search_Tab, double-clicked on Rho GTPase-Activating Protein 26, the view went back to the Edit panel but neither the hierarchy or the concept in the Edit panel changed to the desired concept (the concept I was APLP1 wt Allele C119730), which I was viewing and had not edited (the Save and Cancel buttons were greyed out). I then focused on another concept and tried to select Rho GTPase-Activating Protein 26 from the Lucene_Search_Tab again and still no movement. I am not sure if this is a refresh issue (I had created a new concept that would be a result in the search, ARHGAP32 Gene) because even after running the search again (and seeing the new concept in the results) I could not get Rho GTPase-Activating Protein 26 to populate the Edit panel. Doing a different search (FULL_SYN starts with – token gtpase) did not work either. Searching for an unrelated set of terms did not fix this issue. Only logging out/exiting and logging back in allowed me to migrate between different terms.

Also, could we make the logout/login process less onerous. In our current prod protégé you don’t have to log out or exit protege to refresh the database. File>Open allows the editor to log in again (and exits the first login cleanly).

**Comment by bdionne** [comment]
see #224

**Comment by NCIEVS** [comment]
Revisiting done with the editors and finalized with [EHD].  [Wiki](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege) has been updated with this info.  Some of the salient points:

``copy/clone AND split operations``:  copy all properties and roles to new concept.  SME is responsible for modifying whatever needs to be modified.

``retire``:  OK as written in the [wiki](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege).

``merge``: copy all properties from retiring to surviving concept.  The copied PT/NCI full_syn copied from the retiring to the surviving concept needs to be converted to an SY/NCI full_syn.  Conversions of primitive <-> defined may have been defined elsewhere but those rules are not superseded here.  The SME is, again, responsible for modifying or resolving other issues.  

For all these complex edits, check that the resulting concepts don't have 2+ PT/NCI full_syns.

**Comment by NCIEVS** [comment]
From [EHD] & [NT], triaging.

"First item, 2 PTs are in the Cloned concept but user cannot Save until one has been modified. Additionally, the GUI also won't allow a Save if there are multiple NCI DEFINITION items.

"Second item, no longer an issue, other changes can be made prior to resolving the 2 PTs.                                       

"Third and fourth items, one can still click on a role or a filler value and the hierarchy focus and restriction enforcement will change to that of the branch of said role name or filler value. I don't know if the GUI will prevent the instantiation or Save of an inappropriate role as usually the editor will recognize that the wrong role choices are there and won't assign the inappropriate ones. Someone would need to do testing to purposely "break" this. Additionally, the editor can disable the internal links."

**Comment by NCIEVS** [comment]
Clarification on "first" above:  "Yes, this was fixed in a past version. We may want to revisit the message that popups up and alerts the editor that they cannot Save with 2 NCI PTs or 2 NCI DEFs."

Clarification "third & fourth":  "This is different, this issue is not talking about when the edit panel focus changes to a different concept. I have mostly seen this occur during use of the Complex Edit tab. In some cases, during a Copy or other Complex Edit, the hierarchy pane (and thus the role domain) can become focused elsewhere. The role choices become inappropriate for the concept being edited but I don’t know if the GUI can recognize this disconnect and still properly enforce domain-range restrictions. (When I see this disconnect, I recognize the issue and Save without adding roles. Once I am certain the GUI (meaning both the Edit tab and hierarchy pane) is focused correctly, then I add roles.)"

This ticket will be closed and a new one (#513) opened for the new issue described in "third & fourth".
