### ISSUE TITLE
path delimiter issue in metaproject

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#15]
Build/distribution 9/21/2016.
Editing the metaproject with a client running in windows and a server running in linux results in a path in the file that reflects the windows delimiter.  When the server restarts, it cannot find the history files.  Example from the server-configuration.json file:  "file": "root\data\foo\foo.history"

**Comment by bdionne** [comment]
This is a [known](https://github.com/protegeproject/protege-server/issues/31) protege issue

**Comment by NCIEVS** [comment]
This was fixed and has been in use for several months.  Will label bug for v1 release with fix and close.
