### ISSUE TITLE
reports don't include multiple qualifiers

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#151]
will have to check this one.  The feedback was:

[using nci-0.115} was able to generate a report with pipes between the instances of a property. However, it turns out that you cannot export more than one annotation on a property. For the attached file I selected Preferred_Name and FULL_SYN. For FULL_SYN, I selected the annotations subsource name, source code, term source, and Term Type [i.e. term-group element]. Only  the last one I chose is in the file.

[lucene-export_DNA_2.txt](https://github.com/NCIEVS/nci-protege5/files/685536/lucene-export_DNA_2.txt)

**Comment by NCIEVS** [comment]
This might be an issue with the visibility of the selected qualifiers, can't see them so an error in selecting them (a multi-selection must be done, can't be done one by one) could result in only the last one being actually selected for export.  Probably both are needed:  1) allow one-by-one selection of qualifiers, and 2) make the selected qualifiers visible in the export dialog.

**Comment by bdionne** [comment]
I agree the visibility is an issue. I can look into it, but if I recall it was a bit of work so I decided to get something working in the interest of schedule

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

When users select qualifiers on the annotation properties, they now show up in the list. This behavior is seem in the report write and the Lucene exporter dialogs.

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag-118, edittab-0.3.4.  Please see attached zip file for screen shot and report.  
OS: Windows7
Local server: 8080, Modeler
[lucene-export-Multiple Qualifiers.zip](https://github.com/NCIEVS/nci-protege5/files/746485/lucene-export-Multiple.Qualifiers.zip)

Thanks,
Reza
