### ISSUE TITLE
wraparound on the lucene results panel

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#152]
Some labels are long and they might extend beyond the visible portion of the panel at any given size of the GUI.  Would be good to have wraparound of the text in this panel.  Timeline is 'future release' but might be re-evaluated after UAT.

**Comment by singhik** [comment]
@bdionne :: Hi, Concept created with long label is **not** wrapped around the Lucene Search Panel ::

Concept created with long label ::

![image](https://user-images.githubusercontent.com/36314371/51046126-4431c900-1593-11e9-9af0-679effb516ba.png)


Lucene Search does not show the complete name wrapped in the next line ::


![image](https://user-images.githubusercontent.com/36314371/51046218-7fcc9300-1593-11e9-901f-0d9e30c3a125.png)

**Comment by bdionne** [comment]
Fix for this turns out to be in OWLCellRenderer, so will be in the next release

**Comment by bdionne** [comment]
This is resolved now, needed a change in protege and will be in next tag

**Comment by singhik** [comment]
Tested on Protege Client 3.1.0, works as Expected hence closing the ticket
