### ISSUE TITLE
export to CSV exports a subset of the resultset

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#154]
If a concept gets somehow selected, or the user scrolls between result set pages, the export function only generates a report of the concepts in the current page and it ignores the concepts in the other pages.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

**Comment by rmehri** [comment]
Hi,
This fix has been retested in tag-118, edittab-0.3.4.   Please see attached zip file for  reports in .txt and .csv for more details. 

[lucene-export_Issue 154.zip](https://github.com/NCIEVS/nci-protege5/files/746257/lucene-export_Issue.154.zip)

Thanks,
Reza
