### ISSUE TITLE
Multiple clients can cause locks

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#155]
Multiple clients editing, all with autoupdater enabled can cause deadlocks in protege if the server is paused.

**Comment by bdionne** [comment]
Not sure how easy this is to test. 

The basic scenario is to run 3 clients against the server. One of them is a workflow manager. The manager pauses the server and the other clients attempt to commit. They get the warning to try later. The manager then resumes the server and the modelers commit. The manager then sees a deadlock. This only sporadically occurs, no matter how low one sets the [autoupdate interval](https://github.com/bdionne/protege-server/blob/master/src/main/resources/server-template/server-configuration.json#L646)

**Comment by rmehri** [comment]
Hi Bob,
I have retested this fix with three and also four clients and followed your steps and received no cause locks on manager's client.  Please see attached zip file to play the video clip for more details.  
Great and thanks,
Reza

[Multi client.zip](https://github.com/NCIEVS/nci-protege5/files/690486/Multi.client.zip)
