### ISSUE TITLE
Revision History- Pressing on History Button causes Java Error When A user is not logged into the server

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#156]
Tag-115
Steps to reproduce:
1.Launch server and client
2.Do not login to server
3. Enable Revision Tab 
4. Click on History then you'll see the following error:

Excluding compile: javax.swing.text.GlyphView::getBreakSpot
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
        at org.protege.editor.owl.client.diff.ui.ReviewButtonsPanel$6.actionPerf
ormed(ReviewButtonsPanel.java:173) ~[na:na]
Please see attached zip file to play the video.
Thanks,
 Reza

[History _Button_Error.zip](https://github.com/NCIEVS/nci-protege5/files/687533/History._Button_Error.zip)

**Comment by bdionne** [comment]
I'm not sure what the bug is here? Is there something you expect the revision tab to do without being logged in?

**Comment by NCIEVS** [comment]
Won't fix this one.
