### ISSUE TITLE
some Save/focus issues are still occurring, we need a reminder of unsaved changes

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#157]
Although once we start editing the GUI retains focus on the edited concept until a Save or a Clear, the focus isn't always retained and it's possible to navigate away without Saving.  It would be good to have a reminder that a halfway-edited concept still exists before exiting the GUI.  From EHD:

"One could go to Server>Show Uncommitted Changes before exiting every time, but this is not a great workaround, as an editor would need to remember to do this every editing session; there is currently no visual indication that this menu option is available or may need to be exercised."

On Close, we could have a pop-up that indicates that there are uncommitted changes.  To go along with this, we would have to disable the current Save dialog as it's only applicable to working in file mode, not client-server mode.  I'm setting this up for future release, but depending on further evaluation and UAT results we might need to push it into v1.

**Comment by bdionne** [comment]
Yes this is all problematic still for a few reasons.

With respect to the `Server/Show Uncommitted Changes` though, we need to add something for this, because originally the thinking was that we'd be hiding the server menu items from the modelers, only to be used by managers

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

Navigation pane is no longer locking when a class is being edited. A user can navigate elsewhere and warnings occur when trying to edit a different class when an edit is in progress.

**Comment by rmehri** [comment]
Hi, 
This fix has been retested in tag-118. edittab-0.3.4.  Verified the following:
1) Selected one concept and tried to edit but did not save or clear it. Then selected the second concept and tried to edit it and received the warning message. 
2) Selected two concepts and tried to do dual editing but did not save or clear them. Then select the third concept and tried to edit it and received warning message. 
Please see attached screen shots for more details.


![dual third class_editing-1](https://cloud.githubusercontent.com/assets/8367102/22516172/ed5c70fc-e872-11e6-8563-aa40524bcdbf.png)
![second class_editing-1](https://cloud.githubusercontent.com/assets/8367102/22516181/f325a9b8-e872-11e6-9681-f818f476679b.png)

Thanks,
Reza
