### ISSUE TITLE
batch editing - future tool support

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#158]
In an attempt to do a batch load, TQ on 1/5/17 10:58 AM:

"What should I do to get Protégé to recognize a newly created concept so that I can add children to it? Index?  I manually created Blue Gene and tried a batch load with an old parent and a new parent. And, this time, the error message is correct, the children were not created."

As it turned out, the batch load worked correctly and the issue was a typo in the superclass's fragment IRI.  

We should figure out what can be done to support the creation of batch edit/load files in a future tool/plugin.  Some kind of validation (which could perhaps be done even before attempting to batch load) might not be enough, as the typo'd IRI could have well matched an existing IRI so the batch load would have proceeded successfully but against the wrong superclass.

**Comment by NCIEVS** [comment]
Feature for tool support:  search/replace special characters like from MS Word, smart quotes, non-breaking spaces/dashes, so on.  Characters be configurable by the user.

**Comment by bdionne** [comment]
Prototype was developed and users did not want to adopt it over their existing processes.
