### ISSUE TITLE
the user can still navigate away from a concept while "in edit"  

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#159]
Related to #157.  From EHD, 1/5/17 11:35 AM.

"I went to the new concept that [TQ] created (Blue Gene) and selected to add a restriction. I didn’t actually add the restriction but had to Cancel or Save to navigate away from the concept using the hierarchy. (Currently, if we look at properties/restrictions but don’t make edits we don’t need to do anything before navigating to a new concept.) I could navigate away from the concept by double-clicking on the results from the Lucene Search Tab. But then the Save and Cancel buttons for the next concept were also highlighted as if I had edited that concept.

When I did add a restriction to Blue Gene but didn’t Save, I could navigate away by double-clicking on the results from the Lucene Search Tab. But then the Save and Cancel buttons for the next concept were also highlighted as if I had edited that concept. Additionally, there was no way to know that there were unsaved changes before I exited protege. "

It seems that this would be typical, go back and forth between Edit and Lucene to check on particular concepts.  At some point you might begin an edit but then miss the Save if you happen to go back to Lucene and are distracted.  We need to prevent this or at the minimum display a notification prior to exit #157.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

The behavior is changed: A user can navigate to other classes, search, etc... and then return to editing. If the user edits another class a warning allows the user to either proceed and throw away changes to the older class, or cancel and back out the new ones.

**Comment by rmehri** [comment]
Hi,
I have retested this fix using tag-118, edittab-03.4. I verified the warning message.   
1)	Selected one concept and tried to edit the property but did not save or clear it.  Then
2)	Click Search and searched for another concept. 
3)	Selected the concept from the search result from step#2, and tried to edit property and received warning message.  I press OK to proceed with editing and then save in this step.
Please see attached screen shots for more details. 

![edittab-1](https://cloud.githubusercontent.com/assets/8367102/22560808/e7a49186-e943-11e6-8ae5-d50fcdc0080f.png)
![edittab-2](https://cloud.githubusercontent.com/assets/8367102/22560811/e9895b58-e943-11e6-9fac-bf68337bdefc.png)
![edittab-3](https://cloud.githubusercontent.com/assets/8367102/22560814/ead28b92-e943-11e6-8ce8-6bdc8f68dd38.png)

Thanks,
Reza
