### ISSUE TITLE
Definition reviewer name and date should be read only

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#160]
During editing these are set in the dialog when the user adds a new row to the table or edits an existing one. They should not be editable

**Comment by NCIEVS** [comment]
Edits happening in the ComplexEdit tab should also be covered, the dates & usernames should be updated here as well.

**Comment by NCIEVS** [comment]
By agreement we'll include these read-only properties/qualifiers in the configuration json file, under the "immutable_properties" field.

**Comment by bdionne** [comment]
this is partially fixed in the [`0.3.0`](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.3.0) plugin build, the edits that occur in the complex tables

**Comment by rmehri** [comment]
This fix has been retested using and verified that definition reviewer name and date are read only. Please see attached snapshot for more detail.
Used Tag-116. 
![untitled](https://cloud.githubusercontent.com/assets/8367102/21724602/16fbb53c-d403-11e6-9c4b-2b94c7d05b0b.png)
Thanks,
Reza
