### ISSUE TITLE
Warn user when batch input file and report log are the same name

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#161]
A common workflow is to cut/paster the input file name to the report log field and change the extension. If the modeler fails to change the extension warn them that the file names are identical

**Comment by YinghuaXu2** [comment]
Fixed in https://github.com/bdionne/nci-edit-tab/commit/f08b580499b03ee77a8dc506621a4c2693ef4e2b

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.3.1)

**Comment by rmehri** [comment]
The fix has been retested and verified using tag-116, NCI edittab-0.3.1. 
Please see attached screen shot for more detail. 

![batch file_warning message](https://cloud.githubusercontent.com/assets/8367102/22223381/bb85e72a-e188-11e6-9c25-8b4d5cf397c0.png)

Thanks,
Reza
