### ISSUE TITLE
Constrain domains/ranges when editing descriptions in complex edit tab 

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#162]

**Comment by bdionne** [comment]
This is working as it does in the edit panel. It does have one quirk, the very first time one goes to add a role on any class, the properties will not be restricted. 

This is due to the nature of how Protege loads the plugins, and will be fixed in the next release. The simple workaround is to just cancel and re-enter the object property panel again. Once this is done anytime after the app is loaded it will work thereafter

**Comment by rmehri** [comment]
This issues will be retested on next release.

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
I updated this ticket for further clarification.
Thanks,
Reza

**Comment by bdionne** [comment]
Not sure what you mean by reference point?  "the very first time one goes to add a role on any class, the properties will not be restricted." 

You can use any class
