### ISSUE TITLE
lucene searches on full strings

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#163]
Feature request, to have full property values (e.g. an entire synonym) indexed by lucene.  We currently have a workaround that takes into account rdfs:label but not the full_syn property.  This should be done so the properties that get indexed is admin-configurable, as we wouldn't want to index textual definitions.

**Comment by NCIEVS** [comment]
related to #91

**Comment by bdionne** [comment]
[fixed in 1.0.7](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.7)

**Comment by rmehri** [comment]
Hi Bob, 
I retested this fix using nci-1.007, Lucene Search 1.0.7.  If Full_SYN value (PT/NCI) is too long the search fails.   
Example 1- Used Query Type = exact match -string
I edited the name of Full_Syn from “COMT Gene” to “COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene, COMT Gene,” 
Problem: In lucene search, the Full_Syn field value does not do text wrap up. So property and Query Type fields push to the left side and won’t be readable unless extend the search panel to the right side.
Example 2- Used Query Type = starts with – string
I edited the name of Full_Syn from “COMT”
The search resulted with full values.

Does fix apply to all properties? Or, only Full_SYN?  Please see attached snapshots for more details and  let me know your thought. 

![issue-163-1](https://user-images.githubusercontent.com/8367102/28042132-0722b97a-659a-11e7-8a53-221f08d3e646.png)
![issue-163-2](https://user-images.githubusercontent.com/8367102/28042134-0a3e8bac-659a-11e7-80bc-a4fcb0f4055f.png)
![issue-163-3](https://user-images.githubusercontent.com/8367102/28042140-1207114c-659a-11e7-85e7-d385fe3c8761.png)
![issue-163-4](https://user-images.githubusercontent.com/8367102/28042142-13ce1714-659a-11e7-969d-9e9188df57b4.png)
![issue-163-5](https://user-images.githubusercontent.com/8367102/28042145-16d96a94-659a-11e7-96b7-f3e6f64798ae.png)

Thanks,
Reza

**Comment by bdionne** [comment]
I will look at it. There is n issue with lucene query syntax characters in the indexed fields, though your test case doesn't seem to have those.

Though you can't read the full string, even a large query string that you cut/paste into the box should work.

I'm sure we have a requirement to support large wrapped text strings in the query input. The intent here was so support the users searching for simple `FULL_SYN` values, .eg. `blue ongonene removed` 

Currently we index all the properties, so it should work with any

**Comment by NCIEVS** [comment]
RE large wrapped text strings.  As of now I would say we don't have this requirement.

**Comment by rmehri** [comment]
Hi, 
Thanks for your feedback.  I have extended my retesting for this issue using latest tag nci-1.008, Lucene Search Tab 1.0.7, Edit tab - 0.6.6.  Based on the latest feedback about the requirement, this ticket is closed for now. 
Thanks
Reza
