### ISSUE TITLE
notification when indexing the vocabulary

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#165]
Feature request to have a separate widget to notify the user of the progress &/or completion of the indexing.  Currently if the indexing is begun in a tab other than the lucene search tab, the progress indicator isn't displayed once the user navigates to the lucene tab.

**Comment by rmehri** [comment]
Hi,
This issue will be retested on next release.  
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This issue has been retested using nci-1.005, edit tab-0.5.9.

Thanks,
Reza
