### ISSUE TITLE
prompt for a definition when creating a concept via the GUI

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#166]
This would apply to 
- creating concepts outright using the "child" icon in the tree widget
- creating concepts via copy on the complex edit panel

**Comment by bdionne** [comment]
same error as #391 - bad `gencode` file

**Comment by singhik** [comment]
@bdionne :: Hi Bob , The new 'Create a new OWLClass' dialog prompt with Definition creation option has **three deviations** ::

1. The List 'def source' does not show the list of available definition sources f.e. NCI,NCI-GLOSS etc  ?

![image](https://user-images.githubusercontent.com/36314371/42697825-32165d32-868a-11e8-9f82-fa78b4c19afa.png)



2. The list verbiage name is 'Definition Source' while adding complex properties and in the new 'Create a new OWLClass' is 'def Source'   and 'Definition_Reviewer_Name' and 'Definition_Review_Date'  are missing underscore _  in the naming convention of the corresponding objects in the new 'Create a new OWLCass' dialog prompt ::


3. The field 'attribution' is missing from the new 'Create a new OWLClass' dialog prompt ::


![image](https://user-images.githubusercontent.com/36314371/42698124-fb23b3c8-868a-11e8-98cc-47b701c98f0a.png)

**Comment by safrant** [comment]
For point 1, on QA the definition creation is not creating a default def-source of "NCI".  The def-source is blank.  Does this require an extra configuration step in the metadata project?

**Comment by NCIEVS** [comment]
@safrant , no, the vocab is already configured, it's the dialog that is not fetching the appropriate info.

**Comment by singhik** [comment]
@bdionne  :: Hi Bob, 'Create a new OWLCLass' dialog prompt does show up 'Definition Source' list of values but it **does not** get displayed/selected  post Concept creation :: 


![image](https://user-images.githubusercontent.com/36314371/42768489-a67a43ae-88ed-11e8-8a7b-a7dabca70622.png)


![image](https://user-images.githubusercontent.com/36314371/42768508-b11d2146-88ed-11e8-836c-a2a99f5948d5.png)

**Comment by bdionne** [comment]
@singhik - not sure I follow, your screen shots seem to indicate it's working, what's the issue again?

**Comment by NCIEVS** [comment]
@bdionne , it's the "definition source", it's not showing in the table although the class was created with one (in the class creation dialog "NCI" shows selected).

**Comment by bdionne** [comment]
@singhik - ah, I see, nice catch, will add this to the list

**Comment by bdionne** [comment]
@singhik - this is fixed on [0.8.8](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-0.8.8), update the plugin.

**Comment by singhik** [comment]
@NCIEVS :: Hi , w.r.t  "creating concepts outright using the "child" icon in the tree widget" , does this apply only to 'NCI Edit Tab' ->'Add SubClass'  Icon ? Or it also applies to 'Entities->Classes->Add SubClass' Icon as well ?
As for the second one, the 'Create a new OWLClass'  Dialog prompt is pointing to Old window with no option for DEFINITION : : 

![image](https://user-images.githubusercontent.com/36314371/42825027-1d54a9d0-89af-11e8-9ed0-0c59187f950d.png)

**Comment by safrant** [comment]
Entities is part of the main protege, not our local editing tab.  It is not included in any of these requirements and is not part of our development.  The entire tab can be ignored except as a source of comparison for data.

**Comment by singhik** [comment]
QA has verified new concept creation prompt window to work successfully for Concept creation alongwith DEFINITION creation  via :: 

NCI Edit Tab->Add Subclass   Icon
NCI Edit Tab->Complex Edit->Copy  Radio button operation 

Detailed screen prints are attached and closing the ticket ....

[Issue 166.docx](https://github.com/NCIEVS/nci-protege5/files/2202271/Issue.166.docx)
