### ISSUE TITLE
support for dual editing

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#167]
Related to #149 

Along the lines of the Copy functionality in the ComplexEdit tab.  However, arbitrary classes can be added to each panel, and the main idea is to support copy-and-paste (or cut-and-paste) between the pair of classes, whether the entity is an annotation, a restriction, or a "complex" property/annotation.

Setting up for V1 release, but timeline can be reconsidered taking into account effort & deployment constraints.

**Comment by bdionne** [comment]
The complex edit panel now has a new radio button, `dual edits`. When selected, any two classes can be dragged/dropped onto the panel. 

Additional the user can use the copy/paste menu item to copy properties/roles from one panel to the other.

**Comment by rmehri** [comment]
Hi Bob, 
I have retested this new functionality and verified that I can drag and drop two different concepts and even one concept in both source and target panels.   I also can edit/copy and paste  the property qualifiers as well. Please see attached screen shot for more detail. 

![dual editing functionality](https://cloud.githubusercontent.com/assets/8367102/22452167/6f7f2f8e-e742-11e6-89f3-6af5ac943080.png)

 Thanks,
Reza
