### ISSUE TITLE
annotations on annotations are not indexed on creation

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#168]
This needs an old jar to test, e.g. 0.2.9 on nci-0.115, since > 0.3.0 will not let you edit some fields for instance the "definition reviewer name".  If you edit e.g. a DEFINITION, the new/edited DEF will get indexed right away, but if you add a qualifier to the definition, e.g. 'definition reviewer name' = 'Santa Claus', it's not not indexed and you need to rebuild the indices.

Setting for V1 release, but has a workaround so can be considered for future release.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

**Comment by rmehri** [comment]
This fix has been retested in tag -118, edit tab-0.3.3.   Please see attached zip file for more details.

[Issue-168.zip](https://github.com/NCIEVS/nci-protege5/files/743303/Issue-168.zip)

Thanks,
Reza
