### ISSUE TITLE
batch edit failure on qualifiers

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#169]
A batch edit of DEFINITIONS is only partially successful, a number of qualifiers are batch-edited in, but some others aren't.  In this particular example (attached), the 'definition review date' failed to go in.

Related to #143 

[TQv6-Def.txt](https://github.com/NCIEVS/nci-protege5/files/690574/TQv6-Def.txt)

**Comment by NCIEVS** [comment]
This one turned out to be a typo in the "definition review date" element (in the "Defintion" portion).  After fixing the typo the batch edit worked fine.  However, in the initial batch edit with the typo the log didn't notify of an issue, each row was "successful".  Incorrect logging is still an issue (although not as bad as a failure in the batch edit itself).

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag-120, edit tab-0.3.7.  I received the correct logging for the invalid qualifier.  Please attached zip file for batch edit files for more details. 

[RMv3-Def-With NoTypo-Tag-120-Out.zip](https://github.com/NCIEVS/nci-protege5/files/764282/RMv3-Def-With.NoTypo-Tag-120-Out.zip)

Thanks,
Reza
