### ISSUE TITLE
Sort classes alphabetically in classes pane

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#17]
When new classes are added they should be sorted immediately

**Comment by bdionne** [comment]
Couple of things going on here:

An [off by one](https://github.com/protegeproject/protege/pull/527) bug in Protege I believe, which can cause 'windows baz' to sort before 'windows bar' 

More importantly, the tree view doesn't refresh when new nodes are added. I can force one, there is a refresh method in protege 5 that we have access to. It will re-open to the newly added class, however it will also collapse other nodes. Notice the following two screen shots:

<img width="1012" alt="screen shot 2016-09-09 at 9 54 04 am" src="https://cloud.githubusercontent.com/assets/31741/18390220/488b441c-7677-11e6-87fc-8d7cb7772797.png">

<img width="1020" alt="screen shot 2016-09-09 at 9 54 32 am" src="https://cloud.githubusercontent.com/assets/31741/18390228/52269486-7677-11e6-8c97-bdebd007d149.png">

**Comment by NCIEVS** [comment]
This appears to have been fixed.  Can go through more testing in QA.  Will mark it as enhancement ready for QA for v1 release.  If it fails in some cases, will downgrade to future release (this functionality doesn't exist in our current production environment).

**Comment by rmehri** [comment]
I have retested and validated this fix that when a new class is added to the tree it gets sorted immediately. This issue can be closed.  Please see attached screen shot for more detail.
