### ISSUE TITLE
utilize PT for validation of batch loads

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#171]
Temporary workaround to use when creating concepts in batch (loads).  Query the vocabulary with the term in each row and if it matches "case insensitive" with an existing rdfs:label/Preferred_Name then fail that edit.  But continue with the batch loads of non-existent concept/terms.  The user will need to create those concepts manually.

This one we should try to get in V1.

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.3.4)

A search is now run on each of the `preferred_names` in a batch load. If the name already exists then an error is created in the log for that record.

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified the error message using tag-120, edittab-0.3.7  when the  preferred names that exist. Please see attached Batch Edit files for more details. 

[ADD ClassByName_Tag-120.txt](https://github.com/NCIEVS/nci-protege5/files/764435/ADD.ClassByName_Tag-120.txt)
[ADD ClassByName_Tag-120_out1.txt](https://github.com/NCIEVS/nci-protege5/files/764437/ADD.ClassByName_Tag-120_out1.txt)

Thanks,
Reza
