### ISSUE TITLE
reports have trailing field delimiters

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#172]
self explanatory

**Comment by bdionne** [comment]
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by rmehri** [comment]
Hi, 
Can you please elaborate more about this reports enhancement? We already have the field delimiters.

Thanks
Reza

**Comment by rmehri** [comment]
Hi, 
This has been retested using latest tag 1.008. It is not showing fixed. Please see attached files for more details and let me know your thought.

[lucene-export-172.xlsx](https://github.com/NCIEVS/nci-protege5/files/1159651/lucene-export-172.xlsx)
[lucene-export-172-2.xlsx](https://github.com/NCIEVS/nci-protege5/files/1159652/lucene-export-172-2.xlsx)

Thanks,
Reza

**Comment by bdionne** [comment]
[fixed in 1.0.8](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.8)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using 1.008, Lucene search 1.0.8. Please see attached files for more details.

[ReportWriter.xlsx](https://github.com/NCIEVS/nci-protege5/files/1178722/ReportWriter.xlsx)
[lucene-export.xlsx](https://github.com/NCIEVS/nci-protege5/files/1178727/lucene-export.xlsx)

Thanks,
Reza
