### ISSUE TITLE
assigning users to projects in the admin panel - some sort of grouping is desirable

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#179]
Currently users get assigned roles over a project.  If a project gets created all the users that need access to that project need to be granted the role manually.  It would be good to have some sort of grouping of editors so that updating the group<->project will update the access of all editors in that group.  Dealing with the editors individually would be error prone.

**Comment by bdionne** [comment]
Not sure this is still necessary given the ability to squash history. Once a set of `Workflow Modelers` are assigned to the project, it won't need to be done again. It's not clear that adding additional groupings is worth the added complexity

**Comment by NCIEVS** [comment]
Agreed.  This won't be necessary when projects are squashed.  I think we can close it with 'wontfix'.
