### ISSUE TITLE
pellet appears to extract elements twice before classification

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#180]
Not sure that this is required (we also see it in P3.x).  Question for C&P.  The output in question from the server is:

INFO: Loading ontology d9c238f8-d782-44e6-9ea0-c32b12652b5f
Classifiying 1 elements
Classifiying:  100% complete in 00:00:00.002
Classifiying finished in 00:00:00.005
Jan 11, 2017 2:18:52 PM com.clarkparsia.pellet.server.protege.model.ProtegeServerState createOntologyState
INFO: Loaded revision 0
Jan 11, 2017 2:19:55 PM com.clarkparsia.pellet.server.protege.model.ProtegeOntologyState updateOntology
INFO: Updating State(http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl) from #0 to #327
Loaded ontology, now updating from server
Jan 11, 2017 2:20:05 PM com.clarkparsia.pellet.server.model.impl.OntologyStateImpl update
INFO: Classifying updated ontology Ontology(OntologyID(OntologyIRI.... <snip>....</snip>
**Extracting 125638 elements
Extracting:  100% complete in 00:02:45.782
Extracting finished in 00:02:45.783
Extracting 125638 elements
Extracting:  100% complete in 00:02:33.379
Extracting finished in 00:02:33.380**

This step (in bold above) is only 2 mins each time, but it makes you wonder about what else the server might be doing twice.

**Comment by bdionne** [comment]
#204 -- this is one of the issue in that larger ticket
