### ISSUE TITLE
Protege server needs to support multiple authentication methods

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#181]
The protege server can authenticate users locally or via LDAP.  But the pellet server will most likely only be able to use local accounts in production. The users in the metaproject already have a login mechanism associated with them; the protege server could authenticate itself or pass on to LDAP based on that setting.  I think we'd need this on v1 unless we create local accounts for all our users.

**Comment by bdionne** [comment]
We've added the default login authentication as a backup to the `LDAP` authentication, available as of the `nci-0.120` build. This is a workaround for the problem that the protege user does not have an `LDAP` account. An attempt is made to use the configured login service. If it fails then the default login service is tried

**Comment by rmehri** [comment]
Hi Bob,
 Thanks for your feedback! We'll discuss about this ticket in tomorrow's meeting.
 Reza

**Comment by rmehri** [comment]
Hi, 
This enhancement has been retested and verified using tag-120, edittab-0.3.8.
Sever: https://nciws-d699-v.nci.nih.gov:9090
Login: My LDAP

Thanks,
Reza
