### ISSUE TITLE
pellet traffic with the protege client will be required to use https

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#182]
Before we can open pellet & protege at the firewall, we'll need to have https for all communications.  The pellet server can already use https to talk to protege, but this is as a client and I'm not sure that as a server the protege desktop could communicate to pellet via https.  For v1 we could restrict ourselves to VPN and keep protege & pellet behind the firewall.

**Comment by bdionne** [comment]
As of `nci-0.119` the pellet server now supports `HTTPs`

**Comment by bdionne** [comment]
The protege client communicates with the pellet reasoner. This pellet reasoner is running as a separate server. It needs to be able to support HTTPs since clients will be running outside the firewall.

`HTTPs` can be enabled in the pellet server by changing the host url in the pellet server settings file to being with `https` rather than `http`

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! We'll discuss about this ticket in tomorrow's meeting.
Reza

**Comment by rmehri** [comment]
Hi, 
This enhancement has been retested and verified using tag-120, edittab-0.3.8.
Sever: https://nciws-d699-v.nci.nih.gov:9090
Login: My LDAP
https://github.com/NCIEVS/nci-protege5/issues/25
https://github.com/NCIEVS/nci-protege5/issues/181
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This issue was closed accidentally.  This issue will remain open for further resolution. 

Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I tried to setup the Pellet server for the local client and it fails.  Please see screen shots and log files  for more details.

2017-03-21 17:20:42.811 [Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: Axiom: TransitiveObjectProperty(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Disease_May_Have_Normal_Cell_Origin>).
org.mindswap.pellet.exceptions.UnsupportedFeatureException: Axiom: TransitiveObjectProperty(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Disease_May_Have_Normal_Cell_Origin>)
	at com.clarkparsia.pellet.owlapiv3.PelletVisitor.addUnsupportedAxiom(PelletVisitor.java:215) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletVisitor.verify(PelletVisitor.java:260) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletReasoner.refresh(PelletReasoner.java:958) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletReasoner.<init>(PelletReasoner.java:334) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletReasonerFactory.createReasoner(PelletReasonerFactory.java:68) ~[na:na]
	at com.clarkparsia.pellet.owlapiv3.PelletReasonerFactory.createReasoner(PelletReasonerFactory.java:32) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]

![pellet_setup](https://cloud.githubusercontent.com/assets/8367102/24172695/8170cfc4-0e5f-11e7-9015-acc2fd0c017d.png)

[Pellet_Setup.txt](https://github.com/NCIEVS/nci-protege5/files/859772/Pellet_Setup.txt)

Thanks,
Reza

**Comment by bdionne** [comment]
Not sure what to make of this. That exception indicates something the reasoner deliberately threw because a feature is not supported.

@rmehri - can you attach the pellet server config file you are using?

**Comment by bdionne** [comment]
@rmehri - it would also be good to see the Pellet console when it comes up. Did the classification complete?

**Comment by rmehri** [comment]
Hi Bob,
About classification complete? No It did not even start it.  But I have replicated the same on different machine and the classification ran but it resulted with the same error as I reported.  Also, I am not sure about specific Pellet console log. Do you mean the protégé client log file? If so, Yes I have it. About pellet server config file?  I see only “server.roperties and server configuration”.  Please see attached zip for more details and let me know if you need more information.

[Pellet_Log File_Server_Config.zip](https://github.com/NCIEVS/nci-protege5/files/861902/Pellet_Log.File_Server_Config.zip)


Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - Are you running the pellet server? The protege client communicates with the pellet reasoner. This pellet reasoner is running as a separate server. When you configure the reasoner in protege to use `remote` and point it to `http://localhost:18080` it assumes there is a pellet server running there at that port. If you configure it to local it will use the classifier bundled with protege. 

The `server.properties` file in the zip looks like a default one, and it would not work as is. Mainly it's missing an entry that specifies which project to classify. [Here](https://github.com/bdionne/pellet/tree/master/server) are detailed instructions for starting the pellet server, and attached is the `server.properties` from my machine. 

There's a couple of thinks to note. It needs to specify which project or projects in protege to classify, .eg.:

````
protege.ontologies=1c7556a8-bdc4-48a3-9cfe-5d434b5748fb
````

The pellet sever and protege communicate in both directions. Pellet talks to protege using:
````
protege.host=localhost
protege.port=8080

and protege talks to pellet using:

````
pellet.host=https://127.0.0.1
pellet.port=18080
```` 
Pellet can listen for `http` or `https` traffic, that's why you see the `https://127.0.0.1` above.
Pellet also assumes the protege server is listening for `https`. 

So in order to test this ticket both servers need certificates set up. Not sure how this works on windows but on linux and OS X, system properties are passed in to the startup scripts, with the names of the certs and password, .eg.:

````
-Dorg.protege.editor.owl.server.security.ssl.keystore=my_foo.jks
-Dorg.protege.editor.owl.server.security.ssl.keystore.type=JKS
-Dorg.protege.editor.owl.server.security.ssl.password=xxxxxxx
````

When you start the pellet server, you will see it connect to protege, pull the project over and classify. After that when you connect from protege to the reasoner you will be able to see the asserted view and get explanations.

**Comment by rmehri** [comment]
Hi Bob,
Thank you for your information and detailed instructions. I will follow and retry. 
Reza

**Comment by NCIEVS** [comment]
Closing this one, https is being used in production.
