### ISSUE TITLE
Tag116-Merging Old Concepts causes Exception Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#183]
Steps to reproduce:
 OS: Windows7- Server: https://nciws-d699-v.nci.nih.gov:9090, user: Alice (Manager) Tag-116, =NCI Edit Tab 0.3.1
1.Select Edit tab
2.Used the following concepts:  
 IL-2R Alpha-Positive Neoplastic Cells Present "C71599" was the surviving partner and CD25-Positive Neoplastic Cells Present "C70850" was the retiring partner.
3.Click Merge then the exception error occurs.
Note:  Referenced Issue https://github.com/NCIEVS/nci-protege5/issues/126

Please see attached zip file for screen shot and log file for more details.
[Merge_Error.zip](https://github.com/NCIEVS/nci-protege5/files/724716/Merge_Error.zip)

 Thanks,
 Reza

**Comment by bdionne** [comment]
This is the same issue as #126
