### ISSUE TITLE
Tag-116-Batch File -Adding Class Children By Name to Parent Class is Failing

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#184]
Steps to reproduce:

1.	Launch server and client
2.	Log into local host http://localhost:8080, Use "alice" Manager
3.	Select NCI Edit tab
4.	Select Batch Load/Edit
5.	Use attached batch file and start the process and you’ll see the error massage that the super class does not exists, while the parent class exists in the batch file. 
Question:  for adding children to a class by name, are we going to use the same format as before? 
Or else?  See below:  
"Class name, preferred name, class parent"  
Please attached zip file for snapshot and batch files for more detail.
[Protege_ByName_Load_v3_Out.zip](https://github.com/NCIEVS/nci-protege5/files/727125/Protege_ByName_Load_v3_Out.zip)

 Thanks,
 Reza

**Comment by bdionne** [comment]
Hi @rmehri -- as I mentioned in the email to you earlier today:

"Batch load now takes two fields: 1. The preferred name of the new class and 2. The IRI fragment of the parent class".

I'm assuming you are testing batch load, correct?  You are using the old format, which is incorrect.

You may want to wait until the next build before opening new tickets against batch load/edit. The WIKI will be updated and it's going to change considerably from tickets #169, #170, #171, and #174.

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! Yes.  I will retest them in next build.
Reza

**Comment by rmehri** [comment]
Hi Bob, 
For adding new definitions to a class children, I have retested the Batch file with batch type=Edit, and the following is the results:

1. Cannot get the date into the definition 
2. Any reviewer name is accepted, and I used "This is a test user."
3.The qualifiers like def-source=NCI, , attr =Batch testing are accepted. 

"Used:  https://nciws-d699-v.nci.nih.gov:9090, User: alice (Manager)
Vocabulary: "ncit-owl2-v3-17.01a-test"
Tag-116, Edittab-0.3.1"

Please see attached zip file for input and output file and screen shot for more details. 

[Definition Review Date_Missing.zip](https://github.com/NCIEVS/nci-protege5/files/727990/Definition.Review.Date_Missing.zip)

************************************************************
*Note: By the way, I  have closed the referenced issue  https://github.com/NCIEVS/nci-protege5/issues/185 as duplicate. The email thread below is for development tracking purpose.  

-----Original Message-----
From: Bob Dionne [mailto:dionne@dionne-associates.com] 
Sent: Tuesday, January 24, 2017 11:43 AM
To: Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov>
Cc: Alkis, Barry (NIH/NCI) [C] <barry.alkis@nih.gov>; Fragoso, Gilberto (NIH/NCI) [E] <fragosog@mail.nih.gov>
Subject: Re: Github notes

Thanks Reza,

Please attach this input file to the GH ticket you are testing, so we don’t lose information, and with that let’s conclude this thread?

Best,

Bob

**Comment by rmehri** [comment]
Hi, 
I have retested adding Classes By Names using tag-118, edittab-0.3.5 .  All the records were successfully added into protégé by batch load.  Please see attached zip file for more details. 

[Add_Class_Load-Tag-118.zip](https://github.com/NCIEVS/nci-protege5/files/751606/Add_Class_Load-Tag-118.zip)


Thanks,
Reza
