### ISSUE TITLE
Tag-116-Batch File -Adding Definition Properties to Class Children Failing 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#185]
Steps to reproduce:
1.Launch server and client
2.Log into local host https://nciws-d699-v.nci.nih.gov:9090; User "alice" Manager,
Vocabulary:  "ncit-owl2-v3-17.01a-test"
3.Select NCI Edit tab
4.Select Batch Load/Edit
5.Use attached batch file and start the process and you’ll see the error massage that the super class does not exists, 
Please see attached input file and the email thread below for more details.

[Add_Complex_Annotation_Property.txt](https://github.com/NCIEVS/nci-protege5/files/727400/Add_Complex_Annotation_Property.txt)

Email Thread:
-----Original Message-----
From: Bob Dionne [mailto:dionne@dionne-associates.com] 
Sent: Tuesday, January 24, 2017 11:43 AM
To: Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov>
Cc: Alkis, Barry (NIH/NCI) [C] <barry.alkis@nih.gov>; Fragoso, Gilberto (NIH/NCI) [E] <fragosog@mail.nih.gov>
Subject: Re: Github notes

Thanks Reza,

Please attach this input file to the GH ticket you are testing, so we don’t lose information, and with that let’s conclude this thread?

Best,

Bob
> On Jan 24, 2017, at 11:21 AM, Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov> wrote:
> 
> Hi Bob,
> 
> You're welcome! Please see my answers to notes below and attached batch input file for more details. 
> 
> Thanks,
> Reza Mehri
> Data Science and Information Technology Program (DSITP) Frederick 
> National Laboratory for Cancer Research Operated by: Leidos Biomedical 
> Research, Inc.
> 9605 Medical Center Drive, Suite 280-2 Rockville, MD 20850 Phone : 
> 240-276-5285 BB : 240- 477-3734
> 
> -----Original Message-----
> From: Bob Dionne [mailto:dionne@dionne-associates.com]
> Sent: Tuesday, January 24, 2017 10:59 AM
> To: Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov>
> Cc: Alkis, Barry (NIH/NCI) [C] <barry.alkis@nih.gov>; Fragoso, 
> Gilberto (NIH/NCI) [E] <fragosog@mail.nih.gov>
> Subject: Re: Github notes
> 
> Thanks Reza,
> 
> Please see my answer to note #1 below. If you are testing batch load, the format has changed. I’ve also made this exact comment in the ticket#184 that you just opened.
> 
> Please let me know if you have more questions.
> 
> I hope this helps,
> 
> Bob
>> On Jan 24, 2017, at 9:28 AM, Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov> wrote:
>> 
>> Hi Bob,
>> 
>> I will do that.
>> 
>> Thanks for your feedback,
>> Reza Mehri
>> Data Science and Information Technology Program (DSITP) Frederick 
>> National Laboratory for Cancer Research Operated by: Leidos 
>> Biomedical Research, Inc.
>> 9605 Medical Center Drive, Suite 280-2 Rockville, MD 20850 Phone : 
>> 240-276-5285 BB : 240- 477-3734
>> 
>> 
>> -----Original Message-----
>> From: Bob Dionne [mailto:dionne@dionne-associates.com]
>> Sent: Tuesday, January 24, 2017 6:47 AM
>> To: Mehri, Gholamreza (NIH/NCI) [C] <gholamreza.mehri@nih.gov>
>> Cc: Fragoso, Gilberto (NIH/NCI) [E] <fragosog@mail.nih.gov>
>> Subject: Github notes
>> 
>> Reza,
>> 
>> I think the GH notes facility on the project tracker is not working 
>> as we thought, I’m not able to edit them and respond to your 
>> questions (see below). Going forward please just ask questions in the 
>> tickets you are testing. If they end up spawning new issues we can 
>> add tickets then,
>> 
>> Bob
>> 
>> 
>> ====== note 1. ================
>> Hi,
>> Batch file Load  by name is failing as well as adding property: For adding children to a class by name, are we going to use the same format as before? Or else?  See below:  
>> "Class name , preferred name, class parent"  Thanks, Reza 
>> ================================
>> 
>> Is this about batch load or batch edit? Yes and I received your 
>> answer in issue#184
>> 
>> Batch load now takes two fields: 1. The preferred name of the new 
>> class and 2. The IRI fragment of the parent class
>> 
>> =========== note 2. ===============
>> Here is a line of batch file for adding definition that I used and failed: 
>> C250374	new	DEFINITION	The type of Gene for Testing. 	Definition_Reviewer_Name	This is a test user.	Defintion_Review_Date	2017-01-23	def-source	NCI	
>> 
>> attr	Batch Testing
>> =============================
>> Are you using the tab key for the field delimiter?
> Yes
> If you can attach
>> the test input file to the GH ticket that would be great
>> 
>> ============ note 3. ==========
>> Hi,
>> I am trying to add definition properties to the class children using batch file according to complex property batch format in GITGUB.  and I receive "super class does not exist." Here is a line of  Input batch file.
>> ================================
>> Is this part of note 2? Yes.
>> 
> 
> <Add_Complex_Annotation_Property.txt>

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri -- what is the question?

**Comment by rmehri** [comment]
Hi Bob, 
This ticket has been opened as per your development information and tracking purpose.  I  changed the label to help wanted  and have no question at this time. 
Thanks,
Reza

**Comment by rmehri** [comment]
This is a duplicate issue.  Referenced issue: https://github.com/NCIEVS/nci-protege5/issues/184
