### ISSUE TITLE
Save button is not enabled after editing defined class definition

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#188]

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.3.8)

**Comment by rmehri** [comment]
This fix has been retested and verified using tag-120, edittab-0.3.7. 
Please see attached screen shot for more detail.
![definition_save button](https://cloud.githubusercontent.com/assets/8367102/22789037/d5f575a6-eeaf-11e6-9462-3554b16d07f4.png)

Thanks,
Reza
