### ISSUE TITLE
Improve gestures for copy/paste in description panel

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#189]
currently one has to use keyboard `Ctrl-C` and `Ctrl-V` and it's not clear where to paste. Add drag/drop and/or right click menu items

**Comment by bdionne** [comment]
relates to #208

**Comment by NCIEVS** [comment]
This is really a documentation issue, where to click and so on.  Leave flag as documentation for a future release so it doesn't get dropped, but take it out of the development backlog.

**Comment by NCIEVS** [comment]
Slate for 2.7.0, but note that it might not make it because of the big backend change.

**Comment by singhik** [comment]
@bdionne : #208 talks about 'dual-editing' panel and this #189 talks about 'Description' Panel, neither of them have 'copy'/'paste' buttons and keyboard clip shorcut keys in CTRL+C,CTRL+X,CTRL+V works in neither ?
I also don't find any option to copy/paste via Right click in both 'DUal Edit' and 'Description panel' ?

What is the implementation for this ticket ?

**Comment by singhik** [comment]
@bdionne  : Is this implementation same as #541 ? I don't find any new implementation on Dual Edit Panel from before, Complex Properties had 'Add','Edit','Delete' buttons before and Right click 'Copy' , 'Paste' options are not present in Dual Edit Panel .

What is the implementation as part of this ticket ? Please elaborate .

**Comment by bdionne** [comment]
@singhik - yes, I left a comment in the other ticket. You can now select a term in those panels, but only one at a time. If you select a complex prop it will select all the qualifiers also. You can then choose copy/paste from the edit menu or Ctrl-X/Ctrl-V

>@singhik - yes, thanks. It's been changed in all the dual panes in version [nci-edit-tab-1.3.7](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.7), this will also address single select in the description panels (see https://github.com/NCIEVS/nci-protege5/issues/189)
