### ISSUE TITLE
ReportWriter prefers rdfs:labels on classes

### ISSUE THREAD

**Issue by rwynne** [NCIEVS/nci-protege5#19]
When starting a report classes need an rdfs:label or a dialogue pops up notifying the user the IRI short form will be used instead (requiring a click).  There could be the potential for many of these.  Consider removing the warning.

**Comment by NCIEVS** [comment]
The foo vocab was configured to require rdfs:label, even though not all classes have it.  The NCIt won't generate these repeated warnings since all classes have labels.  Some more user-friendliness can be incorporated in the future to deal with edge cases.

**Comment by NCIEVS** [comment]
Closing ticket.  The rdfs:label is a required entity per the metaproject.
