### ISSUE TITLE
In Revision History tab, would like to also have conflicts flags in the Commits panel

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#192]
Currently the Conflicts are only visible in a column in a Changes panel when focused on one editor.  When the user sorts to find the conflicts much of the providence is lost. It would be nice to show where conflicts are in the Commits panel because then the workflow manager can focus on a single set of edits that have conflicts by clicking on the set of commits.

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using nci-1.0069 and edittab-0.6.5.
Please see attached snapshot for more detail.

![issue-192](https://user-images.githubusercontent.com/8367102/27450328-637ca8e2-5759-11e7-8816-837b0bf9631c.png)

Thanks,
Reza
