### ISSUE TITLE
Connect edited concepts in the Revision History tab to their positions in the hierarchy

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#193]
Currently in the Prompt tab there is a tab that has the hierarchy and when the workflow manager chooses to focus on a change in the Users subtab that concept can also be viewed in the Tree View subtab. This gives the workflow manager some insight into the domain that the edited concept belongs in and can also help the manager decide if the editors in conflict would normally work in the same domain or not.

**Comment by bdionne** [comment]
ready in [revision history](https://github.com/bdionne/revision-history/releases/tag/revision-history-1.0.0). This requires the `nci-1.006` tag

**Comment by rmehri** [comment]
Hi, 
This issue has been retested and verified using  nci-1.006  tag . Please see attached screenshot for more detail. 
![issue-193](https://cloud.githubusercontent.com/assets/8367102/25918621/13487ac6-359a-11e7-954c-6c3d78124039.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - I'm not sure what the screenshots show here, did you upload the wrong ones by mistake?

What you should see in this new plugin is a tree view tab. When you select a commit, the tree view will switch focus to the class that the commit is about. It should change as you select different commits. The window is also floatable and can be detached

<img width="1015" alt="screen shot 2017-05-10 at 4 43 49 pm" src="https://cloud.githubusercontent.com/assets/31741/25920506/35450dbe-35a0-11e7-837f-211655007f8f.png">

**Comment by bdionne** [comment]
Reza, you may not see it for two reasons:

 * not logged in as a workflow manager
 * need to reset to default state

**Comment by rmehri** [comment]
Hi Bob,
I was logged into the protégé. It is working. I did not attach the second screenshot. Because I closed the domain tree to test the default to state for this page to see if it works. That's why you don't see that on first screenshot. Please see attached second screen for more detail.  This issue can be closed.
![issue-193-1](https://cloud.githubusercontent.com/assets/8367102/25923112/043f31c2-35aa-11e7-9ea2-9cc3c958ba09.png)

Thanks,
Reza

**Comment by bdionne** [comment]
nice
