### ISSUE TITLE
Tag-120-NCI-Edit Tab -Classes Contents Not Available

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#194]
Used: 
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
 Logins: Modeler & Manager      

Tag-120 & NCI Edit-0.4 
      
Steps to reproduce:
1)	Launch protégé server and client 
2)	Log into the local server (8080), login: modeler 
3)	Select NCI Edit Tab 
4)	Receive “IndexOutOfBoundsException” error
5)	Select Window/ Reset Selected tab to default state
6)	Select a class or concept 
7)	Under Edit tab you don’t see property tables or etc., and user cannot do anything at this point.
Please see attached zip file for video to play and log file for more details.

[NCI Edit Tab_4.0 Not Loading.zip](https://github.com/NCIEVS/nci-protege5/files/772515/NCI.Edit.Tab_4.0.Not.Loading.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - this works fine for me, and I had Gilberto try also, to see if it's the NCI server. Some questions:

1. Are you using the NCI dev server or your local?

2. can you attach the console log?

3. It looks like the issue could be either the server config file or you OWL project. Is this an older one? Please attach the server config and the OWL file you are using, I'd like see if I can reproduce this locally

It looks like something is out of sync

**Comment by rmehri** [comment]
Hi Bob,
Thanks for your feedback! Please see attached log file and my answers below:
1) Yes both NCI dev server and my local server
2) Please see attached log file for more details.
Please let me know if you need more information. 

[protege_Log file.txt](https://github.com/NCIEVS/nci-protege5/files/774440/protege_Log.file.txt)

Thanks
Reza

**Comment by bdionne** [comment]
Thanks @rmehri , I'd like to also see the OWL file you used to build the local project and the server config file. That way I can try to reproduce

**Comment by rmehri** [comment]
You're welcome! Please see attached zip file for my server config file and OWL files that I used to build my local projects.
[Local project template _Server-Config.zip](https://github.com/NCIEVS/nci-protege5/files/774566/Local.project.template._Server-Config.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
The config file looks fine, not sure what to make of this. Does the problem persist if you exit the application and then bring it back up again?

The problem is that the preferences on your machine are different than what's in that server config, .ie. they are out of sync.

**Comment by rmehri** [comment]
Hi Bob, 
Thanks, yes it does.  I will restart my machine again and also try to use different machine to see if the same issue occurs. I will keep you all updated for the further progress. 
Thanks,
Reza

**Comment by bdionne** [comment]
Reza, I would not waste much time on this, unless it is blocking you from working. If you like you can drop this edit tab jar file into the plugins directory of your protege install. It will at least stop the exception and you can see the the issue is.

[nci-edit-tab-0.4.3-test-SNAPSHOT.jar.zip](https://github.com/NCIEVS/nci-protege5/files/774677/nci-edit-tab-0.4.3-test-SNAPSHOT.jar.zip)

**Comment by rmehri** [comment]
Thanks and will do that.
Reza

**Comment by rmehri** [comment]
Hi Bob, 
I added nci-edit-tab-0.4.3 into plug folder and tested good.  But the plugin shows as "Edit Tab-04.2 instead of 0.4.3"!
Note: the protégé UI has been retested as well.

Thanks,
Reza

**Comment by bdionne** [comment]
please re-open if this is still an issue

**Comment by rmehri** [comment]
Hi Bob,
I have retested this issue using Tag-120 & NCI Edit-0.4.7.  It works fine. Please see attached screen shot for more detail.

![nci edit tab_0 4 7](https://cloud.githubusercontent.com/assets/8367102/23626351/8b94da54-027a-11e7-8be1-11666362ce15.png)

*Note: this ticket will be reopened if the same behavior occurs again. 
Thanks,
Reza
