### ISSUE TITLE
Tag-120-NCI-Edit Tab-Definition Missing Values

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#195]
Used:
 Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
 Logins: Modeler & Manager

Tag-120 & NCI Edit-0.4.2

Steps to reproduce:
1.Launch protégé server and client
2.Log into the local server (8080), login: modeler
3.Select NCI Edit Tab
4.Select a class (Concept)
5.Add definition and you'll some of the values like "definition reviewer name" and "definition review Date" do not get added. 

Note:  repeat step#5 for adding Al-Definition and you'll see the same issue occurs.

Please see attached zip file for video to play for more details.

[NCI-Edit Tab-Add Definition.zip](https://github.com/NCIEVS/nci-protege5/files/777461/NCI-Edit.Tab-Add.Definition.zip)

Thanks,
Reza

**Comment by NCIEVS** [comment]
Could this be a configuration issue?  This doesn't occur in production.  Will close.
