### ISSUE TITLE
Tag-120-ComplexEdit-Copy Radio Buton Not Selected When  a Class is Cloned

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#197]
Used:
 Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
 Logins: Modeler & Manager

Steps to reproduce:
 1.Launch protégé server and client
 2.Log into the local server (8080), login: modeler
 3.Select NCI Edit Tab
 4.Select a class (Concept)
5.Right click on the class and select Clone then 
6.The ComplexEdit page displays. But the "Copy" radio button is not showing selected.  
 
Please see attached screen shot for more detail.

![nci-protege-clone](https://cloud.githubusercontent.com/assets/8367102/22992580/1d90ecaa-f38e-11e6-850f-ced24ba8d4f2.png)

Thanks,
Reza

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.4.4)

**Comment by rmehri** [comment]
This fix has been retested and verified using tag-121, nci-edit tab-0.4.4.
Please see attached screen shot for more detail.

![tag-121-clone](https://cloud.githubusercontent.com/assets/8367102/23040333/f00f0f74-f45e-11e6-9f30-0a11bcff937a.png)

Thanks,
Reza
