### ISSUE TITLE
splitting conjunctions/disjunctions in primitive classes

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#198]
I thought we could do this in earlier snapshots, but disallowing splitting of these expressions in equivalent classes (#42) might have spilled over into primitive classes.  Presently a class expression in a primitive class can't be "split" into its components.  While editing, a change can be reverted with Clear but once you Save you can't restore the original expression.  We would prefer to be able to do these edits from the GUI.  

A workaround with the class expression editor widget is available.

**Comment by bdionne** [comment]
Looks like we need to deal with this for V1. The split subclasses menu item applies to the entire ontology, and the description editor isn't aware of names that name classes and roles.

**Comment by bdionne** [comment]
In the subclasses section of the description pane, a new menu item appears that will allow the user to split up conjunctions and disjunctions.

This requires [nci-0.122]
(https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.122)

**Comment by rmehri** [comment]
Hi Bob,
Thanks, I have retested this ticket and verified the new menu . But when press on "Split up the selected conjunts or disjuncts " nothing happens.  Please see attached screen shot for more details. 

Tag-123, edittab-0.4.6

![untitled1](https://cloud.githubusercontent.com/assets/8367102/23173330/d64d5be2-f826-11e6-959f-244aae834b27.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified.
Thanks,
Reza
