### ISSUE TITLE
self-parenting is currently allowed

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#199]
It's also leading to data loss so it should be prevented.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.122) - the user can no longer add a class as a parent to itself

**Comment by rmehri** [comment]
Hi, 
Thanks for your feedback! This fix has been retested and verified in Tag-123, edittab-0.4.6.  Please see attached screen shot for more detail.
Used login: Modeler & Manager
Local server: 8080

![nci-edit tab- self parenting](https://cloud.githubusercontent.com/assets/8367102/23181450/0d8e8344-f843-11e6-9f3b-665cb221e932.png)

Thanks,
Reza
