### ISSUE TITLE
scripted shutdown of the server

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#2]
This won't be done frequently in production, but it would be good to have a shutdown command/script to enable graceful shutdowns on maintenance periods.

**Comment by bdionne** [comment]
I added a new [shutdown](https://github.com/bdionne/protege-server/commit/3eb627130e5ff1fbab168bdf1524304342f3521b) endpoint to the server, and a sample `shutdown` script that we can use. It's written for just `http` over port `8081` but can be modified as needed for the environment. I've tested it also with the sample self signed cert.

**Comment by rmehri** [comment]
I have tested and verified that "shutdown.sh" in tag-110 successfully. 
Used my localhost 8081
This ticket can be closed.

Thanks,
Reza
