### ISSUE TITLE
drag/drop onto copy operation causes split button to be enabled

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#20]
- Select clone in the complex edit pane
- Drag/drop class onto pane
- Split button becomes enabled

**Comment by NCIEVS** [comment]
However, the operation doesn't change to a "split" action, the "copy" concept (clone) is created.  Might just be a labeling issue.  Setting for v1 release as a bug, but can be downgraded to future release.

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
This fix has been successfully retested in Tag-110. This issue can be closed.  Please see attached snapshot for more detail. 
Thanks,
Reza

![copy operation](https://cloud.githubusercontent.com/assets/8367102/21083620/4a3a8608-bfc2-11e6-9256-b9841b4c709a.png)
