### ISSUE TITLE
copy/paste in dual edits fails with complex properties

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#203]

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by bdionne** [comment]
This is pretty easy to reproduce, it’s best seen by running the nci-0.123 version of protege:

 - login as anyone
 - select any complex operation (split/clone/merge/dual-edit)
 - populate the two panels with any two classes that have complex properties
 - copy/paste any complex property from one panel to the other and see the error

**Comment by rmehri** [comment]
Hi Bob,
Thanks for your feedback! I have retested and verified this fix using tag-125, Nci Edittab-04.9.  This ticket can be closed.  Please see attached screen shots complex properties copied from Source to Target and Vice Versa 

![dual edits-al definition](https://cloud.githubusercontent.com/assets/8367102/23816763/87a002c6-05bc-11e7-872e-562c78de42c5.png)
![dual edits-al definition-1](https://cloud.githubusercontent.com/assets/8367102/23816766/8a3242f6-05bc-11e7-8871-b311293a7e9c.png)
![dual edits-full_syn-1](https://cloud.githubusercontent.com/assets/8367102/23816711/4c225c6c-05bc-11e7-95d4-eecfd5e1f3cd.png)
![dual edits-full_syn-2](https://cloud.githubusercontent.com/assets/8367102/23816713/4dd1131e-05bc-11e7-91b4-ec519be5bc12.png)
![dual edits-definition-1](https://cloud.githubusercontent.com/assets/8367102/23816730/5be1f84c-05bc-11e7-953f-3333beb67a95.png)
![dual edits-definition-2](https://cloud.githubusercontent.com/assets/8367102/23816731/5d91c0dc-05bc-11e7-80f9-74768817b172.png)

Thanks,
Reza
