### ISSUE TITLE
Issues with Pellet

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#204]

**Comment by bdionne** [comment]
* extraction runs twice
 
* memory issues with explanation

 * exceptions

 * results not always shown after editing

 * classification results view is too slow

**Comment by NCIEVS** [comment]
On "classification results view is too slow", the classification panel shows inferences that we don't need, and these are a lot of them, but it doesn't show inferences of interest to us.  For instance, if you state that A isa B, we are not interested in the inference that A isa B, but would be interested if A was inferred to be isa C (as well as isa Nothing, which does show).

**Comment by NCIEVS** [comment]
Individual items have their own git issues and most have been fixed/closed.  Closing this ticket.
