### ISSUE TITLE
Including BatchEditIRIs and ReadOnlyClass panels by default

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#206]
This may have been done already.  
Include batcheditIRIs and readonlyclass panels by default, as there were some quirks activating the tabs.

**Comment by bdionne** [comment]
They are included. If they aren't visible I suspect the usual issue, where the GUI layout is saved as a preference? Is so resetting the state ought to fix it.

**Comment by bdionne** [comment]
pretty sure this is a prefs issues, see nothing that would prevent these form coming up

**Comment by rmehri** [comment]
Hi, 
Retested this issue and see BatchEditIRIs and ReadOnlyClass panels by default.  
Used: NCI-1.0069, nci-edit-0.6.5
Local server "8080"
Please see attached snapshots for more details.
![issue-206-1](https://user-images.githubusercontent.com/8367102/27454722-e9da06c8-5768-11e7-9f65-054173b7f0aa.png)
![issue-206-2](https://user-images.githubusercontent.com/8367102/27454727-ee759972-5768-11e7-9623-0788157ccd94.png)

Thanks,
Reza
