### ISSUE TITLE
Dealing with access at more granular levels

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#207]
Derived from the utilization of Def_Curator and Special_Review.
Increased granularity in access control
- mark properties as restricted, editable only by specific users
- mark concepts as restricted, editable only by specific users
- mark branches as restricted, editable only by specific users

For now, mark definitions with a DONOTTOUCH source replacing Special_Review

See [the wiki](https://github.com/NCIEVS/nci-protege5/wiki/increased-granularity-of-access-control)

**Comment by bdionne** [comment]
[see WIKI for details](https://github.com/NCIEVS/nci-protege5/wiki/increased-granularity-of-access-control)

**Comment by singhik** [comment]
@NCIEVS @bdionne  :: 
Can you please provide Steps to Reproduce on this issue in terms of what level of granular access has been restricted and for which operations ? Is it role specific or user specific ?

**Comment by bdionne** [comment]
The idea here is to use one annotation property to restrict another. The software assumes a property called `restricted_by`, whose value is the `IRI` of another property. In this case we add `restricted_by` to `DEFINITION` and it's value is `definition_curator`. Don't confuse this with `Def_Curator` which mat be there for legacy purposes, but should probably be cleaned out at some point.

`definition_curator` has a range of `definition_curator_enum` and `definition_curator_enum` has a value that is a set of names, in this case `cancer_curators` and `drug_curators`. Each of these is an enum whose value will be specific users.

To restrict editing of `DEFINITION` on a specific class, add the `definition_curator` property to the class, selecting as value for it the desired enum. 

The screenshots below show how this was done for SmallBase



<img width="1143" alt="screen shot 2018-04-05 at 11 51 25 am" src="https://user-images.githubusercontent.com/31741/38377661-812d9804-38c9-11e8-8ce0-5c59d043e944.png">
<img width="1021" alt="screen shot 2018-04-05 at 11 51 40 am" src="https://user-images.githubusercontent.com/31741/38377662-813a699e-38c9-11e8-85bb-062d4e3c8e3f.png">
<img width="1038" alt="screen shot 2018-04-05 at 11 52 00 am" src="https://user-images.githubusercontent.com/31741/38377663-814932ee-38c9-11e8-99e9-7aa6c288e5aa.png">
<img width="1022" alt="screen shot 2018-04-05 at 11 52 20 am" src="https://user-images.githubusercontent.com/31741/38377664-8156bb8a-38c9-11e8-93e6-7a9ab89d52c5.png">
<img width="1043" alt="screen shot 2018-04-05 at 11 53 07 am" src="https://user-images.githubusercontent.com/31741/38377665-816c2b6e-38c9-11e8-8b9e-3bb8f72f3eff.png">

**Comment by singhik** [comment]
@bdionne @NCIEVS  ::  Hi ,   Restriction works for non-allowed users to Add/Edit 'DEFINITION' Complex property  but for the list of allowed users, addition/edition only works when the User Name is specified as complete name (Itendra Singh) but not when userid is specified (singhik) under 'DataType definitions', can you please confirm if this is expected ?  Below screen print shows the details ::

When userid (singhik) is added as part of restriction group, DEFINITION add/edit is not allowed ::

![image](https://user-images.githubusercontent.com/36314371/38635585-da0f1f28-3d93-11e8-85ef-8c408d80d5b1.png)


When complete Name (Itendra Singh) is added as part of restriction group, then DEFINITION add/edit is allowed ::

![image](https://user-images.githubusercontent.com/36314371/38635639-ff9ee78c-3d93-11e8-923f-795ea529d67b.png)

**Comment by bdionne** [comment]
nice catch, @singhik - this is just a bug - and [fixed](https://github.com/bdionne/nci-edit-tab/commit/160873484ad2050e6c1202891d3c61151f8c1a40) - I just finished merging another bug fix for #366 - let me check with @NCIEVS tomorrow about pushing another edit tab plugin, maybe we'll throw that in also, or just tease this out separately as a separate commit otherwise

**Comment by bdionne** [comment]
This is now fixed in [0.8.1](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.8.1)

**Comment by singhik** [comment]
@bdionne : Hi Bob, Thanks,  User id (singhik)  now works as the list of allowed users to Add/Edit DEFINITION . 

For restricted users, ADD and EDIT of DEFINITION is not allowed, however DELETE of DEFINITION is allowed for restricted users, need to confirm if DELETE is part of allowed operation for restricted users ?

**Comment by bdionne** [comment]
Delete should be restricted also, I just [pushed](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-0.8.2) a fix for that case.

**Comment by singhik** [comment]
QA has verified Edition,Deletion,Addition of DEFINITION complex property as NOT allowed for 'restricted users'.
QA has verified Edition,Deletion,Addition of DEFINITION complex property as allowed for 'non-restricted users' with userid .

Attached doc with screen prints ....
[Issue 207.docx](https://github.com/NCIEVS/nci-protege5/files/1907596/Issue.207.docx)

**Comment by bdionne** [comment]
this is done? closing it, please reopen if not
