### ISSUE TITLE
From UAT [EHD 2/27] - Lucene by default

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#209]
In the Preferences > General tab, the Search type should be Lucene search by default.

**Comment by NCIEVS** [comment]
This one will be taken care of when preferences are redone to be per instance rather than global.  A basic config could be distributed with a new build.

**Comment by rmehri** [comment]
Hi,
This issue will be retested on next release.  
Thanks,
Reza

**Comment by rmehri** [comment]
HI, 
The fix has been retested using nci-1005, Lucene Search Tab-1.0.3. 

Thanks,
Reza
