### ISSUE TITLE
Save button doesn't disable after all changes are committed

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#21]
This should happen in all `EditTab` panes

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
Can you please elaborate more for this fix? So I can validate the fix

Fixes:
- save button no longer enabled for property edits by managers
- save button correctly resets

Thanks,
Reza

**Comment by bdionne** [comment]
When the save button is pressed, the changes are committed. The buttons are then disabled

**Comment by rmehri** [comment]
This fix has been retested and verified.
