### ISSUE TITLE
From UAT [EHD 2/27] - display the originating class of anonymous ancestors

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#211]
One feature request was to have the Description tab display where the roles in the SubClassOf (Anonymous Ancestor) originate

**Comment by bdionne** [comment]
make this configurable:
 - display all
 - display only one in case of multiple inheritance
 - display none

**Comment by bdionne** [comment]
@NCIEVS - I was thinking we would add a section in the `renderer` panel in the preferences. Let me know if you think another one would be more appropriate:

<img width="887" alt="screen shot 2018-08-08 at 8 55 22 am" src="https://user-images.githubusercontent.com/31741/43838361-1c6d9130-9ae9-11e8-9da1-9ccd1ae1c609.png">

**Comment by NCIEVS** [comment]
@bdionne I'm looking at the General tab, it seems it might fit better in there.  There are sections already on axioms and tree levels, showing inherited conditions wouldn't seem out of place here, perhaps above the "Search type" section?

![image](https://user-images.githubusercontent.com/7783321/43843723-cc2b71ba-9aed-11e8-8651-da60d671426e.png)

**Comment by bdionne** [comment]
ok, we'll go with that. I chose renderer because it is changing how something is rendered that is already there, similar to using codes versus labels.

But this tab also speaks to display. We'll put a section before the `Seaech type`

**Comment by safrant** [comment]
Can you suggest an example class that will display a difference in behavior between "display originating class" and "display only one originating class"

**Comment by singhik** [comment]
@bdionne :Hi Bob,  When i set up my Preferences as either 'display only one originating class of Anonymous ancestors'  or 'Display none of the originating class of anonymous ancestors', **i am still able to view all the Anonymous ancestors** under Subclass Of header per below :: 

![image](https://user-images.githubusercontent.com/36314371/44872319-2f4b3d80-ac63-11e8-80bf-060a9f620f84.png)


![image](https://user-images.githubusercontent.com/36314371/44872370-4be77580-ac63-11e8-9d68-6d97c28359c1.png)

**Comment by safrant** [comment]
@singhik You should always be able to see the inherited roles.  What clicking "display one" or "display all" will do is show you from where these roles are inherited.  This is from "display one"  
![screen shot 2018-08-30 at 2 51 51 pm](https://user-images.githubusercontent.com/2364871/44872721-49395000-ac64-11e8-9657-fd0a933e8776.png)

**Comment by bdionne** [comment]
@safrant - some of the cancer genes, like BRCA, inherit the same restriction twice from parents transitively. I don’t know of any off hand that inherit from multiple direct parents. What I did was make one up

**Comment by singhik** [comment]
QA has validated the option to display Originating Class of anonymous ancestors from 'Preferences->General->Anonymous Ancestors Display' Tab .

'Display originating class of anonymous ancestors ' does display the originating class in paranthesis as expected :: 

![image](https://user-images.githubusercontent.com/36314371/45056224-46719d00-b060-11e8-9bb8-17278d6d6901.png)





'Don't display originating  class of anonymous ancestors'  does not display the originating class as expected :: 


![image](https://user-images.githubusercontent.com/36314371/45056207-38238100-b060-11e8-9818-48ed9b7071ab.png)



'Display only one originating class of anonymous ancestors' could not be verified due to no concept present with such a scenario to validate ...

**Comment by bdionne** [comment]
@NCIEVS @singhik - here's a somewhat contrived example that show the diffs between the three settings in the preferences:
option 1 - show nothing. I create two classes `foo` and `foo2` as subclasses of `Action. On both of them I add the same anonymous object restriction. Then create `bar` as a subclass of both `foo1` and `foo2`. Notice that now `bar` inherits two object restrictions that are the same

option 2 - by showing the classes that own the inherited object restrictions you can now see they cone from `foo1` and `foo2

option 3 - filters out the duplicate and just picks on, in this case the one from `foo2`


<img width="886" alt="screen shot 2018-09-06 at 2 38 56 pm" src="https://user-images.githubusercontent.com/31741/45178286-3f26cc80-b1e3-11e8-8f59-991be4f18a98.png">
<img width="917" alt="screen shot 2018-09-06 at 2 39 34 pm" src="https://user-images.githubusercontent.com/31741/45178287-3f26cc80-b1e3-11e8-87dc-faf1f8484cac.png">
<img width="919" alt="screen shot 2018-09-06 at 2 39 46 pm" src="https://user-images.githubusercontent.com/31741/45178288-3f26cc80-b1e3-11e8-8f7a-c1c782859668.png">
<img width="920" alt="screen shot 2018-09-06 at 2 40 01 pm" src="https://user-images.githubusercontent.com/31741/45178289-3f26cc80-b1e3-11e8-9d59-008bea54bdaa.png">
<img width="883" alt="screen shot 2018-09-06 at 2 40 30 pm" src="https://user-images.githubusercontent.com/31741/45178290-3f26cc80-b1e3-11e8-837f-c0cf2693ec25.png">
<img width="921" alt="screen shot 2018-09-06 at 2 40 46 pm" src="https://user-images.githubusercontent.com/31741/45178291-3fbf6300-b1e3-11e8-8fb9-686de607e1a2.png">
<img width="890" alt="screen shot 2018-09-06 at 2 41 09 pm" src="https://user-images.githubusercontent.com/31741/45178292-3fbf6300-b1e3-11e8-9336-0510ee11c405.png">
<img width="922" alt="screen shot 2018-09-06 at 2 41 26 pm" src="https://user-images.githubusercontent.com/31741/45178293-3fbf6300-b1e3-11e8-9c2c-195e9bb72a35.png">

**Comment by singhik** [comment]
Thanks @bdionne  .... Closing the ticket
