### ISSUE TITLE
From UAT [EHD 2/27] - search improvements on strings (vs tokens)

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#212]
Another feature request, allow exact match (non-case sensitive) searches for FULL_SYN [strings (as opposed to tokens] and also allow this in nested searches for FULL_SYN and label (should match an existing request but we may want to change its priority because many editors have asked for this). 

[This one might be a duplicate.]

**Comment by bdionne** [comment]
same as #163 ?
