### ISSUE TITLE
From UAT [EHD 2/27] - labels in edit dialogs of complex properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#213]
Complex property edit windows [dialogs] don't always display non-required property names (such as FULL_SYN subsource and source code, and DEF/ALT_DEF attribution) next to the slot. In general, if you use the hierarchy right click menu to add a Complex Property, usually the labels are present; if the editor uses an add button on the Complex Properties subtab of the Edit tab, these labels are not always displayed.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi , 
I will retest and verify this fix in the latest build.

Thanks,
Reza

**Comment by rmehri** [comment]
H

**Comment by bdionne** [comment]
This one fixes precisely what is described above in the description, labels for qualifiers weren't always showing up

**Comment by rmehri** [comment]
Hi, 
Thanks for your comment. This fix has been retested and verified using tag-125, NCI Edit Tab-0.5.0.
Please see attached screen shots for more details.


![label complex property-1](https://cloud.githubusercontent.com/assets/8367102/23965816/aa4db3d2-098f-11e7-9b4a-15564bd82cfc.png)
![label complex property-2](https://cloud.githubusercontent.com/assets/8367102/23965819/adc86fe8-098f-11e7-8ebd-1a51205bfe10.png)
![label complex property-3](https://cloud.githubusercontent.com/assets/8367102/23965828/b19bb904-098f-11e7-985d-20180f49b1a
![label complex property-4](https://cloud.githubusercontent.com/assets/8367102/23965850/bc51832e-098f-11e7-9363-4b43667d188b.png)

Thanks,
Reza

8.png)
