### ISSUE TITLE
From UAT [EHD 2/27] - object properties selected per domain of edited class

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#214]
Domain/Range for the Restricted property in the Object restriction creator is not working properly. (This has been reported previously and is still not functioning, even the workaround of hitting Cancel and trying again does not consistently produce results.)

**Comment by bdionne** [comment]
I'll work on this some more, and remove the need for a workaround. 

I'm having a hard time reproducing it though. Do we have an example which exhibits the failure. I'm wondering if the domains are set properly. On SmallBase many of the object properties have no domain

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi,
Would you have a reproducible example for this issue? So it can be verified. 

![object property tab](https://cloud.githubusercontent.com/assets/8367102/23824489/bc9ee558-0645-11e7-9e40-76f9f87e8062.png)

Thanks,
Reza

**Comment by bdionne** [comment]
I do not, as commented above I am unable to reproduce this. There was one edge case which required a workaround (see above and earlier tickets on this subject) but that has also been fixed.

The requirement is the following:

`ObjectProperties` sometimes called `ROLES` have domains and ranges, you can view these in the entities tab. When new subclass object restrictions are added to a class only the object properties that belong to the same domain can be used. The selection should be filtered. Additionally only classes that are subclass of the object property's range can be used as fillers in the assertion.

You might be able to get a reproducible test case from the modelers and see it using `nci-0.123`

**Comment by rmehri** [comment]
Hi Liz,
Thanks for the reproducible steps.
I have retested this issue using the latest tag-125, NCI Edit Tab-0.5.0 and verified this fix. 
Used: Local Server 8080. 
https://nciws-d699-v.nci.nih.gov:9090 (This server is not available)
*Note: I have retested this issue using the previous tag 123 and could not seen reproduce the issue. 
Steps to follow:
1. Navigate to a disease concept 
2. Under Descriptions tab, click + button and  add an Object Property 
3. All the roles in the first window should start with the word Disease.
Please see attached screen shots for more details.

![issue 214-added an object property_disease class](https://cloud.githubusercontent.com/assets/8367102/24058649/4f36fbcc-0b22-11e7-8972-90d514b64f26.png)

Thanks,
Reza
