### ISSUE TITLE
From UAT [EHD 2/27] - Alternate term types AQ and HD prevent SY from being added

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#215]
Terms without a PT but with an equivalent Term Type (AQ, HD) cannot have additional SY added because the interface is not seeing that these are equivalent to a PT.

**Comment by bdionne** [comment]
[fixed}(https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using tag-125, NCI Edit tab-0.4.9. Please see attached screen shots for more detail.

![full_syn](https://cloud.githubusercontent.com/assets/8367102/23904780/83a29f4a-089f-11e7-91f4-3111bdc3417e.png)
![full_syn1](https://cloud.githubusercontent.com/assets/8367102/23904788/886b630e-089f-11e7-8d39-5ba50b5a7615.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
Please see the following update:

I will add the following  scenarios  and more screen shots into the GTH -Issue 215. Please let me know if need more information.

1)	Selected a class and added Full_SYN with “NCI & AQ”   Passed
2)	Selected a different class and added Full_SYN with “NCI & HD”   Passed
3)	On step#1, I added Full_SYN with “NCI & Sys” --Passed
4)	On step#2, I added Full_SYN with “NCI & Sys” --Passed
5)	On step#1, I tried to add  Full_SYN with “NCI & AQ”  --Passed (Received warning message : One and only one PT with source NCI is allowed) 
6)	On step#2, I tried to add  Full_SYN with “NCI & PT” --Passed (Received warning message : One and only one PT with source NCI is allowed) 
7)	On step#1, I tried to add  more one Full_SYN with “NCI & AQ” --Passed (Received warning message : One and only one PT with source NCI is allowed) 
8)	On step#2, I tried to add  more one Full_SYN with “NCI & HD” --Passed (Received warning message : One and only one PT with source NCI is allowed)

HD, AQ and PT are equivalent Full-Syn term types. (i.e. an NCI/AQ can take the place of an NCI/PT)

https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege


![full_syn5](https://cloud.githubusercontent.com/assets/8367102/23907735/694b9918-08a8-11e7-9333-0ccf5defaf7f.png)
![full_syn3](https://cloud.githubusercontent.com/assets/8367102/23907734/6946fd40-08a8-11e7-834a-80a045a7ae05.png)
![full_syn4](https://cloud.githubusercontent.com/assets/8367102/23907736/695c4d9e-08a8-11e7-8cf8-6373d35b3684.png)
![full_syn2](https://cloud.githubusercontent.com/assets/8367102/23907752/738dd274-08a8-11e7-962e-79fc361df471.png)


Thanks,
Reza
