### ISSUE TITLE
From UAT [EHD 2/27] - anonymous ancestors, change of focus 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#216]
Remove editing buttons for roles in the SubClassOf (Anonymous Ancestor). This changes the focus to the ancestor and may interfere with completing the editing of the original concept.

**Comment by NCIEVS** [comment]
This kind of ties in with navigation when editing a concept and the enabling of the Save button.  Probably needs an integrated look.

**Comment by hahndane** [comment]
Make configurable in the preferences.

**Comment by bdionne** [comment]
Navigating in general, when you click on a class everywhere, can be disabled in `Preferences/Renderer`. 

We've removed the edit buttons from `SubClassOf (Anonymous Ancestor)` so that the user can't change the class focus. 

Perhaps we should go with this, and let user's set the global preference wrt navigating links, rather than customizing navigation to just this section?

**Comment by NCIEVS** [comment]
Agreed, the Preferences/Renderer supports the configurability that we need, "show hyperlinks..." in the dialog:

![image](https://user-images.githubusercontent.com/7783321/28935101-60207c50-7851-11e7-9a03-edaa76ddec94.png)

I believe this ticket can be closed.  Yes?

**Comment by bdionne** [comment]
yea it's done, but not in QA/prod yet (the remove the buttons part)

**Comment by rmehri** [comment]
Hi,
 This ticket will be retested and verified when the protege QA server is ready.
 Thanks,
 Reza

**Comment by rmehri** [comment]
Hi, 
This has been retested  using tag 1.0083 and Client-V2.1.10083 on my local and QA servers. Please see attached snapshots for more details. 
![issue 216-1](https://user-images.githubusercontent.com/8367102/30084248-a0867a74-925f-11e7-8e78-6bb63b7bd01a.png)
![issue 216-2](https://user-images.githubusercontent.com/8367102/30084253-a2506a04-925f-11e7-870a-80904d8708e1.png)

Thanks,
Reza
