### ISSUE TITLE
From UAT [NS 2/27] - object restriction creator not showing properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#218]
The Object restriction creator window is not behaving properly. The owl:topObjectProperty is not able to be expanded in the Restricted property panel. [User] has been searching for a filler value and adding the role owl:topObjectProperty some filler value; then when he edits that role he is then able to expand the owl:topObjectProperty and find a restriction. The Domain/Range also is not functioning as expected here.

**Comment by NCIEVS** [comment]
We might need to see this over webex.

**Comment by bdionne** [comment]
need a reproducible test case for this

**Comment by rmehri** [comment]
Hi,
This issue will be retested on next release.  
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
I have retested this issue using latest tag nci-1.005. 
Thanks,
Reza
