### ISSUE TITLE
From UAT [NS 2/27] - changing subtabs within an edit action

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#219]
[User] had issues editing a concept and changing subtabs without saving. I could not replicate this in my version.

**Comment by rmehri** [comment]
Hi,
This issue will be retested on next release.  
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This issue has been retested using nci-1.005, edit tab-0.5.9.
Thanks,
Reza
