### ISSUE TITLE
From UAT [NS 2/27] - issues adding a PT to a concept with an existing PT

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#220]
[User] created a new concept C250565 and then tried to add an additional FULL_SYN before saving. However, he didn't change the Term Type on the new FULL_SYN from PT to SY. He got the appropriate warning messages but the original PT disappeared, the "new" unwanted PT did not display and the concept was left without a PN, PT or code, only the IRI remained. I can no longer see or search for this concept (I don't know if there is an IRI search somewhere in protégé 5) but he could use the navigation buttons to go back to it. Since there were no other complex properties present (specifically FULL_SYN), he could not fix the concept. I was able to replicate this in my instance (IRI C250268) but when I hit Save the concept appeared in the hierarchy under owl:thing it has the original PT, PN and label, and it has a code and IRI. There is no parent and no Semantic_Type. I still don't see Nick's concept and cannot use property = code to find either concept or other existing concepts.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi,
I have retested this issue using tag 125, nci edit tab 0.5.0. and not seen the same behavior as reported. 
Used: https://nciws-d699-v.nci.nih.gov:9090 & 8080 (Local)
Please see attached screen shots for more detail.

![issue-220-1](https://cloud.githubusercontent.com/assets/8367102/23962132/80eb8552-0983-11e7-8ace-5f62aa820939.png)
![issue-220-2](https://cloud.githubusercontent.com/assets/8367102/23962129/80e51db6-0983-11e7-85c7-9f5a9acbdc47.png)
![issue-220-3](https://cloud.githubusercontent.com/assets/8367102/23962131/80e7a072-0983-11e7-84c7-e6c2d919d741.png)
![issue-220-4](https://cloud.githubusercontent.com/assets/8367102/23962130/80e6a910-0983-11e7-91d9-9ec2cc592510.png)
![issue-220-5](https://cloud.githubusercontent.com/assets/8367102/23962128/80e49de6-0983-11e7-9197-e2dd6206ac77.png)

Thanks,
Reza
