### ISSUE TITLE
Additional scenarios related to adding PTs to concepts with pre-existing PTs

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#222]
If you are adding several FULL_SYNs using the green plus button in the Complex Properties subtab of the Edit tab and after adding one or two forget to change the next one from NCI PT to NCI SY (or something else), you are prompted to change the one you are adding, but once you fix it the last one you added disappears and doesn’t reappear when you Save.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi,
I have replicated this issue using the previous tag-123 and could not reproduce it.  I have also retested this issue using latest tag-125, NCI Edit tab -0.4.9 and not seen the same behavior as reported in this issue.  In this case,  I would consider this ticket fixed.  Please see attached screen shot.
*Note: This issue will be reopened if the same behavior occurs but for now it can be closed.

![full_syn_plus sign](https://cloud.githubusercontent.com/assets/8367102/23919069/c7ad754e-08cb-11e7-8f81-c0a74c8798cf.png)

Thanks,
Reza
