### ISSUE TITLE
Reports using a list of codes for input is failing

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#223]
From EHD, 3/3, 1:19 PM

I tried to run a report using a file of codes (02232017_Eligibility_old_Codes.txt attached) that had a mixture of existing and non-existing codes. The Report Writer console displayed an error for all of the codes (the ones that start C131 or C132 don’t exist in the test version of NCIt).
 
But the window to export a file did appear. I hit the + sign next to Entities (by mistake) and the GUI froze. There were no error messages in the listener but I couldn’t close this export file window and had to exit using ctrl-c in the listener.
 
So I tried again, using the same input file. This time I was able to choose a set of properties to export (because I didn’t select the button to add Entities) but nothing was in the file except the properties I chose because I selected Include headers in first line.

So I tried again but this time I removed the non-existent codes from the file (02232017_test_Codes.txt attached). I got the same message in the console even though these codes should exist in the database. I chose the same set of properties to export but nothing was in the file except the properties I chose because I selected Include headers in first line.

 I know I have tested this before and I thought it was working, is there something wrong with the format of the input files?

**Comment by bdionne** [comment]
If we can attach the file form the email, I can try to reproduce

**Comment by NCIEVS** [comment]
[02232017_Eligibility_old_Codes.txt](https://github.com/NCIEVS/nci-protege5/files/822315/02232017_Eligibility_old_Codes.txt)
[02232017_test_Codes.txt](https://github.com/NCIEVS/nci-protege5/files/822314/02232017_test_Codes.txt)

**Comment by bdionne** [comment]
@hahndane - two issue going on with this:

1. When you click to add entities, the CSV export plugin creates a list with the entire terminology in it. On SmallBase it does actually come up after about a minute. I've mitigated this somewhat with a fix in the next push but it needs to be rewritten. The LQT option also suffers the same problem. We can disable it for V1.0, especially if it is seldom used.

2. You need to specify the IRIs of the classes. The codes will work if you are using a by code terminology but if you are using by name you will need to specify a mixture of names and codes, with codes used for the new ones

**Comment by hahndane** [comment]
Hi Bob


1.      Gilberto and I discussed this and disabling this button is probably the best answer.

2.      The current functionality in Protégé 3 is code-based and this functionality accepted codes in earlier Protégé 5 snapshots, so I don’t understand why the requirements changed.

Thanks,
Liz

**Comment by bdionne** [comment]
@hahndane -

1. ok, will disable

2. I'm pretty sure it's always been this way, I just checked the code going back to 9/30/16 This is the same issue in batch edit, and the reason we created the IRIs tab. 

When we go to production we will likely be using a `byCode` thesaurus and this will work. The issue is when you have a by name thesaurus you need to specify the name. Otherwise I have no way of knowing which is which as new classes will have the code in the IRI and old ones won't.

**Comment by hahndane** [comment]
Hi Gilberto

When we start the QA process, can we use the latest publication version of NCIt (17.02d) as by-code? I would not want the first by-code version that the editors see to be the one we use during the dual editing period.

Thanks,
Liz

**Comment by rmehri** [comment]
Hi,
This issue will be retested on next release.  
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I retested this issue and the entities button is showing not disable. Please see attached screenshots.
Used local server and byname project.
Latest tag: nci-1.005, edit tab-0.5.9

![export to cvs-1](https://cloud.githubusercontent.com/assets/8367102/25495211/635b3f76-2b4a-11e7-8e8a-c81f9e5ac563.png)
![export to cvs-2](https://cloud.githubusercontent.com/assets/8367102/25495237/72f2821e-2b4a-11e7-8a16-a8bb6c208cb6.png)
![export to cvs-3](https://cloud.githubusercontent.com/assets/8367102/25495244/7b265a50-2b4a-11e7-9eb5-59b68a95d96c.png)

Thanks,
Reza

**Comment by bdionne** [comment]
<img width="1021" alt="screen shot 2017-04-27 at 1 47 36 pm" src="https://cloud.githubusercontent.com/assets/31741/25499893/01971ff6-2b5b-11e7-9bd4-ed9b7b15d963.png">

**Comment by bdionne** [comment]
Hi Reza, this should be retested in `nci-1.006` I believe it's working

**Comment by rmehri** [comment]
Hi Bob,
I have retested this issue using  nci-1.006, and it fails.  

1) Used attached input file by code and received the error message error message for each class that class does not exist .
02232017_Eligibility_old_Codes.txt
02232017_test_Codes.txt
2)  Used attached input file by codes and IRI names and received the same error message for each class that class does not exist .
[05112017_test_Codes_IRI.txt](https://github.com/NCIEVS/nci-protege5/files/994300/05112017_test_Codes_IRI.txt)

3) Used attached input file by code only from my local project and received the the same error message for each class that class does not exist .
[05112017_test_Codes.txt](https://github.com/NCIEVS/nci-protege5/files/994306/05112017_test_Codes.txt)
4) In Export to CSV file window, the "Entities" is disabled. ======>Fixed.
Please see attached screenshots for more details.

![issue-223-1](https://cloud.githubusercontent.com/assets/8367102/25970267/fb177df4-3665-11e7-9b1d-7c55cbcda422.
![issue-223-2](https://cloud.githubusercontent.com/assets/8367102/25970301/1b1cf39a-3666-11e7-835e-60cb71d668fb.png)
png)

![issue-223-3](https://cloud.githubusercontent.com/assets/8367102/25970322/2d488232-3666-11e7-9a7d-12af6ffb2e7c.png)
![issue-223-4](https://cloud.githubusercontent.com/assets/8367102/25970321/2d2a0ece-3666-11e7-9ca6-33d068421084.png)
![issue-223-5](https://cloud.githubusercontent.com/assets/8367102/25970319/2d25dae8-3666-11e7-81cd-170bc2c623f4.png)
![issue-223-6](https://cloud.githubusercontent.com/assets/8367102/25970320/2d28877a-3666-11e7-9ae9-948d3eb82fda.png)


Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri  - I believe you are testing using incorrect input files. They should contain just codes, not codes and IRIs

**Comment by rmehri** [comment]
Hi Bob, 
I have retested this issue using nci-1.006 tag with different input files: 

Test1) 1.Used attached input file by code and received it passed.  However, the message says "Exported using the LQT Configuration finished successfully".  But the report type was selected as "Export an input file"!  Please see attached input file and screenshots for more details.
![Uploading Input_ByCode_5.15.2017.png…]()
![Uploading Input_ByCode-1_5.15.2017.png…]()
![Uploading Input_ByCode-2_5.15.2017.png…]()
[Uploading 05.15.2017_test_ByCode-1.txt…]()
[Uploading lucene-export_ByCode.csv…]()
----------------------------------------------------------------------------
Test2) Used attached input file byname mixed bycode and received errors that the class does not exist 
I tried and retested with the different codes and names arrangement in the input file and received the same error. Although the report was exported correctly.  Please see attached input file and screenshots for more details and let me know your thoughts.

[Uploading 05.15.2017_test_By Name Mixed Codes.txt…]()
[Uploading 05.15.2017_test_By Name Mixed Codes-2.txt…]()
![Uploading Input_ByName-Mixed-Code_5.15.2017.png…]()
![Uploading Input_ByName-Mixed-Code_5.15.2017-1.png…]()
[lucene-export_Byname-ByCode.zip](https://github.com/NCIEVS/nci-protege5/files/1002003/lucene-export_Byname-ByCode.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - could you tell me what specifically fails? The first file you attached is ill-formed and won't work for this test. The second file should show failures if you have names in it and are using a by code ontology or have codes in it and are using a by name ontology.

Thanks for clarifying this

**Comment by rmehri** [comment]
Hi Bob, 
Yes. It is the second input file that has the mixture of codes & names and using by name ontology. 
Here are the steps:
a)	Select Report Writer
b)	Select Configure
c)	Report Type=Export Using an input file
d)	Select the second input file “05.15.2017_test_By Name Mixed Codes-2.txt”
e)	In Export to CSV file menu, under Entities, you’ll see all the classes by name display
f)	Add all the necessary properties 
g)	Include field delimiter and include all the necessary check boxes and press Ok
Test Results:
In ReportWriter panel, the following failure errors display:
OWLNamedClass does not exist for code:Body Cavity
OWLNamedClass does not exist for code:Body Cavity1
OWLNamedClass does not exist for code:Body Cavity2
OWLNamedClass does not exist for code:Body Cavity3
Exported using the LQT configuration finished successfully.
*Note:  I can see the file was exported correctly.
Please see attached screenshot and attached input file. 

![second test](https://cloud.githubusercontent.com/assets/8367102/26108407/703d20ae-3a1a-11e7-8c5b-b1ce237da132.png)
Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - I'm sorry Reza, let me repeat my question. What is it that is failing?

The file has 8 records in it. 4 seemed to have loaded and produced results (as seen in the csv in the zip file) and 4 were not found. 

This seems like what it should do. Are you saying it should find all 8 and it's not?

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! I already attached the input file 05.15.2017_test_ByCode-1.txt. for yesterday's test1. This ticket can be closed.

Thanks,
Reza
