### ISSUE TITLE
Issues editing in the regular edit panel after using the dual-editing panel

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#225]
I was editing two classes in the Complex Edits panel using the Dual Edit option. I added a Project_Name on the concept in the Target window and then copied and pasted it into the concept in the Source window and hit Save. Everything looks fine here. But I went to another concept in the Edit tab (normal editing) and tried to add a Project_Name to that concept. It never showed up in the concept, I could add other properties (OMIM_Number, Has_Target (association), DEF, FULL_SYN) without issue but I cannot add Project_Name.

I had to exit and log back in to add this property to concepts again.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag 125, nci edit tab-0.4.9. Please see attached screen shots for more details. 

![dual-editing_project name-1](https://cloud.githubusercontent.com/assets/8367102/23858902/647ec48a-07d8-11e7-9c87-451a78a6f7f1.png)
![dual-editing_project name-2](https://cloud.githubusercontent.com/assets/8367102/23858918/6edbfbf0-07d8-11e7-8d83-7ca0443394f6.png)

![dual-editing_project name-3](https://cloud.githubusercontent.com/assets/8367102/23858917/6edbb23a-07d8-11e7-9c78-e3792a7ebcca.png)
![dual-editing_project name-4](https://cloud.githubusercontent.com/assets/8367102/23858916/6ed95468-07d8-11e7-97f3-9300e8c2287b.png)

Thanks,
Reza
