### ISSUE TITLE
double-clicking on "add annotations"

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#226]
If an editor mistakenly double clicks on an add property button (object property or annotation property) two windows popup. This seems to be a minor issue now as the windows popup quickly and the second window is the only one that can be edited (see screenshot). Even if you hit cancel or edit and hit OK on the top (second) window the first one is not functional. So while this is annoying, it is much less confusing then it was previously when you needed to wait for all the windows to open and all of them were functional.

**Comment by bdionne** [comment]
this is fixed, was required for a fix elsewhere

**Comment by rmehri** [comment]
Hi, 
Can you please provide the screen screenshot as noted in the problem description above?
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified for both object properties and annotation properties. 
Used latest tag: nci-1.003, nci-edit-tab-0.5.6, lucene-search-tab-1.0.2 .
Login Role: Workflow-manager
Please see attached screenshot for more detail.

![object properties](https://cloud.githubusercontent.com/assets/8367102/25232569/d241cc9e-25a9-11e7-942d-da02162e4667.png)
![annotation properties](https://cloud.githubusercontent.com/assets/8367102/25232574/d7ca69aa-25a9-11e7-9e52-377038d669c9.png)

Thanks,
Reza
