### ISSUE TITLE
QA-ReportWriter-Export as Report With Attributes-Cancelled Report Mismatch Number

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#229]
Used:
 Servers: http://localhost:8080 
 Logins: Modeler & Manager

Tag-123 & NCI Edit-0.4.7

Steps to reproduce:
 1.Launch protégé server and client
 2.Log into the local server (8080), login: modeler
 3.Select NCI Edit Tab
 4.Select hierarchy with many classes (Concepts)
 5.Select ReportWriter
 6.Select Report type= Export as report with attributes
7. Select Ok and name the report
8. Press "Start" to generate report then press Cancel immediately to cancel the report
9. you'll see 11 out of 131 completed then at the end of report you notice "o out of 131 completed while the report is generated.

Please see the attached screen shots and zip file to view the report for more details.

![reportwriter1](https://cloud.githubusercontent.com/assets/8367102/23630953/ecdb70d8-028a-11e7-9656-6b3c6aa68fe7.png)
![reportwriter2](https://cloud.githubusercontent.com/assets/8367102/23630954/eeaf5f00-028a-11e7-97da-dc6271a0dff6.png)
![reportwriter3](https://cloud.githubusercontent.com/assets/8367102/23630957/f11b1810-028a-11e7-96cf-84f843f336c0.png)

[reportwriter_test.zip](https://github.com/NCIEVS/nci-protege5/files/822593/reportwriter_test.zip)

Thanks,
Reza

**Comment by NCIEVS** [comment]
What is the bug?

**Comment by bdionne** [comment]
@rmehri - this doesn't seem to be a bug, it's working as intended. Could you clarify what the issue is?

<img width="1022" alt="screen shot 2017-03-06 at 5 42 38 pm" src="https://cloud.githubusercontent.com/assets/31741/23633592/57dcf39e-0294-11e7-8d18-22f4fa1dcd36.png">

**Comment by rmehri** [comment]
Hi Bob,
The issue is the final message, which displays as "0 out of 131 completed” while “11 out of 131” was completed. That is the mismatch.  Please let me know if you need more information.
Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri  - you canceled the job, correct? What should it say? I don't believe anything was written to the file. Please clarify

**Comment by rmehri** [comment]
Hi Bob,
Yes.  The report was zipped along with screen shots.  But please see below for the report contents.

Pediatric Disorder
	code: C89328
	Preferred_Name: Pediatric Disorder

	UMLS_CUI: C0679381
	NICHD_Hierarchy_Term: Pediatric Disorder
	Semantic_Type: Disease or Syndrome
	label: Pediatric Disorder
	Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#National_Institute_of_Child_Health_and_Human_Development_Newborn_Screening_Terminology
	Contributing_Source: NICHD
	Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#National_Institute_of_Child_Health_and_Human_Development_Pediatric_Terminology
	code: C89328
	Has_NICHD_Parent: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Diseases_and_Disorders
	Preferred_Name: Pediatric Disorder

	FULL_SYN: Pediatric Disease or Disorder
		term-group: PT
		term-source: NICHD
	FULL_SYN: Pediatric Disease
		term-group: PT
		term-source: NICHD
	FULL_SYN: Pediatric Disorder
		term-group: PT
		term-source: NICHD
	DEFINITION: A non-neoplastic or neoplastic disorder which occurs during infancy, childhood, or adolescence.
		Definition_Review_Date: 160719
		Definition_Reviewer_Name: Theresa Quinn
		def-source: NCI

	Named Superclass: Disease or Disorder


	Childhood Neoplasm
		code: C6283
		Preferred_Name: Childhood Neoplasm

		label: Childhood Neoplasm
		UMLS_CUI: C1368871
		Legacy_Concept_Name: Childhood_Neoplasm
		code: C6283
		Neoplastic_Status: Undetermined
		Semantic_Type: Neoplastic Process
		Preferred_Name: Childhood Neoplasm

		DEFINITION: A benign or malignant neoplasm arising during childhood.
			Definition_Review_Date: 060504
			Definition_Reviewer_Name: DEFAULT_Review
			def-source: NCI
		FULL_SYN: Pediatric Tumor
			term-group: SY
			term-source: NCI
		FULL_SYN: Childhood Neoplasm
			term-group: SY
			term-source: NCI
		FULL_SYN: Childhood Tumor
			term-group: SY
			term-source: NCI
		FULL_SYN: Pediatric Neoplasm
			term-group: SY
			term-source: NCI

		Named Superclass: Pediatric Disorder
		Named Superclass: Neoplasm by Special Category

		Restriction: some Disease_Has_Finding Childhood_Lesion [defined]

		Childhood Central Nervous System Neoplasm
			code: C5132
			Preferred_Name: Childhood Central Nervous System Neoplasm

			Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#CTRP_Terminology
			Legacy_Concept_Name: Childhood_Central_Nervous_System_Neoplasm
			Contributing_Source: CTRP
			label: Childhood Central Nervous System Neoplasm
			code: C5132
			Semantic_Type: Neoplastic Process
			Display_Name: Childhood Central Nervous System Neoplasm
			Editor_Note: MissingCTRPs
			Neoplastic_Status: Undetermined
			Preferred_Name: Childhood Central Nervous System Neoplasm
			UMLS_CUI: C1377665

			FULL_SYN: Childhood Tumor of the CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Central Nervous System Neoplasm
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Tumor of Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Neoplasm of Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Neoplasm of the Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood CNS Neoplasm
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Central Nervous System Neoplasm
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Neoplasm of Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Tumor of Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Neoplasm of CNS
				term-group: SY
				term-source: NCI
			DEFINITION: A benign or malignant neoplasm of the brain, spinal cord, or meninges occurring in children.  Representative examples include posterior fossa astrocytoma, optic pathway glioma, medulloblastoma, ependymoma, and craniopharyngioma.
				Definition_Review_Date: 101102
				Definition_Reviewer_Name: Nicholas Sioutos
				def-source: NCI
			FULL_SYN: Childhood Neoplasm of the Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Tumor of CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood CNS Tumors
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood CNS Neoplasms
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Tumor of the CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Neoplasm of the CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Central Nervous System Neoplasms
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Central Nervous System Tumors
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Central Nervous System Tumor
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Neoplasm of CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Tumor of the Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric CNS Neoplasm
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Tumor of the Central Nervous System
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Central Nervous System Tumor
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric Tumor of CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood Neoplasm of the CNS
				term-group: SY
				term-source: NCI
			FULL_SYN: Childhood CNS Tumor
				term-group: SY
				term-source: NCI
			FULL_SYN: Pediatric CNS Tumor
				term-group: SY
				term-source: NCI

			Named Superclass: Childhood Neoplasm
			Named Superclass: Central Nervous System Neoplasm


			Childhood Intracranial Neoplasm
				Preferred_Name: Childhood Intracranial Neoplasm
				code: C35876

				Preferred_Name: Childhood Intracranial Neoplasm
				code: C35876
				Neoplastic_Status: Undetermined
				Legacy_Concept_Name: Childhood_Intracranial_Neoplasm
				Semantic_Type: Neoplastic Process
				label: Childhood Intracranial Neoplasm
				UMLS_CUI: C1332975

				FULL_SYN: Childhood Intracranial Neoplasm
					term-group: PT
					term-source: NCI
				DEFINITION: A neoplasm that arises within the skull and occurs during childhood.
					Definition_Review_Date: 150115
					Definition_Reviewer_Name: Theresa Quinn
					def-source: NCI

				Named Superclass: Childhood Central Nervous System Neoplasm
				Named Superclass: Intracranial Neoplasm


				Childhood Brain Neoplasm
					Preferred_Name: Childhood Brain Neoplasm
					code: C7703

					UMLS_CUI: C0220603
					Preferred_Name: Childhood Brain Neoplasm
					Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#CTRP_Terminology
					code: C7703
					Contributing_Source: CTRP
					Semantic_Type: Neoplastic Process
					Editor_Note: MissingCTRPs
					Neoplastic_Status: Undetermined
					Legacy_Concept_Name: Childhood_Brain_Neoplasm
					Display_Name: Childhood Brain Neoplasm
					label: Childhood Brain Neoplasm

					FULL_SYN: Brain Neoplasms, Childhood
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Tumor of Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Childhood Neoplasm of the Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Childhood Tumor of Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Neoplasm of the Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Tumor of the Brain
						term-group: SY
						term-source: NCI
					DEFINITION: A benign or malignant, primary or metastatic neoplasm of the brain occurring in children.
						Definition_Review_Date: 101102
						Definition_Reviewer_Name: Nicholas Sioutos
						def-source: NCI
					FULL_SYN: Childhood Neoplasm of Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Brain Tumor
						term-group: SY
						term-source: NCI
					FULL_SYN: Childhood Brain Neoplasm
						term-group: SY
						term-source: NCI
					FULL_SYN: Childhood Brain Tumor
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Brain Neoplasm
						term-group: SY
						term-source: NCI
					FULL_SYN: Childhood Tumor of the Brain
						term-group: SY
						term-source: NCI
					FULL_SYN: Pediatric Neoplasm of Brain
						term-group: SY
						term-source: NCI

					Named Superclass: Brain Neoplasm
					Named Superclass: Childhood Intracranial Neoplasm


					Childhood Infratentorial Neoplasm
						code: C5802
						Preferred_Name: Childhood Infratentorial Neoplasm

						Neoplastic_Status: Undetermined
						code: C5802
						Legacy_Concept_Name: Childhood_Infratentorial_Neoplasm
						Preferred_Name: Childhood Infratentorial Neoplasm
						label: Childhood Infratentorial Neoplasm
						Semantic_Type: Neoplastic Process
						UMLS_CUI: C1332973

						FULL_SYN: Pediatric Infratentorial Tumor
							term-group: SY
							term-source: NCI
						DEFINITION: A neoplasm that affects the infratentorial region of the brain and occurs during childhood.
							Definition_Review_Date: 150115
							Definition_Reviewer_Name: Theresa Quinn
							def-source: NCI
						FULL_SYN: Childhood Infratentorial Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Childhood Infratentorial Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Pediatric Infratentorial Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Childhood Infratentorial Neoplasms
							term-group: SY
							term-source: NCI
						FULL_SYN: Childhood Infratentorial Tumors
							term-group: SY
							term-source: NCI

						Named Superclass: Infratentorial Neoplasm
						Named Superclass: Childhood Brain Neoplasm


						Childhood Brain Stem Neoplasm
							code: C5969
							Preferred_Name: Childhood Brain Stem Neoplasm

							code: C5969
							Preferred_Name: Childhood Brain Stem Neoplasm
							Semantic_Type: Neoplastic Process
							label: Childhood Brain Stem Neoplasm
							Neoplastic_Status: Undetermined
							Legacy_Concept_Name: Childhood_Brain_Stem_Neoplasm
							UMLS_CUI: C1332951

							FULL_SYN: Pediatric Tumor of the Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Brainstem Tumor
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Brainstem Neoplasm
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Brainstem Tumor
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Tumor of Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Tumor of the Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Brain Stem Tumor
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Neoplasm of the Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Brainstem Neoplasm
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of the Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Brain Stem Neoplasm
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of the Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Tumor of Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Brain Stem Neoplasm
								term-group: SY
								term-source: NCI
							DEFINITION: A neoplasm that affects the brain stem and occurs during childhood.
								Definition_Review_Date: 150115
								Definition_Reviewer_Name: Theresa Quinn
								def-source: NCI
							FULL_SYN: Childhood Neoplasm of Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Neoplasm of Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of the Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of Brain Stem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of the Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Neoplasm of the Brainstem
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Brain Stem Tumor
								term-group: SY
								term-source: NCI

							Named Superclass: Brain Stem Neoplasm
							Named Superclass: Childhood Infratentorial Neoplasm


						Childhood Cerebellar Neoplasm
							Preferred_Name: Childhood Cerebellar Neoplasm
							code: C5970

							Neoplastic_Status: Undetermined
							label: Childhood Cerebellar Neoplasm
							UMLS_CUI: C1332959
							Preferred_Name: Childhood Cerebellar Neoplasm
							code: C5970
							Legacy_Concept_Name: Childhood_Cerebellar_Neoplasm
							Semantic_Type: Neoplastic Process

							FULL_SYN: Childhood Neoplasm of the Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Tumor of the Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Tumor of the Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Neoplasm of Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Tumor of Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Cerebellar Tumor
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Cerebellar Neoplasm
								term-group: SY
								term-source: NCI
							DEFINITION: A neoplasm that affects the cerebellum and occurs during childhood.
								Definition_Review_Date: 150115
								Definition_Reviewer_Name: Theresa Quinn
								def-source: NCI
							FULL_SYN: Childhood Cerebellar Tumors
								term-group: SY
								term-source: NCI
							FULL_SYN: Pediatric Neoplasm of the Cerebellum
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Cerebellar Tumor
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Cerebellar Neoplasm
								term-group: SY
								term-source: NCI
							FULL_SYN: Childhood Cerebellar Neoplasms
								term-group: SY
								term-source: NCI

							Named Superclass: Childhood Infratentorial Neoplasm
							Named Superclass: Cerebellar Neoplasm


					Childhood Supratentorial Neoplasm
						Preferred_Name: Childhood Supratentorial Neoplasm
						code: C5960

						Preferred_Name: Childhood Supratentorial Neoplasm
						Neoplastic_Status: Undetermined
						code: C5960
						Legacy_Concept_Name: Childhood_Supratentorial_Neoplasm
						UMLS_CUI: C1333004
						label: Childhood Supratentorial Neoplasm
						Semantic_Type: Neoplastic Process

						FULL_SYN: Childhood Supratentorial Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Pediatric Supratentorial Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Childhood Supratentorial Neoplasms
							term-group: SY
							term-source: NCI
						FULL_SYN: Pediatric Supratentorial Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Childhood Supratentorial Tumor
							term-group: SY
							term-source: NCI
						DEFINITION: A neoplasm that affects the supratentorial region of the brain and occurs during childhood.
							Definition_Review_Date: 150115
							Definition_Reviewer_Name: Theresa Quinn
							def-source: NCI
						FULL_SYN: Childhood Supratentorial Tumors
							term-group: SY
							term-source: NCI

						Named Superclass: Supratentorial Neoplasm
						Named Superclass: Childhood Brain Neoplasm


					Recurrent Childhood Brain Neoplasm
						Preferred_Name: Recurrent Childhood Brain Neoplasm
						code: C7834

						Legacy_Concept_Name: Recurrent_Childhood_Brain_Neoplasm
						Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#CTRP_Terminology
						Contributing_Source: CTRP
						UMLS_CUI: C0278690
						Preferred_Name: Recurrent Childhood Brain Neoplasm
						Semantic_Type: Neoplastic Process
						Editor_Note: MissingCTRPs
						Neoplastic_Status: Undetermined
						code: C7834
						label: Recurrent Childhood Brain Neoplasm
						Display_Name: Recurrent Childhood Brain Neoplasm

						DEFINITION: The reemergence of brain neoplasm in childhood after a period of remission.
							Definition_Review_Date: 150115
							Definition_Reviewer_Name: Theresa Quinn
							def-source: NCI
						FULL_SYN: Relapsed Tumor of Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Tumor of the Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Neoplasm of Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Neoplasm of the Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Pediatric Brain Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Childhood Brain Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Neoplasm of Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Pediatric Brain Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Pediatric Brain Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Childhood Brain Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Neoplasm of the Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Neoplasm of the Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Neoplasm of Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Tumor of Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Childhood Brain Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Tumor of the Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Pediatric Brain Tumor
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Childhood Brain Neoplasm
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Neoplasm of the Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Neoplasm of Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Tumor of Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Tumor of Childhood Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Relapsed Tumor of the Pediatric Brain
							term-group: SY
							term-source: NCI
						FULL_SYN: Recurrent Tumor of the Childhood Brain
							term-group: SY
							term-source: NCI

						Named Superclass: Recurrent Brain Neoplasm
						Named Superclass: Childhood Brain Neoplasm
						Named Superclass: Recurrent Childhood Central Nervous System Neoplasm


			Childhood Spinal Cord Neoplasm
				code: C9234
				Preferred_Name: Childhood Spinal Cord Neoplasm

				UMLS_CUI: C1134515
				Display_Name: Childhood Spinal Cord Neoplasm
				Neoplastic_Status: Undetermined
				Concept_In_Subset: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#CTRP_Terminology
				Contributing_Source: CTRP
				code: C9234
				Legacy_Concept_Name: Childhood_Spinal_Cord_Neoplasm
				Preferred_Name: Childhood Spinal Cord Neoplasm
				label: Childhood Spinal Cord Neoplasm
				Semantic_Type: Neoplastic Process

				FULL_SYN: Childhood Spinal Cord Tumor
					term-group: PT
					term-source: NCI
				DEFINITION: A benign or malignant neoplasm affecting the spinal cord during childhood.
					Definition_Review_Date: 071003
					Definition_Reviewer_Name: Nicholas Sioutos
					def-source: NCI
				FULL_SYN: Childhood Spinal Cord Neoplasm
					term-group: PT
					term-source: NCI

				Named Superclass: Spinal Cord Neoplasm
				Named Superclass: Childhood Central Nervous System Neoplasm


Thanks,
Reza

**Comment by bdionne** [comment]
so what should it do here, not write the file? Or print a different message?
