### ISSUE TITLE
Inherit semantic types

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#23]
When a new definition is added the class should inherit the semantic type of the parent

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/commit/7c482b00d43925af1650f7c8393633be49834233)

**Comment by NCIEVS** [comment]
@rmehri, to clarify using Protege terminology, when a class is created it inherits the semantic type of the parent.

**Comment by rmehri** [comment]
Can you please give  me a specific example?  So I can verify the fix for this issue. 

Thanks,
Reza

**Comment by bdionne** [comment]
take any class - it should have a semantic type - create a child class of that class - see if it inherits the semantic type

**Comment by rmehri** [comment]
Thanks for your feedback!  This fix has been retested and verified using tag-116, edit tab. Please see attached screen shots for more detail.

![semantic type inherit-1](https://cloud.githubusercontent.com/assets/8367102/22079922/812e8204-dd8b-11e6-820f-d3a314ce1f0d.png)
![semantic type inherit-2](https://cloud.githubusercontent.com/assets/8367102/22079923/834772bc-dd8b-11e6-99b0-5b468ba60798.png)

Thanks,
Reza
