### ISSUE TITLE
Preferred_Name -Warning Message for characters “:,!, ? or @” Should be Changed to  “! and ?”  

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#230]
Steps to reproduce:
Tag-125, NCI Edit Tab-0.4.9
1) Log into the local server (8080),  Modeler /Manager,
2) Select NCI Edit Tab
3) Select a class 
4) Add a sub class and name as Subclass_Test!?
5) You'll receive the following warning message:   "Preferred name cannot contain :!? or @"
6) According to the statement below: the warning message should be updated for “! and ?”  

1.	#202 - "Allow : in preferred name" - Note that the preferred_name, the FULL_SYN that has source NCI and term group PT, and the rdfs:label always have the same value so this rule will hold for them as well. It was identified that we also want to all @, so as @NCIEVS comments above int he preferred_name we allow : and @ but continue to prevent ! and ?

Please see attached snapshots for more details.

![preferred_name-warning message for invalid punctuation-](https://cloud.githubusercontent.com/assets/8367102/23873368/30bc9b4c-0808-11e7-9f84-3795c4673ce5.png)
![preferred_name-with invalid punctuation](https://cloud.githubusercontent.com/assets/8367102/23873371/3336d4aa-0808-11e7-9364-26b4b5a7e510.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - we already have a ticket for this, so I'm closing this one and re-opening the other.

**Comment by rmehri** [comment]
Ok, Thanks,
Reza
