### ISSUE TITLE
desktop app tries to update from server after logoff

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#231]
The same thing happens when logging out and reconnecting to the server via the admin port.

**Comment by rmehri** [comment]
I have retested this fix and verified the following:
1) Logged into the server admin and then logged off from and no updates took place.  (Pass)
2) Logged into the Client and logged off from it and I see the client is updating from server. I would consider this is fail.  But please let me know if there are specific reproducible steps for this issue, so I can retest and verify the fix.

Thanks,
Reza

**Comment by rmehri** [comment]
This issue has been retested.
Used rebuilt nci-1.006 tag
nci-edit-tab-0.6.1
lucent-search-tab-1.0.4
metaproject-admin-1.0.0

Thanks,,
Reza
