### ISSUE TITLE
editing in the "General" tab requires that annotation properties have a range

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#232]
Currently, in 0.125, a) can't edit an existing annotation on a class if the property declaration doesn't have a range, b) when adding a new property the properties dialog doesn't navigate to literal sub-tab.  There should be a default action instead for when a property is an untyped literal, i.e. no range.

**Comment by bdionne** [comment]
a) throws a null pointer exception when the property has no range. 

b) needs some clarification. When adding a new property the panel should come up with whatever property was last used selected. The editor for the value should correspond to the property's range. When selecting different properties it won't change to another editor if the range on a property doesn't exist. Do you want the default in the case of no range to be the constant editor (untyped literal with the text area)?

I think both of these are addressed in the `0.5.4` dev version of `EditTab`

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using latest build-1.0069 and nci-edit-065. Please see sample screenshots for more details. 
![general_annotation_property](https://user-images.githubusercontent.com/8367102/27301567-a37fa660-5501-11e7-87a9-e98af44e0fee.png)
![add_annotation property](https://user-images.githubusercontent.com/8367102/27301577-b2b246ba-5501-11e7-9942-f59a0d245150.png)
![annotation_property-1](https://user-images.githubusercontent.com/8367102/27301575-b2affd7e-5501-11e7-987b-56a27266aebb.png)
![datatypes-1](https://user-images.githubusercontent.com/8367102/27301574-b2ae7d8c-5501-11e7-8a47-fdaad51de33d.png)
![general_annotation_property](https://user-images.githubusercontent.com/8367102/27301576-b2b036c2-5501-11e7-81c2-ffd8ee39d37d.png)

Thanks,
Reza
