### ISSUE TITLE
update of pellet's config file when access to prod server is restricted

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#234]
On a weekly revision history processing of the vocab, the vocab is exported to an OWL file and the OWL file is then reimported to create a new project with a new ID.  This is done to "squash" changes into a single snapshot file.  But changing the ID in the metaproject will require that the ID be also changed in the pellet config file.  Several options,: automated squashing maintaining IDs, gui support for pellet administration.

**Comment by bdionne** [comment]
An important goal here is to keep the two servers separate and not introduce any dependencies.

I think all the information is there already and there is no real need to manually create a new project as we do currently. When the manager reviews the weekly changes and is ready to produce a new snapshot the process can be started by a button or gesture in the revision diff panel.

A new snapshot is made and pushed to the same project. Perhaps we use the old snapshot as a backup or have an archiving scheme that copies them elsewhere.

A mechanism is needed for the clients when they resume work (once the server is started again) to know their snapshot is out of date and a new one is required. One way to cleanly do this is to store a metadata like hear in the history file containing info about the base snapshots. Clients would retrieve this first before opening the local snapshot, so they would know whether a new snapshot would need to be fetched first.

**Comment by bdionne** [comment]
There is no longer any need to specify the project or ontology id in the pellet startup config file. As long as the project in the metaproject file has the property `classifiable` set to true, the pellet server will fetch and classify that project.

This means that after history is squashed, all one needs to do is restart the pellet server, which managers are empowered to do.

**Comment by rmehri** [comment]
Hi,
Thanks, this fix has been retested on QA server using latest tag 1.0083 and Client-V2.1.10083. 
Start reasoner and restart remote reasoner. Please see attached snapshot for more detail.

![issue 234](https://user-images.githubusercontent.com/8367102/30184387-ee053c4e-93eb-11e7-9797-53777a1522fa.png)

Thanks,
Reza
