### ISSUE TITLE
superclass and superclass (inferred) widgets are unavailable

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#235]
This sounds like a permissions issue.  From EHD:

[NS] does not have the option to add the Superclass hierarchy and Superclass hierarchy (inferred) views. I was logged in first to demo them in his client but when he was logged in later to look at them by himself, the menu items were greyed out. (May be a permissions issue?)

**Comment by bdionne** [comment]
Could be, currently the classification and inferred view tabs are restricted to workflow manager. Is it required to be used by [modelers](https://github.com/NCIEVS/nci-protege5/wiki/editability-of-tabs-per-role) also?

If so that's an easy fix but will require a build

**Comment by NCIEVS** [comment]
Yes, it would be required by modelers.  A build with minimal changes is fine.

**Comment by bdionne** [comment]
requires `nci-0.126`

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using tag-126, NCI Edit-0.5.1.  Used: Workflow-Modeler & Workflow-Manager logins
Please see attached snapshots for more detail. 

![issue-235-workflow-modeler](https://cloud.githubusercontent.com/assets/8367102/24269076/3fb6b0fc-0fe6-11e7-84f3-a682a681c15a.png)
![issue-235-workflow-manager](https://cloud.githubusercontent.com/assets/8367102/24269083/46306842-0fe6-11e7-944b-75ac9c4f6fbc.png)

Thanks,
Reza
