### ISSUE TITLE
using topObjectProperty in a restriction

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#236]
It would be very good if the edit tab could disallow restrictions using this property, i.e. catch this at edit time rather than at classification time.  From EHD:

Classifier still has an issue running to completion when the onotology is turned "upside down". When [NS] had created roles of owl:topObjectProperty (which I assume would turn the ontology upside down), we couldn’t get the reasoner to complete the classification. Once we removed these rol.es, the reasoner took <5 min to complete the classification.

**Comment by bdionne** [comment]
This can be restricted in the next release. It's not clear what's mean by turning the ontology "upside down". Presumably it's a universal relation and would subsume all the others but wouldn't just only push that particular class up towards Thing?

**Comment by NCIEVS** [comment]
Yes, that's a [TR] term;  I suppose [EHD] is using it generically for hard classification problems.  [TR's] scenario is when you have restrictions but no named classes among the N&S conditions; inferred trees wind up duplicated under owl:Thing.

**Comment by rmehri** [comment]
Hi,
Would you please share the reproducible steps so I can verify the fix?
Thanks,
Reza

**Comment by bdionne** [comment]
Yes, this one is captured nicely by the title:

Add an object restriction to any class and select `topObjectProperty` as the object property. YOu should be unable to do this

**Comment by rmehri** [comment]
Thanks for your feedback. This fix has been retested.
Reza
