### ISSUE TITLE
Object properties not always filtered by domain

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#237]
When classes are defined, or have parents defined, object properties are not correctly filtered by domain

**Comment by bdionne** [comment]
requires `nci-0.126`

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag-126, NCI Edit Tab-0.5.1. Please attached snap shots for more details. 

![parent class_object property-domain1](https://cloud.githubusercontent.com/assets/8367102/24267073/6ec20df8-0fdf-11e7-8545-2e69a20a5889.png)
![parent class_object property-domain2](https://cloud.githubusercontent.com/assets/8367102/24267077/6ec6a66a-0fdf-11e7-8451-0a1e09f6f4de.png)
![parent class_object property-domain3](https://cloud.githubusercontent.com/assets/8367102/24267076/6ec31df6-0fdf-11e7-99ba-0ca074cbeb18.png)
![parent class_object property-domain4](https://cloud.githubusercontent.com/assets/8367102/24267074/6ec278ec-0fdf-11e7-89b5-a4d98b0eaf8b.png)
![parent class_object property-domain5](https://cloud.githubusercontent.com/assets/8367102/24267089/807dc65e-0fdf-11e7-8d61-43cc60d56dea.png)

Thanks,
Reza
