### ISSUE TITLE
NCI -Edit Tab-Copy-Concept with Only One FULL_SYN NCI and PT Allows to be Changed to different values

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#238]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-125 & NCI Edit-0.5.0
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select NCI Edit Tab
4.	Select a class with only one Full_SYN with NCI and PT then select CompexEdit tab
5.	Select Copy radio button
6.	Drag the selected class into the Clone pane
7.	Name a class for Clone To 
8.	In Clone pane, select Full-SYN and edit the values for “Term Type” and “Term source” to different values other than requirement below 
“HD, AQ and PT are equivalent Full-Syn term types. (i.e. an NCI/AQ can take the place of an NCI/PT)”
9.	Repeat step# 8 for Clone To then save changes. 
10.	Go to the same classes “Clone From and Clone To”, and you see both classes have only one Full_SYN with no NCI-PT? 

*Note: this behavior occurs on all Split, Dual Edit and also, in step# 8, you delete the value as well.

![edit full_syn-1](https://cloud.githubusercontent.com/assets/8367102/24162276/62c1011a-0e3d-11e7-8d53-bb5fda1dc2eb.png)
![edit full_syn-2](https://cloud.githubusercontent.com/assets/8367102/24162281/648ab586-0e3d-11e7-9aba-9a704fe8a3b7.png)
![edit full_syn-3](https://cloud.githubusercontent.com/assets/8367102/24162285/6612a0a8-0e3d-11e7-828c-49f64d97c8b5.png)
![edit full_syn-4](https://cloud.githubusercontent.com/assets/8367102/24162287/67a17b56-0e3d-11e7-8bc2-97f8f29342b3.png)
![edit full_syn-5](https://cloud.githubusercontent.com/assets/8367102/24162289/69514490-0e3d-11e7-93f5-87ec7049e239.png)
Please see attached screen shots for more details.
 
Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri @NCIEVS nice catch - This is not really a bug, but something I should have considered when allowing the protege widgets to be used in these double panes. Protege uses a different set of embedded editors for these annotations on annotations. So they have none of the features of the annotation editors we have on the general pane, where for example we are sensitive to the type of the annotation. 

There are three approaches to fixing this, which after some investigation I can enumerate in increasing order of code changes:

 * do nothing - my favorite. Warn the modelers of editing outside the complex property tables. We have this same problem currently in the entities tab, which managers can access. They can edit complex props outside the tables

 * modify protege slightly - allow the base classes to take a new interface that allows the edittab to override the post editing code and provide a path into the rules checking. This is not too much code but it's tricky in that the base classes are used by many widgets.

 * modify the frame list in this widget - similar to what we did in the csv exporter - disable the `@` icon that allows the editing of the qualifiers, modify the edit icon and when clicked bring up the property dialog we have from the tables panel. This is probably the ideal solution as it then creates a path through all the existing edittab code with respect to checking rules, etc.. though it still will require modification to protege, somewhat less than the second option.

@NCIEVS - I'll can flesh out these approaches some more today and see what comes up. Let me know which you prefer

**Comment by rmehri** [comment]
Hi Bob,
Thank you for your detailed feedback.  I will retested this issue whenever it is ready for QA. 
Reza

**Comment by NCIEVS** [comment]
Per [EHD], when we get to modify this, we'd also want to include the class expression widgets to enforce role domain/range consistency.

**Comment by bdionne** [comment]
dl;kjlkj #34

**Comment by NCIEVS** [comment]
Check against the new editing dialogs in 2.2.0.  this might not be an issue anymore.

**Comment by singhik** [comment]
QA Verified the clone functionality of a Concept to **not** allow edit of FULL_SYN property for  both the original class as well as cloned class for any value other than NCI/PT/AQ/HD ...
Attached are the screen prints for reference ....
[Issue 238.docx](https://github.com/NCIEVS/nci-protege5/files/1741505/Issue.238.docx)
