### ISSUE TITLE
Merge panels and labels are awkward

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#24]
The merge panel follows the design of split/clone, with the `from` on the left and the `to` on the right.

Additionally the labels `Merge From` and `Merge To` are not as clear as the original `Retiring concept` and `Surviving Concept`

**Comment by rmehri** [comment]
I have retested and validated the fix in "tag -110" successfully.  This issue can be closed. Please attached zip file for video to play for more details. 
Thanks,
Reza
[Merge Panel.zip](https://github.com/NCIEVS/nci-protege5/files/644814/Merge.Panel.zip)
