### ISSUE TITLE
SupperClass Hierarchy Views Pane Showing the SupperClass In Reverse Arrangement.

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#242]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-126 & NCI Edit-0.5.1
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select NCI Edit Tab
4.	Select Window/Views/Super Class Hierarchy View and drag into right pane of NCI Edit Tab
5.	Select parent class or a class then you’ll see the selected parent class 
6.	In Superclass hierarchy: pane, you’ll see the hierarchy arrangement is reverse?
7.	I am not sure if this is by design or else.

*Note: this behavior occurs in superclass inferred as well.

Please see attached screen shots for more details.

![superclass](https://cloud.githubusercontent.com/assets/8367102/24311445/91240cae-10aa-11e7-983d-c2ba0605e2fe.png)
![superclass-1](https://cloud.githubusercontent.com/assets/8367102/24311427/762587de-10aa-11e7-8ca4-bddd7910ecab.png)
![superclass-2](https://cloud.githubusercontent.com/assets/8367102/24311428/78360b84-10aa-11e7-8281-f2d46c38ae03.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Yes, I think it's always been this way. I guess the idea is that one has a class in mind when accessing this view, so it's easier to start there and see the path to the top rather than the other way around.

Myself, what I would do is have it start at the top but open up the tree to the selected class.

**Comment by rmehri** [comment]
Hi Bob,
Thank you, based on your feedback, this ticket can be closed. 
Reza
