### ISSUE TITLE
NCI Edit Tab-Reseting to Default State Causes Exception on dispose: null

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#243]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-126 & NCI Edit-0.5.1
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select NCI Edit Tab
4.	Select Window/Views/Super Class Hierarchy View and drag into right pane of NCI Edit Tab
5.	Select the “Reset Selected tab to default state” 
6.	You’ll see the null exception and then classes contents get unavailable unless log out and log back into the protégé local server 8080.

BAD ViewComponent: (NCIEditViewComponent) Exception on dispose: null
BAD ViewComponent: (ReadOnlyClassViewComponent) Exception on dispose: null
Exception thrown by listener: org.protege.editor.owl.client.ClientSession$1.  De
tatching bad listener.
Checking for updates

Please see attached screen shots and log file for more details

 
[Error_Reset to default State.txt](https://github.com/NCIEVS/nci-protege5/files/873273/Error_Reset.to.default.State.txt)

[Error_Reset to default State.txt](https://github.com/NCIEVS/nci-protege5/files/873135/Error_Reset.to.default.State.txt)

Thanks,
Reza

**Comment by NCIEVS** [comment]
Not a bug.  Debug behavior of stock protege.
