### ISSUE TITLE
Create new class not correctly checking for duplicates

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#244]
From Liz:

This may only be a problem with the byCode, the user is not warned (no red words appear) when they are creating a new concept with a potentially overlapping label. I think this box is still comparing IRI.
 
It did warn me when I tried to type an “illegal” character into the Create Preferred Name slot. However, it is not allowing >, which we use in gene mutation PTs. Although I was able to substitute a hyphen and change it to a > in the Edit pane.

**Comment by bdionne** [comment]
this is [fixed](https://github.com/bdionne/nci-edit-tab/commit/b4eccd8465252b629a4e2e6e1869f12ea973f777) on the new development branch and can be cherry picked for v1.0 is needed, it's kind of an edge case

**Comment by rmehri** [comment]
Hi, 
I have retested and verified this fix using latest tag-nci-1.004, nci-edit ta-05.4 and lucene search tab-1.0.3.
Please see attached screenshot for more detail.

![issue 244](https://cloud.githubusercontent.com/assets/8367102/25359043/9f612cb4-2911-11e7-9fd1-aad3cb45a6af.png)

Thanks,
Reza

**Comment by NCIEVS** [comment]
This is not working in a "byCode" environment where the IRI fragments are meaningless.  The original software tested for dups in the fragment IRI, and that is still working.  It needs to be tested on the label or preferred name.

**Comment by bdionne** [comment]
Is this on the current prod, `0.127', or is this `nci-1.005`? 

Was the ontology indexed?

**Comment by NCIEVS** [comment]
This was in 1.005, and I believe it was indexed (or searches wouldn't work).  Let me try it again after doing a manual indexing.

**Comment by bdionne** [comment]
ok, I'll load a byCode later and test it

**Comment by NCIEVS** [comment]
OK, I just verified that in byCode the collisiion is not detected.  To clarify, it should not be forbidden to create a concept with a PT that is in use elsewhere, just issue a warning that the PT already exists (and click "yes" to proceed).

**Comment by bdionne** [comment]
ok, I'm loading the large byCode now and will try to reproduce. If this requires the Lucene search as we did for the batch load it will have to wait for the next post production release as it will need more rework. The searching code is heavily threaded and doesn't behave well within dialogs.

I can check but I believe we don't require the user not create a dup, they are see an `ok/cancel` which gives them the choice

**Comment by bdionne** [comment]
this is working locally, using byCode, we'll have to dig into it
<img width="1016" alt="screen shot 2017-04-26 at 1 14 54 pm" src="https://cloud.githubusercontent.com/assets/31741/25447253/7aaa48fc-2a82-11e7-9876-9f53a2c6325a.png">

**Comment by NCIEVS** [comment]
Ah, try a multi-token string.  The one I tried was "Access to Care".

**Comment by rmehri** [comment]
As per development's comment, this ticket will remain open for further investigation.  Thanks

**Comment by bdionne** [comment]
@rmehri - I'm not sure which developer comment you are referring to. As far as I know this is fixed and ready for QA

**Comment by rmehri** [comment]
Hi Bob, 
As per your comment below, I responded.  Also, this ticket was retested and verified and closed once before using nci-1.004.  Please let me know if you need to do further investigation. Or, I can close this issue. Thanks.

Bob Stated:
this is working locally, using byCode, we'll have to dig into it

**Comment by bdionne** [comment]
I see the confusion, Gilberto's next comment indicate the issue is caused by multi-token names:

"Ah, try a multi-token string. The one I tried was "Access to Care"."

That enabled me to reproduce the bug readily and fix it, which is why I marked it ready for QA again and removed the other labels.

Yes this needs to be verified again in the 1.005 build

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! I have retested this fix using tag-1.005.  Also, I did not receive the warning message for class duplication. Please see attached screenshots for more details.
![issue-244-1](https://cloud.githubusercontent.com/assets/8367102/25913566/3c213480-3589-11e7-8174-bcd9cd74cb05.png)
![issue-244-2](https://cloud.githubusercontent.com/assets/8367102/25913570/3dc12462-3589-11e7-82ad-15ce2e7434c9.png)
![issue-244-3](https://cloud.githubusercontent.com/assets/8367102/25913712/b91a3e14-3589-11e7-8ae9-ff6759304dbe.png)
Thanks,
Reza
