### ISSUE TITLE
Use the renderer to sort results in Lucene Query Plugin

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#246]
From Liz:

the search results in the Lucene Search Tab of the byCode NCIt appear to be sorted by IRI (in this case it is sorted by the codes)

**Comment by rmehri** [comment]
This issue has been retested good. Thanks.

**Comment by NCIEVS** [comment]
Reopening issue.  The sorted output is broken in 1.008.

**Comment by bdionne** [comment]
[fixed in 1.0.8](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.8)

**Comment by rmehri** [comment]
Hi,
This fix has been retested using tag 1.008, Lucene Search Tab 1.0.8. Please see attached snapshots for more details.

![issue-246-1](https://user-images.githubusercontent.com/8367102/28631092-1ac402e2-71fa-11e7-9a71-2a2fd5e070be.png)
![issue-246-2](https://user-images.githubusercontent.com/8367102/28631096-1ac99b9e-71fa-11e7-807b-55b73ef87482.png)
![issue-246-3](https://user-images.githubusercontent.com/8367102/28631093-1ac42a6a-71fa-11e7-8cd3-88ffd2bd17be.png)
![issue-246-4](https://user-images.githubusercontent.com/8367102/28631095-1ac66ff0-71fa-11e7-8c15-f9fc7f223caf.png)
![issue-246-5](https://user-images.githubusercontent.com/8367102/28631091-1ac3c322-71fa-11e7-9bae-b876cca1b8b9.png)
![issue-246-6](https://user-images.githubusercontent.com/8367102/28631094-1ac42cd6-71fa-11e7-825f-dee8ac66e8a7.png)

Thanks,
Reza
