### ISSUE TITLE
Tag-126-Help-Documentation-Protege Release Number Not Updated

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#248]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-126 & NCI Edit-0.5.1
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select Help link and you’ll see the protégé release number for the following links have different release number like “5.2.0”, and “5.0”,”5.1.1”  

" Protégé Documentation, Release Notes and About"
Please see attached screen shots for more details.

![protege_help-release number-2](https://cloud.githubusercontent.com/assets/8367102/24477836/9e398806-14a6-11e7-99f0-fb33eb662c59.png)
![protege_help-release number](https://cloud.githubusercontent.com/assets/8367102/24477837/9e3aae70-14a6-11e7-854a-b5c7bb108f6a.png)
![protege_help-release number-1](https://cloud.githubusercontent.com/assets/8367102/24477838/9e3ff3d0-14a6-11e7-8c8b-895344ad94f9.png)

Thanks,
Reza

**Comment by NCIEVS** [comment]
This is because our current build doesn't use that codebase.

**Comment by rmehri** [comment]
Hi, 
Thank you for your feedback!
Reza
