### ISSUE TITLE
use LDAP for authentication

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#25]

**Comment by NCIEVS** [comment]
Will not create LDAP groups for protege, these will be managed from within Protege itself.  However, authentication in production will still be against NIH's AD/LDAP.  Renaming this ticket to "use LDAP for authentication".

**Comment by bdionne** [comment]
To test this the server needs to be run configured with the `LDAP` authenticator:

````
"authenticate": "org.protege.editor.owl.server.security.LDAPLoginService"
````
and the appropriate `host/port` props need to be set for `LDAP`

````
"ldap_host:xxx"
"ldap_port:yyy"
````

The client must login with a valid `LDAP` user

**Comment by rmehri** [comment]
Hi Bob,
 Thanks for your feedback! We'll discuss about this ticket in today's meeting.
 Reza

**Comment by rmehri** [comment]
Hi, 
This enhancement has been retested and verified using tag-120, edittab-0.3.8.
Sever: https://nciws-d699-v.nci.nih.gov:9090
Login: My LDAP

Thanks,
Reza
