### ISSUE TITLE
enhance basic query searches

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#251]
Users are accustomed to typing in multiple in multiple words into a basic query search, .eg. "Gene Throat" and having the effect be the same as two basic queries, one for each word. Tokenize the search string and treat as an implicit conjunction

**Comment by rmehri** [comment]
Hi, 
I have retested this fix using nci-1.005, Lucene Search Tab 1.0.3 and Edit Tab -0.5.8.  The search functionality on both lucene search tab and edit tab works fine.  But pressing Ok button causes exception error with or without using any search criteria.  Please see the attached screen shots and log file for more detail.

![search1](https://cloud.githubusercontent.com/assets/8367102/25449983/7ae66e6e-2a8b-11e7-90c5-66333a3bfba2.png)
![search2](https://cloud.githubusercontent.com/assets/8367102/25449988/7c40ac66-2a8b-11e7-8e8a-080b0bcd64cb.png)
![nci edit tab-search-error](https://cloud.githubusercontent.com/assets/8367102/25449999/87108f58-2a8b-11e7-989e-614935f1ba9f.png)

[Log file Eror.txt](https://github.com/NCIEVS/nci-protege5/files/959374/Log.file.Eror.txt)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri 

This sounds like a separate issue that exists independently of this one. You should open a new ticket

**Comment by rmehri** [comment]
Hi Bob, 
Thanks and I agree. This issue can be closed. For Ok button I created a new issue: https://github.com/NCIEVS/nci-protege5/issues/269

Thanks,
Reza
