### ISSUE TITLE
issue renaming a project after creation 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#252]
a new vocab was created with the same name as an existing one.  it was renamed afterwards, but this resulted in the vocab not being accessible from the protege server.  the config file had the correct ID for the renamed project, this project existed in the correct location, but the snapshot & history filenames didn't match.  The renamed project name included version info, the snapshot wasn't renamed, and there were 2 history files, one didn't match:
    NCI_Thesaurus.history
    NCI_Thesaurus.history-snapshot
    NCI_Thesaurus_17.04b.history

**Comment by rmehri** [comment]
Hi,
This issue has been retested and verified the fix using latest tag nci-1.0069, Metaproject Admin1.0 and Edit Tab - 065. The renamed vocab is accessible as well. Please see attached snapshots for more detail.

![issue-252-1-previous](https://user-images.githubusercontent.com/8367102/27254743-37bcf144-535d-11e7-9f1d-6700513ce6d8.png)
![issue-252-2](https://user-images.githubusercontent.com/8367102/27254749-3d4413fe-535d-11e7-9bfd-3ed11bcbcbf0.png)
![issue-252_3](https://user-images.githubusercontent.com/8367102/27254753-48695b9a-535d-11e7-9816-b0bcf4f1e480.png)
![issue-252_4](https://user-images.githubusercontent.com/8367102/27254754-486a5cac-535d-11e7-8f40-30fd8540617d.png)

Thanks,
Reza
