### ISSUE TITLE
quirky behavior when editing annotation properties

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#253]
There is currently an interaction between these tabs and the NCI tab. When e.g. properties are edited and committed, switching to the NCI tab results in a previously highlighted class flagged as "(editing)", which prevents the user from doing much until a Save or Clear. In some linux environments there is a rendering issue where these buttons are not displayed. The workaround for now is that the admin user needs to exit & restart Protege after doing property edits

**Comment by bdionne** [comment]
not reproducible in `NCI-1.005`

**Comment by NCIEVS** [comment]
Issue fixed as side effect of renderer work elsewhere.
