### ISSUE TITLE
'maintenance mode' message when server is paused

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#256]
In the new p5 baseline, every time I try to Save edits, I am getting a message that says “Server in maintenance mode, please try later.”

It appeared that the server is not paused and it is updating. I tried to manually initiate a server update but it says the local copy is up to date and there were no uncommitted changes. I then paused the server and unpaused it, now it appears to work.

[perhaps the message needs to be changed, awaiting feedback.]

**Comment by hahndane** [comment]
This is related to issues with Pause Server function and the fact that the user instance that pauses the server is required to unpause the server as well. The server was most likely not unpaused properly after the Revision History review, baseline export and new project creation. (I am not sure why this occurred.) However, when I logged in and selected Pause Server, I became the "owner" of the pause action and then was able to successfully unpause the server.

**Comment by bdionne** [comment]
can't reproduce this in `nci-1.005`, I'm not sure exactly what's going on, I did fix the autoupdater but that's unrelated.

@hahndane - that's not quite the way it works, though you may perceive it that way. The only restriction on this function is that the user must be a `workflow manager`. We can discuss this if it's preferred to require that only the user who `pauses` can `unpause` but currently any workflow manager should be able to do it.

**Comment by hahndane** [comment]
There are two issues here, the first is that I don't know how to replicate the series of events that occurred.  Nicole did the squashing of the old baseline and creation of the new project. The second issue is, if I don't select Pause Server then I don't see that Pause Server was selected by another user and thus cannot deselect it to unpause.

**Comment by bdionne** [comment]
these are separate issues: I'll try to reproduce the error you see. With respect to the second, we have a ticket for an enhancement to display the state of the server so that you can tell when logging in whether or not someone else has paused the server. That should help clear up the confusion

**Comment by NCIEVS** [comment]
Closing.  Consider fixed based on inability to replicate.
