### ISSUE TITLE
output of empty optional qualifiers

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#258]
This is apparently happening with newly created concepts, see P385 & P386 below.

    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133398"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ypTNM Finding</owl:annotatedTarget>
        <P385 rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></P385>
        <P386 rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></P386>
        <term-group rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SY</term-group>
        <term-source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</term-source>
    </owl:Axiom>

**Comment by bdionne** [comment]
The [issue](https://github.com/bdionne/nci-edit-tab/commit/082dd245508b8e2abf3ec6ea2aacf84baa98f803) was were checking for nulls rather than empty strings which are what come out of the widgets. This will be available in the next `EditTab` push

**Comment by rmehri** [comment]
This issue will be retested in the next release of  EditTab .
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I created a new concept or class and Full_SYN with PT & NCI then added the second FULL_SYN with SY & NCI.  Would you have the reproducible steps? So I can verify the fix.

Thanks,
Reza

**Comment by bdionne** [comment]
There are no specific steps, other than to edit a full syn and leave out optional qualifiers and then inspect the exported xml for null tags as above

**Comment by rmehri** [comment]
Thanks for your feedback! I will retest it.

**Comment by NCIEVS** [comment]
Or you can enable the Entities tab and examine the full_syn (or other complex property) in there.  The empty properties will be there but without a value.

**Comment by rmehri** [comment]
Hi, 
I have retested and verify the fix using nci-1.005, edit tab-0.5.9, Lucene Search Tab-1.0.3

lass rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C1001">
        <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Activity"/>
        <Thesaurus:FULL_SYN rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></Thesaurus:FULL_SYN>
        <Thesaurus:FULL_SYN rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Test_Issue258</Thesaurus:FULL_SYN>
        <Thesaurus:Preferred_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Test_Issue258</Thesaurus:Preferred_Name>
        <Thesaurus:Semantic_Type rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Activity</Thesaurus:Semantic_Type>
        <Thesaurus:code rdf:datatype="http://www.w3.org/2001/XMLSchema#string">C1001</Thesaurus:code>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Test_Issue258</rdfs:label>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C1001"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#FULL_SYN"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></owl:annotatedTarget>
        <Thesaurus:term-group rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SY</Thesaurus:term-group>
        <Thesaurus:term-source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</Thesaurus:term-source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C1001"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#FULL_SYN"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Test_Issue258</owl:annotatedTarget>
        <Thesaurus:term-group rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PT</Thesaurus:term-group>
        <Thesaurus:term-source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</Thesaurus:term-source>

Thanks,
Reza
