### ISSUE TITLE
Issues from modelers with respect to dual editing period - 4/19/17

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#259]
* syncing data
   - coverage - CDISC has sparse editing schedule
   - editors have full schedules

* classification issue with protege 3, better results in protege 5

* too much editing to keep editing in both systems at once

* new batch editing formats are quite different, makes migration awkward

* data will be synced in the end, main purpose of dual editing is testing the functionality

* Def_Curator is not handled in protege 5 (next round of development)
   - will catch as a QA process on data

* Classification had issues and could not recover

* Can't always save on edits, related to autoupdates?

* One hang, and twice the computer rebooted - seems to be an issue with windows updater

* compares of data, protege5 adds untyped literals

* running protege 5 through rest of publication process
   - inferred view complete
   - OWL summary reports, review of QA report, test master scripts, extract branches

* review next steps/development
   - discussion of categories (bugs, enhancements, tools, infrastructure)
   - infrastructure is lees of a concern to modelers
   - need feedback/priorities from modelers wrt enhancements

* proposal for small group to triage issues and disseminate to larger modeling community

**Comment by NCIEVS** [comment]
Def_curator issue is being handled in another ticket (#207).  This ticket can be closed.
