### ISSUE TITLE
indexing goes out of sync

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#261]
Feedback was:  "I have found that I often need to rebuild the Lucene Index manually during the course of a day editing. Otherwise new content may not show up as search results."

**Comment by NCIEVS** [comment]
Currently in nci-1.006, this has turned out to be a high-frequency issue.  Might need to increase the priority as it happens not only with content that is fetched from the server, but also with content developed by the editors themselves during any given session.

**Comment by NCIEVS** [comment]
Mostly fixed, but there might be some edge cases, like the indexing of annotations on annotations (e.g. when they get deleted).

**Comment by bdionne** [comment]
Itendra: Please provide steps to reproduce this issue .

This is an old one. I don't know the use case here, perhaps one of the modelers or Gilberto might know.

**Comment by NCIEVS** [comment]
This one is not easy to reproduce or test
- start with a freshly indexed vocab
- do editing, including periodic concept creations, for several hours
- periodically search for new/edited content to review or re-edit the content
- at some point, if the bug is there, edited content or new content willl not show up in a search

So under some condition lucene fails to reindex changes to the content.  a) a particular editing operation fails to be indexed every time (however only used periodically during the day), or b) some ill-defined change of state in protege during prolonged editing that makes the indexer fail on new edits.  To cover "a", I think @bdionne reviewed all the editing cases and the spots he found he fixed.

**Comment by singhik** [comment]
@NCIEVS & @bdionne  : Hi ,   I have been performing Concept creations and Edit on Client V2.2.0 Beta-2 Protege and then Searching . It appears to work 'in-sync '  for Concept creation and Property addition, 

However it is 'Out-Of-Sync' for Property Deletion : Please find below the screen prints with details : 

Concept 'Index_26' has a Property 'Editor_Note' associated as below :: 

![image](https://user-images.githubusercontent.com/36314371/36808250-933c6ce4-1c92-11e8-9ed0-16195c677265.png)

Removing the Property 'Editor_Note' and saving the Concept 'Index_26' ::

![image](https://user-images.githubusercontent.com/36314371/36808295-a8ec307e-1c92-11e8-8969-7b5d8bd64ea5.png)

After removing, searching for Property 'Editor_Note' still shows concept 'Index_26' returned in search Results ::


![image](https://user-images.githubusercontent.com/36314371/36808377-e99a39a4-1c92-11e8-9e42-1805aa125c38.png)

![image](https://user-images.githubusercontent.com/36314371/36808385-efd6ac08-1c92-11e8-9514-39d81bab14cb.png)

**Comment by bdionne** [comment]
This works fine for me, @singhik by any chance had you forgotten to save the concept? I tried it with `Editor_Note` and some other properties also.

When you test it, look on the console and see if you see messages like:

````
2018-03-01 18:50:00.946 [pool-1-thread-1] INFO  SearchTabManager    Updating index with 1 change(s)
We have the following 626354 and in ram 0
````

You should see that when you insert and something similar when you delete. If you don't then it's not updating.

**Comment by bdionne** [comment]
I'm still not able to see any issue with this. @singhik - I'm around all day if you'd like to do a screen share over skype or webex, so you can show me the context, let me know.

**Comment by singhik** [comment]
@bdionne : Hi Bob, i am still able to reproduce the same. If you could please join the webex meeting i sent you from 11:30 AM Est to go over these ...

**Comment by bdionne** [comment]
@singhik - I got your email, will join the webex. I'm thinking if this issue is real and reproducible I'll probably recommend we put both of them off until the next release (I'll get feedback from @NCIEVS )

they are both minor with easy workarounds

**Comment by singhik** [comment]
@bdionne :Sure, Thanks Bob ...

**Comment by singhik** [comment]
Hi All,
          Bob and I discussed this and found that Indexing is better than  prior but still there are few cases where Search results do not retrieve expected results f.e. Deletion of annotation properties and in few cases of addition of properties too. This behavior however is only reproducible in Windows (Windows 10 is being used by QA) as Bob is not able to reproduce it in Mac OS . Attached are the logs which we gathered from Protege Console during call for reference ..

[Issue_261_Logs.txt](https://github.com/NCIEVS/nci-protege5/files/1776044/Issue_261_Logs.txt)

**Comment by bdionne** [comment]
moving this to 2.3 - to be revisited then

**Comment by singhik** [comment]
@bdionne : Hi Bob, is this Issue Ready For QA as yet ?

**Comment by NCIEVS** [comment]
Per [EHD] and [NT] hasn't been seen recently, perhaps because of the recent autoupdate fix.  Close and open new ticket if it's observed again.
