### ISSUE TITLE
alignment of values in tables (complex properties)

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#262]
The request is to have all annotations on annotations be horizontally centered and vertically top-aligned in the complex properties tables.  Feedback from [EHD]:  "I know we talked about having the values in the Complex Property fields be aligned to the top and centered in the cell so the shorter values could be found more easily. They were centered in the cell before so in the DEF and ALT_DEF charts (where the Value can be quite long) the sources and other annotations were difficult to see. Now most of them are on the right but still centered in the height of the cell. It looks like one field has been adjusted so that the value is displayed at the top right side of the cell, the ALT_DEF def-source. It looks very strange because it is not centered (minor annoyance) and because the DEF def-source is still in the middle of the height cell. See the example below."

[in the image sent over email, 11:17 AM 4/20/17, the image shows the complex properties ALT_DEFINITION and DEFINITION, with the "definition source" aligned Horizontally left & Vertically top aligned in ALT_DEF but H-left & V-center in the DEF.  The definition_reviewer_name and the definition_review_date in both definitions are H-left & V-center aligned.]

**Comment by rmehri** [comment]
This issue has been retested.  The following behaviors still exist: 

1) In Alt_Definition, table, the "definition Review Date" and "definition Source" still aligned 
horizontally left & vertically top.  
2) In Alt_Definition, table, the "Comment" field does not text wrap. 
 
Please see attached snapshots for more details.
![issue_262](https://cloud.githubusercontent.com/assets/8367102/26375790/423d1b00-3fd8-11e7-9ca4-0b51edb7d7b9.png)
![issue_262-1](https://cloud.githubusercontent.com/assets/8367102/26375793/43dc7b9a-3fd8-11e7-8d75-e4e4919ca229.png)

Used
Local Server: "8080"
Used latest rebuilt tag nci-1006, 
Edit Tab -0.6.1
Lucene Search Tab-1.0.4
metaproject1.0.0
Metaproject Admin-1.0.0

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - It looks to me like the `Value` column is also not wrapped. Can you please enumerate the steps to reproduce this? The only way I can reproduce this is by shrinking and stretching the columns. Was this `ALT_DEFINITION` there already or was this one you added? 

Here's what I see when I add a new `ALT_DEFINITION`:
<img width="1025" alt="screen shot 2017-05-24 at 9 10 56 am" src="https://cloud.githubusercontent.com/assets/31741/26404747/036d93ee-4061-11e7-9311-992b70f35870.png">

But then if I shrink the `Definition Reviewer Name` and then stretch it back out until the label appears I see:
<img width="1022" alt="screen shot 2017-05-24 at 9 12 09 am" src="https://cloud.githubusercontent.com/assets/31741/26404817/397f0f08-4061-11e7-85c4-1f6ed9f991c0.png">

**Comment by rmehri** [comment]
Hi Bob,

Yes I was removed the existing property rows and added new property rows, which did not show correctly.   But , I retested again and added a new class with their properties. Here are the steps below to reproduce: 

1.	Launch server and client
2.	Log into local host http://localhost:8080  
3.	Select NCI Edit tab
4.	Create a new class and save it.
5.	Edit Full_Syn and add short text into the comment field and save it.
6.	You’ll see all the values are horizontally centered and vertically top-aligned, except the text in the “Value” field, which is not aligned correctly. 
7.	Repeat step 5 and add long text into the comment field and save it.
8.	You’ll see the long text in the comment field does wrap up correctly.
9.	Do the right click on the class and select Add Complex Property
10.	Add definition and select all the values and then add short text into the value field and save it.
11.	You’ll see the text in the Value field is not aligned correctly.
12.	Repeat step 9 through step 11 for Alt_definition and you’ll see the text in the Value field is not aligned correctly either.
13.	In Add definition comment field, if you add short text, the short text aligns correctly.  But 
for long text, the text does wrap up.  Please see attached snapshots for more details.


![issue-262-1a](https://cloud.githubusercontent.com/assets/8367102/26412239/0e84f1ae-4076-11e7-868b-1995c0a6e90b.png)
![issue-262-1b](https://cloud.githubusercontent.com/assets/8367102/26412245/12bd8bfa-4076-11e7-96d2-b0c53bc436e5.png)
![issue-262-1c](https://cloud.githubusercontent.com/assets/8367102/26412249/169f5fd2-4076-11e7-9ca4-fbdfc69f0130.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - I believe this is working as intended. The requirement was to make the `Value` column wrapping, but not any of the other qualifiers.

All the other qualifiers are aligned top center. We can change this if needed, there's some back and forth from the modelers about it and possibly the preference to make them top left aligned

**Comment by rmehri** [comment]
Thanks for the feedback! So this ticket will remain open for the further requirement clarification. 
Reza

**Comment by bdionne** [comment]
yes, if it ends up require more work we can change it to the next milestone, but it will be good to let the modelers have a look at it first

**Comment by rmehri** [comment]
Hi,
This issue has been retested using nci-1.0069, nci-edit-0.6.5. I still see the same behaviors still exist:
Used local server""8080"
1) The values in the value fields for the following are still off alignment
  properties FULL_Syn, Definition and Al_Definition 
2) The value in comment fields are not wrapped up. and some the values are centered.
Please see attached snapshots for more details and let me know your thought.
![issue-262](https://user-images.githubusercontent.com/8367102/27456394-e5b8a4b8-576e-11e7-80a8-3060b70f0033.png)

Thanks,
Reza

**Comment by NCIEVS** [comment]
The current behavior in 2.1.0.14 is consistent across annotation properties displayed in the complex property tables.  H-centered, V-top, except for the value itself which is H-left, V-top to allow for wrapping.

**Comment by singhik** [comment]
Complex property columns are all H-Centerd ,V Top except for Value which is H-left ,V-top in Protege client v2.2.0 ....

![image](https://user-images.githubusercontent.com/36314371/36434029-0d5fcc54-162c-11e8-9176-8f855c40274b.png)
