### ISSUE TITLE
Do edit checks at the time the concept is Saved 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#263]
Dual-editing feedback from [NT]:  "I’m not sure it is possible to change the preferred name of a concept. If you create a second Full_Syn with ‘PT’ you get an error: “One and only one PT with source NCI is allowed”; if you try to first change the existing PT Full_Syn to SY you get the same message. The check needs to be at ‘Save’, not at Full-Syn creation/edit. I thought I had figured out a work-around, but I can’t remember what it was and I can’t duplicate it now. If we don’t have a procedure for this, then it rises above “annoyance”.

There is a workaround for now using the dual edit panel.

**Comment by NCIEVS** [comment]
Related to the above, from [EHD]:
"The NCI PN/PT/label properties will not be edited if you try to add a new term to the Preferred Name slot at the top of the concept view in the Edit tab. The only way to change a PT is to edit the NCI PT in the FULL_SYN table. You can type or copy/paste a value in the PN slot but that edit is not Saved; no message is given by the GUI or in the log, that field just reverts to whatever it was before editing the PN field."

This was tried as a workaround for the issue above.  Whether this additional editing path needs to be supported once the Save issue is resolved remains to be determined.

**Comment by rmehri** [comment]
Hi,
Can you please let me know the fix description so I can retest and verify? 
Thanks,
Reza

**Comment by bdionne** [comment]
Three things were going on here:

1. editing the preferred name text box in the edit panel. On save it should change the `FULL_SYN/PT`

2. being able to change the `FULL_SYN/PT` to another `FULL_SYN`. There can only be one so for now you have to switch the values. This was not working before

3. Replacing `PT` with `AQ` or `HD` - all three are the same

**Comment by rmehri** [comment]
Hi,
Thanks for the feedback!  I have retested this fix. Please see attached snapshots for more details.
used: nci-1.006, Edit Tab-0.6.1, 
 
![issue_263-1](https://cloud.githubusercontent.com/assets/8367102/26470714/ad4e1f44-416c-11e7-9dcd-62b009e07ebe.png)
![issue_263-2](https://cloud.githubusercontent.com/assets/8367102/26470712/ad4c73ec-416c-11e7-9c85-4a848a645e0e.png)
![issue_263-3](https://cloud.githubusercontent.com/assets/8367102/26470711/ad4c1b54-416c-11e7-89bb-1d32ea0b14cb.png)
![issue_263-4](https://cloud.githubusercontent.com/assets/8367102/26470713/ad4df456-416c-11e7-88e4-ea0371056934.png)
![issue_263-5](https://cloud.githubusercontent.com/assets/8367102/26470716/ad515b64-416c-11e7-8ea4-3000df848503.png)
![issue_263-6](https://cloud.githubusercontent.com/assets/8367102/26470715/ad4e2e80-416c-11e7-8e6d-821c73a8afbc.png)
![issue_263-7](https://cloud.githubusercontent.com/assets/8367102/26470717/ad5290f6-416c-11e7-8221-24bb42ab5b2f.png)
![issue_263-8](https://cloud.githubusercontent.com/assets/8367102/26470719/ad5759d8-416c-11e7-9044-3c2b44e6ce13.png)
 
Thanks,
Reza
