### ISSUE TITLE
Tag-1.003 - Tools-Duplicate links- Export to CSV

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#265]
Steps to reproduce:
Logins: Modeler & Manager
 Tag-1.003 & NCI Edit-0.5.6
 Steps to reproduce:
1.Launch protégé server and client
2.Log into the local server (8080)
3. On top browser, select Tools and you’ll see the duplicated links for Export to CSV.

Note: this behavior happens with and without logging into protégé on tag 1.003 but not on the previous tag. Please see attached screenshot for more detail.

![duplicate export to csv](https://cloud.githubusercontent.com/assets/8367102/25247076/be929e5c-25d7-11e7-8a62-663096aa4e95.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Thanks Reza, I'll take a look at it

**Comment by rmehri** [comment]
You're welcome,
Reza

**Comment by bdionne** [comment]
I suspect this issue is because you have the new lucene-search-tab plugin loaded as well as the csv-export-plugin

Try this again with the nci-1.004 tag and use the two plugins from the NCI autoupdate, lucene-search-tab and edittab.

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using nci-1.004 tag, Edit Tab-0.5.4, Lucene Search Tab-1.0.3. The CSV-export-plug is excluded from project .
Thanks,
Reza
