### ISSUE TITLE
Issues with datatypes in batch edits (Concept_In_Subset)

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#268]
From EHD:

Hi
 
I had batched in Concept_In_Subset properties for ~140 concepts for Teri’s FDA Blood and Tissue Form Terminology, but I had misaligned the codes for the concepts that were edited, so about 60 of these got the wrong value. I tried modifying these values in batch and then tried to delete these values in batch and neither file worked (I used full IRI for these values as per the template). The modify file had some new concepts and adding Concept_In_Subset to these terms worked.
 
The output files for the modify and delete batches all say that those values don’t exist. All the batch files and output files are attached. I haven’t added the correct values in batch yet because I will need to manually delete the inappropriate values first.
 
Thanks,
Liz

**Comment by bdionne** [comment]
The bug here was not using the property's datatype on `delete` and `modify` to look up the value. The value was treated as an `OWLLiteral` as opposed to `xsd:anyURI`

**Comment by bdionne** [comment]
[FDABlood_CIS_delete_OUT.txt](https://github.com/NCIEVS/nci-protege5/files/958640/FDABlood_CIS_delete_OUT.txt)
[FDABlood_CIS_Fix_OUT.txt](https://github.com/NCIEVS/nci-protege5/files/958641/FDABlood_CIS_Fix_OUT.txt)

**Comment by bdionne** [comment]
fixed in `nci-edit-tab-0.5.8`

**Comment by rmehri** [comment]
Hi, 
Would you have the input files for this issue? 
Thanks,
Reza

**Comment by bdionne** [comment]
[FDABlood_CIS_delete_Batch.txt](https://github.com/NCIEVS/nci-protege5/files/964485/FDABlood_CIS_delete_Batch.txt)
[FDABlood_CIS_Fix_Batch.txt](https://github.com/NCIEVS/nci-protege5/files/964486/FDABlood_CIS_Fix_Batch.txt)

**Comment by rmehri** [comment]
Thank you!
Reza
