### ISSUE TITLE
NCI Edit tab-Search-Pressing Ok Button Causes Exception Error 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#269]
Steps to reproduce:
Used Local Server (8080),  nci-1.005, Lucene Search Tab 1.0.3 and Edit Tab -0.5.8. 
1) Launch protégé server and client
2) Select NCI Edit tab
3) Select Search tab
4) Pressing Ok button causes exception error with or without using any search criteria. Please see the attached screen shots and log file for more detail.
[Log.file.Eror.txt](https://github.com/NCIEVS/nci-protege5/files/959488/Log.file.Eror.txt)
![search1](https://cloud.githubusercontent.com/assets/8367102/25451867/9cbd59ac-2a91-11e7-8bbc-bd913708775e.png)
![search2](https://cloud.githubusercontent.com/assets/8367102/25451869/9e72d79a-2a91-11e7-8d2d-4e668e42cd25.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Ok, this throws an exception if the user *doesn't* select a result and proceed to hit `ok`

Other than the exception is there anything not working?

**Comment by rmehri** [comment]
Hi Bob, 
No. The searches work fine.  
Thanks
Reza

**Comment by bdionne** [comment]
see #271
