### ISSUE TITLE
Tag-nci-1.005-Unable to switch from vocab view to Server Admin

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#270]
Steps to reproduce:
Used:
Servers: http://localhost:8080 &  http://localhost:8081
Logins: Modeler & Manager
Tag-nci-1.005 & NCI Edit-0.5.9
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select project 
4.	Navigate through NCI Edit Tab and Lucene Search Tab plugs
5.	Logout from client or launch another client
6.	On the top browser, select Server 
7.	Login into the local system admin “8181” with sysadmin or i.e. via 
8.	You’ll see the user logged into server but the browser displays for vocabulary. 
*Note: I did the “Reset Selected tab to default state quite a few times to no help. 
Please see attached screenshots for more details. 

![server-admin-1](https://cloud.githubusercontent.com/assets/8367102/25491664/a7a718be-2b3e-11e7-925e-bc38f3b01e21.png)
![server-admin-2](https://cloud.githubusercontent.com/assets/8367102/25491668/a9597d6e-2b3e-11e7-95a8-8f42b5ecfdc0.png)

Thanks,
Reza

**Comment by bdionne** [comment]
you probably need to delete existing preferences

**Comment by rmehri** [comment]
Hi, 
I have reset the preferences and retested it successfully. 
Used: Tag-nci-1.005  
Thanks,
Reza
