### ISSUE TITLE
strings not rendered properly in changes detail panel

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#272]
Better formatting needed in prompt changes details panel

**Comment by bdionne** [comment]
ready in [revision history](https://github.com/bdionne/revision-history/releases/tag/revision-history-1.0.0). This requires the `nci-1.006` tag

**Comment by rmehri** [comment]
Hi Bob, 
I compared the change details panel content for a selected class and compared it with the previous tag and don't see much change in this panel.  Can you please let me know the reproducible steps? so I can verify this fix.  Used nci-1.006 tag against the following tags: 1) nci-1.003 and 2) nci-1.004
Meanwhile, please see attached screenshot for more detail.
![untitled1](https://cloud.githubusercontent.com/assets/8367102/26076093/96e876e4-3985-11e7-8c0c-2c73dbd71562.png)


Thanks,
Reza

**Comment by bdionne** [comment]
The issue here is that when the text string are very long they were not wrapping properly and could not be read.

**Comment by rmehri** [comment]
Thanks for your feedback! This issue has been retested and verified using nci-1.006 tag. Please see attached screenshot for more detail. 
![issue-272](https://cloud.githubusercontent.com/assets/8367102/26106334/93ccd002-3a13-11e7-94c8-43feebe16ef5.png)
Reza
