### ISSUE TITLE
display associated "qualifiers" of complex properties for selection in report writer

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#273]
From [EHD]:
"Would it be possible to enhance the report mechanism to make choosing complex property annotations easier? Right now when you choose a complex property value in a report, i.e. DEF or FULL_SYN, when you choose the annotations you want to add you are choosing from the entire list of properties/restrictions in NCIt. Additionally, if you want to choose annotations that don't all start with the same letters, i.e. term-source and subsource, you cannot use the type ahead to narrow down the list because you have to multiselect the annotations simultaneously. What would be ideal is when choosing a complex property is to only show the annotations that are part of that property based on the data in the metaproject. For example, if an editor wants to generate a report that includes DEFINITIONs and is choosing the DEF annotations they would only have to pick from attr, def-source, Definition_Review_Name and Definition_Reviewer_Name (maybe comment could be there as well, although this is not stated as part of the DEF in the metaproject). Or if the report includes Maps_To the annotations would be restricted to Target_Terminology, Target_Code, Target_Term_Type, Relationship_to_Target, and comment. What do you think?"

**Comment by NCIEVS** [comment]
Yes, it should go in the queue.  However, we are going to be redoing some of the stuff that we have in the metaproject and the qualifier dependencies might wind up in the content in "special" properties.  So yes, this will be good, but it might come later rather than sooner.

**Comment by NCIEVS** [comment]
It shouldn’t be too hard, I’d have to look, but I would think you’d want to give the user an out, like a “…” at the bottom so they can choose from the entire list. I’m thinking of the use case where someone wants to add another annotation on some classes that we haven’t configured?

**Comment by NCIEVS** [comment]
I agree with the above [GF]

**Comment by NCIEVS** [comment]
Review on 2.5.0, possibly restrict qualifier display only for complex properties declared in the metaproject.  If an undeclare annotation property is annotated on its property value though, all the properties should be available in the display widget for export as annotations.

**Comment by singhik** [comment]
@NCIEVS :: Hello,  Not clear on the changes requested/intended as part of this ticket for 'Report Writer' Export using LQT section ::

1>I do not notice any changes from Export under ReportWriter from previous versions to current version , f.e.  When a 'Full Syn' property is selected and when we  choose 'Annotations' @  for it, i still see all the properties listed like before , 

![image](https://user-images.githubusercontent.com/36314371/42589700-dcbe8f60-850f-11e8-9117-ff7d7e31a232.png)

2. Not clear with this part of the Requirement " If an undeclare annotation property is annotated on its property value though, all the properties should be available in the display widget for export as annotations" , please provide examples to illustrate above .

**Comment by NCIEVS** [comment]
OK, "1" is wrong, it should only display the subset of properties that have been flagged (in the metaproject) as annotations on annotations of the property in question, e..g for full_syn only the term type, term source, and the rest of the properties that you can see in the "complex properties" subtab of the edit tab.

For "2", any property can be annotated on its property values, not only full_syn, definion, and the rest that you see in the "complex properties" subtab.  However, if these other properties are not flagged in the metaproject as "complex" they won't appear in this tab, they would appear in the "general" subtab in an indented "tree" format.  For these properties, any new annotations or annotations on annotations that you add, the entire list of annotation properties is available to select from.

**Comment by bdionne** [comment]
This is working fine for me, I checked the obvious thing first: Is all the new code checked in, and that looks good. These are the versions of plugins I have:

<img width="1154" alt="screen shot 2018-07-12 at 7 18 11 am" src="https://user-images.githubusercontent.com/31741/42600015-51f68f5a-85a4-11e8-8b23-4df2b9a5f5c0.png">

In particular the needed code change was in the `lucene-search-tab` plugin. This is what I see:

<img width="1019" alt="screen shot 2018-07-12 at 6 50 43 am" src="https://user-images.githubusercontent.com/31741/42600067-7401314a-85a4-11e8-82bb-3ff72dac9abc.png">

**Comment by NCIEVS** [comment]
@safrant, looks like we don't have the latest lucene tab in the client package.

**Comment by safrant** [comment]
I think it is because https://github.com/NCIEVS/lucene-search-tab/blob/master/src/main/resources/update.properties still points to 1.1.3

**Comment by NCIEVS** [comment]
No, that's OK, @bdionne can do the push to ncievs.

**Comment by bdionne** [comment]
sorry, my bad, I pushed the jar and props but forgot to push the branch to the nci account. It's [there](https://github.com/NCIEVS/lucene-search-tab/blob/master/src/main/resources/update.properties) now

**Comment by singhik** [comment]
@bdionne @NCIEVS :: Hi, I do see the subset of limited properties(in congruence with Complex Properties list) now as part of Report Writer Export using LQT but have couple of minor observations,needing clarification ::

1. For 'DEFINITION' and 'ALT_DEFINITION' complex properties, i see 'Definition Source' as **striked** out? Not sure if this is OS specific or a setting in Protege Client which i need to change as in Bob's screen print,the 'Def Source' appears as non-striked text. 

![image](https://user-images.githubusercontent.com/36314371/42765309-bf3c27a2-88e5-11e8-911e-b0ecad41f9b6.png)


2. When we select 'attribution' and 'Definition Source' from the list of Properties, it gets selected and is displayed in IRI Short Name Id format (P381 and P378) whereas when 'Definition_Reviewer_Name' and 'Definition_Review_Date' is selected , they are shown with rdfs:label  i.e. Definition_Reviewer_Name and Definition_Review_Date  . 

![image](https://user-images.githubusercontent.com/36314371/42765506-3669a796-88e6-11e8-8d58-2e7a633834e4.png)

**Comment by NCIEVS** [comment]
@singhik , "1" is related to #80, likely not all areas of the code have been fixed.  Please open a separate ticket for this one.  Probably won't be fixed right away.

On "2", it seems like it's picking up the short IRI in all cases.  The last two properties exist like that in the editing version of the NCIt (i.e. these two properties are not using codes in the editing environment).

**Comment by singhik** [comment]
@NCIEVS :: Hi ,

1. QA has verified successfully the Functionality of limiting the list of displaying  annotations for Complex properties via 'ReportWriter' ->'Export using LQT'  ,to be in congruence with what gets displayed under 'Edit' Panel  for Complex properties .

2. QA has verified successfully the Functionality of display of all  annotations available in the MetaProject for other properties via 'ReportWriter' ->'Export using LQT'  .

3. #394 has been raised for the minor display issue of striked out 'Definition source' .

[Issue 273.docx](https://github.com/NCIEVS/nci-protege5/files/2198923/Issue.273.docx)


Hence, QA is closing this ticket ....

**Comment by bdionne** [comment]
@singhik , @NCIEVS  [1.1.6](https://github.com/NCIEVS/lucene-search-tab/releases/tag/lucene-search-tab-1.1.6) fixes the codes, like `P378` showing up in the list, item 2 above. This is similar to the byCode/Name issue we saw in adding a `DEFINITIION` complex property to the new class dialog.

I thought I recall we had agreed to leave all the display names in the `IRIs` for the qualifiers? I forget, anyway some have the codes in the `IRI` and others the names, and the names are also inconsistent between the by name versions and the by code version. Perhaps since our current modelers never use the byName version we could consider dropping it? Either way we can consider a more complete solution in the next release.

I'll comment on the stirke out for `Definition Source` in #80

**Comment by NCIEVS** [comment]
We may have left some properties byName because of issues with downstream applications, but we should use rdfs:label for gui displays (which insulates us from the IRIs).  But yes, if the fix really involves new work we can defer until the next release.

**Comment by safrant** [comment]
We were forced to leave the display names in the IRI of the qualifiers because of hard-coding elsewhere in the application.  I thought the eventual plan was to fix that and have it all coded IRIs.

**Comment by NCIEVS** [comment]
I don't recall this in protege.  But I do recall that lexevs was expecting to see some values for specific properties, and we had to revert those.

**Comment by bdionne** [comment]
@NCIEVS - for sure, agreed, we should always use `rdfs:label` regardless. This ticket required a modified `OWLCellRenderer` and we had to add support for qualifiers. So these qualifiers will now display correctly when you pull the latest, except for the strike through which will come later
