### ISSUE TITLE
automatic conversion of untyped literal to xsd:integer in some annotation properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#274]
Currently, the rdfs:range in the declaration of GenBank Accession No and SwissProt is xsd:string, although it is a plain literal in all the assertions; but when edited in a class assertion the plain literals are automatically turned into xsd:integer datatype; this behavior is overriden if on the edit the xsd:string datatype is selected.  This datatype conversion (from untyped to xsd:integer) seems to not happen if the identifiers have a character, e.g. Q1234 vs 1234. In the copy panel, you get an error message when editing these properties, but the edits are saved (the datatype is not displayed after the save).  We probably need to define all the scenarios where this happens.

**Comment by bdionne** [comment]
I'm not sure this is a bug. The current annotation editor doesn't respect the types specified in the schema.

By untyped literal do you mean there is no range at all? If so, and no type is selected in the annotation editor, I think it will try to be clever and assume 1234 is an integer.

**Comment by bdionne** [comment]
What kind of error message do you see in the copy pane?

**Comment by bdionne** [comment]
The datatypes declared for a property determine how it should be edited. If the datatype is an `enum` or `xsd:anyURI` then the annotation editor should respect this and display the appropriate edit tab. If no datatype is specified then it should be treated as an untyped literal.

To simplify downstream processes, .eg. sparql queries, it's also desired that no types be placed in the assertions. In other words, use the types to inform and guide the editing process but do not needlessly add typing information to individual assertions.

**Comment by rmehri** [comment]
Hi, 
Has this issue been fixed? Or work as design?
Please clarify so I can take the next action.

![issue-274](https://cloud.githubusercontent.com/assets/8367102/26420247/0a19ca3a-4090-11e7-81ae-37a07fb4b63e.png)

Thanks,
Reza

**Comment by bdionne** [comment]
when annotation assertions on classes are edited, the tab that comes up should be opened to the the tab defined by the datatype of the annotation. For example if the type is `xsd:anyURI` the entity IRI tab should come up.

**Comment by rmehri** [comment]
Hi, 
Thanks for feedback! I have retested this issue.  Please see attached example snapshot for more detail.

![issue-274-1](https://cloud.githubusercontent.com/assets/8367102/26468827/d1c7b3e6-4165-11e7-87fb-842fcec8148b.png)

Thanks,
Reza
