### ISSUE TITLE
edit on a class is asserted on a previously edited class

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#275]
Placeholder, not enough information.  Infrequently, protege falls into a state where it gets stuck on a class, and any other class that you try to edit, all the edits wind up on the stuck class.  We don't know yet what triggers this state.

**Comment by bdionne** [comment]
which version is this?

**Comment by NCIEVS** [comment]
It happens in both 0.127 and 1.005.

**Comment by NCIEVS** [comment]
Haven't received reports about this issue appearing in a number of months.  Closing ticket.  This issue appeared in a number of scenarios and we may have hit all of them.  Any new instances of this issue will be documented in a new ticket.
