### ISSUE TITLE
Revision History needs to sync with `EVS` History

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#276]
Currently if commits are rejected that  is no retraction of the relevant `evs_history`

**Comment by bdionne** [comment]
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by bdionne** [comment]
No longer necessary as `pre-merge` and `pre-retire` don't record `evs_history`. This happens when the manager approves.

**Comment by rmehri** [comment]
Hi,
This fix will be retested and verified in the next build nci-1.008. 

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
I have retested this fix using nci-1.008, edit tab -0.6.6.  I committed a reject for pre-merged classes of tree and don't see the record of it in the evs-history file. Please see attached snapshots for more details and let me know if you need more information.


![evs history_reject not showing](https://user-images.githubusercontent.com/8367102/28243021-15c4abd8-698b-11e7-9cbe-d87ba9fb19dd.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi Bob,
Thanks for your comment.   I have retested this fix using nci-1.008, edit tab -0.6.6.  The evs- history recorded the merge and retirement.   Please see attached snapshots for more details. 

Approving steps:
Pre-merged to Merge:
1)	Select pre-merged concept 
2)	Drag it into the merge panes
3)	Select “Merge” button
4)	Press “Save” button
Pre-retied to Retirement:
1)	Select pre-retired concept 
2)	Right click on pre-retired concept or select Retire tab and drag the concept into pane
3)	Select “Approve” button
4)	Press “Save” button
Note: the retired concepts can be found in the retired concept bin.

![completed pre-retired to retirement](https://user-images.githubusercontent.com/8367102/28278287-9ae29a9a-6aea-11e7-8433-fee0c0ef7368.png)
![completed merge](https://user-images.githubusercontent.com/8367102/28278292-9f74a1ca-6aea-11e7-9e49-b3c2b473a40d.png)
![evs history](https://user-images.githubusercontent.com/8367102/28278296-a1842ca6-6aea-11e7-8735-9d0bd646ad69.png)

Thanks,
Reza
