### ISSUE TITLE
Comment column in Revision History needs to reflect `EVS` History

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#277]
The "comment" column in the Changes widget doesn't quite match edit actions. E.g. a "create" event is not logged, but all the activities related to creating a concept appear as "edit", add a preferred_name, add an rdfs:label, add a superclass, add a semantic_type, add a code. We should review the actions and eventually modify the messages that appear under "comment."

**Comment by NCIEVS** [comment]
It looks like it's only the "create" action.  Edit, clone, split, merge, retire show as such.

**Comment by bdionne** [comment]
Itendra: Need the scope of operations/actions for which the Comment section has been changed and the corresponding verbiage under Comment section for those operations, f.e. Adding Class ,Deleting Class,Adding property etc ? 

The only comment that is changed is when the user creates a new class. It's been changed from `EDIT` to `CREATE`

**Comment by singhik** [comment]
This has been QA Verified for 'Revision History' tab to have a change in verbiage for 'Comment' column for a class/concept creation from EDIT to CREATE ... Pfa, screen prints for reference .
[Issue 277.docx](https://github.com/NCIEVS/nci-protege5/files/1732927/Issue.277.docx)
