### ISSUE TITLE
change to evs_history to record 'timestamp' rather than 'date'

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#278]
Note that concept_history will still use the 'date' of publication and not the 'timestamp' of edit.

**Comment by bdionne** [comment]
Which format would you prefer?

`2017-05-18T14:09:47.523`

**Comment by NCIEVS** [comment]
Not sure.  On export from the DB, we were using something that looked like this:  ```2017-05-18 14:09:47```.  a) What will be better in terms of generating concept_history?  And b) further down the line, what will be better in order to support evs_history queries?  (URL to internal history servlet can be sent separately.)

**Comment by bdionne** [comment]
ok, so we'll use [ISO_LOCAL_DATE_TIME}(https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE_TIME)

**Comment by rmehri** [comment]
Hi,
This fix has been rested and verified using tag-1.0069, local server "8080"
Please see attached log files for more details.

[evs_history_tag 1.zip](https://github.com/NCIEVS/nci-protege5/files/1103589/evs_history_tag.1.zip)

Thanks,
Reza
