### ISSUE TITLE
read only properties should be uneditable

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#28]

**Comment by NCIEVS** [comment]
e.g. code, legacy_name

**Comment by rmehri** [comment]
Hi Bob, 
Can you please elaborate more for this fix? So I can retest and verify them. 
Thanks,
Reza

**Comment by bdionne** [comment]
The subject of this ticket is a complete description of the issue. Certain properties, .eg. `code` are not meant to be edited. In the case of `code` it is generated when the class is created. Other properties are used by the complex operations, .eg. `Split_From`, and are assigned as part of the operation:

<img width="1020" alt="screen shot 2017-01-03 at 2 28 27 pm" src="https://cloud.githubusercontent.com/assets/31741/21620320/bc41e4e2-d1c1-11e6-8019-16e1b42689e5.png">

Notice that in the screenshot above, `Split_From` and `code` are read only. The complete list of immutable properties is specified by the modelers in the [config file](https://github.com/bdionne/protege-server/blob/master/src/main/resources/server-template/server-configuration.json#L223-L234)

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback! I retested this fix using tag-116, edit tab-0.3.1. Please see attached screen shot for more detail. 
Reza

![merge](https://cloud.githubusercontent.com/assets/8367102/21858327/a750a0c4-d7f6-11e6-8e91-329c1ee7b6a1.png)
