### ISSUE TITLE
batch editing of the preferred_name property fails

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#281]
It might be related to our business rules as editing preferred_names via the GUI is also tricky.  
- the preferred_name needs to be synchronized with the rdfs:label and the full_syn NCI/PT.  
- dups of properties are not allowed so a full_syn NCI/PT that gets changed to one that resembles an existing full_syn NCI/SY might be failing.

[EditSPL-PTs2.txt](https://github.com/NCIEVS/nci-protege5/files/991406/EditSPL-PTs2.txt)

**Comment by bdionne** [comment]
Fixed in `nci-edit-tab-0.6.1`

**Comment by rmehri** [comment]
Hi, 
I have retested this fix.  33 out of 46 modifications were successful and the rest of classes did not exist in the dictionary.  Please see attached input and output files.

Used:  
Dictionary : QA -Only-Thesaurus-byCode via https://nciws-d699-v.nci.nih.gov:9090,
Tag: nci-1.006
[EditSPL-PTs2.txt](https://github.com/NCIEVS/nci-protege5/files/1029344/EditSPL-PTs2.txt)
[EditSPL-PTs2-Out.txt](https://github.com/NCIEVS/nci-protege5/files/1029345/EditSPL-PTs2-Out.txt)
![issue -281](https://cloud.githubusercontent.com/assets/8367102/26456347/c66b5d98-413a-11e7-8624-90aa810a615a.png)
![issue -281-1](https://cloud.githubusercontent.com/assets/8367102/26456356/caebfec2-413a-11e7-8a34-88163714bb95.png)
Thanks,
Reza
