### ISSUE TITLE
complex properties panel doesn't display all values unless other optional annotations also have values

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#282]
This particular item was found with the full_syn complex property.  One of the fields, subsource name, configured in the metaproject, doesn't display data.  However, on review it appears that if another full_syn annotation, in this case the source code, is present, then the subsource name is displayed.  

More details: these annotations are configured in the metaproject, are optional, but they are not flagged as 'required', nor do they have a 'default' value.  This might be a general issue not restricted to the full_syn property table.

The email thread is from 5/11/17.

**Comment by bdionne** [comment]
is subsource an enum datatype? Or are subsource and source-code both string?

**Comment by NCIEVS** [comment]
Both of these are strings.

**Comment by YinghuaXu2** [comment]
Can you give me a hint how to reproduce the issue?

**Comment by bdionne** [comment]
use the `FULL_SYN` property, add two more qualifiers, `Subsource` and `source-code`, then try various combos of adding new rows and/or editing existing ones. It's also dependent on the row order so you may have to play with the `Value`.

For example, for me, if the first row has a `comment` and I add a `source-code` but there's no `Subsource` I will see the `comment not show up, even though it's there.

**Comment by bdionne** [comment]
forgot this needs testing

**Comment by rmehri** [comment]
This issue has been retested and the same reported behavior did not occur. 

Local Server: "8080"
Used latest tag nci-1006, 
Edit Tab -0.6.1
Lucene Search Tab-1.0.4
metaproject1.0.0
Metaproject Admin-1.0.0

Thanks,
Reza
Thanks,
Reza
