### ISSUE TITLE
refresh of complex properties panel on batch edits

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#283]
Refresh issue on the complex properties panel, from [TQ]:
"I just batched in some concept in Subset and they showed up immediately in Protégé; however, I batched in some FullSYNs and the output showed a success, but I couldn’t see the values. I indexed and they didn’t show. I logged out and back in and they were there."

This appears to be similar to what was described towards the bottom of #149, except that in that case the edits were not done in batch.

**Comment by bdionne** [comment]
This is not easily reproducible, I sometimes don't see batch edit changes on a class if it's in focus, but moving away and then back seems to fix it. On other classes not in focus, moving to them shows changes from batch edits
