### ISSUE TITLE
unable to change PTs into HD or AQ term type 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#285]
**High priority.**  Issue observed with HD but will need to be examined with AQ as well.  

An existing NCI/PT full_syn cannot be changed into an NCI/HD full_syn.  It is feasible to do so in the dialog but the change doesn't take in the table or the Save action.

Also, if a concept with a pre-existing NCI/HD full_syn is edited, not necessarily in the full_syn table, could be a definition, the HD is changed to a PT on Save.

**Comment by bdionne** [comment]
This has been pushed to production in the `0.6.0` version of edittab

**Comment by bdionne** [comment]
this was hot patched to production, it probably still should go thru the normal testing

**Comment by rmehri** [comment]
This issue has been retested and verified. using the following tag and plugins.
nci-edit-tab-0.6.1
revision-history-1.0.1
lucent-search-tab-1.0.4
metaproject-admin-1.0.0
Please see attached screenshots for more detail.
![issue-285-2](https://cloud.githubusercontent.com/assets/8367102/26266088/de7c0eb0-3cb1-11e7-979b-9932b63df6ab.png)
![issue-285-1](https://cloud.githubusercontent.com/assets/8367102/26266033/9034f546-3cb1-11e7-8975-4619c9faf513.png)

Thanks,
Reza
