### ISSUE TITLE
remote access to logs

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#286]
needs to be discussed.

**Comment by NCIEVS** [comment]
Possibilities
- let apache server logs
- create endpoint to serve logs from protege

**Comment by NCIEVS** [comment]
This is done and already available in prod.  This endpoint won't be made accessible outside the firewall.  Moving to QA.  

@singhik , please contact if you need additional details.  No urls in tickets.

**Comment by singhik** [comment]
@NCIEVS  ::  Below are QA Verified and i believe this ticket can be closed now :: 

1. Logs(explanation-cron,pellet-console,protserv-console) are accessible using LDAP Creds over https protocol remotely when connected to VPN .
2. Logs are NOT accessible when not connected to VPN .
3. Logs show real-time updation .

**Comment by NCIEVS** [comment]
Agreed, can be closed.
