### ISSUE TITLE
retired classes become editable under some circumstances

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#289]
If a retired concept is selected from the lucene query tab after a search, that concept can be edited.  

From [EHD]:

- Search for a Retired Concept in the Lucene Search Tab.  
- Double click on that concept in the search result panel
- The GUI puts the user in that concept in the Edit subtab of the NCI Edit Tab and allows editing and saving on that concept. 

The GUI needs to direct a user to the ReadOnlyClass subtab of the NCI Edit Tab when a Retired Concept is chosen from the search results in the Lucene Search Tab and/or the GUI needs to reject edits to Retired Concepts either at the property level or when the user tries to Save the edits.

**Comment by bdionne** [comment]
There's two steps to retiring, retiring which re-trees and adds the note, followed by save that commits it. Was the `save` actually executed?

**Comment by NCIEVS** [comment]
According to EHD, yes, the retired concept was edited accidentally in the edit tab and then Saved.

**Comment by bdionne** [comment]
Interesting, I just tried this a few times and the only way I can reproduce it is if I forget to hist save after hitting retire, then search in Lucene and double click the concept

**Comment by hahndane** [comment]
Teri searched for C129719, which was recently retired before the last squashing, using the Lucene Search tab and double-clicked on it. It opened in the Edit subtab. She removed the ALT_DEF and Saved the change.

**Comment by bdionne** [comment]
Thanks Liz, Do you have any others that were retired before the squashing? If so could you search for one, double click it and see if it's editable? Don't edit it obviously, just see if it's editable

**Comment by bdionne** [comment]
Ok thanks, I'm able to reproduce this logged in as a modeler and see the problem (from the code it should also happen to admins)

````
Hi Bob
 
Regarding your message from github, I already did this with Gilberto watching. Then Gilberto replicated this as a workflow modeler because he thought I would have permission to edit retired concepts as a workflow manager.
 
Thanks,
Liz
````

![image001](https://cloud.githubusercontent.com/assets/31741/26652451/f23bf472-461d-11e7-85d7-e23a3a7a6e75.png)

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified on my local server "8080", nci-1.0069, nciedit-0.6.5
Please see attached snapshots for more details.
![retired-bile_salt-1](https://user-images.githubusercontent.com/8367102/27453432-6e5384b0-5764-11e7-8233-fc9530d79353.png)
![retired-bile_salt_readonlyclass-2](https://user-images.githubusercontent.com/8367102/27453485-a0a021b2-5764-11e7-9729-e59ec585c382.png)

Thanks,
Reza
