### ISSUE TITLE
Search entry text box is too small and doesn't resize properly

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#29]
This is a issue in the [search tab](https://github.com/protegeproject/lucene-search-tab/issues/5)

**Comment by NCIEVS** [comment]
@hahndane: this was fixed upstream.  I'd say we can go with this.  Will flag it ready for QA but if you think we need further changes we can open a new ticket.

**Comment by rmehri** [comment]
This fix has been successfully retested in tag-110.  Please see attached snapshot for more detail. This ticket can be closed.

Thanks,
Reza

![lucene-search](https://cloud.githubusercontent.com/assets/8367102/21103506/c1b013e0-c050-11e6-8313-d6ac4af319ac.png)
