### ISSUE TITLE
Datatypes allowing duplicate properties

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#290]
The production export produced duplicate properties differing only in the datatype assigned.
Concepts with duplicate properties within: 3
C133805:SPL Pharmaceutical Quality/Chemistry, Manufacturing, and Controls Terminology=P322:FDA
C2688:Nab-paclitaxel=P90:Nanoparticle Albumin-bound Paclitaxel
C98831:Brigatinib=P322:FDA

    <owl:Class rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133805">
        <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54452"/>
        <A8 rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133805"/>
        <NHC0>C133805</NHC0>
        <P106>Intellectual Product</P106>
        <P108 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SPL Pharmaceutical Quality/Chemistry, Manufacturing, and Controls Terminology</P108>
        <P322>FDA</P322>
        <P322 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">FDA</P322>

**Comment by rmehri** [comment]
Hi
Retested this fix using latest tag nci-1.0068.
Plugin  Registry: https://github.com/bdionne/autoupdate/blob/master/plugins.repository
steps that I used to validate this fix
1) used modeler login
2) Created a new class with Full_syn  and values "NCI/PT" and save it. 
3) Tried to add the third Full_Syn property with the same values FDA/PT and did not accept it. But I did not receive any warning message that duplication is not allowed.  Do you expect a warning message for duplication?  Please see attached snapshots for more details an let me know your thoughts.

![issue-290](https://user-images.githubusercontent.com/8367102/27150922-f6c41372-5116-11e7-92e5-d94e8c29168e.png)

![issue-290-1](https://user-images.githubusercontent.com/8367102/27150932-fe326c62-5116-11e7-8790-4797d6067871.png)

![issue-290-2](https://user-images.githubusercontent.com/8367102/27150942-084a01b0-5117-11e7-8b4e-de615e7f52d1.png)


Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - no, if you create a duplicate property Protégé will just not add it.

This issue has to do with create a property that is a duplicate but it has a different datatype. When the `OWL` file is saved it shows up as a duplicate in the `XML`

You can see the `XML` above:

````
<P322>FDA</P322>
    <P322 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">FDA</P322>
````
There are two `P322` property assertions, and the are the same value, but have different datatypes

**Comment by rmehri** [comment]
Thanks. 
This fix has been retested and verified using nci-1.0069, edit tab-0.6.5. 

   <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C1000006"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#FULL_SYN"/>
        <owl:annotatedTarget>Test-Issue 290</owl:annotatedTarget>
        <term-group>PT</term-group>
        <term-source>FDA</term-source>
        <rdfs:comment>Test-Issue 290</rdfs:comment>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C1000006"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#FULL_SYN"/>
        <owl:annotatedTarget>Test-Issue 290</owl:annotatedTarget>
        <term-group>PT</term-group>
        <term-source>NCI</term-source>
    </owl:Axiom>
    

Thanks,
Reza
