### ISSUE TITLE
It is possible to add multiple NCI:PT

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#291]
The 17.05e export revealed one concept with 2 NCI:PT

    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C121704"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90"/>
        <owl:annotatedTarget>Degree Fatigue Interfered with Physical Functioning</owl:annotatedTarget>
        <term-group>PT</term-group>
        <term-source>NCI</term-source>
    </owl:Axiom>

    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C121704"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90"/>
        <owl:annotatedTarget>Fatigue Interference with Physical Function</owl:annotatedTarget>
        <term-group>PT</term-group>
        <term-source>NCI</term-source>
    </owl:Axiom>

**Comment by bdionne** [comment]
Which version of the code was used for the export?

**Comment by NCIEVS** [comment]
This export was done with nci-1.005.

**Comment by NCIEVS** [comment]
We know that this ticket describes an issue where a concept wound up with two PTs.  But we don't know under what circumstances it happened:  this doesn't happen in the complex editing panel of the Edit tab.  Keep "watch-and-wait".

**Comment by bdionne** [comment]
old ticket, no info to triage with, hasn't occurred again since.
