### ISSUE TITLE
pre-merge by editors results in an extra superclass 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#292]
From [EHD]:
When an editor who is not a Workflow Manager does a merge, the concept sits in the Premerged_Concept bin until the Workflow Manager approves the merge using the ComplexEdit subtab. At the time of the approval of the merge the Retiring Partner is being assigned OLD_PARENT NHC50000, which is the Premerged_Concept bin. This should not be given as an OLD_PARENT because it is not published and has a not-for-publication code. It is also not valid as an OLD_PARENT. (In prod see codes C132280, C129719, C129743). This does not happen when a Workflow Manager merges a concept (because the concept never resides in the Premerged_Concept bin) and also doesn’t happen when an editor preretires a concept and a Workflow Manager approves the retirement (see codes C90511 and C92485).

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using nci-1.0068. 
Plugin Registery: https://github.com/bdionne/autoupdate/blob/master/plugins.repository
1) Retested for pre merge  (Workflow Modeler)
2)  Retested for merge  (Workflow Manager)
Please see attached snapshots for more details. 

![issue-292-merge_manger-2](https://user-images.githubusercontent.com/8367102/27154922-d1341d7e-5124-11e7-86f6-e5179cb58a88.png)
![issue-292-second_class_pre-merge_surviving concept](https://user-images.githubusercontent.com/8367102/27154921-d133bdc0-5124-11e7-95f8-99ed82c38b74.png)
![issue-292-first class_pre-merge_retiring concept](https://user-images.githubusercontent.com/8367102/27154924-d1375746-5124-11e7-8f41-c29265c6c1f4.png)
![issue-292_pre-merged_surviving concept](https://user-images.githubusercontent.com/8367102/27154923-d134cb70-5124-11e7-8ba2-6d092922d917.png)
![issue-292-merge_manger-1](https://user-images.githubusercontent.com/8367102/27154925-d13850f6-5124-11e7-9d38-ff923ac7a718.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
 This fix has been retested and verified using nci-1.0068.
 1.Retested for pre merge (Workflow Modeler)
2.Retested for merge (Workflow Manager)
 Please see attached snapshots for more details.
![premerge](https://user-images.githubusercontent.com/8367102/27306419-88175370-5513-11e7-8fd7-de42d84833ee.png)

![merge1](https://user-images.githubusercontent.com/8367102/27306391-75b74622-5513-11e7-90bd-8864850834dd.png)
![merge2](https://user-images.githubusercontent.com/8367102/27306397-792106d6-5513-11e7-83b9-2a3158ae611b.png)
![merge3](https://user-images.githubusercontent.com/8367102/27306404-7f74fc90-5513-11e7-94a7-122756fdf97f.png)

Thanks,
Reza
