### ISSUE TITLE
Show number of conflicts and authors involved in the commit list

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#294]
From [issue #71](https://github.com/NCIEVS/nci-protege5/issues/71):

 - in the "authors" widget, it would be good to show the number of concepts (or include this number as well as the number of commits) as well as the number of conflicting concepts next to each author's name.

**Comment by rmehri** [comment]
Hi,
This fix has been retested and verified using nci-1.0069, nci-edit-0.6.5 and local server 8080.
Please see attached snapshot for more details.
![issue 294](https://user-images.githubusercontent.com/8367102/27457152-a3e289e8-5771-11e7-8357-dbf8a0eeba5a.png)
 
Thanks,
Reza
