### ISSUE TITLE
if the server is paused, can't commit rejects, general weird behavior

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#295]

**Comment by rmehri** [comment]
Hi, 
I retested this fix  using nci-tag-1.0068. 

1) I paused the server
2) Tried to reject and commit a change and it did not go through commit review. 
Please see attached screenshot for more detail. 
Would you have a specific repressible step so I can retest it again?

![issue_295-1](https://user-images.githubusercontent.com/8367102/27195042-13a0b132-51d3-11e7-9617-c67cc75b0469.png)
Thanks,
Reza

**Comment by bdionne** [comment]
I think the issue was with any commit that the manager tried to reject. When you say it didn't go through what explicitly happened?

**Comment by rmehri** [comment]
Hi Bob, 
I have retested this fix using nci-1.0069 and edit tab-0.6.5. 
Used Workflow-Manager
1)  Paused the server
2) Added couple of FULL_SYN to Clonal Regression concept Code: C17656
3) In Revision History, I committed the changed 
4) Pressed on Reject and nothing happened. 
Please see attached snapshots for more details.

![colnal regression-1](https://user-images.githubusercontent.com/8367102/27447907-c66b2270-5750-11e7-8f3a-3555ecbaa004.png)
![colnal regression-2](https://user-images.githubusercontent.com/8367102/27447909-c85c635a-5750-11e7-886a-ed7d82dc7667.png)

Thanks,
Reza
