### ISSUE TITLE
Preferences lost in certain scenarios

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#299]
On OS X occasionally the connection info is lost, as well as settings such as enabling/disabling the plugin updater and the entry for the search indices location. This last one cause the ontology to be re-indexed when the app is brought up again, creating a new set of indices

**Comment by bdionne** [comment]
I believe I have a [workaround](https://github.com/bdionne/protege/commit/22d7c874de8d24d12f5c0142d730fa78ce7aa198) for this. The file backing store is loaded before the `OSGI` framework starts it's thing. It add a shutdown hook that exits the VM after all the bundles are stopped. It seems to be clobbering the file preferences file, I believe because the file hasn't been written completely when it exits. 

This small sleep makes the problem go away on OS X, we'll have to watch it and see.

The file backing store factory class get loaded before `OSGI` by the system class loader as we weren't able to get `OSGI` to find it when initializing plugins.

**Comment by kondareddys2** [comment]
The defect is fixed and tested in V2.1.010 Dev. Closing the defect.
Test Steps:
1.File-->preferences-->change settings-->ok
2.Exit protege
3.Start Protege
4.Perform search
5.re-indexing does not happen,
