### ISSUE TITLE
complex property tables display incorrectly when columns are missing data

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#30]
<img width="1017" alt="screen shot 2016-10-04 at 3 00 00 pm" src="https://cloud.githubusercontent.com/assets/31741/19088253/6383ec58-8a43-11e6-8afa-c181fb4249fc.png">

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
This fix has been retested using tag 112 and verified the complex property tables display correctly when columns are missing data.  Please see attached snapshot for more details.

Thanks,
Reza

![complex property table](https://cloud.githubusercontent.com/assets/8367102/21363854/46f39614-c6bc-11e6-9d9e-b7db54ea06fa.png)
