### ISSUE TITLE
annotations on annotations not being taken into account to detect duplicate full_syns

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#300]
Probably not specific for full_syns.  

From [NT]:
I’ve been trying to add new synonyms to concept “Almost all of the Time”, C119986; every effort returns the error “Duplicates not allowed.” regardless of what the string is.

From [GF]:
I could reproduce the issue.  I can add full_syns to any concept except this one.  There are two full_syns in there that only differ in that one has ‘source code’ and ‘subsource name’ optional annotations, and the other doesn’t.  I deleted the dup without the optional qualifiers in the entities tab and then [NT] was able to edit the concept in the nciedittab.  It seems that the behavior has changed.  Core protégé used to take into account all the annotations before declaring something a dup.  Did we loosen up the comparison in the edittab?

**Comment by rmehri** [comment]
This fix has been retested good.
Thanks,
Reza
