### ISSUE TITLE
Tag-1.0069-NCI-Edit Tab Plugin Error Cannot be Removed Unless Restart Client and Server

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#302]
Steps to reproduce:
1.	Launch server and client
2.	Log into local host http://localhost:8081 ==>" Server Admin"
3.	Use "Bob"
4.	Add new users 
5.	Add new project 
6.	Add Access Control Policy and save and logout
7.	Launch a client and you’ll see the error on NCi Edit tab
8.	Add the following link into preferences/ Plugin registry
https://raw.githubusercontent.com/bdionne/autoupdate/master/plugins.repository
9.	Log into the protégé Owl Server and select the vocab or project 
10.	Go to Preferences/ General and set the search type = Lucene Search
11.	You’ll still see the same error on NCi Edit tab
12.	Try to unselect NCI Edit Tab, but it won’t let you.
13.	Go to Window/tab and re-select NCI-Edit tab and you’ll see duplicated NCI -Edit tab one with error and other one without error. 
14.	Logout and end the client and server sessions 
15.	 Re-launch the server and client them log into the protégé then you don’t see the error.

Please see screenshot for more detail

![nci edit tab_error](https://user-images.githubusercontent.com/8367102/27255142-2c051ee0-5366-11e7-889d-a5b84dd4e6fc.png)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - This is a build issue. `Edittab` depends on the `Lucene-Search-Tab`. When you first load the plugins after installing the general preferences will be set to the default rather than Lucene. This is because the plugin is not yet there until you restart the app.

After installing the plugins, you restart the app to pick them up. If you then go into preferences and switch it to Lucene *before* you login, it should work

**Comment by bdionne** [comment]
@rmehri - is this the same issue you were seeing last night and emailed about?

**Comment by rmehri** [comment]
Hi Bob,
Yes it is.  I will look into it.

Thanks,
Reza

**Comment by rmehri** [comment]
Hi Bob, 
I have re-built nci-1.008 again and tried adding the latest nci-edit tab -0.6.7 along with the other plugins automatically successfully, except the Lucene Search Tab plugin done by downloading the jar file and adding it to protégé client plugin folder.  Afterwards, I received the same errors again.  But this time when I restarted the client and server, the error cleared. It is working now. Meanwhile, please see the attached snapshots and log file for more details.

[protege_logfile-2017.07.25.txt](https://github.com/NCIEVS/nci-protege5/files/1174147/protege_logfile-2017.07.25.txt)
![build-1 008-error](https://user-images.githubusercontent.com/8367102/28583584-b121cb3e-7137-11e7-902f-067194af8056.png)
![build-1 008-1](https://user-images.githubusercontent.com/8367102/28583589-b64c0520-7137-11e7-8f3b-ad15a0eff4e0.png)
![build-1 008-2](https://user-images.githubusercontent.com/8367102/28583597-b996eaba-7137-11e7-9917-7f303b1fcb98.png)

Thanks,
Reza
