### ISSUE TITLE
LOAD should not be default for batch edit combobox

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#303]
Capture and remember the user's preference

Often a user will be batch editing a lots of simple properties. It was make it easier to use if we store the last selected value as a preference and use that to populate the combobox

**Comment by bdionne** [comment]
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using latest tag nci-1.008 , NCI-Edit Tab-0.6.6.

Steps to reproduce:
1) launch server and client
2) Select NCI_ Edit tab 
3) Select Batch Load/Edit
4) Select Batch Type = Edit_Complex_Props  (example) 
5) Close Batch Load/Edit and return to it then you'll see this stored value "Edit_Complex_Props" as a preference. 
6) Go to  NCI_ Edit tab 
7) Select Batch Load/Edit then you'll see this stored value "Edit_Complex_Props" as a preference 
 
Please see attached snapshots for more details.

![issue-303-1](https://user-images.githubusercontent.com/8367102/28381510-1e480bf0-6c89-11e7-83d1-f83d93330420.png)
![issue-303-2](https://user-images.githubusercontent.com/8367102/28381513-23213d4a-6c89-11e7-8a97-02171b1c752a.png)

Thanks,
Reza
