### ISSUE TITLE
Null pointer exception makes revision panel unusable

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#304]
Hi, 
I  have caught this error while retesting this issue https://github.com/NCIEVS/nci-protege5/issues/292
Possibly, this is intermittent problem. 

Steps to reproduce:
1.	Launch server and client
2.	Launch two separate client sessions and log into each one as (Workflow-Editor and Workflow-Manager)
3.	Do pre-merge of two concepts using Workflow-Editor login
4.	Do merge to complete the pre-merge using Workflow-Manager login
5.	Go back to client page that has workflow- editor login and double check on retired folder to see if the merged class exists.
6.	Go to client page that has Workflow-Manager and select Revision History page and do the following:
a.	Refresh the page to see the merged class (I did not see latest up on merged concept
b.	Remove the revision history tab then re-selected revision history tab from Window/tab then you’ll see the errors.
Please see attached screenshot for more details. 

![revision history tab](https://user-images.githubusercontent.com/8367102/27305836-5b5dda68-5511-11e7-8e49-f23578dc2d94.png)

Thanks,
Reza

**Comment by kondareddys2** [comment]
Verified on the latest Build V2.1.010 . This issue is not reproducible.
