### ISSUE TITLE
Tag-1.0069-Revision History - Pressing History Button Causes Error 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#305]
Steps to reproduce:
1.	Launch server and client
2.	Log into local host http://localhost:8080  (Used Workflow Manager), nci-1.0069
3.	Select Revision History tab
4.	Select one or more records and press History button to generate concept history
5.	The concept history gets generated with server and client errors
Please see errors below and attached zip file to see the log files and screenshot for more details.

Server failed to generate concept history (contact server admin for further assi
stance)org.protege.editor.owl.client.api.exception.ClientRequestException: Server faile
d to generate concept history (contact server admin for further assistance)
[con_history_Tag-1.zip](https://github.com/NCIEVS/nci-protege5/files/1103556/con_history_Tag-1.zip)

![revision_history](https://user-images.githubusercontent.com/8367102/27561665-0372080c-5a97-11e7-9b34-34b7f894232c.png)

Thanks,
Reza

**Comment by safrant** [comment]
This is attempting to create a folder ./root/archive/<hashhashhashhash>-TIMESTAMP.  The Timestamp includes a colon in the time, which is throwing an illegal character exception.

**Comment by bdionne** [comment]
agreed, it's what I thought it was. Windows doesn't support the file names. Not sure we want to bother with it since our servers run on Linux, but I'm happy to change it if required.

**Comment by NCIEVS** [comment]
Let's leave for a future enhancement.  We are in prod with this now, and i don't want to request a change in directory names that i don't have access to.  If we get back to this, perhaps the thing to do is to keep the colon but trap the exception and only then use a different format for the directory name.

**Comment by bdionne** [comment]
pushing this one to a future release. This is an issue only for running protege server on windows. It's an easy change to use different file names for archiving, but this needs to be evaluated in terms of impact to existing operations, and detail needs to be provided on what to change the names to.

**Comment by NCIEVS** [comment]
Bringing this up in priority.  It had been done in a tag around December 2020 but it appears it didn't make it to master.  nciedittab is being used externally by a group using windows so we need this change sooner rather than later.  As a reminder, I believe that this is the format that we settled on for the datetimeformatter, "yyyyMMdd-HHmmss".

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/protege/commit/79234c9c31e113bcc8a7)

**Comment by bdionne** [comment]
This needs a protege server build, on windows, needed for Alabama.

**Comment by NCIEVS** [comment]
This was tested along with a related issue (#495) and is already in production (v3.5.3).  Closing
