### ISSUE TITLE
Search not clearing prior results correctly

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#306]
When the results set is large enough to be paged, results form previous queries are not cleared when the next result set is not pages. 

The problem arises on export of the results

**Comment by bdionne** [comment]
this is available now in 1.0.6](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.0.6)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using nci-1.0069, nci-edit 1.0.6.
Please see attached snapshots for more details.

![issue-306](https://user-images.githubusercontent.com/8367102/27698161-47bf6598-5cc4-11e7-9335-faae5f81ecd3.png)
![issue-306-1](https://user-images.githubusercontent.com/8367102/27698160-47bf1246-5cc4-11e7-88a0-3123199a0f00.png)
![issue-306-2](https://user-images.githubusercontent.com/8367102/27698164-47c2a38e-5cc4-11e7-8530-881ef2d334ac.png)
![issue-306-3](https://user-images.githubusercontent.com/8367102/27698163-47c28e80-5cc4-11e7-907a-0798f45312ae.png)
![issue-306-4](https://user-images.githubusercontent.com/8367102/27698162-47c0b6f0-5cc4-11e7-8af3-220ff3260705.png)

Thanks,
Reza
