### ISSUE TITLE
request for File Open/Save dialog to open to the last used directory

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#307]
from [TQ]:
"Would it be relatively simple to make the default search location the last one used in the Report Writer the same way you have it configured in the Export LQT results (which is very nice, thank you very much)? I think the current default is the Documents folder which is a couple of blocks down and over the railroad tracks from where I usually store my results."

And if the location is being persisted in other File Open/Save elsewhere in the GUI, we should also set this directory location to persist between sessions.

Priority is low.

**Comment by bdionne** [comment]
should be easy, we did this already elsewhere

**Comment by NCIEVS** [comment]
Addition from [EHD]:
Should apply to the resultset File/Save from the report writer, as well as the code list File/Open into the report writer (input list of codes).

**Comment by bdionne** [comment]
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using latest tag NCI-1.008, NCI-Edit-Tab-0.6.6.
Please see attached snapshots for more details.

![issue307-1](https://user-images.githubusercontent.com/8367102/28232558-5fe2541c-68bf-11e7-94c1-e5a0b45aff6e.png)
![issue 307-2](https://user-images.githubusercontent.com/8367102/28232562-64d38888-68bf-11e7-9ec7-b611aa5009de.png)
![issue307-3](https://user-images.githubusercontent.com/8367102/28232563-67fb99ce-68bf-11e7-9368-823c6bdef532.png)

Thanks,
Reza
