### ISSUE TITLE
under some circumstances the concept to retire in a merge is treed under "retired concepts" rather than "premerged concepts"

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#308]
From [NS]:
"I just merged lung mucinous cystadenocarcinoma to its parent lung colloid carcinoma. I am doing some WHO-updating of lung cancers today. I followed the merge rules but, after I saved this merging action, the concept that was to be dropped, had disappeared from the terminology and I found it to be already retired instead of being in the premerged concepts. A similar thing had happened about 10 days ago and I had mentioned it to you as well."

It seems that under some circumstances the "save to premerge" is bypassed.  We need more info at this time from [NS], but we'll have to prevent this bypass from happening.

**Comment by bdionne** [comment]
I believe this is the same as #301

**Comment by NCIEVS** [comment]
Agreed.  Missed #301.  thx!
