### ISSUE TITLE
set Concept_Status property on retirement

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#309]
to value Retired_Concept (taken from the enumerated range).  This would include retirements on merges as well as outright retirements.  Probably needs discussion.

**Comment by NCIEVS** [comment]
by agreement:
use the key "deprecated_concept_status" in the project's section of the metaproject.  the value for that key is a pair of values, the IRI of the property that records concept_status, and the value of the concept_status property.  Entering this using the server admin's dialog will generate a comma-separated pair of values; the IRI should be entered first, but the code should test for the IRI in case the user enters it second.

**Comment by bdionne** [comment]
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by rmehri** [comment]
Hi, 
Can you please elaborate reproducible steps? 

Thanks,
Reza

**Comment by bdionne** [comment]
`Concept_Status` is an annotation property, that can take on different values. One of those values is `Retired_Concept`.

The requirement is that when a concept is retired, this annotation with this value is added to it. In order for this to happen the property must be set in the server's config file (see the email about the `nci-1.008` build:

````
"deprecated_concept_status": [
         "Retired_Concept",
         "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Concept_Status"
       ],

````

In the `nci-1.008` build the sample `byName` project already has this property set. It can also be set in the `admin` panel. When this is present, if a concept is retired, this property will show up:

<img width="1023" alt="screen shot 2017-07-14 at 4 40 05 pm" src="https://user-images.githubusercontent.com/31741/28230231-140cd356-68b4-11e7-903b-404bbf8e26a3.png">

**Comment by rmehri** [comment]
Hi, 
Thanks for your information, I have retested this fix using latest tag-NCI-1.008, NCI-Edit Tab-0.6.6.
Please see attached snapshots for more details.

![issue-309-1](https://user-images.githubusercontent.com/8367102/28233400-92478620-68c4-11e7-8579-8a0b9bad7edd.png)

![issue-309-2](https://user-images.githubusercontent.com/8367102/28233402-95880742-68c4-11e7-8c12-899b7f7f10ea.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Did you include the incorrect screenshots, this doesn't seem to validate the feature

**Comment by rmehri** [comment]
Hi Bob, 
Yes I did include the third screenshot. Additionally, I retested this fix on QA server as well as my local server.  Please see attached snapshots for more details.  This is fixed. 

![issue-309-3](https://user-images.githubusercontent.com/8367102/28241524-1476f492-6964-11e7-9ae5-d99cf3e57103.png)
Today's retest:
![issue-309-qa server-1](https://user-images.githubusercontent.com/8367102/28241526-28d8d14e-6964-11e7-824e-838263c4f284.png)
![issue-309-qa server-2](https://user-images.githubusercontent.com/8367102/28241528-2ad2cf4a-6964-11e7-8b03-674f89e24ad4.png)

Thanks,
Reza

**Comment by bdionne** [comment]
great, thanks Reza.

**Comment by rmehri** [comment]
You're welcome!
Reza
