### ISSUE TITLE
Display connected host, user, and project

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#313]
Need visual indication somewhere with respect to which host is connected to, the user logged in and the project opened

**Comment by rmehri** [comment]
Hi,
I have retested via latest protégé tag nci-1.008, NCI-Edit tab-0.6.6. Please see attached screen shots for more details. 

![local-server-issue-313](https://user-images.githubusercontent.com/8367102/28216993-97bc0970-6881-11e7-9c97-f21358d68afe.png)
![qa server-issue-313](https://user-images.githubusercontent.com/8367102/28216997-9a967aa4-6881-11e7-89c3-e3a00be7649b.png)

Thanks,
Reza
