### ISSUE TITLE
 Workflow Manager Not able to Reject the Pre-merged Classes Tree

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#314]
Hi, 
How can a Workflow-manager reject the pre-merged classes tree?
Please see attached screen shot for more details. 

![issue-301-parent-3](https://user-images.githubusercontent.com/8367102/28173994-323ab128-67be-11e7-982c-91d3fdc98f77.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Reza,

I'm not sure what the issue is here. What exactly is failing for the Workflow Manager? Thanks, Bob

**Comment by rmehri** [comment]
Hi Bob,
Workflow-modeler merged several classes of tree and sent them to Pre-merged bin, but workflow-manager did not agree with this merge then tried to reject them but the reject functionality was not available. This test was done in the previous tag nci-1.007, nci-edit tab-0.6.5. We need to retest this in current tag 1.008 again.  Please let me know if you need more information. 
Thanks,
Reza

**Comment by bdionne** [comment]
ok, so what happens when you reject them?

**Comment by rmehri** [comment]
The Reject was not available. As I mentioned, we need to retest this ticket using 1.008.

**Comment by bdionne** [comment]
ok, let's discuss at status next week. I need to have steps to show me how the rejections are failing. It works fine as far as I can tell in both nci-1.007 and nci-1.008.

**Comment by rmehri** [comment]
Hi Bob,
I have  retested this issue using latest tag nci-1.008, nci-edit tab-0.6.6.  The Reject works. 
Please see attached screenshots for more details.

![premerge-1](https://user-images.githubusercontent.com/8367102/28242948-494d2a82-6988-11e7-96f0-c074de92b6f5.png)
![reject premerge-2](https://user-images.githubusercontent.com/8367102/28242953-906d4e4c-6988-11e7-8965-e59e46a1e71e.png)

Thanks,
Reza
