### ISSUE TITLE
dialog indicating "class already being edited" during merge

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#315]
This dialog comes up when the merge gets approved.  If "yes" is clicked, the merge result is flawed.  The dialog needs to be X'd out instead of Yes'd to get the merge to work.

**Comment by bdionne** [comment]
Thanks for triaging this. I have a fix for this that I'll push tomorrow after some more testing.

The real issue is that the dialog should no appear at all. The software is confusing the merge with a `DUAL` edit.

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using tag nci-1.008, editta-0.6.7.  I retested this issue for both modeler and manager and did not see this dialog menu "class already being edited".  Please see attached zip files for snapshots for more details.

[Manager -merged.zip](https://github.com/NCIEVS/nci-protege5/files/1178658/Manager.-merged.zip)
[Modeler-Pre-Merged.zip](https://github.com/NCIEVS/nci-protege5/files/1178660/Modeler-Pre-Merged.zip)

Thanks,
Reza
