### ISSUE TITLE
tweak tree widget in revision history panel to deal with batch edits

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#316]
From [EHD]:
"The tree view in the Revision History tab behaves badly when the Workflow Manager is reviewing a batch edit. I think it cycles between all of the concepts edited during that commit. I needed to minimize the horizontal dimension once I could focus on one edit, otherwise it was out of control while viewing the commit for a batch edit."

**Comment by rmehri** [comment]
Hi, 
This ticket will be retested and verified when the protege QA server is ready. 
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
Is there a screenshot for this issue?
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I have retested this fix using tag 1.0082 on my local server and passed. But on QA sever, I received an error in Revision History.  I will keep this ticket opened and retest this issue when latest tag 1.0083 is ready on QA sever.  Please see attached screenshots and log file for more details.
1) Local server -Passed
![issue 316-local server-test](https://user-images.githubusercontent.com/8367102/29881521-d0a03d30-8d78-11e7-9b0a-78c2d7b0218a.png)
![issue 316-local server-test1](https://user-images.githubusercontent.com/8367102/29881524-d3f418d0-8d78-11e7-837e-5f0b7089d8cf.png)

2) 1) QA server -Received error on Revision History - Authors - when clicking on mehrig:

![qa_server-revision history -authors-java error](https://user-images.githubusercontent.com/8367102/29881915-8a23f760-8d79-11e7-8e8d-e8e48a3185ee.png)
[QA Server-Tag 10082.txt](https://github.com/NCIEVS/nci-protege5/files/1264238/QA.Server-Tag.10082.txt)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This fix has been retested on QA server using latest tag 1.0083 and Client-V2.1.10083.
Please see attached screenshot and for more details.

![qa server-issue 316](https://user-images.githubusercontent.com/8367102/29947049-c3882f24-8e75-11e7-9a4a-5ba1645ddb4e.png)

Thanks,
Reza
