### ISSUE TITLE
failure of a batch delete of an association 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#317]
From [TQ]:
"These two batch deletes are not working, I get the error message super class does not exist."
"One is to delete a retired Concept in Subset and the other is an active Concept in Subset (#2)."

To clarify, the concepts being edited are all "active".  It's the filler value of one of the associations being edited that is a retired concept.  

It seems that the batch processor is treating the batch edit files as batch load files.  The message being output is "super class does not exist", which is present in BatchLoadTask.java.

"Batch" file below has the retired filler, and "Batch2" file below has the active filler.

[25JulyRemoveSubsetBatch.txt](https://github.com/NCIEVS/nci-protege5/files/1174356/25JulyRemoveSubsetBatch.txt)
[25JulyRemoveSubsetBatch2.txt](https://github.com/NCIEVS/nci-protege5/files/1174355/25JulyRemoveSubsetBatch2.txt)

**Comment by NCIEVS** [comment]
@rmehri 
For regression testing, we need a set of batch files that exercise all of the edit actions: new, modify, and delete, for simple annotation edits, complex annotation edits, parents, and roles.

**Comment by bdionne** [comment]
[fixed in 0.6.](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.8)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using tag-1.0081, edit tab-0.6.9.  Please see attached log files and screenshots for more details. 

[01AugRemoveSubsetBatch-1.zip](https://github.com/NCIEVS/nci-protege5/files/1191755/01AugRemoveSubsetBatch-1.zip)

Thanks,
Reza
