### ISSUE TITLE
edits on a class wind up on a previously edited class

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#319]
From [CM]:
"I was making some edits for the Accepted therapeutic use for. I noticed that all was fine adding this and saving but if I wanted to edit an existing one (adding more diseases to the text field) it would let me save it but then it wouldn’t let me safe the next concept. That information would jump back to the previous concept and adding it to the previous concept."

Can be reproduced with any property:
- Open the tree anywhere you have multiple siblings, this is just out of convenience so you can switch between them without doing searches.
- select concept 1 and add a new property rdfs:comment = test 3, then Save
- select concept 2 and add a new property rdfs:comment = test 4, then Save
- select concept 3 and add a new property rdfs:comment = test 5, then Save
- select previous concept 2 and edit property rdfs:comment = test 4 to rdfs:comment = test 45, then Save
- select concept 4 and add a new property rdfs:comment = test 6
This last edit winds up in concept 2, now with two rdfs:comments, one = test 45 and the second with test 6.  

However, the above "edit the last concept" scenario can happen without any new properties being added beforehand;
- start with a new protege instance
- select concept X and edit an existing text property, say an editor_note
- select concept Y and add a new property editor_note = test
This last value will wind up in concept X and not in concept Y.

**Comment by bdionne** [comment]
[fixed in 0.6.9](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.9)

**Comment by rmehri** [comment]
Hi, 
This issue has been retested using the reproducible steps above and using the previous tag 1.008, Edit Tab -0.6.7 and the latest tag 1.0081, Edit Tab -0.6.9.  I did not see the same reported behavior.  Please see attached snapshots for more details.
 
![tag-1008--edit tab-06 7-concept1](https://user-images.githubusercontent.com/8367102/28741479-ccf09c1e-73e4-11e7-99a8-c0892a268a1d.png)
![tag-1008--edit tab-06 7-concept2](https://user-images.githubusercontent.com/8367102/28741477-cceb97d2-73e4-11e7-9617-8975a05d40d6.png)
![tag-1008--edit tab-06 7-concept3](https://user-images.githubusercontent.com/8367102/28741480-ccf0d74c-73e4-11e7-8380-cf07ebd0b574.png)
![tag-1008--edit tab-06 7-concept2-edited](https://user-images.githubusercontent.com/8367102/28741478-ccee9252-73e4-11e7-91a0-a24bc2f1ec15.png)

-----------------------------------------
![tag-10081--edit tab-0 6 9](https://user-images.githubusercontent.com/8367102/28741481-ccf999ea-73e4-11e7-9ca5-83ed30ccb05e.png)
![tag-10081--edit tab-0 6 9-edited concept1](https://user-images.githubusercontent.com/8367102/28741482-ccff359e-73e4-11e7-9db2-56a028bbda7c.png)
![tag-10081--edit tab-0 6 9-edited concept2](https://user-images.githubusercontent.com/8367102/28741483-cd00b0e0-73e4-11e7-8c82-0a3aff164fda.png)
![tag-10081--edit tab-0 6 9-back to concept1](https://user-images.githubusercontent.com/8367102/28741476-cce9182c-73e4-11e7-9e02-d62b7d27fbea.png)

Thanks,
Reza
