### ISSUE TITLE
complex property half-way configured (declared as complex, but no qualifiers associated with it)

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#32]
nciedittab has issues displaying the table (blank panel) when a property is declared complex but no properties are associated with it as "qualifiers".  No exception is thrown, but a two-line message is displayed in the console:  

`The data: null`
`BAD ViewComponent: (NCIEditViewComponent) Exception on dispose: null`

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
Can you please elaborate more on steps to reproduce?   

Thanks,
Reza

**Comment by bdionne** [comment]
see #137 for details

**Comment by rmehri** [comment]
The fix has been retested and verified using tag -116, edit tab-0.3.1.  No errors were occurred in the console. 
Please see attached  screenshot for more detail.

Thanks,
Reza

![complex property_no qualifier](https://cloud.githubusercontent.com/assets/8367102/21827226/bae0d616-d758-11e6-83a9-85bec692ada2.png)
