### ISSUE TITLE
Improve classification results

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#320]
The classification results panel is unusable as is, it retrieves much too much information and when fetching from a remote reasoner the performance is unacceptable.

Add a new classification results panel, than only shows the axioms that have changed. Along side each of them display whether the axiom should be added, removed (for redundant super-concept assertions), or repaired due to an inconsistency.

Something like this is more suitable:

<img width="1020" alt="screen shot 2017-08-03 at 4 56 47 pm" src="https://user-images.githubusercontent.com/31741/28943421-c98c1472-786c-11e7-9e10-91dcdd3c8d34.png">

**Comment by rmehri** [comment]
Hi, 
This ticket will be retested and verified when the protege QA server is ready for testing.
Thanks,
Reza

**Comment by bdionne** [comment]
To test this, first enable the classification results tab using a prior version of the software. Notice how long it takes to come up, note also how many results are returned. Now try the same thing with the new version and see that the results come back quickly and only new results are returned.

After classification the results to display are computed as the difference between the asserted and inferred view. Previously it was retrieving all the results from the classifier which include the asserted axioms as well.

Additionally we now display (see screenshot above) suggestions as to edit operations that can be performed. Once these edits are performed and classification is run again, the suggestions should go away. This supports a use case from Nick

**Comment by rmehri** [comment]
Hi 
Thanks for your feedback! This fix has been retested using latest tag 1.0083, Client-V2.1.10083 on QA server.

Used the following steps:

1)	Login to protege as workflow-manager
2)	Start Reasoner
3)	Create two concepts test1 and test2
4)	On test1 have the object property “conceptual_part_of” use a filler like Disease
5)	On test2 have the same object property but with a filler like some subclass of disease
6)	The classifier will then put test2 as child of test1 and it show them 
7)	The Classification results panel will suggest you add one axiom and remove another
Please see attached screenshot for more details.

![issue 320](https://user-images.githubusercontent.com/8367102/30185551-f6654e34-93ef-11e7-8355-ab0dfc95b785.png)

Thanks,
Reza
