### ISSUE TITLE
Tag: nci-1.0082 ncievs - Windows7- Not Seeing  Pellet Reasoner Plugin

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#322]
I have successfully built the latest nci-1.0082 ncievs on Windows, I am not seeing the Pellet Reasoner Plugin when I start from Windows.   Please see snapshots for more details. 

![preferences-1](https://user-images.githubusercontent.com/8367102/29691610-ce52811a-88f9-11e7-98b1-9f52932eac04.png)
![preferences-2](https://user-images.githubusercontent.com/8367102/29691611-ce53ffcc-88f9-11e7-9c96-e2f7580bfd73.png)

Thanks,
Reza

**Comment by bdionne** [comment]
The Pellet reasoner comes packaged already in the build.

You can see it there in your first screenshot above showing the installed plugins. It's Pellet::Protege 2.4.0

**Comment by bdionne** [comment]
@rmehri - is this still an issue?

**Comment by rmehri** [comment]
Hi Bob,
No. As per your feedback, this ticket can be closed. 
Thanks,
Reza
