### ISSUE TITLE
persistence of namespace prefix

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#323]
On export to OWL, the OWLAPI assigns a "Thesaurus" prefix to the NCIt (it doesn't have a prefix to start with).  What we would like to do is to define an "ncit" prefix in Protege so that this prefix is what gets written out to the OWL file on export.  However, you can add a new prefix for the NCIt to the vocabulary but the prefix is not committed to the server.  This is using the Ontology Prefixes subtab of the Active Ontology tab.

**Comment by NCIEVS** [comment]
A potential workaround doesn't work either, adjusting the prefix in the owl file before loading it to the server.

**Comment by bdionne** [comment]
This requires more work than anticipated, persisting to the owl file is easy, to the server it involves sizable rework to foundational classes. Will postpone until after the OWL API upgrade

**Comment by singhik** [comment]
@NCIEVS  : Hi, how to export the ontology from UI ? 'Window'->'Export Current Tab'  Exports it in .XML format and 'File'->'Export Inferred Axioms'  only exports inferred axioms , ?

**Comment by NCIEVS** [comment]
Hi @singhik, use File -> Save as -> rdf/xml syntax.  On the exported file, the prefixes would be listed at the top of the file in an RDF block:

<rdf:RDF xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xml:base="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:ncit="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:owl="http://www.w3.org/2002/07/owl#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:xml="http://www.w3.org/XML/1998/namespace"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:protege="http://protege.stanford.edu/plugins/owl/protege#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xmlns:dc="http://purl.org/dc/elements/1.1/">

The snippet above is from the "3.9.0" vocab in DEV, it already has the "ncit" prefix.  You can test by changing it in the GUI to something else, e.g. "newpref" and exporting.

**Comment by singhik** [comment]
@NCIEVS  : Hi, Is the expectation post updating ontology Prefix via 'Active Ontology' Tab is  for the change to get 'auto-updated' to server ?
If yes, it does not happen, Change has to be manually committed (FYI) .

**Comment by NCIEVS** [comment]
Hi @singhik , no, we won't be auto-committing from the stock protege tabs (e.g. the Active Ontology tab).  We have to do the manual commit after editing/creating a prefix.
