### ISSUE TITLE
undesirable self-parenting on a merge

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#324]
From [EHD]:
"I did a merge of the child into this concept and it automatically copied the self as parent from the child."

Edge case as it was a child concept being merged to a parent, but the merge should check that the resulting concept does not have itself as a superclass.

**Comment by bdionne** [comment]
fixed in [latest nci-edit-tab](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.7.2) release

**Comment by NCIEVS** [comment]
Depending on which is the older concept, e.g. lowest code value, the defect as described will occur in one case and not the other.  To test reproducibly:  
- create a concept that is a subclass of any target class.  The new concept will have a higher code than the old concept.  
- Merge the new concept with its parent, but make the subclass the surviving class rather than the retiring class.  
- Note that because the newer code is the surviving concept, the GUI will prompt you to switch them (which is surviving & which is retiring), select Cancel to maintain the right order to reproduce the defect.
- executing the merge will result in the new, surviving concept to have itself as a superclass.  This is wrong and it is the defect.

**Comment by kondareddys2** [comment]
The defect is fixed and tested in V2.1.012 Dev. Closing the defect.
