### ISSUE TITLE
Revision History tab Changes panel Change Subject column sorting should be alphabetical by Label

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#327]
If you are looking at the Changes panel of the Revision History tab and you are focused on the changes of All Authors or a single author and you sort by the Change Subject column, it does not sort the label display alphabetically (it is probably sorting based on IRI instead of label. See screen shot after trying to sort the column.

![image](https://user-images.githubusercontent.com/21345553/30713979-27997c1a-9edf-11e7-8db2-1364d0f06279.png)

**Comment by bdionne** [comment]
Close, it's using the default which is a call to `toString`. That generally works on most fields but the underlying values in this column are `OWLObjects`.

We'll have to add custom sorts for columns like this.

**Comment by singhik** [comment]
@bdionne :: Hello Bob, Sorting on Revision History Tab for column 'Change Subject' is not in Alphabetical order for the text in it ,  as an example 'Deep Inspiration Breath Hold' is sorted before 'Avoidance', below are the screen prints ::

![image](https://user-images.githubusercontent.com/36314371/42583455-f97ae24a-84fe-11e8-8dbc-d431201bc19f.png)

**Comment by bdionne** [comment]
Thus looks like the `Prompt` plugin was not fully published, try this again, checking first that the version you see is `1.0.7`

<img width="1154" alt="screen shot 2018-07-12 at 7 18 11 am" src="https://user-images.githubusercontent.com/31741/42600617-51b8ef36-85a6-11e8-9b8d-3206da4bb893.png">

**Comment by safrant** [comment]
The revision history properties at https://raw.githubusercontent.com/ncievs/revision-history/master/src/main/resources/update.properties is still set to 1.0.6

**Comment by singhik** [comment]
Alphabetical sort works on 'Change Subject' Column header of 'Changes' panel under 'Revision History' Tab.  Attached are screen prints ....
[Issue 327.docx](https://github.com/NCIEVS/nci-protege5/files/2193634/Issue.327.docx)
