### ISSUE TITLE
Deadlock using autoupdate

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#33]
I was testing the nci-0.99 client with the real thesaurus, I enabled auto-update, and went to complex edit. I got to a deadlock. The UI is frozen. Java detected it.
[deadlock-nci-client-099.txt](https://github.com/NCIEVS/nci-protege5/files/515113/deadlock-nci-client-099.txt)

**Comment by johardi** [comment]
I made a PR in your protege-client fork. Please check if it can solve the issue.

**Comment by bdionne** [comment]
@johardi - thanks, I'll try this in the next build. I think this is a good change anyway and may have for this case, but I suspect there are some locking issues in protege.

**Comment by bdionne** [comment]
needs checking in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107) seems to work locally

**Comment by rmehri** [comment]
Hi Bob, 
I have retested this issue using tag 116, edittab-0.3.1. No errors were received. 
Used roles:  "Workflow-Modeler and  Workflow-Manager"
Used my local server "8080", ProjectBaseByName  
Used "https://nciws-d699-v.nci.nih.gov:9090", ncit

Thanks,
Reza
