### ISSUE TITLE
persist tabs across sessions

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#331]
Feature request.  Currently (in 1.0083) selecting "Window -> Store current layout" does not persist any new tabs that may have been enabled into the next session.

**Comment by singhik** [comment]
@NCIEVS  : Hello, a minor and non-significant clarification, does the new tabs which were saved earlier have to be in the same order  as saved earlier, in terms of appearance ? F.e. 

I saved four tabs in this order ::

![image](https://user-images.githubusercontent.com/36314371/50927469-e338b280-1425-11e9-9a59-9e67f7f20c4a.png)


New session had four tabs as saved but order of appearance was different, i am pretty sure  this is fine , but please second ::

![image](https://user-images.githubusercontent.com/36314371/50928423-a0c4a500-1428-11e9-888f-0909c60f9ef5.png)

**Comment by NCIEVS** [comment]
Hi @singhik, I don't think it matters.  Maybe someone will request later to have the order persist as well, but this works for me.
