### ISSUE TITLE
difficult to edit while the reasoner is on 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#333]
Either set as regular or incremental.  

Turning off the classifier while edits are done would help, but then the suggestions can't be retrieved

- persist classification "suggestions" when the classifier is off
- allow copy-paste or Saving of the "suggestions"

Perhaps some of this might be ameliorated with the "accept" & "undo" buttons in the classification panel (see #332).

Keep this as a placeholder while we get additional feedback and this is discussed further.

**Comment by NCIEVS** [comment]
Wait on this one until the performance of the remote classifier can be tested against this use case (i.e. editing the "suggested" changes).

**Comment by bdionne** [comment]
for sure, we shouldn't pursue improving this until we decide to abandon the remote and use the classifier locally (in theory, given what we use the classifier for, it should be entirely local).

In the V2.1.001-DEV build, this works better on normal saves, but when `synchronize` is used from the reasoner menu it can hang a bit while waiting for a response

**Comment by kondareddys2** [comment]
This issue is fixed and verified in V2.1.012 Dev build tested on QA server.
