### ISSUE TITLE
opening inferred/asserted bottom-up tree changes focus

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#334]
When opening the bottom-up trees used in the classification panel, mainly the inferred view but also the asserted view, the focus concept changes to the one that is being opened.  

The behavior of these tree widgets would be better if the opening-node and get focus functions are separated, so that the tree can be opened up to the root concept without losing the intermediate path-to-root concepts from the display, inherent to a change in focus.

**Comment by kondareddys2** [comment]
The defect is fixed  and tested in V2.1.012 Dev. Closing the defect.
