### ISSUE TITLE
clicking on ? for explanations after classification returns slowly

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#335]
This is when classification is done locally, haven't examined this when classification is done remotely.  It has also thrown an exception on occasion when asking for the explanation (will capture the exception the next time i get one).

There might be something that can be done to increase the performance of this step.  Will probably require investigation & experimentation.

**Comment by bdionne** [comment]
On a reasonably sized machine, the explanations take about 3-5 seconds using the remote pellet server.

This is with the V2.1.010-DEV build

**Comment by bdionne** [comment]
Not sure what the issue is here

**Comment by kondareddys2** [comment]
Request more information on the defect to retest the same.

**Comment by bdionne** [comment]
this feature may change if classification reworked

**Comment by bdionne** [comment]
low priority

**Comment by NCIEVS** [comment]
Closed as pellet is no longer used.  Created new ticket (#497) for curator explanations.
