### ISSUE TITLE
cannot search after resetting the preferences

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#336]
The vocab needs to be reindexed after modifying the preferences (File -> Preferences), or Protege needs to be restarted.

**Comment by bdionne** [comment]
Protégé steps on it when the preferences are [saved](https://github.com/bdionne/lucene-search-tab/commit/f5e38ef3a557d49427517ed6bd5585ed462f058d), even if the search preferences are not touched.

**Comment by kondareddys2** [comment]
The defect is fixed and tested in V2.1.010 Dev. Closing the defect.
