### ISSUE TITLE
Proposed GUI changes

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#34]
Part 1. If you have multiple complex properties, then the boxes are too small to accommodate the default text size. Here is a screenshot of the complex property view for the concept Crying:

![image003](https://cloud.githubusercontent.com/assets/31741/19199160/b07db864-8c90-11e6-9fa6-7f01da94606c.jpg)

Part 2. The default size for each column doesn’t work well for DEF/ALT_DEF because you can only read a small part of the value field, which is where the definition text exists. Here is a screenshot of the complex property view for the concepts Screaming (which has the same problem as Crying) and Ingestive Behavior (which only has two complex properties and the value column displays the height of the text well but it is insufficient for the length of the text).

![image005](https://cloud.githubusercontent.com/assets/31741/19199173/bf0a0496-8c90-11e6-8f4a-a6c639e698bb.jpg)
![image006](https://cloud.githubusercontent.com/assets/31741/19199174/bf0faa86-8c90-11e6-9e21-1b25228390c2.jpg)

Part 3. We need the code displayed some where. Also the Preferred Name or Display (i.e. Basic Editing: Screaming) and the code need to be selectable to copy/paste.

**Comment by bdionne** [comment]
Since this is a function of the space on the page, could we revisit having a separate tab for Complex Properties and Descriptions (where the Parents, Restrictions and other logic-based entities are found).

**Comment by NCIEVS** [comment]
- a single tab has been dedicated to complex properties (DL definitions moved to its own tab)
- scroll bars have been added to both the tab and each table
- the code & PN are displayed in the general subtab of the edit tab

flagging ready for QA & v1 release

**Comment by rmehri** [comment]
This fix has been successfully retested in tag-110.  But in "General" tab, I noticed that the Code is located on too far to the top right navigator! It does not seem to be noticeable. Please see the attached General screen shot and let me know your thought.
*Note: This issue will remain open for your feedback. 
Thanks,
Reza

![complex property](https://cloud.githubusercontent.com/assets/8367102/21105729/48523bfa-c059-11e6-8c0c-e5cbfdefa3fb.png)
![general](https://cloud.githubusercontent.com/assets/8367102/21105747/56b6cba2-c059-11e6-8c8b-e4268c50d88a.png)

**Comment by rmehri** [comment]
This fix has been retested and verified.
