### ISSUE TITLE
Add and Remove in Inference Results are active links

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#342]
Minor issue.  When viewing Classification results on the Inference Results tab, the "Add Axiom" and "Remove Axiom" text has live links to the NCI concepts for "Remove" and "Add".

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/protege/commit/0b53c2458ef8), will be in next build

We changed the text of the hints to ensure no words are also the labels of classes

**Comment by bdionne** [comment]
ready in `2.1.0.13`

**Comment by singhik** [comment]
Unable to Test this currently as starting Reasoner is throwing error logs in QA Client V2.2.0 

![image](https://user-images.githubusercontent.com/36314371/36329518-3abd703e-1334-11e8-80a7-c4a2c0f2d388.png)

**Comment by bdionne** [comment]
This indicates an issue with your explanation server. Is it running correctly?

**Comment by singhik** [comment]
@bdionne : Can you please provide a class name with 'Remove Axiom' Inference, unable to find that ?

**Comment by bdionne** [comment]
I"m not sure there are any in the content you have. You can create one by:

 * create a new class
 * create two children of the new class
 * make both children defined by adding an equivalent object restriction, using the same object property in both, and choosing the fillers so that one is a parent of the other
 * sync the classifier

One of the suggestions should be a remove axiom

**Comment by singhik** [comment]
@bdionne : Hi Bob, I have tried replicating above steps with Tracy Safran  but am only able to see 'Add Axiom' and not 'Remove Axiom' .

I am confident that the hyperlink would have been removed from 'Remove Axiom' too as it must be the same subroutine that is being called for 'Add Axiom' and 'Remove Axiom' but  for validation would need to check on 'Remove Axiom' verbiage as well ... 

Please help, if you can get one added with 'Remove Axiom'

![image](https://user-images.githubusercontent.com/36314371/36692506-3bae95b6-1b06-11e8-956e-bf4ddcb3afa2.png)

![image](https://user-images.githubusercontent.com/36314371/36692520-431354cc-1b06-11e8-91a9-b5bf9f4cfc78.png)


![image](https://user-images.githubusercontent.com/36314371/36692524-4817988e-1b06-11e8-88bb-6d0ff7566324.png)

**Comment by bdionne** [comment]
@singhik @safrant - not sure what to say, here's a sample I just ran. I use SmallBase but this should work on any content:

 - Create foo12 as a subclass on 'Molecular Abnormality'

<img width="1023" alt="screen shot 2018-02-26 at 3 22 12 pm" src="https://user-images.githubusercontent.com/31741/36693405-311d51a2-1b09-11e8-866d-00afb41aa7a5.png">

- Create a child of foo12, called bar121 and add an equivalent class to it, `Conceptual_Part_of some Gene`

<img width="1016" alt="screen shot 2018-02-26 at 3 25 07 pm" src="https://user-images.githubusercontent.com/31741/36693478-6364076e-1b09-11e8-98e5-18d9dee14966.png">

- Create another child, bar122 and add the same object restriction as you did in bar121 except the filler is now `Cancer Gene`

<img width="1019" alt="screen shot 2018-02-26 at 3 26 46 pm" src="https://user-images.githubusercontent.com/31741/36693553-96da2ace-1b09-11e8-8cf3-952020caf0f6.png">

- Now check the inferences panel and you'll see the remove axiom

<img width="1023" alt="screen shot 2018-02-26 at 3 28 52 pm" src="https://user-images.githubusercontent.com/31741/36693621-dd746b3e-1b09-11e8-8769-db17e645f97d.png">

**Comment by singhik** [comment]
QA has verified for 'Add Axiom' and 'Remove Axiom'  under  'Inference Results' Tab to not have hyperlinks in description, but plain text .
