### ISSUE TITLE
Configure Protege/Pellet to use rolling file appenders for log files.

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#343]

**Comment by safrant** [comment]
Are there any configuration settings I need to make, or is everything set?

**Comment by singhik** [comment]
This ticket needs Business Users input for validation, assigning the ticket to Tracy Safran (safrant) for the same ...

**Comment by safrant** [comment]
These logs are rolling over based on date.  Not sure if that is intended. 

![protrolllog](https://user-images.githubusercontent.com/2364871/36561933-4bf6240a-17e3-11e8-946a-7473191c1a0f.jpeg)

**Comment by NCIEVS** [comment]
Up to us.  We could roll them by size instead.  1 Meg?  What are the servers set for?

**Comment by bdionne** [comment]
Exactly, you can get rid of the [time based policy](https://github.com/bdionne/protege/commit/2e5968b7) and go with just size.

It is nice to see at a glance what the daily usage is like

**Comment by safrant** [comment]
I am fine with this.  Just wanted to check, since that is not what the ticket says.
