### ISSUE TITLE
Change default Lucene indices location to directory app runs out of

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#344]

**Comment by bdionne** [comment]
Itendra: Please provide steps to reproduce 

This one is very simple. The Lucene indices were being stored in the users home directory. So on OS X that would be `/User/joe/.Protege/lucene/...`

The change is to store these in the directory where the app is installed and run from

**Comment by singhik** [comment]
QA verified the Indices being stored in the location of the client install-able for V 2.2.0 ...
Attached are the screen prints for reference  ....
[Issue 344.docx](https://github.com/NCIEVS/nci-protege5/files/1744469/Issue.344.docx)
