### ISSUE TITLE
Restriction values not properly rendered

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#345]
From Liz:

In protégé, the restriction value concept links don’t work if the Description window is narrow and the restriction needs to wrap around but if you widen the window the links work fine. However, for C37317 in my GUI, even with the window expanded, some of the restriction filler value links are acting as if each term in the filler is a separate concept. For example the last role in the window is Gene_Product_Encoded_By_Gene PPP2R3B Gene and when you hover over the PPP2R3B part there is no link but when you hover over the word Gene there is a link to the Gene concept not to the PPP2R3B Gene concept. C37317 has ~20 restrictions and the first 11 behave properly but the rest behave as if each word could link to another concept.
 
I am able to replicate this in separate sessions and I did find other examples. All of them have a large number of restrictions. I just found one where none of the restriction links  work properly (C37317). I haven’t seen enough of this to determine if there is a number of restrictions that is the breaking point and actually I have found some concepts with ~20 restrictions where the links are working (C17580, C17924 and C26488). So I am not sure of the cause.

**Comment by safrant** [comment]
Which part of this has actually been fixed?  The wrap around links seem to work but the role groups do not.

**Comment by bdionne** [comment]
@safrant - do you have an example. I'm not sure what you mean by role groups, we don't have those anymore, but if you  mean the compex `and/or` definitions, they seem to work. Here are two screen shots where the filler `Human` has an active link even when the screen is scrunched and it wraps:

<img width="986" alt="screen shot 2018-07-17 at 7 49 44 am" src="https://user-images.githubusercontent.com/31741/42785571-5fc3803e-8996-11e8-9aff-74c194ffb943.png">
<img width="314" alt="screen shot 2018-07-17 at 7 50 05 am" src="https://user-images.githubusercontent.com/31741/42785572-5ff9ede0-8996-11e8-8767-9da8b0272a6a.png">

**Comment by safrant** [comment]
The second part of the ticket was about links not working on four listed concepts when many roles were present.  I checked C37317 and C26488 and discovered the Equivalent_To group of roles has only a link to the very last concept listed.  In your example I can link to "Human" and "KISS1 Gene" but not "1q32" or "1: 200897271-200891127".

**Comment by bdionne** [comment]
Interesting, both of those work fine for me, perhaps this is an OSX/Windoze thing @safrant 

We can spend some more time on this, but I'll leave the priority to @NCIEVS , this involves mucking with `OWLCellRenderer` which is a home grown thing and very tricky to modify as it affects every widget that renders

**Comment by NCIEVS** [comment]
I have the impression this might be a jar issue.  What @safrant is describing above in Mac I'm seeing in Windows.

**Comment by safrant** [comment]
quicktime mov
[2018-07-16 19-32-55.mov.zip](https://github.com/NCIEVS/nci-protege5/files/2199657/2018-07-16.19-32-55.mov.zip)

**Comment by bdionne** [comment]
Yes, I can see the error where it goes for `Human` regardless of what you click. Thanks @safrant 

@NCIEVS - you still need to think about the priority if this one, as I suspect it will require more change to `OWLCellRenderer`. At a minimum that means an additional client build of protégé

**Comment by bdionne** [comment]
@NCIEVS - let's give it a couple of more days for Yinghua and I to study it. It's easy enough to revert if needed, but will requite another build. We'll see how that delete error works out. I suspect it's a corrupt file issue or another format we're not parsing right, but if it requires a new protege-server build we can revert this other one then also

**Comment by bdionne** [comment]
This is done and ready actually, my mistake. There is another ticket for the lucene results wrapping, #152, which is already in the future release bucket. So I'll move this to QA for 2.6.0

**Comment by singhik** [comment]
QA has verified and works as expected, hence closing this ticket ....
