### ISSUE TITLE
slow to display an added DEF when there is not an existing DEF present.

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#346]
From [EHD].  Still to be tested whether this is a "first time use" of the widget or if it happens every time.

**Comment by NCIEVS** [comment]
Follow up from [EHD]:  This issue does not appear to be a first time only occurrence.

**Comment by bdionne** [comment]
Itendra: When i add a unique 'DEFINITION' property(NCI Edit->Edit), i dont see a slow display , which DEF does this issue specifically refers to ? please provide steps to reproduce.

I don't have steps to reproduce. The description above indicates this occurs when a `DEFINITION` is added to a class that doesn't have any.

**Comment by singhik** [comment]
This has been QA Tested for adding a DEFINITION complex property when a class didn't have any . No delay has been observed during the addition. Please refer to the screen prints attached ...
[Issue 346.docx](https://github.com/NCIEVS/nci-protege5/files/1732826/Issue.346.docx)
