### ISSUE TITLE
permissions/locking on inappropriate shutdown

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#348]
From [EHD]:

"I inadvertently hit Shutdown instead of Lock to leave my desk and protégé was shutdown in the process. Now I am having issues searching and I got an error in the listener when trying to Build index (see text below) and it is not reindexing. (I think the shutdown caused some of my settings to be lost as I had to reset my Lucene settings too.)"

This turned out to be a permissions issue on Windows, seems like it locked a number of files and/or made them read-only.  Had to reinstall.  

No action, but perhaps this edge case should be examined if/when we support offline editing so local data doesn't get lost if this scenario is repeated offline.

**Comment by bdionne** [comment]
deal with this when he do #491

**Comment by NCIEVS** [comment]
Examine this one when #491 is being discussed/planned.

**Comment by fragosog** [comment]
Should be able to do something like this:  https://adambien.blog/roller/abien/entry/sigterm_sigint_sigkill_and_java.

additional info:  
- https://learn.microsoft.com/en-us/previous-versions/ms811896(v=msdn.10)?redirectedfrom=MSDN
-  https://docs.oracle.com/javase/8/docs/api/

**Comment by singhik** [comment]
@bdionne @fragosog : Hi, what is the fix applied to this Ticket ? Protege always had an 'Auto-update' option at Server level which would save and commit changes at server side in case of forced shutdown. What new has been added/edited for me to Test ?

**Comment by fragosog** [comment]
Hi @singhik , in this one there is an effort to trap signals from the OS so when it tells a program to quit before a shutdown the JVM can exit gracefully.  It cannot catch everything, a "kill" is definitive. The only test is to repeat what [EHD] did, do some edits, searches, tree browsing, and then leave protege running and shut down the windows PC.  On boot up, and then protege launch, you should be able to do searches, tree browse, and edits.  If protege is responsive when doing those operations then the fix worked and captured what it needed to capture.

**Comment by bdionne** [comment]
>  Hi, what is the fix applied to this Ticket ? - @singhik 

If the JVM receives a SIGINT from the OS, the Lucene Indexer will attempt to close open indices.

**Comment by singhik** [comment]
@bdionne  @fragosog  :  Hi, The specific trigger of Lucene Index attempting to close open indices when/if OS sends any procedure call (f.e. SIGINT) to JVM, **can not** be Functionally validated as  it is a Use Case at Unit Level for White Box validations .

I have validated the Operations with multiple edits (including a few unsaved edits) and a forced shut down of Windows. On Relogging, none of the Concepts were locked for edits and all Protege Operations were working fine, so i believe this ticket can be closed  . (Build : 4.2.0-dev1)
