### ISSUE TITLE
update setseq to be project specific

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#349]
the script would need to be updated to reflect the newer server configurations where each project has its own gencode.

**Comment by bdionne** [comment]
Itendra: Please provide steps to reproduce the updated script change .

You'll want to see Tracy for this. I gave her a [modified script](https://github.com/bdionne/protege-server/blob/master/scripts/setseq.sh) that she customized for NCI with particulars for the environment.

There was no code change involved here

**Comment by singhik** [comment]
Assigning the ticket to Tracy Safran to validate  @safrant ...

**Comment by safrant** [comment]
Tested successfully on both Dev and QA
