### ISSUE TITLE
Improve batch edit progress reporting

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#350]
It's never clear when batch edit are completely finished

**Comment by bdionne** [comment]
Itendra: How to ensure this edit progress is improved ? Loading a batch input file and Starting the process , how will i differentiate the improved change .

The main change is that the progress dialog cannot be dismissed until the job is completely finished, including updates to the server

**Comment by singhik** [comment]
@bdionne  :  Hi, 

1.Batch Type 'Load' works fine with the sample file ,if the super class is specified by Class Code and does not work when specified with name .

2. During Batch Type loading, when trying to cancel the 'Progress dialog', it does not get cancelled (as Expected),  but, after completion, it hangs and does not let any operation to be completed as the 'Class Saved Successfully' dialog does not appear . This hangs Protege v2.2.0 and has to be restarted to be able to return back to normalcy ..




Batch processing completed, and Protégé  is hanged now,none of the buttons are clickable(Save,Clear,Close,Cancel) ::

![image](https://user-images.githubusercontent.com/36314371/36505179-b2ff39d4-1720-11e8-8b3f-be83d2b90dcb.png)

**Comment by bdionne** [comment]
@singhik - interesting, I'm wondering if you were inactive for a while before running the load, and no longer logged in? The server will timeout when that happens and next time you save an edit ask you to login again. Perhaps this *doesn't* happen in batch load. I'm just speculating, as your screenshot seems to indicate it did all the creates but it hasn't committed them yet.

Here's a [sample](https://github.com/bdionne/nci-edit-tab/blob/master/samples/batch_load1.dat) file that ships with the code that loads 1000 classes. The input files can be tricky, if you use the default delimiter, it's a tab and you need to make sure the delimiter is specified in the dialog. 

Also the parent is typically the code, as that is the IRI fragment that uniquely identifies the class, though it's not always a code, for example in this test I used Activity as the parent. When you select a class you can see the IRI fragment in the main edit panel:

<img width="1022" alt="screen shot 2018-02-21 at 4 22 35 pm" src="https://user-images.githubusercontent.com/31741/36506534-f09a49ba-1724-11e8-84ab-3ebc07cf254b.png">

<img width="1010" alt="screen shot 2018-02-21 at 4 20 17 pm" src="https://user-images.githubusercontent.com/31741/36506544-f89b7774-1724-11e8-8614-0c5be6bf3606.png">

<img width="1022" alt="screen shot 2018-02-21 at 4 33 59 pm" src="https://user-images.githubusercontent.com/31741/36506580-0f09c7b8-1725-11e8-8cca-93b8dee09fcf.png">

**Comment by singhik** [comment]
@bdionne  : Hi , I waited for over 20 mins for 9 Concepts load but it did not prompt for 'Class Saved Successfully'  dialog prompt, this behavior of getting hanged only appears to happen if one tries to Cancel the Load while it's in-progress . If i leave it untouched, then it works fine for me too ,so to summarize here are the open threads on this issue : 

1. Do i need to run Batch Type load for all like EDIT_SIMPLE_PROPS,EDIT_COMPLEX_PROPS,EDIT_PARENTS,EDIT_ROLES ?

2. Should the user intervention of trying to cancel the Load, make it hang or should it still save the classes and after completion should close the Progress dialog, as in my case, the former is the case where it hangs when interrupted to close ?

**Comment by bdionne** [comment]
@singhik - thanks, I'll try to reproduce that behavior, so far cancel seems to work fine for me.

1. Yes this ticket is for all the batch functions, I would imagine loads are usually large, but I think some modelers do some pretty large edits of simple properties. You might check with one of them for some interesting samples. There are more [here](https://github.com/bdionne/nci-edit-tab/tree/master/samples) that I use with my local `SmallBase` ontology. Also [here](https://github.com/NCIEVS/nci-protege5/wiki/batch-edit-formats) the spec for them is you want to create more.

2. Cancel should stop and close the progress dialog. However if you've already reached 100% I don't think cancel will work. What happens is that the commit to the server is a long operation, but we changed the progress dialog to leave it up so that the modeler won't think it's finished. I'll try it with sever thousand classes and see if I can get it to hang

**Comment by bdionne** [comment]
The next build 2.2.0-beta2 will be a little different in how the dialog dismisses, and hopefully less subject to freezes

**Comment by singhik** [comment]
@bdionne : Hi Bob, The progress bar for 'Batch Load/Edit' does not hang now  but for 'EDIT_ROLES' , i do not see any progress bar like i see for other 'Batch Type' ?

![image](https://user-images.githubusercontent.com/36314371/36752991-c6d746ac-1bd2-11e8-8436-8e799eb3279e.png)

![image](https://user-images.githubusercontent.com/36314371/36753006-d1b8ea76-1bd2-11e8-9078-3e7b3016a696.png)

**Comment by bdionne** [comment]
@singhik  = Interesting, perhaps because it happens so fast? Were the edits performed? If you can attach the file you used to run this I can try it on my end

**Comment by singhik** [comment]
@bdionne : Hi Bob, My initial thought too was due to the fast record updates the progress dialog box prompt does not become visible but i have tried all other batch_types for fewer records and the progress dialog box does show up for a glimpse of time unlike the case for Batch_Type:EDIT_ROLES .

I have attached the file i have used, have modified it for new Edit to be successful, you may please try it on your end and confirm if you  see the Progress Dialog prompt showing completion ....

[Edit_Role_New.txt](https://github.com/NCIEVS/nci-protege5/files/1771635/Edit_Role_New.txt)

**Comment by bdionne** [comment]
@singhik 
It's there, but flies by very quickly, perhaps because it's a simple edit, and a small file. I saw it once briefly out of 5 tries.

I put it in the debugger and you can easily see it when stepping (see screenshot). This is a good thing :)

<img width="1018" alt="screen shot 2018-03-01 at 11 50 56 am" src="https://user-images.githubusercontent.com/31741/36857649-0ea49b9a-1d47-11e8-9e69-3f90e16e8bf0.png">

**Comment by singhik** [comment]
@bdionne : Thanks Bob ....

QA has verified Edit Process Progress bar for Batch_Types . Attached is the screen print document for reference ....

[Issue 350_New.docx](https://github.com/NCIEVS/nci-protege5/files/1772187/Issue.350_New.docx)
