### ISSUE TITLE
Enable individuals by class tab

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#351]
Enable the "individuals by class" tab (role-restricted to workflow managers) so we can search for dangling properties (#264) and delete them in the gui. All the views in the Windows->Views->Individual Views should be selectable by the workflow manager to add to the individuals tab.

**Comment by singhik** [comment]
1. Window->Views->Individual Views->       [does not  have 'Individuals by class' option as the requirement header mentions ]
2. Windows->Tabs->      [ has 'Individuals by class' option but is disabled for manager role ]

**Comment by bdionne** [comment]
oops, this is my bad, forgot to check in changes to `protege-client`, this will be in next build

**Comment by bdionne** [comment]
Fixed in 2.2.0-beta2

**Comment by singhik** [comment]
@bdionne : Hi, Unable to re-test on 2.2.0-beta 2  due to missing plugin jar in Edit Tab ..

**Comment by bdionne** [comment]
my bad, didn't publish the jar, it's there now

**Comment by singhik** [comment]
@bdionne : Hi Bob, Can you please provide an example of 'Dangling Properties', so that i can verify their search-ability from 'Individuals by Class' tab ?

**Comment by bdionne** [comment]
@singhik - sorry I have no examples. This issue relates to these properties showing up in exports. The idea is to enable the individuals tab in order to see them. To date no one seems to know how they get created. One of the modelers might be able to help you

**Comment by singhik** [comment]
Hi,
      QA has verified the Enabling of 'Windows->Tabs->Individuals By Tab' for WorkFlow Manager Role  .
      QA has verified the Disabling of 'Windows->Tabs->Individuals By Tab' for WorkFlow Modeler Role  .

Windows->Tabs->Individuals By Tab: Enabled for Workflow Manager Role

![image](https://user-images.githubusercontent.com/36314371/36691860-77dcb376-1b04-11e8-9e51-d9326f9fca5b.png)

Windows->Tabs->Individuals By Tab: Disabled  for Workflow Modeler Role 

![image](https://user-images.githubusercontent.com/36314371/36691875-846b9990-1b04-11e8-98fb-b3f7a78e80e4.png)


Panels ::

![image](https://user-images.githubusercontent.com/36314371/36691914-9d9f001e-1b04-11e8-99e9-8b10965778d1.png)
