### ISSUE TITLE
batch editing of retired classes by workflow managers

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#352]
At least once a year there is a need to retree retired classes to an archive bin.  We've done this in the past by creating a new project after processing the file data.  It would be more convenient if the workflow managers were able to edit these classes in batch; currently the workflow managers can edit them in the gui but not in batch.

**Comment by singhik** [comment]
@NCIEVS :: Hi, Have tried  'Batch Edit Modify' via 'Batch Load/Edit' for 'Batch Type' "EDIT PARENTS'   for Retired Concepts and was able to successfully retree them under any other non-retired Concept , attached is the detailed screen print document for reference . I am only aware of this Batch Edit process , Is there any other Batch Edit process which is used for Batch Editing ? If yes, please do let know else we can close this ticket .....

[Issue 352.docx](https://github.com/NCIEVS/nci-protege5/files/2193445/Issue.352.docx)

**Comment by NCIEVS** [comment]
@singhik, we can skip other batch edits on retired concepts.  The scenario is reparenting, but please test reparenting from one retired class to another retired class, e.g. a class under "Retired concept current year" to "Retired concept 2017".

**Comment by singhik** [comment]
Retree of retired concepts via Batch Edit Modify is working fine for Workflow Manager Role, for both when re-parented from a Retired Concept to non-retired Concept and when re-parented from a Retired Concept to another Retired Concept  ... Attached document with detailed screen prints ::
[Issue 352.docx](https://github.com/NCIEVS/nci-protege5/files/2193572/Issue.352.docx)
