### ISSUE TITLE
make accessible outside the firewall

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#353]
related to #286

**Comment by NCIEVS** [comment]
Begin scanning at any time.  Tentative request for waiver on the 2.4.0 timeframe.

**Comment by singhik** [comment]
@NCIEVS : Hi, Please provide any other logs or connection requests that needs validation outside the firewall(LAN) apart from below ::

1.Logs(explanation-cron,pellet-console,protserv-console) are accessible using LDAP Credentials over https protocol remotely when connected to VPN .
2. Logs are NOT accessible when not connected to VPN .

**Comment by singhik** [comment]
Thanks @NCIEVS , closed ticket ,working as expected with Protege Client 3.0.0 .
