### ISSUE TITLE
Client loses server/update menu item

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#355]
After a period of time editing, the client gets to a state where:

* it goes to save an edit
* is told that it is out of sync
* server/update is disabled, as well as server/changehistory and server/getuncommitedchanges

User can clear or undo edits but the problem persists until the app is restarted

Note: the client app was using 6.5G of RAM

**Comment by NCIEVS** [comment]
Goes with #255.  Underlying issue might be the same

**Comment by NCIEVS** [comment]
closing.  reasoner running locally, server reasoner dropped.
