### ISSUE TITLE
support for concept deletion

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#357]
This would only be done for concepts that have been created accidentally but have not yet been published, i.e. they are safe to delete.  Maybe the evs_history can retain a record of their brief existence, but the concept_history should not.

Because only concepts that have yet to be published can be deleted, somehow there needs to be knowledge about the process stored or coded somewhere.

Longer term/low priority.

**Comment by bdionne** [comment]
There's a couple of approaches we can take to this, I think it needs some discussion about:

 - existing save/cancel semantics of edit tab
 - use of entities tab
 - whether to write new `DELETE` records to `EVS` history and then filter when publishing `CONCEPT` history

Given we'll need to commit changes to the server regardless, it's probably less confusing for the users to add a new `DELETE` icon to the navigation pane

**Comment by bdionne** [comment]
clarification: In order for a concept to be deleted:

 - must be retired
 - must have been create in the current cycle (exists in `current_evs_history`)

We can then delete, and write a `DELETE` record to `current_evs_history` and use that to prevent publishing to `concept_history`

**Comment by NCIEVS** [comment]
Late last week I was able to delete after retiring concepts created in the current cycle (tested in DEV).  Today I can't.  I updated my plugins this morning.

**Comment by bdionne** [comment]
@NCIEVS - this is a server side error, it's not able to find the record in the history file or not able to access the file. Do you see any server stack traces? I just tested this locally and it works fine, both byName and byCode versions

@singhik - that's the correct behavior *if* the class was created in en earlier cycle, .ie. before you last published the concept history in the revision history panel. To test the current cycle, create a new class, then retire it and try to delete.

**Comment by NCIEVS** [comment]
Server-side is throwing an out of bounds exception, no stack trace.  Here's an entire session involving creating a concept ("delete_me"), followed by a retirement, then an attempt at deletion.

18:29:00 [XNIO-1 task-31] INFO  - ... Revision #93: AddAxiom(Declaration(Class(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018>)) OntologyID(OntologyID(Anonymous-114))),
AddAxiom(AnnotationAssertion(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "C150018") OntologyID(OntologyID(Anonymous-114))),
AddAxiom(AnnotationAssertion(rdfs:label <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "delete_me") OntologyID(OntologyID(Anonymous-114))),
AddAxiom(AnnotationAssertion(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "delete_me") OntologyID(OntologyID(Anonymous-114))),
AddAxiom(AnnotationAssertion(Annotation(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-group> "PT") Annotation(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-source> "NCI") <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "delete_me") OntologyID(OntologyID(Anonymous-114)))
18:29:00 [XNIO-1 task-31] INFO  - ... success in 0.0 seconds.
18:30:08 [XNIO-1 task-18] INFO  - [Request from JoeBlow (JoeBlow) - Commit changes] Receive revision #94: delete_me(C150018) - RETIRE
18:30:08 [XNIO-1 task-18] INFO  - Writing changes to history
18:30:08 [XNIO-1 task-18] INFO  - ... Revision #94: AddAxiom(AnnotationAssertion(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P95> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "Mon Jul 16 18:30:06 EDT 2018 - Retired on: 2018-07-16 by JoeBlow") OntologyID(OntologyID(Anonymous-115))),
AddAxiom(AnnotationAssertion(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P98> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "Mon Jul 16 18:30:06 EDT 2018 - Retired on: 2018-07-16") OntologyID(OntologyID(Anonymous-115))),
AddAxiom(SubClassOf(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C83485>) OntologyID(OntologyID(Anonymous-115))),
AddAxiom(AnnotationAssertion(owl:deprecated <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "true"^^xsd:boolean) OntologyID(OntologyID(Anonymous-115))),
AddAxiom(AnnotationAssertion(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P310> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150018> "Retired_Concept") OntologyID(OntologyID(Anonymous-115)))
18:30:08 [XNIO-1 task-18] INFO  - ... success in 0.0 seconds.
18:31:27 [XNIO-1 task-5] ERROR - null
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by bdionne** [comment]
would it be possible to attach the current evs history file to this ticket? The . `ArrayIndexOutOfBounds` makes me suspect it's somehow been corrupted

**Comment by NCIEVS** [comment]
OK, posted.  Will send URL separately.

**Comment by singhik** [comment]
QA has verified Concept Deletion functionality for Retired Concept, Created in Same Cycle with WorkFlow Manager Role . 
QA has verified that Concept Deletion button is always Disabled for Modeler Roles.
Attached is the document with screen prints ....

[Issue 357.docx](https://github.com/NCIEVS/nci-protege5/files/2214840/Issue.357.docx)
