### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#359]
Nick reports some issues:

 * right click popups on classes in the nav tree are funky. the class needs to be first selected for the popup to populate correctly

 * application seems to be slow on Fridays. This could be a recent phenomenon, recently other modelers were hitting it pretty hard, which may have caused some contention

 * classification results are not always correct and the app needs to be restarted (#362)

**Comment by NCIEVS** [comment]
Status:
- Right-click suggested fix is being discussed
- On daily testing during two consecutive weeks, [GF] didn't see a deterioration in performance (also measured the classification performance), so at least normal "wear and tear" changesets don't impact significantly.  Remains to be seen whether occasional large batch job changesets have an effect (or whether this is ongoing).
- Occasional issue in the startup of the pellet server was suspected and addressed.  (However, all classifications are now local, plus a new classifier is available now so third bullet is no longer applicable.)

**Comment by bdionne** [comment]
This needs another protege build

**Comment by NCIEVS** [comment]
For QA testing, only the right mouse button popups on tree widgets needs to be tested.  Trees are found in the main edit tab, in entities tab, in the inferences tab, in revision history.  Whether there is a popup, and if so if the selectable items are the correct ones.  

The current behavior is that the class needs to be selected first with the left mouse button, and the popup brought up with the right after class selection.  The new behaviour should be class selection & popup at the same time from the right button.

**Comment by bdionne** [comment]
Closing this ticket, as the only issue being addressed relates to the popup menus, for which there's a new ticket, #511
