### ISSUE TITLE
CSV exporter doesn't respect file extensions

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#36]

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.0)

**Comment by rmehri** [comment]
Hi Bob, 
I retested this fix and verified that when a user does CSV export, the file extension will be .CSV. 
Please see attached screen shot for more detail.  

Note: as per double checking, can you please clarify the description of this ticket?

Thanks,
Reza
  
![export csv file](https://cloud.githubusercontent.com/assets/8367102/21876971/b1367b7c-d855-11e6-8fea-c3d9021cd646.png)

**Comment by bdionne** [comment]
the issue was that it forces the use of `CSV` for the extension, even if one changed it to something else.

**Comment by bdionne** [comment]
Is there still a question here? The issue is allowing the user to use other extensions.

**Comment by rmehri** [comment]
Yes, thanks for your feedback! I retested CSV export with no file extension and it resulted with no file extension.
Steps to reproduce: 
1)	Select a class
2)	Select property row 
3)	Click Tools
4)	Select Export to CSV
5)	Select all necessary properties and values
6)	Click browse to designate a file location 
7)	 Have a file name with no extension
8)	Have file type as .CSV and save the file and the file ends up with no file extension.

In this case, do you expect “.CSV” extension when a user does not specify the file extension?
Please see attached zip file for more details.
 
![csv_extension_1](https://cloud.githubusercontent.com/assets/8367102/22030406/850ee458-dcab-11e6-8426-c04b88a4a38f.png)
![csv_extension_2](https://cloud.githubusercontent.com/assets/8367102/22030414/86ed8626-dcab-11e6-8274-88d0d4d43cc1.png)

Thanks,
Reza

**Comment by bdionne** [comment]
No, I think respecting the file extension selected by the user is correct

**Comment by rmehri** [comment]
Thanks! Based on your feedback, this ticket can be closed. 
Reza
