### ISSUE TITLE
addition of concept_status on merge/retirement

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#361]
from [EHD]:

"I guess one of the new releases began adding Concept Status Retired Concept to concepts when they are being Retired but protege is still not adding Concept Status Retired Concept to the retiring partner of a Merge (probably because this is handled by a separate part of the code Merges are Complex Edits while Retires are their own process). See code "C82949" in prod of NCIt (I will need to add Concept Status Retired Concept manually before the monthly baseline export on Monday, 2/26."

**Comment by bdionne** [comment]
fixed in [0.8.1](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.8.1)

**Comment by singhik** [comment]
QA verified the 'Retiring Concept' of a Merge to get under 'Retired Concept' Tree post Merge . Below are the detailed steps with screen prints ::

Performing Merge on two concepts ::
 
![image](https://user-images.githubusercontent.com/36314371/40241673-95df1502-5a89-11e8-986d-ce3e9e2a3c70.png)

 


Retiring Concept is shown under “Retired Concept” as below::

 
![image](https://user-images.githubusercontent.com/36314371/40241687-9fc9bc66-5a89-11e8-9abb-031324e1b8ed.png)


 
![image](https://user-images.githubusercontent.com/36314371/40241695-a3f35022-5a89-11e8-9687-14e2cd70f1de.png)


Retired Concept now is not present in the Original Java Tree as is moved under Retired Concept Tree ::
 
![image](https://user-images.githubusercontent.com/36314371/40241707-aa3beaa2-5a89-11e8-8d29-e35c39bc94eb.png)
