### ISSUE TITLE
Please fix typo on BatchEditIRIs tab

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#365]
As per Teri, this tab has a column labeled IRI Fregment instead of IRI Fragment.
![image](https://user-images.githubusercontent.com/21345553/37675165-efd037ac-2c4a-11e8-8b32-029a1a6d3aa6.png)

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/commit/8e03e7b6e665cdad5e78a82f2325ca6cf3b4b52d)

**Comment by singhik** [comment]
QA has verified the verbiage 'IRI Fragment' being correctly spelled under  NCI Edit Tab->BatchEditIRIs  per below screen prints  :: 

![image](https://user-images.githubusercontent.com/36314371/38320661-31a1206a-3803-11e8-996f-ba411bfee0b9.png)


![image](https://user-images.githubusercontent.com/36314371/38320689-463c9b94-3803-11e8-95ea-444286a23e73.png)
