### ISSUE TITLE
Qualifier Slots Not Visible/Editable in ComplexEdit Panel

### ISSUE THREAD

**Issue by hahndane** [NCIEVS/nci-protege5#366]
When you use the ComplexEdit pane and try to Edit an existing complex property (FULL_SYN, DEF, ALT_DEF) the only visible slots are whatever already exists on the property you are editing.
Screenshot of edit popup after hitting the pencil button on a FULL_SYN that only has Term Type and Term Source in the Dual Edits mode.
![image](https://user-images.githubusercontent.com/21345553/37772032-c1e4d6a2-2daf-11e8-996e-7404fd2db9c4.png)
Versus selecting to edit the same FULL_SYN in the Edit Tab
![image](https://user-images.githubusercontent.com/21345553/37772065-e176d844-2daf-11e8-8a1d-9c05dab3f3e0.png)
The same thing happens if you are trying to add the complex property in the Complex Edit tab. The visibility/editablity of the qualifiers depends on what was in the complex property that you had the focus on when you selected the desired
![image](https://user-images.githubusercontent.com/21345553/37772211-52c37002-2db0-11e8-9587-8043d430f60a.png) button.

**Comment by NCIEVS** [comment]
Tentative release for 2.4.0.  If there's time, move to 2.3.0.

**Comment by bdionne** [comment]
fixed in [0.8.1](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.8.1)

**Comment by bdionne** [comment]
interesting, I'm wondering if that's always been like that? Anyway, will fix and push in the next plugin update. Good eye!

**Comment by bdionne** [comment]
@singhik - ok, I fixed this label issue in the next plugin update [0.8.4](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-0.8.4)

**Comment by singhik** [comment]
QA has verified the 'Edit' button of Complex Properties (DEFINITION,ALT_DEFINITION,FULL_SYN) to be in congruence with Edit mode and Dual Edit mode and show all Columns for Edition .Attached is the document with screen print results ...
[Issue 366.docx](https://github.com/NCIEVS/nci-protege5/files/2040584/Issue.366.docx)
