### ISSUE TITLE
support for imports from the server

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#367]
Tying an import to a repository as is done with file-based projects.

Begin investigating in 2.4.0

**Comment by NCIEVS** [comment]
We'd need the permission structure to be applicable to the imports as well.  For instance, workflow modeler A can read/write to import X, but workflow modeler B can only read import X (and maybe workflow modeler C cannot see import X at all).

**Comment by NCIEVS** [comment]
Might be a major item.  Might need to be deferred.  Leave it for last in this cycle or for O&M.

**Comment by bdionne** [comment]
same as #371
