### ISSUE TITLE
Investigate OWL API upgrade

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#368]
try newest api to see if it improves memory

**Comment by bdionne** [comment]
Made some good progress, but this is too major to include in the 9/1 release:

- ported our latest non-osgi version of protege to use OWL API 5.1.6, making use of earlier work by [Galigator](https://github.com/Galigator). Protege works fine on file base OWL files.

 - started work on plugins and the first obstacle is binaryowl, which is still at 4.2.8 This looks to need some major changes in order to migrate to 5.1.6

**Comment by bdionne** [comment]
This ready for testing with the 3.0.0-dev tag

**Comment by singhik** [comment]
This requirement was tested as part of Regression Execution with 3.0.0 client build. Regression Execution has been concluded with no major deviations in functionality, hence closing this ticket ....
