### ISSUE TITLE
CSV Exporter - escape characters

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#37]
file and property value delimiters inside property values need escaping

**Comment by NCIEVS** [comment]
from the [spec](https://tools.ietf.org/html/rfc7159):

   The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks, except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using tag 116, edit tab - 0.3.1.  When the entity has double quotes (“ “) as a value, the CSV export report shows as single (‘).  In this case, do you expect single quote or double quotes? Meanwhile, please see attached zip file to see the screen shots and csv export report for more details. 
Thanks,
Reza

[lucene-export-37.zip](https://github.com/NCIEVS/nci-protege5/files/705416/lucene-export-37.zip)

**Comment by bdionne** [comment]
Yes, when field delimiters and/or property value delimiters occur in the values themselves they will be escaped. 
It's a good idea to use the "\t" key for the field delimiter (this is the default in newer builds) as MS eXcel use the "," to separate cells.

**Comment by rmehri** [comment]
Thanks for your feedback! 
Reza
