### ISSUE TITLE
Support for imported ontologies

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#371]

**Comment by bdionne** [comment]
Here are some notes from @NCIEVS describing the 3 use cases we want to support with the enhanced imports

[imports.pdf](https://github.com/NCIEVS/nci-protege5/files/4105364/imports.pdf)

**Comment by bdionne** [comment]
Some test files

[SmallGeneExample.zip](https://github.com/NCIEVS/nci-protege5/files/4483505/SmallGeneExample.zip)

**Comment by NCIEVS** [comment]
Recent NCIt (with local edits) derived from a recent snapshot for some of the testing scenarios:
  [ncit-20200205.owl.zip](https://cbiit-download.nci.nih.gov/evs/Protege/TestVocabularyData/Thesaurus-snapshot-20200205.owl-v2.zip)

A vocab for testing imports, contains nested imports:
  [ro.owl.zip](https://github.com/NCIEVS/nci-protege5/files/4483572/ro.owl.zip)

**Comment by singhik** [comment]
@NCIEVS  : Hello,  Please review below Use Cases and provide any amendment or addition. Also, have few queries needing your input .

**SCENARIOS (USE CASE 1) ::**

>> 'Active Ontology->Direct Import' an EXTERNAL VOCAB(f.e. NS2) in Protege Client .
   Imported Concepts from the EXTERNAL VOCAB(NS2) in Project Hiearchy at NCI EDIT Tab should 
   be listed and non-editable for all operations . 
   Lucene Search should work for the concepts of the EXTERNAL VOCABs(NS2). 
   Concepts(NS1) in Project Hiearchy at NCI EDIT Tab should also be present and editable as BAU .
   Re-Login of Client to the same Project should still show the Imported VOCAB's Concepts(NS2) .   
   Concepts created/present in NS1 should be able to associate as Children of Concepts in 
   EXTERNAL VOCAB(NS2) as Parents .
   Concepts created/present in NS1 should be able to associate with ROles of Concepts in EXTERNAL 
   VOCABS(NS2) .
   Concepts present in EXTERNAL VOCAB (NS2) should  NOT be able to associate as Children of 
   Concepts in NS1 as Parents .
   Concepts present in NS2 should NOT be able to associate with Roles of Concepts in NS1 .
   Each and every time NS1 is Exported , the Concepts of EXTERNAL VOCAB(NS2),their IRIs and other 
   information should also get Exported .
   Navigation Bar for Project should show the stand-alone EXTERNAL VOCAB's(NS2) URL/Location in 
   the Drop Down List. 
   Stand-alone Project of the EXTERNAL VOCAB, when selected from the Navigation Bar, should also 
   be non-editable for all operations.

**SCENARIOS (USE CASE 2) ::**

>> 'Active Ontology->Direct Import' an INTERNAL VOCABS(f.e. NS2) in Protege Client.
   Imported Concepts from the INTERNAL VOCAB(NS2) in Project Hiearchy at NCI EDIT Tab should 
   be listed and editable for all operations . 
   Lucene Search should work for the concepts of the INTERNAL VOCABs(NS2). 
   Concepts(NS1) in Project Hiearchy at NCI EDIT Tab should also be present and editable as BAU .
   Re-Login of Client to the same Project should still show the Imported VOCAB's Concepts(NS2) .    
   Concepts created/present in NS1 should be able to associate as Children of Concepts in 
   INTERNAL VOCAB(NS2) as Parents .
   Concepts created/present in NS1 should be able to associate with ROles of Concepts in INTERNAL 
   VOCABS(NS2) .
   Concepts present in INTERNAL VOCAB (NS2) should  ALSO  be able to associate as Children of 
   Concepts in NS1 as Parents .
   Concepts present in INTERNAL VOCAB (NS2) should ALSO be able to associate with Roles of 
   Concepts in NS1 .
   Each and every time NS1 is Exported , the Concepts of INTERNAL VOCAB(NS2),their IRIs and other 
   information should also get Exported .
   Navigation Bar for Project should show the stand-alone INTERNAL VOCAB's(NS2) URL/Location in 
   the Drop Down List. 
   Stand-alone Project of the INTERNAL VOCAB, when selected from the Navigation Bar, should also 
   be Editable for all operations.

**QUERIES ::**

Question 1. How many Namespaces can be imported ?
Question 2. Which 'Export' are we referring to , Export of entire Tab as an OWL File via 'Window'- 
                    >'Export Current Tab' ?
Question 3. NS2 is imported and is non-editable, so when NS3 is imported, how can NS2 refer to 
                   NS3 as NS2 is non-editable ?

**Comment by singhik** [comment]
@NCIEVS @bdionne  :: Hello, 

A> Scope of 3.3.0 Protege is  Use Case 1 and Use Case 2 only .
B> Export Feature to Export other Concept Details alongwith IRIs is scoped for Future Releases, for 
      3.3.0 ,Export Feature is only for IRIs for imported Name Spaces .
C> Have updated above comments from our discussion to change 2.7 and 2.8 i.e. to not allow Any Edits of INTERNAL VOCAB(NS2) while the Navigation Panel URL is pointing to Existing NAMESPACE(NS1), changes are only allowed when the Navigation Panel URL is pointing to INTERNAL VOCAB(NS2) URL .
D> Have updated the queries with answers as discussed .

**Comment by NCIEVS** [comment]
@singhik Thanks!

**Comment by bdionne** [comment]
@singhik , @NCIEVS , sorry perhaps I missed this part of the chat but:

> B> Export Feature to Export other Concept Details alongwith IRIs is scoped for Future Releases, for
3.3.0 ,Export Feature is only for IRIs for imported Name Spaces .

This works. The import statements and any other edits you do where objects in NS1 refer to objects in NS2 will be in the exported OWL file. For example `NS1:foo subclassOf NS2:bar` will show up in the export.

**Comment by safrant** [comment]
I imported the 3 project above(20200205, ro.owl,ro-merged-clean.owl) into Protege on Dev using the Server Administration GUI.  I notice that "namespace" is not an option in the "Edit Project" dialog.  I need to manually add it to the JSON.  Could we please have the namespace added?  For extra special sauce, could the dialog display all namespaces available from the owl header so I can pick one?

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, In the initial Dry run for the Use Case 1, have noticed few failures and questions .... Document attached has the details . 

**Failures ::**

1.1 Imported Concepts from the EXTERNAL VOCAB(NS2) in Project Hiearchy at NCI EDIT Tab
should be listed and non-editable for all operations .

1.7 Concepts present in EXTERNAL VOCAB (NS2) should NOT be able to associate as Children of
Concepts in NS1 as Parents .

1.11 Stand-alone Project of the EXTERNAL VOCAB, when selected from the Navigation Bar, should
also be non-editable for all operations.

Adhoc> Unable to see 'Code' and 'Preferred Name' of the External 'Imported Ontology' , both when URL is pointing to External Imported Ontology and when URL is pointing to existing Ontology NameSpace.


**Questions ::**

>“Lucene Search” works for imported Concepts only when the URL is pointing to the ‘Imported         Ontology Name Space' , it does not work when the URL is pointing to Original Existing  NameSpace    Ontology , Expected ? (I think so as per Lucene Search Tab behaviour but  need to second )?

>When 'Imported External Ontology'  is Selected in the URL Drop Down , I still do not see it’s Complex Properties ? Is it Expected ?


[Issue 371.docx](https://github.com/NCIEVS/nci-protege5/files/4512450/Issue.371.docx)

**Comment by bdionne** [comment]
Thanks @singhik  

Many of these errors make sense to me,we’ll look into them. @safrant or @NCIEVS  would be possible to get a copy of the server configuration? I’d like to see what permissions the different logins have set up.

Also , @singhik which user did you login as? For 1.11 which user was logged in when you switched to the NS2 in the navigation bar?

Thanks,

Bob

**Comment by singhik** [comment]
@bdionne : Hi, i used 'SinghAdmin' as the user which was 'WorkFlow Manager' for NS1 and 'Guest' for NS2. Document attached has the screen prints of the NameSpace Ontologies with User/Access .

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hello, based on today's conversation, i have added three scenarios for each Use Cases above ,namely 1.12,1.13,1.14 and 2.12,2.13,2.14 ....

**Comment by singhik** [comment]
@bdionne @safrant : Hi, NCI Edit Plug-In 1.10 is throwing issues ::

When the stand-alone imported Vocab(NS2) is selected from URL and again the NS1 URL is selected, Imported NS2  gets removed from Active Ontology tab .

![image](https://user-images.githubusercontent.com/36314371/80258722-e921c980-8651-11ea-9f75-d16fca3e3dd5.png)

![image](https://user-images.githubusercontent.com/36314371/80258735-f0e16e00-8651-11ea-970f-043d48a8cd21.png)

![image](https://user-images.githubusercontent.com/36314371/80258773-0787c500-8652-11ea-9d6f-ea3dad9d651a.png)

Imported Vocab (ro.owl) got removed from Name Space 1 and Active Ontology ::

![image](https://user-images.githubusercontent.com/36314371/80258830-28e8b100-8652-11ea-928a-6a2b888eca24.png)

![image](https://user-images.githubusercontent.com/36314371/80258835-2ede9200-8652-11ea-9b09-1f76c59f5ea2.png)

**Comment by bdionne** [comment]
@singhik , @safrant , the 1.1.0 EditTab plugin requires the new 3.3.0-qa2 tag, are you using that?

The one way I can see this happening is if you switch ontologies after importing but forget to commit the import change. If that heppened you'd be asked if you really want to proceed and it would roll back the import.

I'll try to reproduce this

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, Did a Dry Run of Use Case 1 on 3.3.0-qa2 on QA Server .

Imported External Vocab(ro.owl) automatically **gets deleted** when URL is changed from NS1 Vocab to Imported External Vocab  ::



![image](https://user-images.githubusercontent.com/36314371/80414883-b836d400-889f-11ea-9e40-086fee7ac1c3.png)

![image](https://user-images.githubusercontent.com/36314371/80414911-c1c03c00-889f-11ea-92f3-9d87bf7d93d0.png)

Without changing anything in Existing NS1 Vocab, Protege throws message to save 'pending changes' ??

![image](https://user-images.githubusercontent.com/36314371/80414972-d4d30c00-889f-11ea-86c1-1fa4e9ef580e.png)

![image](https://user-images.githubusercontent.com/36314371/80415229-3bf0c080-88a0-11ea-8cc7-25bac4a146e7.png)

Navigating back to NS1, imported Vocab (ro.owl) gets DELETED auto :  ISSUE

![image](https://user-images.githubusercontent.com/36314371/80415312-617dca00-88a0-11ea-9707-30c7eb346874.png)


![image](https://user-images.githubusercontent.com/36314371/80415333-680c4180-88a0-11ea-9bb0-e94aea2ca0d4.png)

**Comment by bdionne** [comment]
@singhik This is the correct behavior. The warning message will occur whenever you try to switch ontologies when there are changes pending. If you were to look under `server/show uncommitted changes` you would see a change pending. In this case the change is the initial import. You need to manually commit that before switching.

When you proceed to switch anyway it will undo your changes, in this case the import. We can go over this tomorrow. The idea is to prevent the user from making edits in one ontology and then switching to another.

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, Thus far with the Testing of Use Case 2 for Import of Internal Vocabs, i have found one Issue w.r.t Export of NameSpace, below are the screen prints ::


![image](https://user-images.githubusercontent.com/36314371/80746921-a13af080-8af0-11ea-8a81-b42ae22ea300.png)

![image](https://user-images.githubusercontent.com/36314371/80746946-a9932b80-8af0-11ea-820f-24f7780d6ea0.png)

![image](https://user-images.githubusercontent.com/36314371/80746999-b748b100-8af0-11ea-9ef1-4231009b18f2.png)

![image](https://user-images.githubusercontent.com/36314371/80747022-c16aaf80-8af0-11ea-9255-e68ec1d725f1.png)

**Imported NameSpace for 'SmallNotGene' post commit as 'NS1_IMPORT_INTERNAL' when downloaded is not showing Concept details of NS2 'Small Gene' --- ISSUE** 

![image](https://user-images.githubusercontent.com/36314371/80747320-435ad880-8af1-11ea-8ee8-c990ed5788a9.png)


![image](https://user-images.githubusercontent.com/36314371/80747336-49e95000-8af1-11ea-955b-f8c3e6800917.png)

**Comment by singhik** [comment]
@NCIEVS :: Hello, I have completed the Use Case 1 and Use Case 2 Execution as per above descriptive Scenarios .  I have been updating above scenarios for all the discussions we had for Expectations . 

Requesting for your kind review from 1.1 to 1.14 (Use Case 1) and 2.1 to 2.14(Use Case 2) for any deviations from Expected , any amendments or addition of Scenarios if applicable .

**Comment by NCIEVS** [comment]
Hi @singhik , I've reviewed the use case scenarios 1.1 to 1.14 and 2.1 to 2.14.  The look good.

**Comment by singhik** [comment]
@NCIEVS : Thank you . Will close the ticket .
