### ISSUE TITLE
Improve performance and memory usage

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#372]

**Comment by bdionne** [comment]
This kind of task can be done opportunistically

**Comment by bdionne** [comment]
This enhancement is a major goal in the [2023-2024 roadmap](https://github.com/NCIEVS/nci-protege5/wiki/2023-2024-roadmap#scalability)

**Comment by bdionne** [comment]
Rework of the SPARQL query plugin should see improvements as the triple store is no longer in memory.

Please not any improvements here, but let's leave this ticket open for subsequent releases

**Comment by singhik** [comment]
CLosed as no Performance issues were noted in 4.4.0 Milestone Release
