### ISSUE TITLE
resizing the height of table cells on a change of fonts require restart on Windows (Original Ticket #74)

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#374]
Hi,  
      When font size is changed, the Complex Property font does not change until Protege client is restarted on Windows machines, Mac OS apparently changes without restart of protege client .
This ticket has originated from 'https://github.com/NCIEVS/nci-protege5/issues/74' 

Screenprint showing change in font size for only 'Value' Column before restart ::

![image](https://user-images.githubusercontent.com/36314371/38104012-f9be6c18-3355-11e8-923a-57363bff7997.png)

Screenprint showing, change in font size post restart  with cropped Complex property header name ::

![image](https://user-images.githubusercontent.com/36314371/38111002-7a14fa7a-336b-11e8-861a-09f2eb999c31.png)

**Comment by singhik** [comment]
Working as Expected in Protege Client 3.0.0 hence closed ....

**Comment by bdionne** [comment]
More inconsistencies with font changes:

> The current Renderer font size adjustment does not affect all the fonts in the GUI. I set mine to 14 (default is 12) and only the menu items and complex property values are at 14 pt. Qualifiers, hierarchy, restrictions and simple properties are not affected by the font size adjustment

**Comment by bdionne** [comment]
see #74
