### ISSUE TITLE
Term-source and term-group required for edit tab 0.80

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#375]
I loaded the 18.03d export from Thesaurus Production onto Dev and got this error.  In the edit tab 0.8.0 these qualifiers are not appearing.  

![term-source](https://user-images.githubusercontent.com/2364871/38568828-ac6a7ec8-3cb7-11e8-9e29-2fedd7da0459.jpeg)

![noqual](https://user-images.githubusercontent.com/2364871/38568968-093476f4-3cb8-11e8-8993-d82972f39806.jpeg)

**Comment by bdionne** [comment]
That message can appear if the properties don't exist in the content, or if the wrong version (by code versus by name) is specified in the config.

I can't think of what change may have impacted this. @safrant - could you make the content you loaded available (you can attach to this ticket) and the protege server config? I can try to reproduce here

**Comment by safrant** [comment]
The error was in the metaproject.  The template project on Dev has term-source and term-group rather than P384 and P384 specified in the qualifiers for P90 (FULL-SYN).  I have corrected this and the error no longer appears, but I still cannot see these qualifiers on the NCI Edit Tab.

**Comment by safrant** [comment]
Oh, for...  OK found the issue.  I had grabbed the transmorgrified file with the term-source and term-group in their byCode form.  I guess protege still can't handle that and needs the by-name.

**Comment by bdionne** [comment]
It can handle it, I think we made a deliberate decision to retrieve entities using their IRIs
