### ISSUE TITLE
App doesn't exit when closing from the 'close' button in the window frame

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#378]
...Protege continues running in the background and tries to update from the server, at which point it displays a notification gui with an "update error" title (the dialog itself is not painted).  The only way to exit at this point is with ^C on the terminal.

If on the other hand, the user logs out of the server first and then File->Exit, protege exits cleanly.  So it seems that the 'close' button is not following the same exit path.

**Comment by bdionne** [comment]
This relates to the `.fileprefs` corruption issue and I believe will be fixed in this next release

**Comment by singhik** [comment]
QA has validated closing operation from Protege Client Console 'X' button , which closes and Exits Protege successfully, without waiting or seeking updates from the Server. This validation has been performed multiple times and remotely  thus closing the ticket ...
