### ISSUE TITLE
CSV Exporter - JSON values need to adhere to spec

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#38]

**Comment by NCIEVS** [comment]
spec at https://tools.ietf.org/html/rfc7159

**Comment by bdionne** [comment]
ok, so the quotes showing up in the spreadsheets for the `JSON` objects are fine. This is good in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107).

**Comment by rmehri** [comment]
Based on the following fix description, I have retested this issue by exporting series of classes and see the codes in the spreadsheets.  
fix description: 
- fixed type in csv-export dialog (File is now Field)

This ticket can be closed. Please see attached snapshot for more detail.
Thanks,
Reza

![export to csv](https://cloud.githubusercontent.com/assets/8367102/21084098/ebb286e4-bfcb-11e6-9a69-27e0183dfc47.png)
