### ISSUE TITLE
evs history plugin exceptions in stage

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#381]
The latest vocab in stage has an evs_history file, but because the vocab hasn't been edited (and history files haven't been copied) there are no history entries in evs_history.  On a query from the "evs history" plugin the client throws exceptions and after a couple of these the client stops responding.  It might be that the plugin doesn't deal very well with this edge case, but it would be good to confirm (and fix).

**Comment by bdionne** [comment]
This is likely a null pointer problem, the description is a little confusing though, unless some other process puts it there, there should never be an `evs_history` file.

When history is recorded, it's written to `current_evs_history` and `evs_history` at the same time. This makes archiving a copy operation

**Comment by NCIEVS** [comment]
Yes, you are right.  I was looking at the wrong filename, there is no evs_history file in there.

**Comment by singhik** [comment]
@NCIEVS :: Hello , Until what  time in history  can we Search  EVS History tag for ?  As when i search from Feb 2018 till Date for me, it does not return any past data created except for this Month (July 2018) ::

![image](https://user-images.githubusercontent.com/36314371/42580993-ca537c48-84f9-11e8-8019-457b63e0587a.png)

**Comment by NCIEVS** [comment]
It should go back to the "beginning" of time.  But QA's history probably doesn't extend that long.  Perhaps one of the prod backups could be copied to QA.

**Comment by singhik** [comment]
@NCIEVS : Hi, yeah i would need it  else won't be able to apply history Use Cases for EVS History Search , who do you think can help me do that in QA Env ?

**Comment by NCIEVS** [comment]
@safrant should be able to give you a hand with this.  She has access to the backup histories.

**Comment by safrant** [comment]
I can move the ncitevs_history from the last baseline (June 25) and the history and history-snapshot from that same day.  However, in the local history folder there are ~history and history-snapshot-checksum.  Should I just delete those and expect the server to recreate?

**Comment by NCIEVS** [comment]
No, the snapshots are the actual vocabulary.  Just copy the evs_history, and cumulative_evs_history files (I don't remember if these are the right names).

**Comment by safrant** [comment]
OK, files have been copied over.  Please take a look.  They are from the last baseline, so run up to 6.25.2018

**Comment by singhik** [comment]
@safrant : Hi Tracy, i ran an EVS Search from 6.25.2018 to 7.11.2018 , i only see search results returned for 6.25.2018 and not for any other day, including the ones which i did today and day before ? 


![image](https://user-images.githubusercontent.com/36314371/42587611-40728bd0-8509-11e8-867b-c06a2e08e0e9.png)

**Comment by NCIEVS** [comment]
Because the history files were overwritten, you won't see edits that you've done prior to the qa history being replaced w prod.  Any new edits that you do should show up though.

**Comment by singhik** [comment]
@NCIEVS: Hi, thanks , i was thinking the files will get cumulatively added instead of getting overwritten, will try few edits for couple of days and will wait until concept creation issue #391 is resolved, will then Execute this ticket ...

**Comment by singhik** [comment]
@NCIEVS ::  EVS History Search was Executed via simulating  the files from prod back up and performing a Search on old data from 2004 until today (new changes performed this week) . The EVS History Search does show up old data from 2004 and the new data as well .Multiple search criterias were used including Start Date,End Date, Username, Operation. It is practically not possible to conclude that all the old data is shown in entirety but using Boundary Value Analysis, it does show year wise data and all the new data as well ...

This ticket can only be in best proximity be assumed to work for old dates from above Regression in QA. Screen prints are not attached due to name confidentiality. 
Please share your feedback on the same .....

**Comment by NCIEVS** [comment]
@singhik , I'd say approve as it passes the various tests.
