### ISSUE TITLE
restrict set of (qualifier) properties displayed when exporting complex properties in the report writer

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#383]
from [TQ]:
"If possible, what would be dreamy is that when you choose to export items like a complex property, it would be nice if when you clicked the wee @ is that only the appropriate options would show up. In this case, only the pieces of data that are in the FULL_SYN property."
from [EHD]:
"So if you want to include FULL_SYN in your export the @ to choose qualifiers would include Source Code, Subsource Name, Term Source and Term Type."

**Comment by bdionne** [comment]
@NCIEVS - I think this is a dup of #273 ?

**Comment by NCIEVS** [comment]
Oh yes.  Closing as dup.
