### ISSUE TITLE
copying to clipboard from the sparql plugin grid throws exception

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#385]
If a query (with "optional") results in some empty cells, the cell data can't be copy-pasted out of the grid.  Protege throws a null pointer exception (non-fatal).  Workaround for now is to always output something even if it's a quoted empty string.

**Comment by safrant** [comment]
Is 2.4.0 the tag?  I can start working on it now

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by singhik** [comment]
QA has verified Export and Clipboard of SPARQL Query with Optional Clause having empty cells, do not result in an Exception and are allowed to be copied pasted as well as Exported. Attached is the document with screen prints ....

[Issue 385.docx](https://github.com/NCIEVS/nci-protege5/files/2054279/Issue.385.docx)
