### ISSUE TITLE
Invalid code assigned during concept-create following loss of connection to server

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#386]
Modified from [EHD, 5/3/18].  
"[AG] was saving a concept and apparently lost connection during the create of a new concept. He got the following message in a popup:Session expired needs login credentials. But he was able to give his credentials and perform additional editing."  However, the concept saved without an NCIt code, it was assigned a GUID.

"I needed to delete this term, so [AG] could create it again" with a valid NCIt code. 

"it would be good if [losing] connection during a new concept create failed rather than giving a non-valid code or if the Save function in the Edit tab could prompt the user to Cancel since the code was invalid, which would prevent saving/editing of a concept without a vaild code."

PS  concept_history needs to be massaged afterwards to eliminate the bad code.

**Comment by bdionne** [comment]
Was this with the new client install? Or was this an old client left opened that then was forced to reconnect to a new server due to the upgrade. You wouldn't be forced to reconnect until the first request to the server, which in this case would be to fetch the code

**Comment by NCIEVS** [comment]
No, this was with the v2.3.0 version from about a month ago.  The initial report was from May 5th or so, I've been on meetings though so hadn't had put in the ticket. It happened during "normal" operations, not related to a software update (at least not a release, maybe there was a plugin update on that day?).  It came to the forefront because of the "bad" code in concept_history.  

According to [EHD], this happened again maybe last week so we'll see it again in concept_history in the next baseline.

**Comment by singhik** [comment]
QA has validated creation of concept  does **NOT** get completed when the server gets disconnected in between the process. A Warning dialog prompt is thrown to the user stating '**Code can't be generated for this class, see sysadmin**'  and the operation fails as Expected.
