### ISSUE TITLE
lucene search fails with bad listener

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#387]
From [TQ, 6/4/18].
"I have done a simple search for full syn contains Terminology Subset and it just keeps searching without returning results."

"There is a bad listener in here…. Is that relevant?"

Snippet of console output with the listener exception is below:

Loaded ontology, now updating from server
[34mClientSessionChangeEvent: org.protege.editor.owl.client.event.ClientSessionChangeEvent@7c3de2c7[0;39m
[34mInstantiating node LuceneIndexPreferences[0;39m
[34mInstantiating node KEY:ecd96c9c-1faa-40b6-a69f-912a54d1d3b1[0;39m
**[31mException thrown by listener: edu.stanford.protege.search.lucene.tab.engine.SearchTabManager$$Lambda$45/1208043143.  Detatching bad listener.[0;39m**
[34mClientSessionChangeEvent: org.protege.editor.owl.client.event.ClientSessionChangeEvent@1a3bcb81[0;39m
Voila

**Comment by NCIEVS** [comment]
Subsequent note from [TQ]:
"I tossed the version I was using and did a fresh install of the last version and the issue was solved. It was not solved by reindexing."

The snippet below shows her plugin components in the v2.3.0 distribution:
Plugin: EVS History Plugin (1.0.1.SNAPSHOT)
Plugin: Lucene Search Tab (1.1.3.SNAPSHOT)
Plugin: metaproject (1.0.0.SNAPSHOT)
Plugin: Metaproject Admin (1.0.1.SNAPSHOT)
Plugin: Edit Tab (0.8.4.SNAPSHOT)
Plugin: SPARQL Query Plugin (2.0.7.SNAPSHOT)
Plugin: Pellet :: Protege (2.4.0.SNAPSHOT)
Plugin: Protege Client (3.0.0.SNAPSHOT)
Plugin: Protege Server (3.0.0.SNAPSHOT)
Plugin: Prompt (1.0.6.SNAPSHOT)

**Comment by bdionne** [comment]
Is this after a new install? Could be related to changes that affect date in the `.fileprefs` file. I suspect maybe it can't open the search indices so all queries would fail?

**Comment by NCIEVS** [comment]
No, this was with the v2.3.0 installation from about a month ago.  But some of the plugins listed above are pretty recent.

{[TS] didn't get v2.4.0 deployed so we'll be on 2.3.0 for a few more days.}

**Comment by NCIEVS** [comment]
Potentially for 2.6.0, take a look.

**Comment by singhik** [comment]
Retested on 3.5.0-qa1 build, works as Expected hence closing the ticket .
