### ISSUE TITLE
request to notify user when sparql query finishes execution

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#388]
From [EHD]:
" If no results are returned there should be some sort of notification. Currently only a blank table is displayed and the editor may not realize that the query is complete."

"A popup would be my preference but I am not opposed to the other options if a popup is too difficult for some reason."  {The other option mentioned:  enabling/disabling the "execute" button.}

**Comment by bdionne** [comment]
make the button more visible when in the execution phase

**Comment by bdionne** [comment]
Unable to modify the button in the action handler so instead we added an empty results so if a query completes with no results, "NO RESULTS FOUND" appears in the panel instead of just a blank page

**Comment by NCIEVS** [comment]
I think this will do the trick.

**Comment by singhik** [comment]
Tested and an Empty query does show the verbiage "NO RESULTS FOUND !!!" in the results panel , indicating the query did not fetch any results as expected, hence closing the enhancement ...

![image](https://user-images.githubusercontent.com/36314371/50996581-4a229e00-14f0-11e9-9d93-6d5b9ae5b0db.png)
