### ISSUE TITLE
request to alter the bookmarking functionality of the sparql tab

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#389]
From [EHD]:
".. creating a new bookmarked query is not straightforward. If you select NewQuery and add a query and then hit the Bookmark button, the user is prompted to give the Bookmark a name but, the query language is not saved to the new name until you insert the query statement into the box on the top right again. It appears that the NewQuery option is just for test queries or temporary queries. The workflow to save a query is to hit the Bookmark button, give the new Bookmark a name and then put the query statement in the box. This wasn’t obvious from the introductory session. This should be documented somewhere."

[GF}:  " it should be feasible to bookmark (with a new name) any query already in there"

**Comment by bdionne** [comment]
> [GF}: " it should be feasible to bookmark (with a new name) any query already in there"

You can do that now, just select the query and click bookmark, enter a name and a new file will be written

**Comment by NCIEVS** [comment]
Documentation page created in the wiki as ["Bookmarking sparql queries"](https://github.com/NCIEVS/nci-protege5/wiki/Bookmarking-sparql-queries).  Ticket closed.
