### ISSUE TITLE
identify the definition property in the metaproject

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#393]
In order to support adding definitions to concepts from dedicated widgets there should be a key for the definition property in the metaproject, see #166.

**Comment by NCIEVS** [comment]
Let's use `definition` for the metaproject property

**Comment by safrant** [comment]
Property added to both projects in Stage 

        "definition": [
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97"
        ],

**Comment by NCIEVS** [comment]
@singhik , yes, agreed, can be closed.
