### ISSUE TITLE
ReportWriter Export Using LQT shows  'Definition Source' as striked out for 'ALT_DEFINITION' and DEFINITION complex properties

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#394]
Navigate to 'NCI Edit Tab'-> 'ReportWriter'   Tab .
Select 'Configure' and 'Export using LQT' option .
Select 'Properties' button and Choose 'ALT_DEFINITION' or 'DEFINITION' property .
Now add 'annotations' using @ button and check for 'Definition Source' annotation.

Expected: It should appear as normal text of 'Definition Source'without striked out .
Actual: "Definition Source' is displayed as striked out ..

![image](https://user-images.githubusercontent.com/36314371/42774917-05c149ee-8901-11e8-8b5f-68cb57f88667.png)

**Comment by bdionne** [comment]
This is going to be a more difficult fix. The `OWLCellRenderer` and `InqQualRenderers` both make a call to look up an entity based solely on a token, in this case `Definition Source`. Eventually this [low level function](https://github.com/NCIEVS/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/model/cache/OWLEntityRenderingCacheImpl.java#L168-L196) is called which tries to find the entity, first checking for classes, then properties, etc.. So when we have both a class and property of the same name confusion arises. 

Not sure how to fix this yet, as the renderers have no knowledge of these tokens at that level. Will look into it further. This is better than it used to be, I suspect someone probably changed the order in the function.

**Comment by NCIEVS** [comment]
Hi @bdionne , yes, I thought the strike-through issue would be low level so this ticket is set for future release.

**Comment by singhik** [comment]
Issue retested and closed in 3.0.0 Protege Client build
