### ISSUE TITLE
Replace term-group and term-source with byCode

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#395]
Business rules in Protege require us to leave some qualifier-type properties with their byName IRI.  We would like to change this to use the byCode wherever possible.

P383 term-group
P384 term-source

**Comment by safrant** [comment]
NCIEditTab.java

    private boolean isQualsPTNCI(OWLAnnotationAssertionAxiom ax) {
    	return ((getAnnotationValue(ax, "term-group").equals("PT") ||
				getAnnotationValue(ax, "term-group").equals("AQ") ||
				getAnnotationValue(ax, "term-group").equals("HD")) &&
				getAnnotationValue(ax, "term-source").equals("NCI"));
    	
    }

    public boolean isNCIPtFullSyn(String prop_iri, Map<String, String> qualifiers) {
    	OWLAnnotationProperty p = lookUpShort(prop_iri);
    	boolean isIt = false;
    	if (p.equals(getFullSyn())) {
    		String tg = qualifiers.get("term-group");
    		String ts = qualifiers.get("term-source");
    		if (tg != null &&
    				ts != null &&
    				(tg.equals("PT") ||
    						tg.equals("AQ") ||
    						tg.equals("HD"))
    						&&
    				ts.equals("NCI")) {
    			isIt = true;
    		}
    	}
    	return isIt;
    }

**Comment by bdionne** [comment]
Goal in this ticket is to be able to use EditTab with no business rules

**Comment by bdionne** [comment]
need tp specify config file changes to support this

**Comment by NCIEVS** [comment]
use the following keys:
syn_type - the property IRI replacing the hardcoded term-group
syn_source - the property IRI replacing the hardcoded term-source

cc @safrant

**Comment by safrant** [comment]
These setting have been added to the Dev server SmallbaseSample and SmallBaseByName

**Comment by bdionne** [comment]
@NCIEVS @safrant I think we also need one for `def-source` ?

**Comment by safrant** [comment]
The def-source has already been byCode, so is not a concern for processing.  If we are trying to remove all hard-coded values within the application then we should look at it.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
> The def-source has already been byCode, so is not a concern for processing.  If we are trying to remove all hard-coded values within the application then we should look at it.

Yea but we have a rule thet stipulates that there can be only one source of `NCI` in definitions, so the software needs to check that annpotation. Currently what the code does is look for `def-source` and if it can't find that it looks for `P378`, which is the code.

**Comment by safrant** [comment]
OK.  The “def-source” sounds like a good name for the property so I can add that to the dev server.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
> OK.  The “def-source” sounds like a good name for the property so I can add that to the dev server.

use `def_source`, `def-source` is the `byName` value in the `IRI`

**Comment by safrant** [comment]
OK

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, This ticket is NA for QA , as is related to configuration file change at server level and needs to be closed by @safrant  .  QA can perform Regression on a Project which is configured to use byCode .

**Comment by safrant** [comment]
I am seeing source-code twice in the FULL-SYN on NCI Edit Tab.  The syn_source is not there at all. 
[3.5-project-configuration.json.txt](https://github.com/NCIEVS/nci-protege5/files/5319827/3.5-project-configuration.json.txt)

**Comment by bdionne** [comment]
@safrant That config looks fine. I'm wondering if your fileprefs are stale and it's picking up columns from a `by_name` project? When you bring up an edit dialog to edit or add a new `FULL_SYN` do the correct quals show up?

I'll take a look. It looks fine here:

<img width="1016" alt="Screen Shot 2020-10-02 at 3 20 56 PM" src="https://user-images.githubusercontent.com/31741/94961724-3472ba80-04c3-11eb-8d20-c8b793f19019.png">

**Comment by safrant** [comment]
I do see the correct quals in the dialog, yes.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
hmm, that makes me suspect the fileprefs are stale. If you delete them you might see it go away.

I'll look into it as this will be a problem for folks who bounce around different projects

**Comment by safrant** [comment]
Yep, deleting the fileprefs worked.  That file is an unruly dog.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
> Yep, deleting the fileprefs worked.  That file is an unruly dog.

It is @safrant , I'm seeing it cause problems elsewhere. I've seen this writing of `/u0000` entries again, though I can't figure what scenario does it. Seems to be coming from the inference interfaces in protégé

**Comment by safrant** [comment]
Working as requested
