### ISSUE TITLE
Please update Protege to use the byCode version of Definition qualifiers

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#396]
Protege relies on the following properties to use the byName IRI.  Please update so we can use the byCode IRI.

Properties involved: 
P379 Definition_Reviewer_Name
P380 Definition_Review_Date

**Comment by bdionne** [comment]
Need to specify config file changes for this

**Comment by NCIEVS** [comment]
use the following keys:
reviewer_name - the property IRI replacing the hardcoded Definition_Reviewer_Name
review_date - the property IRI replacing the hardcoded Definition_Review_Date

cc @safrant

**Comment by safrant** [comment]
These setting have been added to the Dev server SmallbaseSample and SmallBaseByName

**Comment by bdionne** [comment]
Do these properties have `byCode` versions? If so what are the codes for them, I'd like to use them for testing.

Same question about `term-type` and `term-source` #395 

cc: @safrant @NCIEVS

**Comment by safrant** [comment]
review_date
[http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P380]
reviewer_name
[http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P379]
syn_source
[http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P384]
syn_type
[http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P383]

I have updated the SmallBaseSample on Dev to use these.

Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, This ticket is NA for QA , as is related to configuration file change at server level and needs to be closed by @safrant  .  QA can perform Regression on a Project which is configured to use byCode .

**Comment by safrant** [comment]
Working as requested

**Comment by bdionne** [comment]
This is not working:

 * navigate to any class that you are not the editor for
 * select a definition row in the complex prop table to edit
 * edit the row, notice that the reviewer name and date do not change to the current editor
 * save

**Comment by bdionne** [comment]
fixed in [edit-tab-1.2.1](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.1)

**Comment by safrant** [comment]
Closing as fixed
