### ISSUE TITLE
Creating Concepts with the same name are not allowed from Protege Client 2.5.0 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#397]
Creating concepts with the same name are **NOT** allowed ...
Sister ticket for Concept Creation new enhancement is @ #166

**Comment by NCIEVS** [comment]
There is a workaround for when concepts with duplicate PNs are absolutely necessary.  Create the concept with a different PN and afterwards rename it to the desired PN.  But disallowing the creation of the concept in the first place with a dup PN forces the editor to examine that concept to verify it really wouldn't be a duplicate.  Trying to avoid unnecessary merges and retirements down the line.
