### ISSUE TITLE
fileprefs corrupted

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#399]
Observed by [TQ] on several occassions.  Copying the fileprefs to a working instance of protege recapitulates TQ's issue.  Will not include the fileprefs in this ticket, refer to the email thread from 8/3/2018 (10:44 AM).  Unclear what causes the fileprefs to corrupt, TQ is remote so network lag and impatience clicking on buttons may play a role.

[Maybe related to app shutting down before writing the file out.]

**Comment by bdionne** [comment]
Adding this to the next release. I think this should be improved considerably with the non-osgi version and the bug is related to how the app is shutdown

**Comment by singhik** [comment]
@NCIEVS : Hello, How to specifically replicate copying of filePrefs to an Active instance of protege client and simulate corrupted files being induced , not sure if this is achievable as-is ? 
Can Testing #378 will suffice it's Test as well ?

**Comment by NCIEVS** [comment]
@singhik :  Sharing (via email) the corruped fileprefs file was so that @bdionne could see the issue.  But I don't think copying the corrupted file to a working instance will be a good test for QA.  Essentially the fix (or sets of fixes) have to do with preventing the corruption from taking place in the first place.  Once you have a bad fileprefs file (e.g. by copying) the GUI will not look right regardless of the software fix.

Maybe @bdionne can suggest some test?  Please note that the user in question is remote, so network lag and impatience clicking buttons may have played a role.  

However, if you want to see how the funky GUI looks like after the corruption has taken place, I can send you the file separately.  Don't post it to github though.  Let me know.

**Comment by singhik** [comment]
@NCIEVS : Hello, I agree,  as it would make sense to not induce a corrupted file into my fileprefs  rather trying to create the Environment resulting into the corruption to begin with . 
Remote login and network lag, can be taken care to some extent by running regression auto suite remotely . Not sure of any other way to simulate this one, will wait for input from @bdionne  if in case there is something else precisely that QA can simulate this one ....

**Comment by bdionne** [comment]
I'm not sure how Terri was seeing this, one thing I think was happening was when you had made changes to the column order or some other aspect that causes preferences to be written and then you closed the app. The property tables were coming up blank because the file had been corrupted. It was more a theory than a reproducible scenario, but we did change some code to try and prevent it from happening.

**Comment by singhik** [comment]
QA has **not** observed the issue of mis-alignment of Protege Client UI  while performing many Sanity Executions and re-ordering of columns . As this is more of a once in a while kind of an issue, which is not reproducible at-will and with regressive Executions, for now this ticket can be best assumed to be extremely intermittent and hence be closed ....
