### ISSUE TITLE
protege-client - autoupdate

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#40]
autoupdate enabled by default, interval configurable, 1 minute default

**Comment by NCIEVS** [comment]
Where is the interval configured?  If this is still in the queue, could lower priority for a future release.

**Comment by bdionne** [comment]
sorry, I had this on a local branch and hadn't merged, it's now in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107).

The property you need to set is:

`"autoupdate_interval": "60",`

**Comment by rmehri** [comment]
The auto update works fine on this server "https://nciws-d699-v.nci.nih.gov:9090".
In addition, the "server-configuration.json" file on my local server for tag 107 has been correctly setup.
"autoupdate_interval": "60"
This issue can be closed.
Thanks,
Reza
