### ISSUE TITLE
definition attribute cannot be set in class creation widget

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#401]
Maybe the text box to enter text has been set to read-only?

**Comment by singhik** [comment]
@bdionne : Hi Bob, the 'attribution' text field for 'Create a new OWLClass' is still a read-only text, not allowing or accepting any text to be input :: 

![image](https://user-images.githubusercontent.com/36314371/44798426-75c76c00-ab7f-11e8-9f73-fca368360769.png)

**Comment by bdionne** [comment]
Works fine here, are you running EdiTab 0.9.0? Maybe it's a config issue

<img width="1017" alt="screen shot 2018-08-29 at 11 54 56 am" src="https://user-images.githubusercontent.com/31741/44799996-529ebb80-ab83-11e8-93a4-e0da09f0b428.png">

**Comment by singhik** [comment]
@bdionne : Hi Bob, Yes, i changed the Auto Update Repo URL from CBIT to your Github repo and it shows NCI Edit Tab Plugin as 0.9.1, but it fails to Update the plugin ::

![image](https://user-images.githubusercontent.com/36314371/44800732-1f5d2c00-ab85-11e8-8b7e-3cadb91fc6a2.png)

![image](https://user-images.githubusercontent.com/36314371/44800750-27b56700-ab85-11e8-98c1-859cdd75e48c.png)

Logs ::

![image](https://user-images.githubusercontent.com/36314371/44800880-8bd82b00-ab85-11e8-91c9-a8cc49b4dd65.png)

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/2332904/Logs.txt)

**Comment by bdionne** [comment]
I see, I'll push the 0.9.1 jar, but @singhik it should also work for 0.9.0 if you are currently running that

**Comment by singhik** [comment]
@bdionne :Hi Bob, i don't see 0.9.0 as my current plugin version for Edit Tab, it shows as 0.8.8 and the next available plugin as 0.9.1.

**Comment by bdionne** [comment]
I see, yea that makes sense if you had last updated to 0.8.8 and 0.9.1 failed because there was no jar you never did an update wile 0.9.0 was there.. 

Anyway hopefully 0.9.1 will provide better results. Sorry for the confusion

**Comment by singhik** [comment]
@bdionne : Thanks Bob, it is working fine now, thought after Update the Edit Plugin was not overwritten with 0.9.1 but was still showing as 0.8.8,i manually went to 'plugins' folder and deleted Edit Plugin 0.8.8 and restarted Protege for it to get updated ....

**Comment by bdionne** [comment]
that’s strange I think, I will check it out and see what’s causing it. I don’t think it would leave the other in there. Thanks!
