### ISSUE TITLE
EVS History does not show 'RETIRE' concepts for the same day 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#405]
EVS History Tab does not return search results for 'RETIRE' operations performed for the same day, even after Indexing is complete :: 

Concept created and Retired :: Test_EVS_Retire 

![image](https://user-images.githubusercontent.com/36314371/45236883-28e44380-b2ab-11e8-9bf2-db997a9a9a71.png)

![image](https://user-images.githubusercontent.com/36314371/45236906-3ac5e680-b2ab-11e8-9448-901059d1fc14.png)

![image](https://user-images.githubusercontent.com/36314371/45236921-474a3f00-b2ab-11e8-829d-a5afd2c36013.png)

Doing Indexing manually :: 

![image](https://user-images.githubusercontent.com/36314371/45236995-7fea1880-b2ab-11e8-9580-5882166e4b85.png)

Doing EVS History Search for 'RETIRE' operation after indexing is complete , DOES NOT show concept details for 'Test_EVS_Retire' which was retired above : BUG 

![image](https://user-images.githubusercontent.com/36314371/45237077-b031b700-b2ab-11e8-9bdb-36ab96b9c5b9.png)

**Comment by bdionne** [comment]
Interesting, works fine for me. Are you sure the server is configure properly and are you able to retrieve any history?

cc: @safrant 

<img width="914" alt="screen shot 2018-09-07 at 2 45 59 pm" src="https://user-images.githubusercontent.com/31741/45237653-4fa37980-b2ad-11e8-8f8d-d73011ecd903.png">
<img width="922" alt="screen shot 2018-09-07 at 2 48 40 pm" src="https://user-images.githubusercontent.com/31741/45237654-4fa37980-b2ad-11e8-8452-90188af09f34.png">

**Comment by singhik** [comment]
@Bob: Hi Bob, if you select OPeration as "RETIRE" ,then it does not show up, with 'ALL' it does ....
We can have this scoped for future releases to investigate and conclude ....

**Comment by bdionne** [comment]
@singhik - maybe it's the calendar weirdness you also see. As you seen in the screenshot above when I set the start/end date to day, it finds it. In your case perhaps it never got written

**Comment by singhik** [comment]
@bdionne : Hi Bob, ok, cause i also thought the same and put my search criteria extended from Sep-7 till Sep-9 but i still was not able to . May be i am missing something. I will re-do this scenario next week as an item scoped for future releases ....

**Comment by bdionne** [comment]
sounds good - I have an idea of one possibility. We put in additional logic in the last release relating to allowing certain users (managers only) to delete classes after they've been retired, but only if the retirement was in the current monthly cycle, .ie. hasn't been exported yet. Perhaps there's an edge case there we missed.

I tried another also with success. We can look in the next round

<img width="919" alt="screen shot 2018-09-07 at 3 11 58 pm" src="https://user-images.githubusercontent.com/31741/45238724-d6a62100-b2b0-11e8-9f98-d546010b4b3c.png">

**Comment by singhik** [comment]
@NCIEVS : Hi, not sure why i am still able to reproduce the issue  on my end ::

Created and Retired Concept on 9/24/2018  :: Test_EVS_History

![image](https://user-images.githubusercontent.com/36314371/45958346-3ad12080-bfe5-11e8-9767-fdda66397e21.png)


Did Indexing Manually to ensure data synchronization and then did EVS History Search with RETIRE , not able to search the concept ::

![image](https://user-images.githubusercontent.com/36314371/45958428-6b18bf00-bfe5-11e8-9a1c-42b9e50ebe80.png)

However, CREATE operation does Return the EVS History Search Results for the same Concept ::

![image](https://user-images.githubusercontent.com/36314371/45958487-8b487e00-bfe5-11e8-941f-cd89b458615a.png)

**Comment by singhik** [comment]
@NCIEVS : Hi, Tried in DEV and still able to reproduce the issue ::

Created and Retired Concept on 9/24/2018 :: Test_EVS_DEV

![image](https://user-images.githubusercontent.com/36314371/45971911-471aa500-c008-11e8-99d5-b25a7540f100.png)


Did Indexing Manually to ensure data synchronization and then did EVS History Search with RETIRE , not able to search the concept ::

![image](https://user-images.githubusercontent.com/36314371/45971944-57328480-c008-11e8-8058-a2f411f14704.png)


However, CREATE operation does Return the EVS History Search Results for the same Concept ::

![image](https://user-images.githubusercontent.com/36314371/45971966-6a455480-c008-11e8-9d4d-049a8ed5c07c.png)

**Comment by bdionne** [comment]
odd, couple of simple questions as a sanity check:

After you retire did you hit save to make sure all the changes were committed?

Is the username specified in the search field the same as that from the login?

Does the user have manager privileges?

This should be an easy bug to track down, we can do a screen share and try. The first thing I'd check is the history file on the server to see if the record is getting in there. If it is than the issue would be in the `EVS History` plugin

**Comment by singhik** [comment]
@NCIEVS : Hi, yes , i am able to EVS search 'to_retire_on_creation_day' successfully against your id . 
@bdionne : Hi ,

After you retire did you hit save to make sure all the changes were committed? 
-- Yes and thats how i can EVS Search CREATE but not RETIRE .

Is the username specified in the search field the same as that from the login?
-- Yes, it's the default that comes up when EVS Search Tab is opened, i did not change it .

Does the user have manager privileges?
--SinghAdmin user i tried on QA Server has Workflow Manager Privileges and i am able to search NCIEVS's record as well with the same user.

**Comment by bdionne** [comment]
> On Sep 24, 2018, at 4:20 PM, NCIEVS <notifications@github.com> wrote:
> 
> In my hands this is working correctly, even if i do a retirement as manager and read the evs history as a modeler. Still, I couldn't see test retirements that @singhik made in DEV.

Were they in the file on the server?  Maybe tomorrow we can try to debug this

**Comment by NCIEVS** [comment]
Oh, no, the reference to @singhik 's retired class is not present on the file in the server.  The list below is all that's present in there from "singhik", the "create" from 9/24/18 is found, but not the "retire":

2018-07-30 11:16:08     singhik C150023 Test_QA CREATE
2018-07-30 13:20:58     singhik C150024 Test_QA_        CREATE
2018-07-30 13:23:09     singhik C150025 Test_QA_Clone   CREATE
2018-07-30 13:24:39     singhik C150025 Test_QA_Clone   DELETE
2018-07-30 14:38:13     singhik C150024 Test_QA_        DELETE
2018-07-31 10:50:46     singhik C150005 Test_Modeler_Role       RETIRE  C12913
2018-07-31 10:51:28     singhik C150026 Test_Role       CREATE
2018-07-31 10:51:55     singhik C150027 Test_Role_Mind  CREATE
2018-07-31 10:52:39     singhik C150028 Test_Role_Def   CREATE
2018-07-31 16:19:44     singhik C150027 Test_Role_Mind  DELETE
2018-07-31 16:19:49     singhik C150028 Test_Role_Def   DELETE
2018-07-31 16:19:55     singhik C150026 Test_Role       DELETE
2018-09-24 14:41:17     singhik C150134 Test_EVS_DEV    CREATE

**Comment by singhik** [comment]
This is an issue specific to Concepts created directly under 'owl:Thing' , Fix is specific to Edit Tab only and will be available in the next Update plug-in .

**Comment by singhik** [comment]
Retested in 3.0.0 Protege Client, works as expected, issue closed ....
