### ISSUE TITLE
protege-client - visibility of active ontology tab

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#41]
active ontology should be visible to modelers, read only and editable by managers

**Comment by NCIEVS** [comment]
this is the "active ontology" tab.

**Comment by bdionne** [comment]
[nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
I have retested this fix in tag-110 with the following roles:  
Workflow Modeler:    
a. Active Ontology not visible   ----> greyed out "Not fixed"
b.Two tabs (NCI Edit Tab & Lucene Search Tab) are visible only
 ------------------------------------------------- 
 Workflow Manager:    
 The following tabs are showing available:
 a. Active Ontology
 b. Entities
 c. Object Properties
 d. Annotation Properties
 e. NCI Edit Tab
 f. Lucene Search Tab
 g. Revision History

Please clarify if Workflow Modeler should see active ontology.  

Thanks,
Reza

**Comment by rmehri** [comment]
This fix has been retested and verified using tag-115.  Please see attached snapshot. 
Thanks,
Reza

![untitled](https://cloud.githubusercontent.com/assets/8367102/21651167/98442320-d275-11e6-82eb-be39742ac90c.png)
Leave a comment
