### ISSUE TITLE
Copy Operation Does Not Pre Populate Preferred Name and IRI 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#410]
Yesterday, Business was using the copy function to create a new concept. When she saved the concept for some reason even though a valid IRI with a code was assigned (C156880); however, the saved concept was missing the code, label and Preferred_Name properties. The code was in the Preferred_Name slot (first screen shot) and she could not edit it, probably because of the missing properties (error message popup in second screenshot). (It is not in the screenshot but the PT, 2 other FULL_SYN and the NCI DEF were present and looked fine.) 

 
![image](https://user-images.githubusercontent.com/36314371/49821275-106f4380-fd48-11e8-8a9e-7789a871d3f3.png)

![image](https://user-images.githubusercontent.com/36314371/49821312-30066c00-fd48-11e8-8f7c-59b783276aef.png)

 

I was able to add the code, label and Preferred_Name properties in the Entities tab to fix the concept. Hopefully, Business can add any other relevant details if I missed something.

**Comment by bdionne** [comment]
check with user if still happening

**Comment by NCIEVS** [comment]
Just to add feedback from last review with [EHD] and [NT].

EHD. This was rare to begin with but I haven't heard of it happening in a long time. Would close and wait for new bug reports to open a new ticket.

NT. I have never seen this
