### ISSUE TITLE
validation of property qualifiers in batch edits 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#412]
From [EHD], email 2019/02/04:
&nbsp;&nbsp;&nbsp;&nbsp;    "I don’t know if we have formally created at ticket for this but when you add a new complex property and only one of the qualifiers fails the rest of the property does not fail. It stinks because then the editor needs to remove all of the data and run a new corrected batch or try to get the more complicated modify file created. It would be easier for the editor to QA if the bad part of the statement caused the full statement to fail.
&nbsp;&nbsp;&nbsp;&nbsp;    Here is a file for adding new FULL_SYN where the code one of the qualifiers in every entry has a lowercase p (p386) instead of uppercase (P386). 
&nbsp;&nbsp;&nbsp;&nbsp;    I know it is probably resource intensive but it would be better if the entire complex edit statement was “proofed” before it is added rather than adding the good parts and failing only the bad parts. (It is possible that the proofing didn’t recognize that the code was bad because most of the checks are not case-sensitive.)"

[FSBatchWithOPT.txt](https://github.com/NCIEVS/nci-protege5/files/2829953/FSBatchWithOPT.txt)

**Comment by bdionne** [comment]
Actually @hahndane the checks are case-sensitive. The issue looks to be the fact that that qualifier is not required, it's optional

**Comment by singhik** [comment]
@hahndane @NCIEVS  : There is a Case check while Batch Edit and it's mostly on Mandatory List objects f.e.  Term-Type, Term-Source etcetra . Please find below various Use Cases and the Results ::

Use Case 1.  Performing Batch Edit on Complex Property with case-sensitive check on 'entity-id'.  
Result 1     . Field is Case Sensitive and lower case concepts are rejected for new/modify/delete .

Use Case 2.  Performing Batch Edit on Complex Property with case-sensitive check on 'Operation'. 
 Result 2     . Field is Case INSensitive and both upper case and lower case are accepted for new/modify/delete .

Use Case 3.  Performing Batch Edit on Complex Property with case-sensitive check on 'prop-id'. 
 Result 3     . Field is Case Sensitive and only  upper case are  accepted with lower cases as rejected for new/modify/delete .

Use Case 4.  Performing Batch Edit on Complex Property with case-sensitive check on qualifier  'term-source'. 
 Result 4     . Field is Case Sensitive and only  lower case are  accepted for new/modify/delete.

Use Case 5.  Performing Batch Edit on Complex Property with case-sensitive check on  value of qualifier  'term-source'. 
 Result 5     . Field is Case Sensitive and only  upper case are  accepted for new/modify/delete.

Use Case 6.  Performing Batch Edit on Complex Property with case-sensitive check on  qualifier  'term-group'. 
 Result 6    . Field is Case Sensitive and only  lower case are  accepted for new/modify/delete.

Use Case 7.  Performing Batch Edit on Complex Property with case-sensitive check on  value of qualifier  'term-group'. 
 Result 7    . Field is Case Sensitive and only  upper case are  accepted for new/modify/delete.

Use Case 8.  Performing Batch Edit on Complex Property with case-sensitive check on  Subsource Name.
 Result 8    . Field is Case INSensitive and both lower and   upper case are  accepted for new/modify/delete.

Use Case 9.  Performing Batch Edit on Complex Property for happy path flow .
 Result 9    . Relative checks are performed and EDIT Complex Property  is successful in accordance with above rules .


Below are the screen prints for reference :: 

Batch File : 

![image](https://user-images.githubusercontent.com/36314371/58068485-841b4500-7b5f-11e9-8553-8e55c2c02b7b.png)

Batch Upload Operation : 

![image](https://user-images.githubusercontent.com/36314371/58068516-a3b26d80-7b5f-11e9-8049-1439351a14c1.png)

![image](https://user-images.githubusercontent.com/36314371/58068544-c04ea580-7b5f-11e9-9254-8c193239a453.png)


Batch Output File : 

![image](https://user-images.githubusercontent.com/36314371/58068571-d9efed00-7b5f-11e9-8ac6-c4319dc67b03.png)


Concept post Batch Edit : 

![image](https://user-images.githubusercontent.com/36314371/58068597-f0964400-7b5f-11e9-826d-e01104077c4f.png)
