### ISSUE TITLE
Running explanations in incremental classification mode conflicts with edit tab rules

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#415]

**Comment by singhik** [comment]
@NCIEVS : Hello, 

1. How to set up Explanation Server to run in incremental classification mode ? Is this by default or is there any server side setting for it ? 

2. 'Conflicts with Edit Tab Rules', can you please give an example of these Rules ? does it refer to any edit operation being performed or some specific Rules in Edit Tab ?

**Comment by NCIEVS** [comment]
Hi @singhik , for "1" you don't need to do anything, there is no remote vs local as a choice, nor regular vs incremental.  It's only one local classification mode now.  The only thing that you can configure on the client is the number of explanations to get when you request inference explanations.  For "2", I don't recall the details, but it has to do with the classifier creating some kind of temporary data that conflicts with our use of Save actions (i.e. you can't edit a class when another class is being edited).  

Hi @bdionne, please correct or add details as needed.

**Comment by singhik** [comment]
@NCIEVS : Hello, I can develop few Use Cases around multiple Class Editions parallely to test this but multi class editions are only possible with multiple instances of Protege Client as when one Class is being Edited, unless it is 'Save'  , Protege's client console does not allow to work on any other Class ?

**Comment by bdionne** [comment]
@singhik - for "2" the issue is the following. When you've made changes to a class but haven't saved them yet, you normally can't edit another class without getting a warning that prompts you do either go ahead and edit the new one, aborting the old class edits *or* abort these new changes and keep the old one. You can only edit one class.

The problem arises when you ask for an explanation. The explanation inference machinery creates some temporary classes, which was causing the edit tab rules to popup that warning.

So you can test this by editing a class, and then asking for an explanation somewhere and see that the explanation comes up without any warnings. After you click ok to exit the explanation window the original edits should still be present.

**Comment by singhik** [comment]
@NCIEVS @bdionne  :: Hello, I have tried replicating a Use Case for Testing this Requirement, requesting you to please second on the correctness .

Editing a Concept f.e. ‘LE Cell Test’ ::

![image](https://user-images.githubusercontent.com/36314371/58126256-91c4df00-7be0-11e9-8383-c8c1128c5cdf.png)

Without Saving the changes, requesting an Explanation of another Concept  :: 

![image](https://user-images.githubusercontent.com/36314371/58126280-9c7f7400-7be0-11e9-9ef1-1097823168de.png)


![image](https://user-images.githubusercontent.com/36314371/58126295-a4d7af00-7be0-11e9-9bf2-cbb6aab77736.png)

![image](https://user-images.githubusercontent.com/36314371/58126308-ae611700-7be0-11e9-8312-24123277fa4d.png)

Closing the Explanation Window , Original Edit operations being performed for concept(LE_Cell_Test) are still present and are saved successfully ::

![image](https://user-images.githubusercontent.com/36314371/58126329-b9b44280-7be0-11e9-83c1-b5986bbe9022.png)

![image](https://user-images.githubusercontent.com/36314371/58126343-c0db5080-7be0-11e9-8653-e32c62144870.png)

**Comment by NCIEVS** [comment]
@singhik , @bdionne , it looks like the issue in question is fixed.  But the explanations are not returning (above, and 3 different separate tries).  This one can stay closed, but we'll need another ticket for the explanations not returning.
