### ISSUE TITLE
Closing Tabs displays the 'Tab' word twice in the verbiage 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#417]
Hello,

When any 'Tab' in Protege client is closed , the message box displays the word 'Tab' twice , please find below screenshots .

![image](https://user-images.githubusercontent.com/36314371/58042747-7935c580-7b09-11e9-98e4-d16a3ed34d5a.png)

**Comment by singhik** [comment]
Moving this ticket to Future Release Bucket as is low priority cosmetic verbiage deviation .

**Comment by bdionne** [comment]
Ha, this is a good one. The name of the plugin is "Lucene Search Tab", so technically this is correct.

If we want to have different names let me know, I'm sure changing them is an easy task. NCI Edit Tab will likely have the same issue

**Comment by NCIEVS** [comment]
OK, in that case we'll close the ticket.  It's kind of like saying windows NT technology :-)
