### ISSUE TITLE
error reading changesets

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#418]
Editors ran into an issue where they couldn't access data after login.  The error message on the GUI was "Failed to read data from server”.  An exception stack trace was output to the terminal:

Level: ERROR Time: 1559739276668 Message: invalid type code: 0D java.io.StreamCorruptedException StackTrace: java.io.ObjectInputStream$BlockDataInputStream.readBlockHeader(Unknown Source) java.io.ObjectInputStream$BlockDataInputStream.refill(Unknown Source) java.io.ObjectInputStream$BlockDataInputStream.read(Unknown Source) java.io.ObjectInputStream.read(Unknown Source) org.semanticweb.binaryowl.BinaryOWLOntologyChangeLog$CountingInputStream.read(BinaryOWLOntologyChangeLog.java:120) org.semanticweb.binaryowl.BinaryOWLOntologyChangeLog.readChanges(BinaryOWLOntologyChangeLog.java:97) org.semanticweb.binaryowl.BinaryOWLOntologyChangeLog.readChanges(BinaryOWLOntologyChangeLog.java:86) org.protege.editor.owl.server.versioning.ChangeHistoryImpl.readBinaryOWLChangeLog(ChangeHistoryImpl.java:168) org.protege.editor.owl.server.versioning.ChangeHistoryImpl.readObject(ChangeHistoryImpl.java:146) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) java.lang.reflect.Method.invoke(Unknown Source) java.io.ObjectStreamClass.invokeReadObject(Unknown Source) java.io.ObjectInputStream.readSerialData(Unknown Source) java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) java.io.ObjectInputStream.readObject0(Unknown Source) java.io.ObjectInputStream.readObject(Unknown Source) org.protege.editor.owl.client.LocalHttpClient.retrieveChangeHistoryFromServerResponse(LocalHttpClient.java:331) org.protege.editor.owl.client.LocalHttpClient.getLatestChanges(LocalHttpClient.java:603) org.protege.editor.owl.client.LocalHttpClient.buildVersionedOntology(LocalHttpClient.java:392) org.protege.editor.owl.client.ui.OpenFromServerPanel.openOntologyDocument(OpenFromServerPanel.java:217) org.protege.editor.owl.client.ui.OpenFromServerPanel$OpenActionListener$1LoadDBWorker.doInBackground(OpenFromServerPanel.java:167) org.protege.editor.owl.client.ui.OpenFromServerPanel$OpenActionListener$1LoadDBWorker.doInBackground(OpenFromServerPanel.java:158) javax.swing.SwingWorker$1.call(Unknown Source) java.util.concurrent.FutureTask.run(Unknown Source) javax.swing.SwingWorker.run(Unknown Source) java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) java.lang.Thread.run(Unknown Source)

**Comment by NCIEVS** [comment]
Some additional info:  a copy of the vocab data in the server was provided by the systems group.  @bdionne couldn't troubleshoot as this error didn't reproduce in the Mac using the production data (but was reproducible in windows and linux).  The data was squashed in the Mac and a new baseline generated usable in prod.  No software fix yet.

**Comment by bdionne** [comment]
@NCIEVS - as I look at this stack trace above again, this is different from the other issues we were discussing yesterday. I was seeing a null pointer error on the client side. This seems to be the file itself being corrupted

**Comment by NCIEVS** [comment]
@bdionne , yes, agreed the exceptions were different.  So we need a different ticket for the "wrong head" write issue from this week, yes?

**Comment by bdionne** [comment]
yes, I opened #423

**Comment by NCIEVS** [comment]
changed to watch-and-wait, not clear how this file is getting corrupted and we need more info.

**Comment by NCIEVS** [comment]
Might have been fixed after related fixes.  Will close & reopen a new ticket if this is observed again.
