### ISSUE TITLE
failure to prevent last remaining superclass from being removed

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#419]
from [EHD] (with some edits):
"I saw an issue (a class lost all its parents and ended up under owl:thing) and I fixed it. .... I am also not sure how protégé allowed the only parent to be removed. I assume the editor was confused by the parent/role display because they removed the parent but this class had several roles; however, shouldn’t protégé have caught the removal at the Save?"

comment from [GF]:
Maybe re-treeing is buggy (where a class might temporarily be parentless)?  Or owl:Thing is being counted as superclass?

**Comment by bdionne** [comment]
The fix for this is available in the [EditTab-1.0.2](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.0.2) plugin

**Comment by singhik** [comment]
@bdionne : Hello, I am able to reproduce this issue, with Batch Edit Parents(Delete) for a Subclass and that Subclass landing directly under 'Owl:Thing' hierarchy . Below are the detailed steps with screen prints ::

'Test_Sub_Class_2'  is a Sub Class of 'Test_Class_1'    and 'Test_Class_1' is a SubClass of 'Abnormal Cell' ::

![image](https://user-images.githubusercontent.com/36314371/63219823-1673ba80-c148-11e9-925d-9f3f2b67dc0b.png)

Doing a 'Batch Edit Parents' for delete operation and removing 'Test_Class_1' as a Super Class for 'Test_Sub_Class_2'  :: 

![image](https://user-images.githubusercontent.com/36314371/63219840-5fc40a00-c148-11e9-852c-1047a56b9ef9.png)

![image](https://user-images.githubusercontent.com/36314371/63219843-74080700-c148-11e9-9649-00a4cffe4051.png)

Post Batch Edit Parents (Delete), 'Test_Sub_Class_2'  came directly under 'Owl:Thing' Tree , which is the issue ::

![image](https://user-images.githubusercontent.com/36314371/63219853-b9c4cf80-c148-11e9-9ab7-bee24666e1bb.png)

**Comment by NCIEVS** [comment]
In the GUI as well as in batch.

**Comment by singhik** [comment]
Re-Tested on 3.5.0-QA1 build, works As Expected for not allowing the last superclass to be deleted, hence closing the ticket .
