### ISSUE TITLE
EditTab - enhanced support for editing class expressions in defined classes

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#42]
allow disjuncts and conjuncts in equivalent classes

same functionality as was done for subclasses

**Comment by bdionne** [comment]
We've decided against this, but we also decided to *disallow* the splitting of an equivalent class conjunction

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.110)

**Comment by rmehri** [comment]
Hi Bob, 
Can you please elaborate more for this enhancement, so I can verify this fix?
Thanks,
Reza

**Comment by bdionne** [comment]
"we also decided to disallow the splitting of an equivalent class conjunction" -- sort of explains it. Equivalent classes conjunctions cannot be split

**Comment by rmehri** [comment]
Can you please give examples?  So I can verify. 
Thanks,
Reza

**Comment by bdionne** [comment]
any class with equivalent classes should do.

**Comment by rmehri** [comment]
This issue is not testable. 
Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This issue is not reproducible.  Need enumerated steps to validate.
Thanks

**Comment by bdionne** [comment]
thanks @rmehri - note that I assigned this one to myself, I'll take care of testing it

**Comment by rmehri** [comment]
Hi Bob, 
This issue was assigned to QA bucket. But as I mentioned in my previous comments, I need the reproducible steps to validate this fix. Otherwise, please let me know if this ticket can be closed.

![untitled1](https://cloud.githubusercontent.com/assets/8367102/23911624/c3c79c2e-08b3-11e7-8ba1-84eb1d94f56d.png)
Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - as I mentioned above ^^ - I will take care of this one
