### ISSUE TITLE
Server changesets out off sync with client snapshots

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#424]

**Comment by bdionne** [comment]
The prompt/publish operations squash existing changesets and produce a new snapshot. When users login, a checksum is used to determine if their snapshot is out of date. When a new one exists it's fetched from the server.

When existing session resume editing after the squashing their snapshots out of sync can lead to corrupted changesets with respect to the version order

**Comment by singhik** [comment]
This issue is out of scope from functional  QA due to configurations needed , hence it would be limited to Unit Level Test  . 
Hence closing this ticket .
