### ISSUE TITLE
explanations not returning

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#426]
The panel with the explanations doesn't populate (see [screenshot](https://user-images.githubusercontent.com/36314371/58126308-ae611700-7be0-11e9-8312-24123277fa4d.png)) in #415 .

**Comment by NCIEVS** [comment]
Not an issue, wrong reasoner had been selected in the explanation form.

**Comment by bdionne** [comment]
@NCIEVS - I think there's still something to look into here. When you first choose the clark parsia reasoner, it sometimes hangs and I'm not sure why it seems to take too long the first time

<img width="1165" alt="Screen Shot 2019-07-21 at 2 34 25 PM" src="https://user-images.githubusercontent.com/31741/61633962-3c4b9380-ac5e-11e9-9d92-7f8c1f53cda4.png">

**Comment by NCIEVS** [comment]
It might just be taking too long and it's not wedged.  But another look is good.

**Comment by NCIEVS** [comment]
@bdionne , I'm wondering if this is related to sometimes the initial classification taking it's good old time to come back.

**Comment by bdionne** [comment]
Not sure, classification has this addition phase at the end, and I don't know if the explanation does the same.

On my machine it seems to be a memory issue, the RAM goes up to about 8.5G when I run the explanations

**Comment by safrant** [comment]
How do you open this explanation form?  Itendra and I can't find it.

**Comment by safrant** [comment]
Steps to replicate - possibly.  Please correct if wrong
Select Pellet under Reasoner
Start reasoner and wait for completion
Select a concept, go the Description tab and click a question mark
In the Explanation dialog, select Pellet Explanation Service from drop down

**Comment by singhik** [comment]
1. Explanations are returning values on Explain inference .
2. Reasoner has to be started as a pre-requisite .(Takes really long to compute and complete classify, 15-20 mins) .
3.  @safrant  will be configuring the settings under 'Preferences->Pellet' to Enable Explanations by default .
