### ISSUE TITLE
fast batch job wedges

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#427]
Placeholder to keep track.  Probably switch to modal dialog.

**Comment by singhik** [comment]
@NCIEVS: Hello, I tested rigorous batch edit files with small data sets and do not see any wedging .
The only dialog that appears is the BAU one w.r.t 'Committing Changes' and it disappears post commit .

Not sure what does 'Switch to Modal Dialog' imply  ? Please provide valuable insight ..

**Comment by NCIEVS** [comment]
@singhik , Oh, that "switch to modal dialog" was a suggestion with the idea of decreasing the potential of wedging by eliminating the thread that updates the progress dialog.  So switch to a different modal dialog rather than keeping the modeless update dialog.

**Comment by singhik** [comment]
@NCIEVS : Hello, ok but the dialog box has not changed, it is the same but wedging is not an issue. If the requirement was 'wedging' issue, then this ticket can be closed , else if the requirement was having a different modal dialog then this ticket will be open , please advice

**Comment by NCIEVS** [comment]
@singhik , that was my suggestion for a fix, but @bdionne may have done something different :-) , so this ticket can be closed.

**Comment by singhik** [comment]
@NCIEVS :: sure, I wanted to double check on the Requirement definition, closing the ticket as Wedging for Batch Jobs with small file or large file does not happen. This functionality will be re-tested during Regression Executions as well ..
