### ISSUE TITLE
fast classification wedges

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#428]
Placeholder.  Probably go to a modal dialog.

**Comment by singhik** [comment]
1. Classification post starting Reasoner on an average is taking 15-20 minutes to classify complete.
2. No Run time or Operation Exceptions are thrown during Classification and post completion.
3. Editors have specified few ambiguous behaviour w.r.t Batch Editing and Classification in parallel and other observations which are not re-producible, hence keeping this ticket open until this is reasoned-out and agreed with all stakeholders .

**Comment by NCIEVS** [comment]
@bdionne , seems like the classification progress bar needs to be modified.  While trying to reproduce [EHD]'s issue (9/13/19 email), I did a classification and then went on standby.  Coming back to the gui later, somebody had edited a number of classes and they had appeared in the inference results panel, which I had left open while on standby.  Unlike [EHD], my gui wasn't frozen.  so I then reclassified and the classification went to completion, pretty fast.  The "I'm done" dialog came up and I clicked on it, but the reasoner progress dialog was still hanging waiting for its usual notification.  Here's a screenshot:

![Screenshot at 2019-09-13 12-57-15](https://user-images.githubusercontent.com/7783321/64881073-d52bd900-d627-11e9-87eb-b7492b3fd426.png)


Later, I pressed Cancel but the dialog wouldn't go away.  However, even though the progress dialog was sitting there, they gui wasn't frozen:  i could navigate the tree, do a search, go to the inference results panel, although I didn't try editing as this was in production.  Don't have suggestions about how to modify this dialog.  Stopping the classifier and then rerunning seems to work and the progress bar goes away; but have to wonder about any potential changed state leading to instability.

**Comment by singhik** [comment]
@bdionne : Can you pls specify what changes are done to the classification modal dialog from before ?

**Comment by bdionne** [comment]
see #472

**Comment by singhik** [comment]
Multiple Edits on two instances with classification works as expected , no hanging, no Exceptions were observed, on 3.5.0 Protege Client Built with 0.0.5 Curator plug in version, hence closing the ticket
