### ISSUE TITLE
NCI Edit Reinitialization Exception

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#429]
Steps to Reproduce ::

1. Login to Protege Client .Select NCI Edit (if not already selected)
2. Logout from the Server and Re-connect .
3. Perform operations on NCI Edit and to initialise/reinitialise it .

Issue ::

Exception is thrown and NCI Edit Tab will not get re-initialised ,unless restarted.

Attached is the document with screen prints ....
[Issue.docx](https://github.com/NCIEVS/nci-protege5/files/3534248/Issue.docx)

**Comment by bdionne** [comment]
@singhik could you clarify the steps to reproduce this? The stapes above don' agree with the sequence of screenshots in the attached doc.

From the screenshots it looks like you disabled the edit tab *after* logging out, the tried to *re-enable* it after logging in again, is that correct? Did you not get the open project dialog?

In any event I've tried both scenarios and set a breakpoint in that stack you posted and cannot see this issue. I suspect it might be another related to fileprefs being corrupted, as we save out which tabs are exposed and will try to re-enable them on login

**Comment by singhik** [comment]
@bdionne : Have attached another document for reference with steps and screen prints for every step .

I did not disable the NCI Edit Tab , i only logged out and relogged in and NCI Edit Tab was not initialized, to try again, once re-logged in, i then de-selected the NCI Edit Tab and reselected it but NCI Edit Tab was still not initialized .

I have deleted fileprefs when doing this operation .

[429.docx](https://github.com/NCIEVS/nci-protege5/files/5257505/429.docx)

**Comment by cmoid** [comment]
Oh I see, you didn't even open a project, you just logged in to the server? Ok, yea that's likely some edge case. I can probably reproduce that.

I can't imagine a user ever doing this, but you never know

**Comment by singhik** [comment]
@cmoid : The project was already logged

**Comment by bdionne** [comment]
Oh I see, you didn't even open a project, you just logged in to the server? Ok, yea that's likely some edge case. I can probably reproduce that.

I can't imagine a user ever doing this, but you never know

**Comment by bdionne** [comment]
yea, @singhik , the project you have opened will be closed when you log out the server. When you do open from sever it does both a login and open the project.

So it won't initialize the project if all you do is login again, you need to re-open the project also.

That said, you should still see EditTab appear ok, with an emtpy tree. I don't see the error you see on the latest build, perhaps you can try that and see if it is still there (3.5.0-dev2)

**Comment by singhik** [comment]
@bdionne : Hi, the project was loaded, in the screen print document, if you refer to the Window header, it does show 'Project: Thesaurus-200608' , i have not tried it in 3.5.0-dev2 build as yet, will give it a try later in the week .

**Comment by bdionne** [comment]
@singhik ok, thanks. Interestingly this new screenshot doc doesn't show the null pointer exception.

I can tell you for sure that when you logout the project is closed, so you will not see anything in edittab if all you do is login to the server, until you open the project again.

> it does show 'Project: Thesaurus-200608' 

it does, I see that too and think that's just a refresh issue

**Comment by singhik** [comment]
Re-tested on 3.5.0-qa1 build , works as expected and hence closing the ticket .
