### ISSUE TITLE
EditTab - scroll bars on complex properties panel

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#43]
Add scroll bar to complex property panel

**Comment by NCIEVS** [comment]
This is ready for QA.

**Comment by rmehri** [comment]
The fix for this issue has been retested and verified using tag-116, edittab-0.3.1.
Please see attached snapshot for more detail. 
Thanks,
Reza

![complex property scroll bars](https://cloud.githubusercontent.com/assets/8367102/21876652/ca02ce88-d852-11e6-9e63-f824022ea8e1.png)
