### ISSUE TITLE
Double Click During Project Selection Login Throws Error -- Low Priority

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#430]
While opening Protege CLient and selecting a Project, if a user double clicks on a Project instead of click and 'Open Project', an error is thrown. 

This is a low priority issue relating to Double click invoke method to Open a project .

![image](https://user-images.githubusercontent.com/36314371/63590457-dd897a80-c579-11e9-8229-d4f21b4ac2a2.png)

**Comment by bdionne** [comment]
is fixed in next tag

**Comment by singhik** [comment]
Works fine and tested on 3.4.0 - qa1 , hence closing the ticket .
