### ISSUE TITLE
sparql plugin enhancement - alphabetic sort of bookmarks

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#433]
Currently the bookmarks are unsorted.  With the growing list of queries it would be good if the bookmark widget would present them alphabetically sorted to make it easier to find.

**Comment by bdionne** [comment]
This is in [sparql-query-plugin 2.1.1](https://github.com/NCIEVS/sparql-query-plugin/releases/tag/sparql-query-plugin-2.1.2) and should work fine in current system also

**Comment by singhik** [comment]
@bdionne : Hi, BookMarks in "SPARQL Tab" do not appear to be alphabetically sorted , Sparql Plug-In version is 2.1.1 . Attached is the screen print document for reference .

[Issue 433.docx](https://github.com/NCIEVS/nci-protege5/files/4504286/Issue.433.docx)

**Comment by bdionne** [comment]
@singhik it looks like you're not using the new 2.1.2 plugin

cc: @safrant

**Comment by singhik** [comment]
Sparql Plugin 2.1.2 has the bookmarks sorted Alphabetically in Ascending order , ticket closed
