### ISSUE TITLE
Batch Edit Issue For Complex and Simple Pty 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#436]
From Business :: 

protégé allowed Business to run the attached P90 FULL_SYN batch file (GDC_PT_Batch_2) as a EDIT_SIMPLE_PROPS. Then all of the added FULL_SYN were missing the required qualifiers term-source and term-group data. Luckily, it allowed Business to delete them by creating a file without these two qualifiers (GDC_PT_Batch_2_Fix) also using EDIT_SIMPLE_PROPS. 
Business  thought the edit checking would either prevent the run of a file that didn’t fit the simple format or prevent the creation of FULL_SYN without the required qualifiers term-source and term-group ? .

**Comment by bdionne** [comment]
This is really user error, we'll add some additional checks to try and catch this and prevent it

**Comment by bdionne** [comment]
We can also do some more logging that helps detect these errors after the fact

**Comment by singhik** [comment]
@bdionne : Hi, I am still able to perform 'Complex Properties' operations (New,Delete,Modify) using 'Batch Simple Edit' File system and option . Attached is the detailed screen print document. 
Per Requirement, I was expecting the File to Error Out and Operation to Fail . 

[Issue 436 - New.docx](https://github.com/NCIEVS/nci-protege5/files/4505308/Issue.436.-.New.docx)

**Comment by bdionne** [comment]
This test case your are using @singhik is invalid. Complex properties have qualifiers, some are required, some optional. If all you put in your case is 4 values it will correctly treat it as a simple property

**Comment by singhik** [comment]
@bdionne : Hi , I have derived the Use Cases from Business's Email which states they tried using 'BATCH EDIT SIMPLE PTY'  File and Operation to perform a Complex Pty Operation of FULL_SYN .
This means 'Batch Edit Simple Pty' should not allow Complex Pty operations of FULL_SYN,DEF,ALT-DEF , hence i used a Batch Edit Simple Pty file format with Complex Pty values and tried performing the operations .

If you could derive your understanding of the Req, i would take a different approach of executing Use Cases .

**Comment by bdionne** [comment]
@singhik Yes, the use tried to choose the simple property action to process a file that was for complex properties. So your test case should use a complex properties file, not a simple properties file. From above in the ticket:

> protégé allowed Business to run the attached P90 FULL_SYN batch file (GDC_PT_Batch_2) as a EDIT_SIMPLE_PROPS. 

If you look at a `P90 FULL_SYN` input file you will see it contains qualifiers. Your test case does not, so when you choose the action of simple edit ti does the cporrect thing

**Comment by singhik** [comment]
@bdionne @NCIEVS  : Ok, Thus far with 'Batch Edit'  i have always assumed One - One Mapping between 'Batch Type' and "Input File', i.e. if anyone is trying to select "EDIT_SIMPLE_PROPS" as Batch Type then they would use the File format for Simple Edit and Not Complex Edit as for Complex Edit, the 'Batch Type' is 'EDIT_COMPLEX_PROPS'  . Hence the Expectation was understood to have Complex Pty Qualifiers like P90,P325,P97  to create an Exception and fail whenever the 'Batch Type' was selected as 'EDIT_SIMPLE_PROPS' .

So,
Q1> Is the Business Expecting to Run a Complex Edit File for all Operations on a 'EDIT_SIMPLE_PROPS' Batch Type operation ,successfully ?

**Comment by bdionne** [comment]
> Q1> Is the Business Expecting to Run a Complex Edit File for all Operations on a 'EDIT_SIMPLE_PROPS' Batch Type operation ,successfully ?

No - If the user selects the batch type `EDIT_SIMPLE_PROPS` and chooses an input file that is for complex properties, it will fail and you will see errors on the console. 

This is the error the user was making, it's a user mistake.

You test case fails to see the error, because you are providing an input file that is for simple properties, your records only have 4 values, they are missing qualifiers. Try testing this problem with the input file the user provided

**Comment by singhik** [comment]
@bdionne @NCIEVS :: Hi, Below Use Cases have been validated, please review and align if any other Scenario is applicable for this Ticket . 


![image](https://user-images.githubusercontent.com/36314371/79803178-7fdb4700-832f-11ea-8281-cb55882a1dc8.png)

**Comment by bdionne** [comment]
@singhik This looks good to me, the code change was to notice that when the input file was for simple edits, there would be either 4 (new and delete) or 5 (modify) columns, wherease complex properties would have more.

I think you got all those cases

**Comment by singhik** [comment]
@bdionne : Thanks, Closing the Ticket .
