### ISSUE TITLE
Move the code to the left of preferred name

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#438]
Sometimes preferred names are too long, causing the codes which are at the far right to be truncated. If the code were to the left of the preferred name it would make these cases more readable.

@NCIEVS This is from Terry, will put it on the queue unless you think otherwise.

**Comment by NCIEVS** [comment]
Agreed, seems simple enough to put in the queue for next release.

**Comment by singhik** [comment]
@bdionne : Hi, If the  Requirement is to have the 'Code' left aligned to 'Preferred Name' .

1. I See 'Code' being Right aligned to 'Preferred Name' :: 
![1](https://user-images.githubusercontent.com/36314371/79765340-7da7c700-82f4-11ea-8a67-8254276bba40.jpg)

2. After putting a Long Name for a Concept as 'Preferred Name', the 'Code' disappears from Console ::

![1](https://user-images.githubusercontent.com/36314371/79765618-d5dec900-82f4-11ea-95f4-8ae924f559ca.jpg)

**Comment by bdionne** [comment]
@singhik are you sure you have the latest plugin? It should be 1.0.9 for EditTab

<img width="892" alt="Screen Shot 2020-04-20 at 12 15 48 PM" src="https://user-images.githubusercontent.com/31741/79774429-c8c7d700-8300-11ea-809f-fecaa186d5f4.png">

**Comment by singhik** [comment]
@bdionne @safrant : Hi, Yes, for me NCI Edit Tab is versioned at 1.0.4 and Sparql at 2.1.1 . My Plugin registry URL is correctly pointing to 'https://raw.githubusercontent.com/ncievs/autoupdate/master/plugins.repository' and 'Automatic Update' is also checked, but do not receive any updates .
Shall i change the pluginregistry to point to Bob's URL ?

![image](https://user-images.githubusercontent.com/36314371/79776016-19403400-8303-11ea-8296-d7736c492522.png)


![image](https://user-images.githubusercontent.com/36314371/79776307-8b187d80-8303-11ea-8d19-11b0da6c07f5.png)

**Comment by bdionne** [comment]
@singhik - yes, the ncievs account points to the prodiction version of the plugins. The bdionne account point to the QA versions

cc: @safrant @NCIEVS

**Comment by singhik** [comment]
@bdionne : Hi , With latest plug-ins via Bob's Repo, 'Code' is left aligned to 'Preferred Name'  , Long names are housed in 'Preferred Name' as Expected. However, if 'Concept' Label (Preferred Name) crosses 80 chars in Length, 'IRI Fragment' gets deleted from the Console . 

So, if the Business Expectation is for Concept's Label within 80 Chars, this ticket is good to close .


Preferred Name (Less than 80 characters) :: IRI Fragment is visible 

![image](https://user-images.githubusercontent.com/36314371/79781976-5b21a800-830c-11ea-83d6-b2aaf100f192.png)


Preferred Name exceeds 80 chars :: IRI Fragment gets Truncated 

![image](https://user-images.githubusercontent.com/36314371/79782064-7391c280-830c-11ea-9ea5-65382a140f1a.png)
