### ISSUE TITLE
Integrate protege-client/server plugins into protege-editor-owl layer

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#439]
In order to fully support imports of existing protege project that are under source control, it's better to integrate these client/server plugins into the owl layer. Otherwise protege owl needs to know if a connection is not present for an import and make one on the fly, .ie. it needs to have knowledge of the plugins.

**Comment by bdionne** [comment]
A first build of this is available:

````
./build.sh 3.3.0-dev1 bdionne
````

**Comment by singhik** [comment]
@bdionne :: Hi , I have build the above extract manually and before i kick start Regression had few questions .

1> How do i confirm that my build is built successfully ? As this is an architecture level change,there is no functionality which can be found,tested and confirmed for the build being latest(3.3.0-dev1) . I did not get any error during the Build process was Executed .

2> Post build, NCI Edit Tab and EVS History plugins were extracted with old versions,  i changed the Plugin repo to point to Bob's and on restart also the latest plugins were not installed/updated with ?

**Comment by bdionne** [comment]
@singhik 

1. There is no new end-use functionality that you can test, so I would say just run all your regression tests and make sure nothing broke

2. There are no new plugins for this build, except the sparql-query-plugin, 2.1.2, which fixes issue #433 If you point to bdionne/autoupdate you should pick it up

**Comment by singhik** [comment]
@bdionne :: Hi Bob, My question was not around the scope of test as that has been identified as 'entire Regression' . I was asking the question to validate the Build, i.e. i did a build manually so how to ensure if the build is built as per 3.3.0 norms as Expected ? 

F.e. if there is a build in 3.2.0 and it has new functions , i can check for those new functionalities and conclude my build is pointing to latest code base. However in 3.3.0 dev1, as that is only architectural level change, i can not validate if the build is pointing to 3.3.0 dev1 code base .

**Comment by bdionne** [comment]
@singhik Hi, I see, I misunderstood the question. When you did the build, .eg.
````
./build.sh 3.3.0-dev1 bdionne
````
Maven will print out tables of each component on the console, so you can see if all the components are successfully built. The string `3.3.3-dev1` is a tag number that I use in the `tagger.sh` script that tags each Github repository with that tag. Some repos may be on branches and some on master, but it won't matter since it uses that tag.

**Comment by singhik** [comment]
@bdionne : Thanks Bob, as you initially mentioned, for Windows ,the build indeed is unstable with non-usability for Regression. Have attached few screen shots of the Protege Console (3.3.0 dev1) showing unstable and overlapping Objects and eventually hangs post clicking on any operation ::

![image](https://user-images.githubusercontent.com/36314371/74472755-6e2d7d00-4e70-11ea-91e2-256ebc987115.png)

**Comment by singhik** [comment]
@bdionne :: With 3.3.0 Dev2 new built as well ,Protege Client console for NCI Edit Tab is broken , please find below screen prints for reference ::

'About' Section showing Latest version ::

![image](https://user-images.githubusercontent.com/36314371/75691248-0057c280-5c72-11ea-9b93-0778d8fdd76a.png)


'Add SubClass' and 'Delete Selected Class' objects are overlapped, post 'Retire' operation, Protege Hangs indefinitely and has to be restarted to bring it up ::
 
![image](https://user-images.githubusercontent.com/36314371/75690828-8293b700-5c71-11ea-97d6-f7f4628d697b.png)

**Comment by singhik** [comment]
Closing this ticket as Automation Regression Execution completed without any major deviations found.... .
