### ISSUE TITLE
EditTab - prepopulate editornote and designnote on retirement

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#44]
Add default design note and editor note in retirement dialog, similar to that of merge

**Comment by NCIEVS** [comment]
Suggest that the design note & editor note get pre-populated in the dialog with "Retired on <date>", allowing room for the editor to expand the notes if needed.  Labelling this for V1 Release.

**Comment by bdionne** [comment]
added design/edit note for retire dialog in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107) using the `ISO_LOCAL_DATE`

**Comment by rmehri** [comment]
This fix for this issue has been retested and verified using tag 116-edit tab 0.3.1.
Local server.
Please see attached snapshots for more detail. 
Thanks,
Reza

![editor note](https://cloud.githubusercontent.com/assets/8367102/21817294/741ad2ee-d731-11e6-930f-b78d2e473c77.png)
![preretired](https://cloud.githubusercontent.com/assets/8367102/21817299/7621c250-d731-11e6-9148-2a2263c424d4.png)
