### ISSUE TITLE
After Retiring Concepts ,Control Does Not Navigate To Retired Concepts Tree

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#442]
@bdionne @NCIEVS : Hi, During Concept Retire process, after 'Save' is clicked post Retiring a concept, the console navigates the Control to 'Retired Concept Current Year' Tree, to list the Retired Concept or to Try 'Delete' it . That is not happening for 3.3.0-qa2 build . Below are the screen prints 

![image](https://user-images.githubusercontent.com/36314371/81110951-4cc9b380-8eea-11ea-9775-96e339ff0e49.png)

![image](https://user-images.githubusercontent.com/36314371/81111007-60751a00-8eea-11ea-8905-99c1e2747d8d.png)

![image](https://user-images.githubusercontent.com/36314371/81111056-6bc84580-8eea-11ea-9bb3-d06d1c94e50c.png)

After Saving the Retired State of a Concept, Control DOES NOT go to 'Retired Concept Current Year' Tree ::

![image](https://user-images.githubusercontent.com/36314371/81111148-99ad8a00-8eea-11ea-8235-98c086da1e4f.png)

**Comment by bdionne** [comment]
@singhik Could you provide more detail please:
 * was the logged in user a modeler or manager?
 * which content? Looks like the full recent snapshot of the Thesaurus?
 * was this by itself or with imports?

I'm not able to reproduce this. Is it easily reproducible for you, does it happen every time?

<img width="1016" alt="Screen Shot 2020-05-06 at 9 00 08 AM" src="https://user-images.githubusercontent.com/31741/81179929-5dc10600-8f78-11ea-935d-c70309925208.png">

**Comment by singhik** [comment]
@bdionne : Hi ,

was the logged in user a modeler or manager? -- Manager
which content? Looks like the full recent snapshot of the Thesaurus? -- All concepts across Project
was this by itself or with imports?  -- itself 

However, i am **not** able to reproduce it today, it's working fine for me this morning, same user , not sure what changed .

**Comment by singhik** [comment]
@bdionne : Hi, Not able to reproduce now after multiple regression tickets, hence closing the ticket . Below is the screen print for Expected behaviour .

![image](https://user-images.githubusercontent.com/36314371/81489351-55035500-9242-11ea-9cce-5bab50b9c3f3.png)

![image](https://user-images.githubusercontent.com/36314371/81489353-5d5b9000-9242-11ea-88bb-a812a5bbb98d.png)

![image](https://user-images.githubusercontent.com/36314371/81489356-62204400-9242-11ea-92c7-879cd7847855.png)
