### ISSUE TITLE
Split Concepts Are Getting Created After Clear Button Functionality

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#443]
@bdionne @NCIEVS : Hi, Split Concepts are getting created ,even after Clear button is clicked, Expected functionality is the Split Concept or any other operation should **not** process  post click of Clear Button . Below are the screen prints :: 

![image](https://user-images.githubusercontent.com/36314371/81328767-752ceb80-906b-11ea-8217-19685a7ee890.png)

![image](https://user-images.githubusercontent.com/36314371/81328786-7c53f980-906b-11ea-99ca-202ad811cd7a.png)

Now, post click on 'CLEAR' button, the Split Concept created still exists with the Split ::

![image](https://user-images.githubusercontent.com/36314371/81328892-a73e4d80-906b-11ea-9fdd-b42cc69fd000.png)

Split Concept Exists :: ISSUE 

![image](https://user-images.githubusercontent.com/36314371/81328926-b91ff080-906b-11ea-9fca-1f6fbe69e6ab.png)

**Comment by bdionne** [comment]
- Does this occur every time you split?
- Did you invoke split using the right click menu on the select class or drag and drop?
- Is this just the Thesaurus content or are there also imports involved?

**Comment by singhik** [comment]
@bdionne : Hi, 

Does this occur every time you split? 
--Yes, have tried 4 times today ,same issue

Did you invoke split using the right click menu on the select class or drag and drop?
-- Doing it via 'Complex Edit->Split' Drag and Drop .

Is this just the Thesaurus content or are there also imports involved?
-- This vocabulary is Thesaurus content Only, i did not use it for Imports or performed split on an imported Vocab as part of this Release .

**Comment by singhik** [comment]
@bdionne : Hi Bob, I have re-tried the Split Clear Scenario now couple of times and it worked fine . Not sure what changed, i will perform more Regression on this as well tomorrow , will keep you posted.

**Comment by bdionne** [comment]
@singhik - Did you see the additional two question I added above?

 - Is the newly created concept really there or is it a refresh issue, .ie. if you close that branch and reopen is it still there?
 - If you click on Server/Show Uncommitted Changes do you see the changes there are are they cleared?

Next time it happens, note these. We found something last night that could explain it happening on windows, but I'm not entirely sure

**Comment by singhik** [comment]
@bdionne : Hi, no, didn't find any questioned yesterday, only saw them posted today morning :

Is the newly created concept really there or is it a refresh issue, .ie. if you close that branch and reopen is it still there? 
-- I could not find the cleared concept after 'Clear' on close and re-open .
If you click on Server/Show Uncommitted Changes do you see the changes there are are they cleared?
-- It shows 'No Uncommitted Changes' dialog prompt .

@bdionne : What was the find that might be causing it on Windows ?

**Comment by bdionne** [comment]
@singhik not sure, but I found one place where a race condition might affect it. There are a lot of things that happen when you hit the clear button. All the changes get undone, which cause other events to get thrown that the double edit panels respond to. It looks to be a refresh issue though which is why I ask the question of whether the classes are really gone or not.

@safrant Do you see this issue on your machine?

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, I am not able to reproduce it and don't think we should do any code push now for  3.3.0 Milestone Release. 
We may look at it as a future Release artifact as and when the issue resurfaces .Not Closing it as yet and adding it to Future Release .

![image](https://user-images.githubusercontent.com/36314371/81489237-25078200-9241-11ea-885e-5034dede3e02.png)

![image](https://user-images.githubusercontent.com/36314371/81489238-2b95f980-9241-11ea-86f2-c43418197142.png)

Post Clicking Clear ::

![image](https://user-images.githubusercontent.com/36314371/81489242-38b2e880-9241-11ea-84af-d60b185c74af.png)

Not able to search as well, as Expected :

![image](https://user-images.githubusercontent.com/36314371/81489268-79aafd00-9241-11ea-9a24-f1dce8ed3fa0.png)

![image](https://user-images.githubusercontent.com/36314371/81489277-82033800-9241-11ea-9b57-1cfe29abe296.png)

**Comment by NCIEVS** [comment]
I checked evs_history, revision history, and the server logs.  Can't find a record of C1000046 having been created or committed, consistent with the split operation having been completed with a Cleared instead of Saved.

**Comment by singhik** [comment]
@NCIEVS : Hello, i am also not able to reproduce the issue of Split->Clear func, search and revision history do not show the cleared concept as Expected as posted above in screen prints hence i took it out of current Release .

The reason i moved it to 3.4.0 is cause @bdionne  has an updated code which might be the fix for the  issue when i first experienced it, hence we can do more due diligence around it in next Release .

**Comment by NCIEVS** [comment]
The random failure issue could have been due to the updater code.  Close & reopen new one if it happens again.
