### ISSUE TITLE
New data doesn't appear after batch load/edit

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#448]
From [EM]:
"I was doing some bulk loads on Friday and the CDISC ALT def bulk load was showing as having been completed but when I checked on the actual concepts themselves all of the CDISC ALT defs were missing. I’ve attached the bulk load file for your perusal. I noticed that when I checked the concepts, there was a blank row in  protégé in the ALT def field."
[The screenshot of the GUI at this point is shown below.]

Additional info:  
1) [EHD] said that a number of prior (same day) batch edits had not behaved like this one.  Only this one showed blank rows after its batch job.
2) While in telecon with [EM], [EHD] could see the edited properties in her GUI at the same time that [EM] could not.  [EM] then tried a "Window>Refresh user interface" but no luck.  After logging out and deleting the fileprefs she was able to see the properties.
3) [NCIEVS] could not reproduce the original report.  If a batch-edited class was visible in the GUI the content was not refreshed after the batch job.  However, navigating away and then doing a search for the class, as [EM] did, and bringing it back into the edit tab showed the text of the batch-edited property, unlike [EM]'s results where she got a blank row.

Was wondering whether a "force refresh of gui contents" is feasible, it seems like it would be useful in any case, i.e. "3" above.  But is it possible that a prior batch edit (or some other edit) exception corrupted the fileprefs file?  
&nbsp;
&nbsp;
![Untitled](https://user-images.githubusercontent.com/7783321/84194860-a5e9b180-aa6b-11ea-90a8-4997992438ed.png)

**Comment by NCIEVS** [comment]
Here's the file that I tested with.  It's a shortened version of [EM]'s eliminating the new concepts because they were missing from the sandbox NCIt.

[EM-2020-06-09_CDISCALTDef.txt](https://github.com/NCIEVS/nci-protege5/files/4766890/EM-2020-06-09_CDISCALTDef.txt)

**Comment by singhik** [comment]
@NCIEVS : Hi, The file isn't formatted for 'Batch Load' as mentioned above, but for 'Batch Edit_Complex_Properties'. Used the same file with my Concept to add Alt-Def for Batch Operation 'Edit_Complex_properties' successfully multiple times .

This is tested in 3.5.0-qa1 Client and works as Expected, hence closing the ticket .
