### ISSUE TITLE
accepting nulls in metaproject - code generator

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#45]
The code generator can accept delimiters, prefixes, and suffixes.  If the json file is edited so that the delimiter is the empty string, codes look fine.  if the metaproject is edited through the gui, an empty string is not acceptable and the key needs to be deleted instead.  At runtime, a "null" is then inserted into the code where the delimiter would have been, e.g. "Cnull100".

**Comment by bdionne** [comment]
The meta project gui is changed now so that an empty value is allowed for the key. I've also [changed](https://github.com/bdionne/protege-server/commit/923e82836) the code generator on the server to handle the case where the delimeter is missing. So .eg. one can have `C44456S` as a valid code

**Comment by NCIEVS** [comment]
The values can now be null.  Labelling this as bug for V1 Release and ready for QA.  

However, there's another issue, will create a separate [ticket #96](https://github.com/NCIEVS/nci-protege5/issues/96) for it, where now the 'null' token is embedded in newly created codes.

**Comment by rmehri** [comment]
The fix for this issue has been retested and verified in tag-116, Edit Tab 0.3.1
Thanks,
Reza
