### ISSUE TITLE
Convert to Defined menu item is disabled

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#450]
From [NS]:
"This doesn't happen everytime but I see this often. I need to add a role to a previously defined concept, so 1. I make the concept primitive, 2. I add the new role and 3. then I make the concept defined again. Protege often won't allow you to do step 3 unless I save first. The "Convert to define class" menu item isn't available after step 2 so I must Save at step 2 and then do step 3 in a separate action."

**Comment by NCIEVS** [comment]
When this happens again, the information that would be very helpful to troubleshoot this is the protege.log, and the time when it happened.

Has as a workaround to Save at step 2.

**Comment by bdionne** [comment]
I tried this on several different primitive and defined classes, with no issue. Does NS or Al possibly have a class on which this happened that we can try?

**Comment by singhik** [comment]
@bdionne : 'Save' button is disabled when converting concept to 'Defined' , Save button remains disabled when a Role is added to the Concept ? Attached is the document with screen prints .

[Issue_450.docx](https://github.com/NCIEVS/nci-protege5/files/5329911/Issue_450.docx)

**Comment by bdionne** [comment]
@singhik     - if you could please enumerate the steps here in the ticket that would be more helpful. The screenshots don't seem to show any buttons at all, and they all appear to indicate you were on the general properties tab? The role you added is not a role but rather an annotation property.

It's ok to attach screenshots but they leave too much guess work. More importantly when we want to search the GH tickets in the future it won't search over attached word docs, that information gets lost. For example:

 * create a new class as a subslass of X (with not logical description
 * using the menu under edit, convert from primitive to defined ( see that save button is disabled )
 * add an object propert restriction (is it added as a subclass or an equivalent restriction?)
 * convert back to primitive (see that save is still disabled)

This is what I thought your screenshots were doing but I can't be sure. I tried this and it worked fine here.

Thanks

**Comment by singhik** [comment]
Tested on 3.5.0-qa1, works as Expected, hence closed .
