### ISSUE TITLE
New concept doesn't appear in hierarchy on Save

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#452]
From [EHD]:
"you create a concept but it doesn’t appear in the hierarchy when you save. If the editor adds a second parent the new concept will be displayed there. This is a display refresh issue and if you select Window>Refresh User Interface the terms will be found under all the parents ink  the hierarchy (unfortunately the hierarchy closes up and the editor needs to re-navigate to the new concept)."

**Comment by singhik** [comment]
@bdionne : Able to reproduce this issue, details @  https://github.com/NCIEVS/nci-protege5/issues/468

**Comment by bdionne** [comment]
fixed in [edit-tab-1.1.9](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.1.9)

**Comment by singhik** [comment]
Adding multiple concepts, child concepts, retree works fine on 3.5.0-qa1 with NCI EDIT Plugin 1.1.9,  issue of Save is not reproducible  , hence closed.
