### ISSUE TITLE
Add support for new reasoner NCI Curator

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#453]
Curator is a new lightweight reaonser intended to support more scalable classification. It implements the OWLReasoner interfaces defined in Protege and can be used as a plugin simiar to how we use Pellet today.

When the plugin is installed, it will appear as a new choice in the Reasoner menu

<img width="770" alt="Screen Shot 2020-07-02 at 12 10 39 PM" src="https://user-images.githubusercontent.com/31741/86384800-44c59000-bc5d-11ea-8989-e0b171629397.png">

It can also be configured, and has some additional real time edit checks that the reasoner supports

<img width="887" alt="Screen Shot 2020-07-02 at 12 10 54 PM" src="https://user-images.githubusercontent.com/31741/86384826-4ee78e80-bc5d-11ea-8c89-d70a734e424e.png">

These are enhancements to NCI EditTab. When chosen they will create popup warnings when the conditions obtain. One is when selection of a new parent is redundant (.ie. there is anoter parent that already is a subclass of the newly chosen one) or if a new parent would cause a class to have mutiple disjoint roots. 

<img width="1018" alt="Screen Shot 2020-07-02 at 12 16 49 PM" src="https://user-images.githubusercontent.com/31741/86385245-f238a380-bc5d-11ea-8da0-115f2dc64c60.png">

If the user selects "yes" then the changes are accepted, if "no" then they are backed out. If the user keeps the changes and ignores the warning they will still see the errors again on classification. The intent of this feature is to catch errors sooner and make for a cleaner terminology.

**Comment by singhik** [comment]
@bdionne  : Hi , Same comment as for #445  :: 

 Not getting the pop-warning which gives user the 'Accept' or 'Reject' options for 'Disjointness', 'Redundancy' or ' Language Constructs' ??  Tag is 3.4.0-qa1 . Concept gets saved successfully, without the Expected Warning prompt pop-up ?

![image](https://user-images.githubusercontent.com/36314371/88709801-a86b9d80-d0e3-11ea-88d4-da2961ab6c97.png)

![image](https://user-images.githubusercontent.com/36314371/88709839-b6212300-d0e3-11ea-9af9-29870b0e09ec.png)

**Comment by bdionne** [comment]
fixed in 1.1.4 of edittab

**Comment by singhik** [comment]
NCI Curator has been tested for Classification for Disjointness, Redundant Parents and scoped unsupported language constructs successfully in 3.4.0-qa2 Client console build , hence closing the ticket .
