### ISSUE TITLE
Failure to Save on Copy operation

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#454]
From [CM]:
"I had 2 instances this morning that I’d like to report. I used the Complex Edit tab to copy a concept to create a new one. In both instances, I saved the concepts in the complex edit tab. After it directed me to the Edit tab and when I was on the edit tab and tried to change the SYs, I could not save the SYs. Then I exited out of protégé and when I logged back in, the concepts were not there. The first one was Methylcantharidimide. The 2nd one was for C173428. (The concept PT I created was Autologous AFP Specific T Cell Receptor Transduced T Cells C-TCR055).

"I always create concepts this way and I almost never have a problem creating concepts."

And a clarification from [CM] on "After it directed me to the Edit tab...":
"When you copy a concept in the complex edit tab and then hit SAVE, the panel automatically moves to the Edit tab of the created concept. That’s what I meant with that. That to me means it was saved."

From follow up, the two instances of the issue came up around the times below, and included are other successful operations around these times.

- unsuccessful copy bug at 11:30 AM, 7/6/2020
- restart protege
- 3 successful copy operations
- unsuccessful copy bug again at 11:53 AM, 7/6/2020
- restart protege
- 10 successful copy operations

The zipped protege log is further below.  There are three WARN notices in the log surrounding the two times above:  

- warning:
2020-07-06 10:47:41.254 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
- restart in the vicinity of 11:30
- warning
2020-07-06 11:38:28.172 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
- restart in the vicinity of 11:50
- warning
2020-07-06 11:53:33.843 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null

Here's the zip of the protege.log

[protege_C.zip](https://github.com/NCIEVS/nci-protege5/files/4898027/protege_C.zip)

**Comment by bdionne** [comment]
Is this the same as #449 ?

**Comment by NCIEVS** [comment]
Doesn't look like it.  In #449 the clone got Saved and only some properties failed to be carried over.  In this one (#454) the cloned concept didn't get Saved.

**Comment by bdionne** [comment]
Still no logs or feedback from users. One small edge case was disciverd that will be fixed in next EditTab tag, but doesn't appear related to save failures

**Comment by NCIEVS** [comment]
Hi @bdionne , this ticket does have a zipped log file, it's at the bottom of the first comment.

**Comment by bdionne** [comment]
oops, sorry @NCIEVS I meant #451

**Comment by NCIEVS** [comment]
@bdionne , I just got a report from [AG], I'll be adding the details to this ticket in a few minutes.

**Comment by bdionne** [comment]
great @NCIEVS , feedback is good. I see he also saw #450 again as well

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, Multiple Iterations of the 'copy' operation is successfully performed on 3.5.0-QA1 built and this issue is 'not reproducible' , hence closing this ticket .
