### ISSUE TITLE
Add capability to display unsupported language constructs when used incorrectly in modeling

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#455]
This is more extensive than thought to add as part of the OWLReasoner interface, however a limited version that can display the incorrect usages will appear in the inferred results panel, allowing the user to click on the offending classes and return to them in the editor.

**Comment by bdionne** [comment]
It will look something like:

<img width="1138" alt="Screen Shot 2020-07-14 at 12 12 05 PM" src="https://user-images.githubusercontent.com/31741/87449575-5ac34100-c5cb-11ea-8a5b-295c561e6ccf.png">

**Comment by NCIEVS** [comment]
Nice!  I see the "only" in there.

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, For 'Language Constructs' , ' Disjointness' and 'Redundancy' , Editors wanted 'Reject' and 'Accept' buttons instead of 'Yes' and 'No'. Don't see them as yet. This is 3.4.0-qa1 build ::

![image](https://user-images.githubusercontent.com/36314371/88716561-3ac46f00-d0ed-11ea-91a5-df2e8e585fed.png)

**Comment by bdionne** [comment]
@singhik 

> Hi, For 'Language Constructs' , ' Disjointness' and 'Redundancy' , Editors wanted 'Reject' and 'Accept' buttons instead of 'Yes' and 'No'. Don't see them as yet

Actually I think the consensus was to sue `accept/cancel`, which isn't supported in Java `JOption` dialogs. So we try `ok/cancel` which is supported and looks pretty good.

I may have missed some code when I moved back to my regular machine, its looks like that plugin is not current

**Comment by singhik** [comment]
@bdionne : Hi , Plugin Screen shot, i am pointing to your(bdionne) repo in the Auto updater ::

![image](https://user-images.githubusercontent.com/36314371/88721242-259f0e80-d0f4-11ea-9e94-65fd2defd04c.png)

**Comment by bdionne** [comment]
it was missing code, check again you'll see 1.1.4

**Comment by singhik** [comment]
@bdionne : Hi, getting two pop-up warnings on Language Constructs  , same for Disjoint and Redundancy . JOptionPane Standard dialgoue boxes function is getting invoked twice for a call  , perhaps a code error ?

**Comment by bdionne** [comment]
@singhik - see #445

**Comment by singhik** [comment]
@NCIEVS : Hi, For every Unsupported Language Construct, which shows a Warning Pop-Up in Edit Tab , post classification, we should see them all under 'Inference Results'->'Unsupported Constructs' ?? 

When i added below, all did show the Pop-up for Language Construct Not Supported, but post classification were not seen in Inference Results ->Unsupported Constructs Panel :: 

![image](https://user-images.githubusercontent.com/36314371/89338639-d5cbc480-d66a-11ea-9c0d-438aa84a27e8.png)

![image](https://user-images.githubusercontent.com/36314371/89338782-175c6f80-d66b-11ea-8d15-7a24d7c7e619.png)

![image](https://user-images.githubusercontent.com/36314371/89338876-3c50e280-d66b-11ea-8183-b7c29386ecea.png)

**Comment by NCIEVS** [comment]
@singhik , ah yes.  @bdionne and I had been talking about the best presentation for these unsupported constructions, and instead of showing them under "unsupported" section, we'd make the class unsatisfiable, i.e. subclass of or equivalent to "owl:Nothing".  They would still be classifiable with pellet, but if they accidentally use an unsupported construction (i.e. click on the wrong yes/no button), the classification result with Curator would entice the user to fix it.  So the above result looks fine.

**Comment by bdionne** [comment]
I can look at this case, but I'm agreeing the more I think about it @NCIEVS that just making these inconsistent is probaly the safest. At a glance it looks like this on also has disjoint parent, which is making it inconsistent so the classifier might not even get to the bad roles, I'll have to check.

Maybe a good approach would be to designate it as inconsistent and if we have the bad constructs not that in parenthesis, which would hint to modeler to go back into the editor and see what's wrong.

**Comment by fragosog** [comment]
Hi @bdionne , I thought you had done it already & didn't dig deeper.  My bad.  No need spend time on it now, can continue bouncing this around later.

**Comment by bdionne** [comment]
@fragosog no, that case above turns out inconsistent because of the disjoint parents. It probably doesn't display the bad roles because the classifier stops earlier on that class. I can check that.

The change we discussed is more involved really and we need to think through it before making it. At least not this close to release time.

**Comment by singhik** [comment]
@NCIEVS : Hi, This has been tested for Language Constructs Pop Warning on 3.4.0-qa2 build client, but as it needed few more changes per above comment, can i move it from current milestone to Future Milestone ?

**Comment by singhik** [comment]
@NCIEVS @bdionne  : This ticket works fine for the scoped unsupported language constructs , for other unsupported constructs ,this ticket might be looked at a later point in time in Future Milestone Releases. Hence ,closing the ticket with Tag 'Future Release Item' to cover other scoped use cases
