### ISSUE TITLE
Add suggestion to remove redundant parents in the inferred results panel

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#456]
Occasionally modelers add parents that are ancestors of existing parents, making them redundant. It has no impact on classification but modelers prefer to get them out.

Add a suggestion to remove them in the inferred sults panel

**Comment by NCIEVS** [comment]
For an example see [here](https://github.com/NCIEVS/nci-protege5/issues/445#issuecomment-660295207) over at #445

**Comment by bdionne** [comment]
Turns out this is quite expensive, and the use case from the modelers need clarification. Will review in next release

**Comment by NCIEVS** [comment]
On review with [EHD] & [NT], a federated sparql query (#461) on a monthly export will suffice for periodic reviews.  Closing.

**Comment by NCIEVS** [comment]
Just to add the feedback noted above.

EHD. Yes the sparql query helps, and now the editor is warned during editing that they may be creating these redundancies. However, it would still be nice if the reasoner could point these out, as we are reliant on [GF] to do the query.

NT. The warning seems to work for most routine problems
