### ISSUE TITLE
Builds appear unstable

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#459]
@singhik I'm opening a new ticket for this as it's not good to clutter all the other tickets with unrelated issues.

The Jenkins build process does not appear to produce a valid build of the latest tag. When Jenkins is run and the `3.4.0-qa2` is specified the build produced has numerous errors and displays `3.3.1-qa1` as the version number.

Additionally the code is unstable, several things appear broken

**Comment by bdionne** [comment]
presumable the last build is ok now, and #440, #451, and #425 can be tested.

**Comment by singhik** [comment]
Build issue has been sorted and verified for correct version , hence closing this ticket
