### ISSUE TITLE
Addition Of Complex Properties To a Concept  Does Not Enable Save Button

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#460]
@bdionne : Hi, Addition of complex properties to a concept does not Enable Save Button, Screen greys out , Attached are the screen prints, Save is also disabled for deleting Complex Properties, Adding Simple properties and Adding Subclass  ::  Build  3.4.0-qa2 

![image](https://user-images.githubusercontent.com/36314371/89227435-abff9880-d5ab-11ea-8e12-4a7363c297ac.png)

Screen Greys Out 
![image](https://user-images.githubusercontent.com/36314371/89227454-b5890080-d5ab-11ea-92ee-8f7d3d1c84ff.png)

Then on Navigation Control and back to concept, the added Property is displayed, no Save button is enabled :

![image](https://user-images.githubusercontent.com/36314371/89227513-d4879280-d5ab-11ea-8aea-0bce2a6df7f9.png)

![image](https://user-images.githubusercontent.com/36314371/89227539-dea99100-d5ab-11ea-9aff-904e70a6c678.png)

Screen Greys Out : 
![image](https://user-images.githubusercontent.com/36314371/89227563-e9642600-d5ab-11ea-9cc6-acf0abacad0a.png)

On Navigation control and back to concept, added Alt Def is displayed without Save button being enabled : 

![image](https://user-images.githubusercontent.com/36314371/89227607-ff71e680-d5ab-11ea-9115-ae1f752151fb.png)

**Comment by singhik** [comment]
From @NCIEVS  :: "Hitting 20.04a NCIt, didn't do the trick, deleting .fileprefs & reconfiguring didn't do the trick.  Wasn't sure what to make of the curator exception since it didn't show up in all my runs.  

However, I unchecked the curator checks in the GUI and now the Save button is enabled, both edits to full_syn and DEF appear as uncommitted changes, and the class can be Saved (after first deleting the extra definition).  So this might be it. ""

**Comment by bdionne** [comment]
fixed in `edittab 1.1.7`

**Comment by singhik** [comment]
@bdionne  : Hi, on the first glance it seems to work fine but can i take this for full regression ? Cause you mentioned 'partially' fixed ? Is there a new build or plugin expected to be released ?

**Comment by bdionne** [comment]
@singhik - I mentioned partially because I was only able to reproduce the error for complex and simple properties. I was not able to reproduce it for subclasses and object properties as you claimed. Perhaps you can try those scenarios again and see if those are fixed also.

**Comment by singhik** [comment]
Working Fine in 3.4.0-qa2 Client build, hence closing the ticket .
