### ISSUE TITLE
Null Pointer Exception On Inferred Hierarchy During Classification 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#464]
From Liz :: 

• Which operation failed? (such as Merge, Copy, Creation, PT 
changing) Lost the save button 
Classification 
• Approximately what time did this failure occur? 
7:55   AM 
• Description or sequence of steps followed: 
Selected Reasoner>Start Reasoner 
• Concepts involved: 

• If necessary, please include the state that the concepts were in at the time of the incident (e.g. edits of roles, defined/primitive changes). Screenshot is good if possible.

• Outcome (screen frozen, concept not created, had to log out and in to get things to work better): 
Null Pointer Exception 

![image](https://user-images.githubusercontent.com/36314371/89900324-998bed00-dbb1-11ea-9912-cf8bf7ed1d93.png)

![image](https://user-images.githubusercontent.com/36314371/89900343-a0b2fb00-dbb1-11ea-9026-6ce33c7274e9.png)

![image](https://user-images.githubusercontent.com/36314371/89900350-a577af00-dbb1-11ea-9518-3d019d0bbb79.png)

[Error_Message.txt](https://github.com/NCIEVS/nci-protege5/files/5057111/Error_Message.txt)

[Logs_2020-08-11.txt](https://github.com/NCIEVS/nci-protege5/files/5057116/Logs_2020-08-11.txt)

From NCIEVS :: 

To change the configuration of Client  , File -> Preferences -> Reasoner -> Displayed inferences to show the 'Satisfiability' and 'Equivalent' Classes clicked. 

![image](https://user-images.githubusercontent.com/36314371/89900875-4fefd200-dbb2-11ea-8b10-ca75f2ee4286.png)

**Comment by bdionne** [comment]
This is easily reproducible and can likely be fixed in the next curator plugin release. The old classifier exhibits the same problem. 

There's an easy workaround for now, just configure the project correctly.

**Comment by bdionne** [comment]
fixed in [curator-0.0.4](https://github.com/bdionne/nci-curator/releases/tag/curator-0.0.4)

**Comment by singhik** [comment]
No Exception found on 3.5.0 built with 0.0.5 Curator Plugin, while classification post multiple edits , hence closing the ticket ....
