### ISSUE TITLE
Fileprefs padded with thousands of \u0000 after adjusting preferences

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#465]
When editing preferences within the Protege client the .fileprefs will be padded with string text of \u0000 thousands of times.  This can cause the application to hang and be unable to close.  

This affects tag V3.4.0-qa2

**Comment by bdionne** [comment]
> When editing preferences within the Protege client 

@safrant Which preferences were edited, and in what order? After editing did you close the app by quitting or did you use the close icon.

**Comment by NCIEVS** [comment]
Was the fileprefs file used for the configuration taken from a template?  Or was it the default fileprefs file that gets created on first use of protege?

**Comment by bdionne** [comment]
possible workaround in [edit-tab-1.1.9](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.1.9) We should try to reproduce this

**Comment by safrant** [comment]
Steps to reproduce https://cbiit-download.nci.nih.gov/evs/Protege/Protege-5-Snapshots/Protege_filePrefs.mp4

**Comment by singhik** [comment]
Tested on 3.5.0-qa1 built, works as Expected hence closing the ticket
