### ISSUE TITLE
Feedback from UAT on staging tier

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#468]
The modelers have spent a couple of days with `3.4.0` on the staging tier and have run into a number of issues, a few of which are existing known issues and some are new. This is a placeholder ticket mainly to have all this feedback in one place. The items that arose:

 1. build issues. A couple of nits with preferences, and a bug in the serialization of the fileprefs file (see #465) 

 2. Editing a new concept (Liz, #466) the save button becomes disabled, the navigation pane collapses, and GUI freezes. User needs to logout/login. No usable info in the logs

 3. Failure to convert primitive to defined (Al, #467). This we've seen before (#450) and at times we've seen the menus for conversions disabled when they should be enabled. The conversions fails and save button is disabled. No usable info in the logs

 4. GUI freezes (Liz) when browsing, looking at content that another modeler just edited. Known issue, perhaps different scenario. No useful information in the logs.

 5. GUI freezes (Nick). Modeler edits a class while classifying then tries to cancel the classification. GUI hangs and no class is saved. No usable info in the logs. We may want to make this progress bar modal

 6. Save button is disabled (Nicole). New parent is added to a class, original parent deleted and save button is lost. No usable info in logs, user needs to relogin to get back to normal. Note that this is similar to the `prim->defined` conversion in item 3 in that a common workflow is to convert defined to primitive, edit the parents, then convert back

 7. Navigation pane collapses to `owl:Thing` (Nick, Liz). This also happened after a classification as well as described in item 2 above

 8. Save button disabled (Alex Chang). Similar to others involving editing parents. User creates a new class and saves ok. Changes focus then comes back to edit parents, adding new parent. Save button is disabled. No usable info in the logs

**Comment by fragosog** [comment]
In #4 above, the parallel edit [AG] had resulted in a class equivalent to its superclass which later led to followup questions on "circularity" of relations.

**Comment by fragosog** [comment]
In #5 above, canceling the classifier disallows further actions until the classification is finished.  Not the best behavior but it has always been like this.

**Comment by fragosog** [comment]
In No. 8 above the Save button came back after a while without a restart.

**Comment by singhik** [comment]
@NCIEVS @bdionne : Hi, I am **able**  to reproduce the disabling of Save Button or Save Button not working . Below are the steps to Reproduce ::

Create a Concept (Test_1), Add a complex property ALT-DEF , Try to save the Concept, 

**Issue** : 'Save' button is enabled but does **not** work i.e. Concept is not saved and 'Class saved successfully' dialog box does not appear post clicking on 'Save' button .


![image](https://user-images.githubusercontent.com/36314371/95119172-89a80980-0719-11eb-899c-1e3f0586c568.png)

**Comment by bdionne** [comment]
All issues referenced in this ticket have been addressed and marked fixed, so I'm closing this. Some of the items have not been reliably reproduced. We can open new tickets for them as they occur.
