### ISSUE TITLE
Tag-nci-0.101-Log In Server-Clicking Windows/Tabs/Server Administraton-Gui freezes Up

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#47]
User root Login

Server address: http://localhost:8081

Login:root

steps to reproduce:

1) Login to server: http://localhost:8081
2) User: root
3) Pass:rootpwd
4) Click Windows/Tabs/Server Administraton
5) The whole Gui freezes up
6) The continues java errors occur.
7) I am able to logout server.

Please see attached screen shots for more details.

Thanks,
Reza

> ![window-tab-server clicked-error](https://cloud.githubusercontent.com/assets/8367102/19407222/31c90b02-9269-11e6-878d-6a3afe1e7e1b.png)
> ![clicked server administration_freezing and error occured](https://cloud.githubusercontent.com/assets/8367102/19407223/3ad61bb8-9269-11e6-8fe0-e9f131e6a2f3.png)

[nci_0101_Server_Login_Freezing.txt](https://github.com/NCIEVS/nci-protege5/files/530748/nci_0101_Server_Login_Freezing.txt)
or.txt)

**Comment by rmehri** [comment]
Need to test further.

**Comment by NCIEVS** [comment]
When login as an admin, the server admin tab comes up by default.  Clicking on it in windows/tabs/server-adiministration disables it and throws an out-of-bounds.  Fix requires that the last remaining tab on protege cannot be unselected.  Will label as bug and future release.

**Comment by bdionne** [comment]
no longer using two ports for admin gui, we've not had any reports about freezes in this area
