### ISSUE TITLE
Classification Failure  - Production Environment Protege

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#470]
From Editors :: 

*            Description or sequence of steps followed:
I started the classifier and the progress bar window opened, b

ut even though the progress bar had only progressed 10%, the Classification Finished popup appeared and when I hit OK, I could see that the classifier progress had stalled.

 
*            Concepts involved:
See below

 
*            If necessary, please include the state that the concepts were in at the time of the incident (e.g. edits of roles, defined/primitive changes). Screenshot is good if possible.
I had logged in around 1:15 and created several new chromosomal translocations and gene fusion concepts. Here is a list of the last codes I created but I had also modeled some existing terms.
C174475
C174476
C174477
C174478
C174479
C174480
C174481
C174482
C174483
C174484

*            Outcome (screen frozen, concept not created, had to log out and in to get things to work better):
I tried to cancel the classification but it didn't seem to work. So I closed the listener window to kill the GUI instance and then I logged in to try again. After logging in again, my attempt to classify was still not successful even though classification did seem to make progress. 

[Protege_Logs.zip](https://github.com/NCIEVS/nci-protege5/files/5228523/Protege_Logs.zip)

**Comment by bdionne** [comment]
@singhik @NCIEVS This is a production bug, against 3.3.0. It's not clear there's anything to do for this in the 3.5.0 milestone unless the same issue occurs there. So far I haven't seen anything

**Comment by bdionne** [comment]
pretty sure this is the content re-treeing issue that led to the thesaurus no longer being classifiable
