### ISSUE TITLE
Full Syn Complex Pty Not Visibile - Production Env - Not Reproducible 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#471]
From Editors ::

"Unable to view Full Syn property for  a Concept  'Adenosarcoma' (C9474)  in Production " 

@singhik  : This issue is not reproducible on QA Environment for 3.3.0 built on 1.1.0 NCI Edit Tab Plugin which is what production has. Attached is the document with results .

[Protege_Full-Syn.docx](https://github.com/NCIEVS/nci-protege5/files/5228543/Protege_Full-Syn.docx)

**Comment by bdionne** [comment]
@singhik Isn't this a duplicate of #469 ?

**Comment by singhik** [comment]
@bdionne : Hi, yup, i wasn't aware if @NCIEVS  raised one  too, will close this as duplicate
