### ISSUE TITLE
remove cancel button on curator progress and make modal

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#472]
classification process never stops so the cancel button never really did anything. The progress bar is now modal, always on top, and prevent the modeler from editing while it is running

**Comment by bdionne** [comment]
available in [0.0.3](https://github.com/bdionne/nci-curator/releases/tag/curator-0.0.3) of the curator

**Comment by singhik** [comment]
@bdionne : PLease specify details of the new classification function that has been added with ? Unable to guage any change or amendment from the description above

**Comment by bdionne** [comment]
@singhik - not sure you have the newest [0.0.5](https://github.com/bdionne/nci-curator/releases/download/curator-0.0.5/nci-curator-0.0.5-SNAPSHOT.jar) or not, I havent' tagged it yet, but you should see two differences. This also applies to #428 

For small classification jobs, they were finishing so quickly that the confirmation dialog was becoming visible before the progress bar (in a separate thread) completed and disposed. So it was getting stuck. Also, while it was running you could force the progress bar in the background and continue to edit. Which is ok, but created modeling problems.

With the newest one, the progress bar is modal, and has no cancel button. It stays on top of the app until it completes and then the confirmation dialog comes up. You should not see it wedge

**Comment by singhik** [comment]
@bdionne  : Hi, I am able to see the 'Cancel' button and also able to perform 'Edit' , while the Classification is in-progress ? On 0.0.5 Curator .

Classification started : 

![image](https://user-images.githubusercontent.com/36314371/95395538-dc75f280-08cc-11eb-9921-f07934821d37.png)

Able to Edit a Concept ,while Classification is on : 

![image](https://user-images.githubusercontent.com/36314371/95395592-fd3e4800-08cc-11eb-97f9-1a5a10edd913.png)

![image](https://user-images.githubusercontent.com/36314371/95395608-04655600-08cd-11eb-9864-1c60a49baa67.png)

Classification is still in-progress while the Edit above is saved : 

![image](https://user-images.githubusercontent.com/36314371/95395622-0f1feb00-08cd-11eb-9bc3-07b67011f169.png)


Plugin Details : 

![image](https://user-images.githubusercontent.com/36314371/95395818-78076300-08cd-11eb-9a0e-a6eec285c26e.png)

**Comment by bdionne** [comment]
@singhik - you have the wrong version of the plugin. I pushed another 0.0.5 jar file as the first was the wrong one. It must have happened after you updated your plugins. You can delete the plugin and download it again, and you should see it working.

I'll also be pushing a new 0.0.6 in the next couple of days, that will include this as well. Sorry for the confusion

**Comment by singhik** [comment]
@bdionne : Hi , has the 0.0.6 plugin been published as yet ? I am pointing to bdionne's repo and don't see it .

**Comment by bdionne** [comment]
@singhik not yet, we haven't yet finished fleshing out the requirements for the `3.6.0` features. 

But for now, if you delete your local `0.0.5` plugin and download what's there now, it will have all the features you're testing in `3.5.0`
