### ISSUE TITLE
Additional curator checks

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#474]
A couple of issues have come up affecting classification in the thesaurus that can be better handled with additional edit time checks by the curator:

 * Ensure that a class that is fully defined does not also have subclass axioms (prevent use from accepting)

 * Ensure that when a class is re-treed (.ie. it's parentage changes) that the domain of the new parent still agrees with the ranges of any object restriction that is currently pointing to it. (prevent use from accepting)

This second instance recently produced a thesaurus with many inconsistencies that failed to classify (see #470)

**Comment by bdionne** [comment]
> Ensure that when a class is re-treed (.ie. it's parentage changes) that the domain of the new parent still agrees with the ranges of any object restriction that is currently pointing to it. (prevent use from accepting)

After discussions with the modelers the consensus was that they only want to see warnings about retreeing in the case where the new parent is in a different disjoint domain, and the class being retreed has usages elsewhere, .ie. classes that refer to it. In this case:

 * popup a warning dialog that only has two buttons, one to cancel the edit and the other to show the usages
 * if the user clicks to see the usages, popup another window that shows the usages, and has an export button that prompts for a file name and dumps the usages to a text file.

After the user cancels to close the warning window, or clicks to see the usages and exports to a file, theedit is backed out. In order for the user to perform this retree operation they will need to collaborate with others and use the entities tab to review and edit the usages. The main goal is to prevent the user from retree operatoins that lead to inconsistencies down the road when classification is performed.

**Comment by bdionne** [comment]
> Ensure that a class that is fully defined does not also have subclass axioms (prevent use from accepting)

So it turns out this can happen few different ways:

 * convert a primitive to defined, then separately add another subclass axiom
 * add an equivalent axiom directly
 * merge a primitive classed into a defined one

**Comment by singhik** [comment]
@bdionne : Hi,  This Ticket is not clear on the Requirement  and what has been implemented :: 

Q1> A Concept which is a subclass of a concept, can not be converted to Defined class ?
   Every concept that is not under root(owl:Thing) Tree will have a subclass clause, so does this mean none of the concepts can be converted to Defined now ?
	
The handled  Warning message when converting Primitive to Defined says 'A defined class needs to have two or more conditions', what are those conditions ?

Q2> Re parenting of a concept with usages f.e. Antigen Gene(C54259) is allowed to a Disjointed Concept f.e. LE Cell(C36716) , only a Warning message appears which shows a warning that this re-parenting will create multiple disjoints, but does not stop the user from reparenting  and also the Usages information is not shown ?

**Comment by bdionne** [comment]
@singhik 
> Q1> A Concept which is a subclass of a concept, can not be converted to Defined class ?

Not sure how you conclude this? As stated at the top of the ticket:

> Ensure that a class that is fully defined does not also have subclass axioms (prevent use from accepting)

What this means is that once a class is defined, one cannot then add a subclass reatriction. There's a couple of ways that happens. One is just adding one, for example here is an attempt to add the subclass `Behavior` to an already defined class:

<img width="1019" alt="Screen Shot 2020-11-27 at 5 18 32 AM" src="https://user-images.githubusercontent.com/31741/100438890-c8e73c80-3070-11eb-9467-c28fc30bcfca.png">

The other way it can happen is during a merge, if the source is primitive and the target defined.

> Q2> Re parenting of a concept with usages f.e. Antigen Gene(C54259) is allowed to a Disjointed Concept f.e. LE Cell(C36716) , only a Warning message appears which shows a warning that this re-parenting will create multiple disjoints, but does not stop the user from reparenting and also the Usages information is not shown ?

That's correct, and I think it's because you added an additional parent. It will warn you if it creates a disjoint situation. Re-treeing is when you select an existing parent and modify it. Here's an example:

<img width="1189" alt="Screen Shot 2020-11-26 at 2 05 46 PM" src="https://user-images.githubusercontent.com/31741/100439312-62aee980-3071-11eb-8ec2-cfc12c23176c.png">
<img width="1085" alt="Screen Shot 2020-11-26 at 2 06 04 PM" src="https://user-images.githubusercontent.com/31741/100439326-65a9da00-3071-11eb-97ad-0b8949b1a063.png">
<img width="1226" alt="Screen Shot 2020-11-26 at 2 06 17 PM" src="https://user-images.githubusercontent.com/31741/100439329-66427080-3071-11eb-9094-a4118c457c52.png">

**Comment by singhik** [comment]
@bdionne : Hi, For "Ensure that a class that is fully defined does not also have subclass axioms (prevent use from accepting)" , this is allowed via Merge operation ? 

**'Test c' is defined and 'Test 4' is primitive :** 

![image](https://user-images.githubusercontent.com/36314371/100477801-6feec700-30b7-11eb-9730-93d48ae0f0a7.png)

**Merging 'Test 4' (Retiring Concept) into 'Test c'(Surviving Concept) :** 

![image](https://user-images.githubusercontent.com/36314371/100477878-9e6ca200-30b7-11eb-87ec-19e616ddcdff.png)

**Adding a SubClass axiom to 'Test c'  a defined concept :** 

![image](https://user-images.githubusercontent.com/36314371/100477916-b7755300-30b7-11eb-9151-7749a31bcc9c.png)


**'Merge' :** 

![image](https://user-images.githubusercontent.com/36314371/100477963-c78d3280-30b7-11eb-8705-3b335651f346.png)

![image](https://user-images.githubusercontent.com/36314371/100477977-d378f480-30b7-11eb-9413-5bf512ed72f1.png)

![image](https://user-images.githubusercontent.com/36314371/100478006-e095e380-30b7-11eb-8119-b154649b2f37.png)

![image](https://user-images.githubusercontent.com/36314371/100478019-f0adc300-30b7-11eb-878c-aa93a69b62e7.png)

**Comment by bdionne** [comment]
With respect to the merge, that's an interesting test case, though I don't think the modelers would ever do that. The assumption I make in merge is that if you are merging a primitive into a defined class then take the primitives parents and add them to the definition.

In your test you perform an edit on the definied class, adding another parent. In this case the way the merge works it also incorporates that parent for the seame reason. This is different from a plain edit of a defined class where if you add a new parent we will prevent it.

So I think this is correct

With respect to the export, disjoints are filtered out and I believe all you will see are uses that are subclass restrictions of role restrictions where the filler points to the class in question.

Again I don't think this likely, and I'd like to see how they use this first, but if needed it would be a minor change to take this filter out.

I notice in your examples @singhik that you have some min cardinality and only restrictions. Presumably you are seeing the warnings, unless you have those prefs disabled, and you are just accepting them.

**Comment by bdionne** [comment]
This ticket needs more work to clarify issues raised by modelers (see attached)
[retreeing-warning-alternatives-rev.xlsx](https://github.com/NCIEVS/nci-protege5/files/5857504/retreeing-warning-alternatives-rev.xlsx)

**Comment by singhik** [comment]
@bdionne @NCIEVS  : 

![image](https://user-images.githubusercontent.com/36314371/106075811-5cbe9e80-60dc-11eb-9504-4189e7ff329b.png)
