### ISSUE TITLE
Adding Complex Property - Defect

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#475]
@bdionne : Adding COmplex Property Issue.

Steps : 

1. Create a Concept .
2. Right click on the concept and create a Complex Propety f.e. ALT-DEF and/or Maps_To .

Expected  : 

After adding the complex property details, the 'Choosing Complex Property' DIalog box should close and the Property should be displayed as added to the concept and 'Save' should be enabled .

Actual : 

After adding the complex property details , The added 'maps_to' is not displayed post closing the complex property dialog, It is displayed after clicking on 'Save' button, but it overwrites the already exisiting 'DEFINITION' property ?? Below are the screen shots 

![image](https://user-images.githubusercontent.com/36314371/95122683-df32e500-071e-11eb-9b23-3f414941fa54.png)

![image](https://user-images.githubusercontent.com/36314371/95122734-f4a80f00-071e-11eb-8262-696c4fd82bd5.png)

![image](https://user-images.githubusercontent.com/36314371/95122805-07224880-071f-11eb-907d-f1c10574b2c7.png)

![image](https://user-images.githubusercontent.com/36314371/95122837-17d2be80-071f-11eb-8dae-aadbeb1ee36e.png)

**Comment by bdionne** [comment]
Good find @singhik this is very reproducible and I suspect this is releated to the comments you made in #468

**Comment by bdionne** [comment]
fixed in [edit-tab-1.1.9](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.1.9)

might need to delete fileprefs first time

**Comment by singhik** [comment]
Works fine on 3.5.0-qa1, with NCI EDIT Plugin 1.1.9 . Hence closed.
