### ISSUE TITLE
Performing Multiple Edits With Multiple Users Throw "Commit Failed" Error 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#477]
@bdionne : Hi, while doing parallel Edits on QA Server on same Project (QA-Thesaurus-3.5.0), both @singhik and @safrant   have faced this Commit Error, everytime we do an Edit and try to Save the Edits ??

Login to two or more Protege Client INstances (3.5.0) with NCI Edit Tab plugin 1.1.9 and do Parallel operations and Edits like Concept Creation, Retire, Delete ,add annotations . 

![image](https://user-images.githubusercontent.com/36314371/95905803-4aa43480-0d67-11eb-9df1-107de7e9c644.png)

![image](https://user-images.githubusercontent.com/36314371/95906467-272db980-0d68-11eb-9359-4e14413c9e52.png)

So, unless we do a manual 'Server->Update', everytime, this error keeps re-occurring .

[logs.txt](https://github.com/NCIEVS/nci-protege5/files/5373613/logs.txt)

**Comment by bdionne** [comment]
@singhik I'm not sure this is a bug, it's supposed to work that way if you're withing the polling interval

**Comment by singhik** [comment]
@NCIEVS : Hi, Please review and provide your insight .

**Comment by bdionne** [comment]
@singhik - as described current, this works as intended

**Comment by singhik** [comment]
@bdionne : Steps to reproduce are provided above which are ""Login to two or more Protege Client INstances (3.5.0) with NCI Edit Tab plugin 1.1.9 and do Parallel operations and Edits like Concept Creation, Retire, Delete ,add annotations ."" 

@NCIEVS needs to review and sign-off if this is Expected .

**Comment by NCIEVS** [comment]
The polling interval is set to 30 seconds in QA.  Can't check prod at the moment.  But perhaps we should test what is the best polling interval for this scenario?  

The behavior, the popup notice, at first sight it doesn't seem to be a bug.  Concerning "unless we do a manual 'Server->Update', everytime, this error keeps re-occurring", question:  does the popup keep reappearing when there's no concurrent editing going on anymore?

**Comment by singhik** [comment]
@NCIEVS : Hi, No, The pop-up appears only during parallel editing on the same Project.

**Comment by bdionne** [comment]
@singhik - The server acts as a version control system. As edits occur the version number increases and has to be linear. So the sequence might look lilke:

`1->2->3->4`

When two editors save something concurrently, one will produce:

`1->2->3->4->5`

The other will try to do the same, and fail. After manually updating, it can then save and produce:

`1->2->3->4->5->6`

This updating often happens automatically because the clients poll, in this case every 30 seconds. If two editors both edit concurrently within that 30 second interval, one will commit and the other will fail

**Comment by singhik** [comment]
As per above comments from  @NCIEVS , parallel edits done within 30 seconds of interval will cause the Pop Up warning and is expected behavior, hence closing the ticket .
