### ISSUE TITLE
Illegal equivalent classes at root break Curator

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#479]
Steps to reproduce:

 * create a child of one of the disjoint root classes
 * convert this child to a defined class (this step is illegal and should be prevented as it violates an NCI rule)
 * run curator

It will blow the stack. It's an edge case and should never happen when edit checks prevent it (#481). This is came up when triaging #478

**Comment by singhik** [comment]
@bdionne : 

1. Concepts 'LE Cell' and 'Activity' are disjointed  and Concept 'Test c' is a subclass of both of these disjointed concepts : 

![image](https://user-images.githubusercontent.com/36314371/100287695-1c5b6c80-2f43-11eb-8cf1-53bdef5e2271.png)

2. 'Test c' is able to get converted to Defined, without any warning to prevent it  <?> : 

![image](https://user-images.githubusercontent.com/36314371/100287742-3a28d180-2f43-11eb-83d4-725ef4be08a7.png)

**Comment by bdionne** [comment]
@singhik yes, you can do this. When you add a second parent, if it's disjoint you see the warning and can still proceed to accept the edit. You can then convert that to a defined class.

This error is about something different. If you follow the steps to reproduce above, you can see this error. However the steps to reproduce above won't work because you can't convert a primitive class with only one parent to a defined one. You'll see this:

<img width="1018" alt="Screen Shot 2020-11-27 at 5 41 59 AM" src="https://user-images.githubusercontent.com/31741/100440806-76f3e600-3073-11eb-9f74-82368d2701c3.png">

If you use the older system, you can reproduce this error. As noted above, create a class with a single parent, convert to defined, and then run the classifier. It will hang.
