### ISSUE TITLE
Users should not be allowed to complete a definition unless it has at least two conditions

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#481]
A modeler should be prevented from converting a class from primitive to defined unless it has at least two conditons.

A condition can be any `subclass` axiom, a role restriction, parent, or other logical expression.

This is a feature from the `3.4` version that was not ported.

**Comment by singhik** [comment]
@bdionne  : 'Test c' has a 'subclass axiom' and a 'disjoint with' , it is not allowing to convert to Defined ? 

![image](https://user-images.githubusercontent.com/36314371/100291138-f33eda00-2f4a-11eb-81e7-1588baaac58f.png)

![image](https://user-images.githubusercontent.com/36314371/100291161-ff2a9c00-2f4a-11eb-8159-5e4ec6855f30.png)

**Comment by bdionne** [comment]
@singhik The two conditions refer to `subclass` restrictions. These can be parent, object restrictions, or conjunctions and so forth. Basically anything in the `subclass` section. Not all thing can be used, .eg. we only allow `some` restrictions, not `all`, but you'll get warnings for the bad ones.
