### ISSUE TITLE
Edit Tab doesn't initialize properly when semantic type is missing

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#482]
from @ncievs:
The server's project configuration file has a semantic_type key for a property used for semantic types.  The semantic type is optional in the vocabulary and class creation shows no issues.  But a semantic type property still needs to be declared in the vocabulary and used as the value for the semantic_type key, otherwise the nci-edit tab complains at the completion of the vocabulary load and nci-edit can't be used (the vocabulary is loaded and accessible from the entities tab though).  It seems that the semantic_type key should be optional in the configuration file and the nci-edit tab should ignore it if missing.

**Comment by singhik** [comment]
Assigning the ticket to @safrant for validation as it corresponds to project template/attributes at server level .

**Comment by safrant** [comment]
I removed the semantic_type option from an existing project using the admin tool.  I then opened the project using the 3.7 client and had no issues viewing the NCI Edit Tab.

I then deleted the Semantic Type property from a class and it saved successfully.
