### ISSUE TITLE
Class creation dialog need to be updated to remove definition source artifacts

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#483]
from @ncievs 
In the createDefinitionPanel method in NCIClassCreationDialog.java there are two spots with hardcoded values for the ncit's definition source, lines 198 & 219, e.g.

`    		if ((propShortForm.equals(DEF_SOURCE)) ||
    				(propShortForm.equals("P378"))) {
`

This doesn't disallow using other properties for definitions, but the above "def_source" also shows up in the class creation dialog for the definition.

**Comment by bdionne** [comment]
fixed in nci-edit-tab-1.2.5

**Comment by fragosog** [comment]
Hi @singhik , there should not be an observable difference in the NCIt.  It's when you configure the NCIt to use a different property for the 'definition source' that you'd see a difference.  Say you create 'my definition source' annotation property, and then configure the project to use that property for the def source:  previously you would have seen 'my definition source' as well as 'definition source' because the latter was hard-coded.  But in this version you would only see 'my definition source'.  Let me know if you need a hand creating that property or configuring the project.

**Comment by safrant** [comment]
To Test:
1. Login as admin user
 
![Screen Shot 2021-05-12 at 5 44 06 PM](https://user-images.githubusercontent.com/2364871/118048180-e7ed3880-b349-11eb-856d-c11888250042.png)

2. Choose a project and click the edit icon next to it in the listing
![Screen Shot 2021-05-12 at 5 44 26 PM](https://user-images.githubusercontent.com/2364871/118048221-f8051800-b349-11eb-9914-9e2c36341209.png)

3. Change the def-source option to the qualifier you wish to use as the def-source
![Screen Shot 2021-05-12 at 5 44 50 PM](https://user-images.githubusercontent.com/2364871/118048309-179c4080-b34a-11eb-9764-c3c450c4b9ab.png)

4. Save the JSON to the server
![Screen Shot 2021-05-12 at 5 45 05 PM](https://user-images.githubusercontent.com/2364871/118048334-2551c600-b34a-11eb-85e0-59eed23c2a81.png)

**Comment by NCIEVS** [comment]
One (or two) additions to the above.  The "my definition source" property also needs to be added as a value of the "definition" property.  the IRI of the definition property will appear as its own key in the "options" dialog (like every other complex property, this is where you specify the qualifiers).  Once you do that you won't see the original "definition source" but then you'll see the new "my definition source".  The second addition would be that as configured in this description, the "my definition source" will appear as a text box in the dialog.  If you want to show a drop-down associated with it, then the range of the declaration of "my definition source" should point to an enumerated datatype.  For testing purposes, you can use the same range specifed in "definition source" for "my definition source".

**Comment by NCIEVS** [comment]
And just to clarify the comment above, for "2" , to get a dropdown, this you would do in the entities tab not in the project configuration.

**Comment by singhik** [comment]
@NCIEVS @bdionne  : Hi, this has failed in re-test . Steps performed are below and attached is the detailed screen print document .

1. Created an annotation Pty (MyDefinitionSource) as an Admin user .
2. Commited changes to the server(Dev).
3. Logged in as Admin & modified  'values' for keys in 'def_source' & 'definitions' for Project 'Thesaurus-221.02d'  with 'IRI' of annotation pty 'MyDefinitionSource'.
4. Restarted protege, deleted .fileprefs and re-logged in to 'Thesaurus-221.02d' .
5. Concept creation dialog does not work, as in the Dialog box does not open up post clicking the Concept Create Button .

**Comment by bdionne** [comment]
Thanks @singhik I'm not sure entirely what you've done, it looks right. @fragosog could you look at this and verify that this test fails? I believe I removed all the hardcoded value specific to NCI customizations in that dialog, and it should present annotation props as they exist.

If you could verify this and then tell me what you expect to see I can fix the code as needed. Thanks.

**Comment by fragosog** [comment]
I did some reconfiguration (the definition key of the project had also been set to the "MyDefinitionSource" so had to undo it).  I'll need to take another look tomorrow.  I can edit a DEF but not add a new one (no exceptions thrown).  I might be missing a bit in the configuration.  Also, not sure that this project has been set up for the 3.5.3 server, this is one of the older vocabs, so I'll try with another one.

![image](https://user-images.githubusercontent.com/2165212/118198077-31a75300-b41e-11eb-9209-f31bbeb1c6cf.png)

**Comment by fragosog** [comment]
@singhik , this looks like it's working in Thesaurus-201019-20.10c.  You can test in this vocab.  Just for reference, here's what i did:
- In the vocab
  - created the "MyDefinitionSource" annotation property. To this property:
   . added an rdfs:label with value ```MyDefinitionSource```
   . added a preferred_name property with value ```MyDefinitionSource```
   . added a code with value ```MYCODE```
   . added as range the same range used by the original def-source (an enumeration)
- In the project
  - on the key ```def_source``` 
    . changed the value to the IRI of MyDefinitionSource
  - on the key ```http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97``` (the DEFINITION property)
   . deleted the value ```http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P378``` (original def-source)
   . added the value ```http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#MyDefinitionSource``` (new mydefsource)

Note that the ALT_DEFINITION's IRI key wasn't edited, so it will continue using the original def-source property

**Comment by singhik** [comment]
@fragosog @NCIEVS : Hi, There are some ambiguities around this , narrating them in pointers below :: 


1. 'Creating a OWL Concept'  dialog  box, still shows 'Definition Source' DDL  , but when Concept is added, the value selected is shown against the column 'MyDefinitionSource' : 

![image](https://user-images.githubusercontent.com/36314371/118305814-80083080-b4b6-11eb-93b9-61c5f557ca1e.png)

![image](https://user-images.githubusercontent.com/36314371/118305893-9b733b80-b4b6-11eb-851d-f233a2063107.png)

2. 'MyDefinitionSource' DDL is shown for 'Adding/Editing Properties' Dialog Box for DEFINITION complex property (ALT-DEF expectedly shows original Definition Source as it was not configured ,as you have mentioned above ) 

![image](https://user-images.githubusercontent.com/36314371/118306188-0d4b8500-b4b7-11eb-8320-f70d9673561a.png)


As the ticket talks about 'Class Creation Dialog' Box, which still shows 'Definition Source' DDL, does it work differently for you ?

**Comment by NCIEVS** [comment]
@singhik @bdionne , i thought i had looked at that.  but i can reproduce your observation above.  on class creation the incorrect qualifier is being displayed.  but after creation, the qualifier that shows up in the table is the right one.  (and on edit of this new class' definition, the popup dialog shows the right qualifier.)

**Comment by singhik** [comment]
@NCIEVS : Thanks, so that needs to be corrected at code-level  (@bdionne ) or at Project configuration level  ?

**Comment by NCIEVS** [comment]
I think it's at code level.  Just in case, i deleted the .fileprefs and restarted & it was the same.  And there are no other spots in the project config that need editing.

**Comment by bdionne** [comment]
@singhik @fragosog This is just another constant that's no longer needed, `DEF_SOURCE_LABEL`. It was a one-liner to change and is in [1.2.7](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.7)

**Comment by singhik** [comment]
@NCIEVS : Hi, i was wondering on what is the Business Use Case for this Req ? The reason being, once a user defined annotation replaces a defined one, all the other previously created concepts loose that Property as well as it's corresponding value (Definition Source, in this case) , which won't allow View or Edition for other user(s) using same Vocabulary ? 

If, this is strictly adhered to a specific user using a specific Vocab(which is not shared), only then it appears reasonable to me .

Please share your thoughts

**Comment by NCIEVS** [comment]
Hi @singhik , for a given vocabulary, you don't need to change the DEF property, just change its label.  It's when you are developing a new vocabulary and you need to declare your own DEF property with its own label that this is required.  This is one of the long term goals that we have, so that other vocabulary developers (inside or outside the NCI) can develop their own vocabs with our software.  (We've done the same recently with other entities, e.g. complex property qualifiers.)

**Comment by singhik** [comment]
@NCIEVS : Thanks ....
