### ISSUE TITLE
Dual Edits - Source and Target Verbiage Text Is Not Displayed

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#484]
@bdionne  :

**Steps :** 

1. Login to Protege Client and navigate to 'NCI Edit Tab'.
2. Click on Any COncept in the tree and navigate to 'ComplexEdit' Tab .
3.  Select 'Split' radio button and then Select 'Dual Edits' .

**Expected Result :** 

After selecting 'Dual Edits' as Radio button, the 'Source' and ' Target' Window should be displayed as the verbiage text for Left and right sided panels .

**Actual Result :** 

After Selecting 'Dual Edits' , the text displayed incorrectly  remains as 'Clone From' and 'Clone To', as in to indicate 'Split' radio button is selected.

![image](https://user-images.githubusercontent.com/36314371/96180356-4eb78a00-0f00-11eb-876c-6f158bd75145.png)

**Comment by NCIEVS** [comment]
Looks like the text of the left and right-side labels are never set for the dual edit operation.  Any labels that were being displayed before selecting dual-edits remain displayed after selection.  It's the same in 3.4.0.  Have to agree on what labels to set.  Can keep as "TBD" for the milestone.

**Comment by bdionne** [comment]
fixed in [edit tab 1.2.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.0)

**Comment by singhik** [comment]
Works fine in 3.5.0 Client , 1.2.0 Edit PLugin, hence closing
