### ISSUE TITLE
Dual Edits - Clear Functionality Is Not Working As Expected 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#485]
@bdionne  : Hi , 

Steps : 

1. Login to Protege console and navigate to NCI Edit Tab .
2. Create Two Concepts (f.e. Test_7 & Test_9) .
3. Navigate to 'Test_7' Concept ->'ComplexEdit'->'Dual Edits' 
4. Drag Test_7 as 'Source' concept and 'Test_9' as 'Target' Concept .
5. Perform edits in both Test_7 and Test_9  ,f.e. update Full-Syn with new Source name etcetera 
6. Click on 'Clear' button .

Expected Result : 

After clicking on Clear button, the changes should be reversed and Concepts should go back to original states prior Dual Edits .

Actual Result : 

After clickn on 'Clear' Button, the concept changes are reflected when navigate to 'Edit' Tab and 'Save' and 'Clear' button becomes enabled for a Second time for the user to click 'Clear' to undo the changes . Screen print below .

![image](https://user-images.githubusercontent.com/36314371/96181590-47917b80-0f02-11eb-8762-f6a265081e80.png)

![image](https://user-images.githubusercontent.com/36314371/96181600-4bbd9900-0f02-11eb-96dd-d68cd7886db3.png)

![image](https://user-images.githubusercontent.com/36314371/96181632-55df9780-0f02-11eb-9028-148dbade9bd4.png)

![image](https://user-images.githubusercontent.com/36314371/96181658-60019600-0f02-11eb-82bc-4f2fcfe2e5c7.png)

![image](https://user-images.githubusercontent.com/36314371/96181697-6abc2b00-0f02-11eb-8534-31fdc50ad0aa.png)

![image](https://user-images.githubusercontent.com/36314371/96181741-77d91a00-0f02-11eb-81ac-3c7e9355b3ad.png)

![image](https://user-images.githubusercontent.com/36314371/96181753-7c053780-0f02-11eb-839d-48bafbac433a.png)

Navigating to 'Edit' Tab, shows the changes done on the Concept and 'Save' and 'Clear' button become enabled again : 

![image](https://user-images.githubusercontent.com/36314371/96181831-993a0600-0f02-11eb-89a3-e677ca177499.png)

'Clear' button needs to clicked again to undo the changes :

**Comment by bdionne** [comment]
fixed in [edit tab 1.2.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.0)

**Comment by singhik** [comment]
Works fine in 3.5.0 Client , 1.2.0 Edit PLugin, hence closing
