### ISSUE TITLE
Alice Login-The Search Tab Is Showing Located Under NCI Edit Tab 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#49]
Steps to reproduce:
1) Log into the protégé as Alice http://localhost:8080 via "Open from Protégé OWL Server"
2) Open "foo" project 
3) Noticed Search tab is showing located under NCI Edit Tab.
4) Click on Search opens " Lucene Query Dialog" menu.
5) Should not Search tab be under Lucene Search Tab? 

Please see attached snapshot for more details.
![nci edit tab_search link_alice login](https://cloud.githubusercontent.com/assets/8367102/19412543/c9e8297c-92e6-11e6-90ed-95375f95c2b9.png)

Thanks,
Reza

**Comment by bdionne** [comment]
That's just a button, which enables you to bring up a search dialog and have a selected result displayed in the navigation tree

**Comment by NCIEVS** [comment]
Will label as question and close with wontfix.
