### ISSUE TITLE
standalone mode

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#491]
Considering this one not to be offline mode, but rather a client-only standalone mode to work with files.  If at some point a project is created meant to be the "master" all work would continue with the server-based vocab.  No changesets are created when in this client-only standalone mode.

**Comment by NCIEVS** [comment]
Examine #348 when working on this one.

**Comment by NCIEVS** [comment]
Goals, a) start a vocab from scratch, b) export config file from standalone that could be used in server config.

**Comment by fragosog** [comment]
Keep in mind when working out the rules, #486.

**Comment by bdionne** [comment]
This ticket is partially fulfilled by the Edit Tab work (see #581 )

The user can now open an owl file in file mode and work with edit tab. The experience might not be complete but it should not crash

**Comment by singhik** [comment]
@bdionne  : Hi , i have tried doing this using smallBase.owl file but facing multiple issues : 

1. Tried creating a concept, Save button is disabled .
![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/f302abf3-a34d-4d00-8d61-8568bbc1c3ec)

2. There are no Complex Properties to select from, have tried configuring NCI Edit Tab with Complex Properties but that also does not work 
![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/a626cfab-482b-4825-bd71-07a84b38b529)

![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/f2aaf122-3458-4283-a07f-aeb63626c109)

3. The Retire Option is disabled and so is the Delete concept button .
![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/984ef346-7c61-4e96-9e33-bc36aa6684af)

**Comment by cmoid** [comment]
@singhik - success here is edit tab not crashing when you open an owl file. Though some things should still work, there is no associated server project so codes can't be generated for new classes and so forth. 

This ticket relates to #581 , where there is specified a [round trip scenario](https://github.com/NCIEVS/nci-protege5/issues/581#issuecomment-1939218628) Beginning with an Owl file, one should be able to produce a `config.json` file that can be used in the metaproject-admin tool to build a new project. That project when then opened as a server project should support all the complex operations.

We can review this again in the weekly status.

**Comment by bdionne** [comment]
@singhik - success here is edit tab not crashing when you open an owl file. Though some things should still work, there is no associated server project so codes can't be generated for new classes and so forth. 

This ticket relates to #581 , where there is specified a [round trip scenario](https://github.com/NCIEVS/nci-protege5/issues/581#issuecomment-1939218628) Beginning with an Owl file, one should be able to produce a `config.json` file that can be used in the metaproject-admin tool to build a new project. That project when then opened as a server project should support all the complex operations.

We can review this again in the weekly status.
