### ISSUE TITLE
squashing in windows

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#495]
Was able to squash in a windows client-server environment and the files copied to the archive dir.  But very soon after, the client threw an exception.  

The top of the exception thrown after the squash was completed is:

java.lang.NoSuchMethodError: org.protege.editor.owl.client.LocalHttpClient.buildVersionedOntology(Lorg/protege/editor/owl/server/versioning/api/ServerDocument;Lorg/semanticweb/owlapi/model/OWLOntologyManager;Ledu/stanford/protege/metaproject/api/ProjectId;)Lorg/protege/editor/owl/server/versioning/api/VersionedOWLOntology;

Depending on prod workflow (e.g. history written before squash), the workflow managers might not identify this as an issue.

**Comment by NCIEVS** [comment]
This has been fixed in commit [46dccaef01ae2b](https://github.com/NCIEVS/revision-history/commit/46dccaef01ae2b0fb40e676638ad15ea7c6d52cf).

**Comment by safrant** [comment]
How should this be tested in QA?

**Comment by NCIEVS** [comment]
Hi Tracy, the server needs to be run from windows.  The client can be anywhere.

The windows issue has to do with archiving & namespaces, so following an edit or two, do a squash, there shouldn’t be an exception (although the vocab is archived).  Then publish history, there shouldn’t be an exception and the history directory created & history files archived.

If you or Itendra are not comfortable running the server in windows, if you package the server I can test it locally.

Thx, Gilberto

**Comment by singhik** [comment]
@NCIEVS  : Hi, please review attached document for Execution screen shot and if any other Use Case is pending, else to which we can close this Ticket . 

[Issue_495.docx](https://github.com/NCIEVS/nci-protege5/files/5974157/Issue_495.docx)

**Comment by NCIEVS** [comment]
Hi @singhik , yes, this looks good for both the squash and history archiving.  Agree that it can be closed.

**Comment by NCIEVS** [comment]
In prod 3.5.3.
