### ISSUE TITLE
support for curator explanations 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#497]
. . . as pellet is no longer used (follow up from #335).  This has a workaround if absolutely necessary.

**Comment by bdionne** [comment]
no longer needed

**Comment by NCIEVS** [comment]
. . .  because a) we catch many things at edit time, and b) where explanation tooling should be helpful e.g. you get 1000 unsatisfiable classes because of a re-tree, the explanations don't help you find the root edit that caused it anyway.  Putting this one to rest.
