### ISSUE TITLE
shutdown of server 

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#498]
fill in after discussion

**Comment by bdionne** [comment]
/login fails when LDAP is missing or not configured properly. Should fail back to using default login and report/log errors to client

**Comment by bdionne** [comment]
current workaround is to use /admin/logn endpoint, which is defunct.

**Comment by bdionne** [comment]
so the admin/login server endpoint is now removed from the client/server and the server does some additional checking to ensure that if the authenticated choice in the config fails to login it will fail back to the default.

This requires a full build of protege to test, [tag 3.6.0-dev4](https://github.com/NCIEVS/protege/tree/3.6.0-dev4)

**Comment by safrant** [comment]
I tested the shutdown script against Stage and it works.  And out handy etc/init immediately starts it again, which is a win
