### ISSUE TITLE
Edits after Clone cause loss of save button

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#499]
Steps to reproduce:

1. clone class
2. edit cloned class, add parents, props, etc..
3. save
4. edit new class and add role
5. save
6. begin to add child to new class, but cancel operation
7. delete parent instead
8. Save button is not enabled

**Comment by bdionne** [comment]
fixed in [1.2.4](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.4)

**Comment by singhik** [comment]
@bdionne  :: 

"Save" button is getting disabled, Steps below : 

1. Create a concept (Test_1) :: 

![image](https://user-images.githubusercontent.com/36314371/118033175-82dc1780-b336-11eb-87d7-ef3f7e488e1e.png)

2. Navigate to 'Complex Edit->Copy' to Clone a Concept, enter all details in 'Create a new OWLClass' CloneTo Dialog prompt but click 'Cancel' instead::

![image](https://user-images.githubusercontent.com/36314371/118033449-d77f9280-b336-11eb-8621-77e97a1351ea.png)

![image](https://user-images.githubusercontent.com/36314371/118033471-dcdcdd00-b336-11eb-8dfb-58686d6f7db9.png)


3. Navigate to original concept (Test_1)  to add /edit /delete properties, "Save" button is Disabled ::

![image](https://user-images.githubusercontent.com/36314371/118033640-0d247b80-b337-11eb-85ef-7ec5955dbd7e.png)

![image](https://user-images.githubusercontent.com/36314371/118033659-11509900-b337-11eb-993c-2e6c2c255ea8.png)

**Comment by bdionne** [comment]
I can reproduce this @singhik, thanks, it looks like a similar edge case but in a different place. I'll investigate, it looks like when you cancel ad go back to edit, it still thinks the operation is cloning.

**Comment by bdionne** [comment]
@singhik 
pushed a fix for this in [1.2.6](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.6)

**Comment by singhik** [comment]
Verified successfully on 3.6.0-dev7 Client with NCI Edit Tab v 1.2.6, hence closed
