### ISSUE TITLE
wordwrapping in dialogs

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#5]
There is not [wordwrapping](http://owlcs.github.io/owlapi/apidocs_5_0_1/index.html) for the values in the synonym or DEFINITION. This is okay for qualifiers but not for the def-definition or the term-name. See screenshot.

![word-wrap](https://cloud.githubusercontent.com/assets/2165212/18068358/ee510aec-6e0e-11e6-8236-5bce59e6fa7c.PNG)

**Comment by bdionne** [comment]
@bdionne I think this is an `EditTab` issue

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
I have retested and verified this fix in tag 110. Please see attached screen shot for more detail.

Thanks,
Reza
![wordwrap](https://cloud.githubusercontent.com/assets/8367102/21111625/5cddfc3c-c070-11e6-8dab-766c5f0b26a6.png)
