### ISSUE TITLE
Protege5-Tag 101- Selecting View and View Visible Content Cause Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#50]
This issue occurs with and without logging into protege OWL server. 
Steps to Reproduce:

1) Launch protege server and client 
2) Go to Window/Capture View
3) Select View and click ok then receive java error. 
4) End the protege client session
5) Re-launch client and repeat step 2
6) Select "view visible content" and click ok then receive java error as well.

Note: 

Please attached screen shots and log files for more details.
![protege_captureview-1](https://cloud.githubusercontent.com/assets/8367102/19523996/4a03822c-95ea-11e6-81f3-0df6c625206a.png)
![protege_captureview-2](https://cloud.githubusercontent.com/assets/8367102/19524002/50a1ae92-95ea-11e6-9a15-03acbb450ae1.png)
[Protege_CaptureView_View Error.txt](https://github.com/NCIEVS/nci-protege5/files/539363/Protege_CaptureView_View.Error.txt)
[Protege_CaptureView_View Visible Content_Error.txt](https://github.com/NCIEVS/nci-protege5/files/539364/Protege_CaptureView_View.Visible.Content_Error.txt)

Regards,
Reza

**Comment by rmehri** [comment]
The same issue occurs in tag 102.

Regards,
Reza

**Comment by bdionne** [comment]
this is a [protege](https://github.com/protegeproject/protege/issues/568)

Not sure if this feature is used at all, if not I'll remove it from the menu

**Comment by NCIEVS** [comment]
has been fixed in protege (see the link above).  As this functionality is not used frequently and has a workaround (use the OS's screen shot facilities/programs), will mark it as a bug but for future release.

**Comment by rmehri** [comment]
This fix has been retested and verified using tag-126,NCT-Edit Tab-0.5.1 . Thanks, Reza
