### ISSUE TITLE
Classification Followed By Revision History Updates In Same Session Is Extremely Slow Per Editors

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#501]
From Editors :: 

"It looks like the slowness I saw last week was just a fluke. Editor asked me to run the baseline this week and the two items that took several minutes to enter and save last week took seconds for me to process today. The only thing I know I did this time that I may have not done last week was after I ran the classifier and reviewed the inference, I exited protégé and opened a new instance to do the Revision History review. I think last week I went right from classification to Revision History and (even though I stopped the classifier before I opened the Revision History tab) it’s possible that doing both of these in the same session is problematic. "

"I experienced a lot of slowness while loading the Revision History tab (it took 5-10 min to load the Conflicts today) and changing and saving the date and version in the Active Ontology tab (took 4-5 min for each step). I haven’t experienced such slow response in the past. It didn’t look like a larger volume of edits than usual (it is difficult to parse the numbers because Revision History change counts are a bit of a black box to me but on March 8 the number of changes was 825 and today it was 635) and the number of Conflicts was very small (total of 6) for this week and the Active Ontology slowness was odd. (I was worried that the Squash History would time out as it usually takes 3-5 min to run, but surprisingly, that part didn’t take any longer than usual.) So I was wondering if there is a difference in memory allocation on the server when systems restarted it last week versus what we had prior to the Thursday restart."

Summary From NCIEVS : 

" Could be a network issue at the Editors end cause of  VPN or other alien reasons , awaiting input from Network Group & will try to reproduce the slowness in Classification followed by Revision History updates "

**Comment by NCIEVS** [comment]
Status:
- memory on the server has not changed
- the followup communication was "It looks like the slowness I saw last week was just a fluke"
- ticket on network slowness is open as of today at CIT, not expecting a response anymore

Two tests to finish this up (from the same followup): 

First
- do edits on 20 concepts
- run classifier
- without exiting protege switch to the revision history, note load time
- switch to active ontology tab, edit date & version, note time to complete

Second, as above but exit and restart protege after classification
 - do edits on 20 other concepts (the previous 20 edits will still be there, no squashing in between tests)
 - run classifier
 - exit and restart
 - switch to revision history, note load time
 - switch active ontology tab, edit date & version, note time to complete


Reassigning for testing.

**Comment by singhik** [comment]
@NCIEVS : Hi, the above steps have been performed couple of times and did not notice any broken or hanging thread in entirity of operation (with or without restart) . Time to load Revision History Tab was 2 seconds & 3 seconds respectively whereas time to perform operations on 'Active Ontology' was 10 seconds each time . 

However, as classification is throwing a bug , i will wait for #506 to be fixed before closing this ticket .

PS: Tests were performed over VPN with high bandwidth of 70 Mbps over 5 Mbps (Upload over Download)

**Comment by singhik** [comment]
@NCIEVS @bdionne  : Hi,  I am unable to get 'Edit' button for 'Active Ontology' Tab ?? 

![image](https://user-images.githubusercontent.com/36314371/116311256-0c0d1f00-a779-11eb-953e-e64924f5f307.png)

**Comment by NCIEVS** [comment]
I wonder if we had your permissions wrong.  I've modified your manager's permissions.  Let me know if that works.

**Comment by singhik** [comment]
@NCIEVS  : Thanks, Yes, i see it now .

**Comment by singhik** [comment]
@NCIEVS : Hi , i  have repeated above steps today as well, both pre and post restart , didn't notice an occurrence of hanging thread. This issue is good to close and is working as Tested on 3.6.0-dev6 Build in multiple iterations ...
