### ISSUE TITLE
Save Button Is Disabled - 3.6.0-dev6 Build

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#507]
@NCIEVS @bdionne  : 

**Steps To Reproduce :** 

Login to Protege client 3.6.0-dev6 and open a workable project 

Create a concept, add a complex property 

**Issue :** 

'Save' button is disabled post adding a complex property and trying to Save the added/edited concept . 

![image](https://user-images.githubusercontent.com/36314371/116009403-78581900-a5e7-11eb-849e-c85c5c8b3c66.png)

Screen blanks out 

![image](https://user-images.githubusercontent.com/36314371/116009406-81e18100-a5e7-11eb-9f44-6e8424553681.png)

Control needs to go to another concept and then when navigate back to original concept, the changes are saved without 'Save' button being enabled and hence clicked 

![image](https://user-images.githubusercontent.com/36314371/116009431-a63d5d80-a5e7-11eb-89cb-c2a529c3580b.png)

**Comment by bdionne** [comment]
same comment as #508

**Comment by singhik** [comment]
Not reproducible now in 3.6.0-dev6 build (Dev server Thesaurus),after multiple iterations of execution , hence closing the ticket .
