### ISSUE TITLE
Save Button Hangs & Becomes Non Operational In Retiring Concepts - 3.6.0-dev6 build

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#508]
@NCIEVS @bdionne  : 

**Steps To Reproduce ::** 

Login to Protege client 3.6.0-dev6 and open a workable project (With workflow manager role)

Create 5 concepts and retire them 

**Issue ::** 

Only couple of Concepts retire, from 3rd concept onwards, 'Save' button becomes non-functional i.e. it 's enabled but clicking on it does not invoke 'Class Saved Successfully' dialog prompt .

This Operation is not intermittent, i have tried multiple restarts and retires  (deleted .fileprefs too) .

![image](https://user-images.githubusercontent.com/36314371/116009962-41373700-a5ea-11eb-8d30-9fca3c2cdb36.png)

![image](https://user-images.githubusercontent.com/36314371/116009970-498f7200-a5ea-11eb-8c09-b7a02f2c378a.png)

multiple clicks on "Save", it's non-operational and only way is to exit is via 'Cancel' 

![image](https://user-images.githubusercontent.com/36314371/116009991-67f56d80-a5ea-11eb-82e7-af4ec7c97fea.png)

![image](https://user-images.githubusercontent.com/36314371/116010057-d6d2c680-a5ea-11eb-97cc-9c0b9da3d5bd.png)

**Comment by singhik** [comment]
[protege.log](https://github.com/NCIEVS/nci-protege5/files/6373092/protege.log)

**Comment by bdionne** [comment]
I'm not seeing this, my first suspicion would be a bad build and/or plugins. Below is my list. There is a null pointer in the log, from EditTab, that I'll look into
````
java.lang.NullPointerException: null
	at gov.nih.nci.ui.NCIEditTab.findUniqueSubjects(NCIEditTab.java:1487) [nci-edit-tab-1.2.5.jar:na]
	at gov.nih.nci.ui.NCIEditTab.stateChanged(NCIEditTab.java:1439) [nci-edit-tab-1.2.5.jar:na]
	at org.protege.editor.owl.client.SessionRecorder.fireStateChanged(SessionRecorder.java:257) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.client.SessionRecorder.logChanges(SessionRecorder.java:173) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.model.OWLModelManagerImpl.ontologiesChanged(OWLModelManagerImpl.java:720) [protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:32) ~[owlapi-osgidistribution-5.1.6-SNAPSHOT.jar:5.1.6-SNAPSHOT.2021-04-22T19:14:27Z]
````
<img width="725" alt="Screen Shot 2021-04-26 at 6 11 55 AM" src="https://user-images.githubusercontent.com/31741/116068487-4a5eed00-a658-11eb-8c7f-aacafb59f844.png">

**Comment by singhik** [comment]
Looping @safrant to comment

**Comment by NCIEVS** [comment]
The dev6 version from @safrant has those plugin versions.

**Comment by bdionne** [comment]
not sure what this is, @safrant I checked the client build with respect to the plugins and the jars in lib and they all look the same as what I get when running the build.

I tested all three of these tickets and saw no issues.

**Comment by safrant** [comment]
I will try rebuilding the server with the previous tag.

Tracy M. Safran
Programmer Analyst - CBIIT
Frederick National Laboratory for Cancer Research
Post Office Box B, Frederick, MD 21702

Ph: 240-276-5172
***@***.******@***.***> (Contractor)

From: Craig Stancl ***@***.***>
Reply-To: NCIEVS/nci-protege5 ***@***.***>
Date: Monday, April 26, 2021 at 12:08 PM
To: NCIEVS/nci-protege5 ***@***.***>
Cc: Tracy Safran ***@***.***>, Mention ***@***.***>
Subject: Re: [NCIEVS/nci-protege5] Save Button Hangs & Becomes Non Operational In Retiring Concepts - 3.6.0-dev6 build (#508)


not sure what this is, @safrant<https://github.com/safrant> I checked the client build with respect to the plugins and the jars in lib and they all look the same as what I get when running the build.

I tested all three of these tickets and saw no issues.

**Comment by singhik** [comment]
Regression Tested in multiple iterations via Automation  on 3.6.0-dev7 build against dev server , found no hanging and no issues in Saving & retiring concepts tree, hence closed .
