### ISSUE TITLE
Upgrade protege-server-export utility

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#509]
[protege-server-export](https://github.com/NCIEVS/protege-server-export) doesn't work with current protege-owl and protege-core versions. Recent changes made to accommodate imports require the use of `OWLEditorKits`.

This needs further investigation. Perhaps the easiest approach is to ignore if they are not required.

**Comment by NCIEVS** [comment]
Verified with editing group that automated exports are not being done, hence closing ticket.  We can resurrect this issue later if needed.
