### ISSUE TITLE
Protege5-Tag 102- Server Administration-Server Settings-Not Populated Information

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#51]
Steps to Reproduce:

1) Launch protege server and client 
2) Login to the protege server (Server Administration)
3) Select Server Settings tab 
4) You'll see no server and properties information populated!
Please see attached screen shot for more details.
Regards,
Reza
![protege_server_setting information section_not populated](https://cloud.githubusercontent.com/assets/8367102/19535984/005966c2-9618-11e6-871a-041b7eef807f.png)

**Comment by bdionne** [comment]
In order to see server settings you must login as the sysadmin

**Comment by NCIEVS** [comment]
Yes, this is an access privilege issue.  The wrong user was used.  Will close with invalid.
