### ISSUE TITLE
Metaproject admin fails adding options to new project

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#510]
* create new project
* choose selection to copy template (by name or by code)
* edit options and add new option
* throws immutable exception and edit fails

**Comment by singhik** [comment]
This ticket is related to creation of new Project Templates, hence assigning it to @safrant for evaluation ....

**Comment by safrant** [comment]
I opened protege using the admin tool and selected + to create a new project.
I chose a template
I then clicked Options and added a new option and value of "codegen_suffix : AA".  The "OK" button did not enable.
I then clicked Browse to choose a file and allowed it to build. 
The project created successfully with the new option included.
