### ISSUE TITLE
subclass dependencies are not displayed during retirement

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#512]
Observed in 3.6.0 dev 7.  Subclasses are not being displayed as dependencies when retiring a concept.  (Classes that are dependent via roles are still being displayed.)  This is working correctly in prod (v 3.5.3).

**Comment by bdionne** [comment]
This is easily reproducible:

 * create any class
 * create a subclass
 * retire the parent
 
The subclass doesn't show up as a class to fix

**Comment by bdionne** [comment]
fixed in [nci-edit-tab-1.2.8](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.2.8)

**Comment by singhik** [comment]
@NCIEVS @bdionne  : Concept with dependencies as 'Roles' and / or as 'Subclasses'  are displayed during 'Retire' and "Retire" operation is **not** allowed until all the corresponding usages of Role or Subclass dependecies are removed. Tested on 3.6.0-dev7 build with NCI Edit Tab 1.2.8 . 
Ticket can be closed as fixed
