### ISSUE TITLE
Change of focus during editing in the complex edit  panel

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#513]
From [EHD] (originally reported during resolution of #149) :

"the edit panel focus changes to a different concept. I have mostly seen this occur during use of the Complex Edit tab. In some cases, during a Copy or other Complex Edit, the hierarchy pane (and thus the role domain) can become focused elsewhere. The role choices become inappropriate for the concept being edited but I don’t know if the GUI can recognize this disconnect and still properly enforce domain-range restrictions. (When I see this disconnect, I recognize the issue and Save without adding roles. Once I am certain the GUI (meaning both the Edit tab and hierarchy pane) is focused correctly, then I add roles.)"

**Comment by NCIEVS** [comment]
Additional info:

This issue has happened with 3.5.3. I have seen this during Copy and Dual Edits in the Complex Edit tab but [NS] has seen this in the Edit tab (I am not sure what lead up to it, but I assume he clicked on a role name or filler value). When it happens in the Edit tab you can “see” the disconnect because the label in the purple Basic Editing bar at the top will not match the Preferred_Name or PT (this embedded screenshot illustrates the location of the purple bar and is NOT demonstrating a mismatch). 

![image](https://user-images.githubusercontent.com/7783321/119821647-cac77680-bec0-11eb-9fbe-116f731fadb7.png)

I believe there is a workaround but I haven’t tested it myself, the editor can use the back (or forward) button   

![image](https://user-images.githubusercontent.com/7783321/119821697-ddda4680-bec0-11eb-9dbe-5a81b41e00ca.png)

until the label in the purple bar matches the Preferred_Name. 

Two items to note: 
1. This issue may occur on Split or Merge but Splits are rare and roles aren’t usually modified during a Merge so there is little chance to click on the roles or filler values. 
2. The workaround doesn’t appear to work when using the Complex Edit tab.

**Comment by bdionne** [comment]
this needs a reproducible scenario, all of the obvious things tried seem to work. Normally if the focus class is changed while editing another class a warning is thrown and the user can either go forward or back. In the complex edit scenarios, two classes can be in edit, with the focus being on one. Since it's a copy or a clone the domains are the same for both.

**Comment by hahndane** [comment]
Possible scenario: Copy a concept with roles (i.e. ULK1 Gene C116612 to create ULK2 Gene). In the Copy panel in the lower right pane click on a role name or filler value (i.e. Gene_Plays_Role_In_Process some 'Serine/Threonine Phosphorylation' click on either Gene_Plays_Role_In_Process or 'Serine/Threonine Phosphorylation') this will change the focus. I just did this in 3.6.0 and clicked on Gene_Plays_Role_In_Process although the name in the purple bar was still ULK1 Gene the Navigation Hierarchy bar said Gene_Plays_Role_In_Process (see screenshot 1)
<img width="196" alt="inappropriate role 3" src="https://user-images.githubusercontent.com/21345553/121066941-7497e480-c798-11eb-9d2e-8b256337a2bb.PNG">
, only role option in the role selection window was for Conceptual_Part_Of (which corresponds to the domain for Gene_Plays_Role_In_Process see screenshot 2).
<img width="326" alt="inappropriate role" src="https://user-images.githubusercontent.com/21345553/121066245-ab212f80-c797-11eb-992c-bbb7105482f8.PNG">
When I clicked on 'Serine/Threonine Phosphorylation' the roles were for the Biological Process domain (see screenshot 3)
<img width="314" alt="inappropriate role 2" src="https://user-images.githubusercontent.com/21345553/121066601-11a64d80-c798-11eb-923a-108dba9fdd00.PNG"> and the Navigation Hierarchy was pointed to 'Serine/Threonine Phosphorylation' (see screenshot 4)
<img width="200" alt="inappropriate role 4" src="https://user-images.githubusercontent.com/21345553/121067052-95f8d080-c798-11eb-8e33-a507c829733a.PNG">

The back button did eventually bring me back to ULK1 Gene and the appropriate role selection for the Gene domain.

Let me know if these screenshots don't work, I saved them on my computer and can email them to you.

**Comment by NCIEVS** [comment]
Thanks @hahndane , I can see this too.  There are no exceptions when it happens.  Don't have any estimates on the frequency but once I knew where to look at it seemed very reproducible.  

Unlike in the edit tab where you get a "do you want to continue" when you navigate away via the roles & fillers, there's no notification and the new class created in the Copy can be saved with the wrong roles &

**Comment by bdionne** [comment]
Yup, thanks @hahndane, I don't see any issue when I click on the role, but can definitely see the switch when I click on the filler. I think for roles it depends on whether the entities tab is open. If it's open it switches to the object property tab and switching back to edit tab seems to be fine.

Will fix it, I imagine whatever works for the filler will work for the role as well. I guess you should be able to switch to the filler and even edit it, but in that case it ought to prompt you to cancel the copy.

**Comment by hahndane** [comment]
Hi Bob, I'm not sure editors will want to Cancel the Clone; could it prompt the editor to not edit the roles instead? 
Also the workaround with the back arrow seems to work to get editing synched back up, could the process prompt the editor to use the back/forward buttons?

**Comment by bdionne** [comment]
@hahndane This is fixed already, you'll see it in the 3.7.0 release. What we did was disable the linking when you in a complex dual pane editing session, so that if you accidentally click on a role or filler it will not try to edit it.

**Comment by hahndane** [comment]
Thanks, that sounds like a good way to fix it.
