### ISSUE TITLE
Lucene Search Is Not Working - 3.6.0

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#516]
@NCIEVS @bdionne : Hi, Lucene Search Query is **not** working and does not return results for valid queries , have run multiple iterations of AUtomation runs and tried them manually too . Attached are the Automation logs and below screen shots 

![image](https://user-images.githubusercontent.com/36314371/120377406-14fa8e80-c2eb-11eb-8f49-bc6ca34eb9c5.png)

![image](https://user-images.githubusercontent.com/36314371/120377434-1cba3300-c2eb-11eb-8032-52928e2c5e76.png)

![image](https://user-images.githubusercontent.com/36314371/120377527-3d828880-c2eb-11eb-8176-03ec68575d20.png)

![image](https://user-images.githubusercontent.com/36314371/120377543-42dfd300-c2eb-11eb-97f7-6ff03eabba54.png)

![image](https://user-images.githubusercontent.com/36314371/120377586-51c68580-c2eb-11eb-9f2a-87d12b4fdc5e.png)

![image](https://user-images.githubusercontent.com/36314371/120377622-5f7c0b00-c2eb-11eb-9bdc-05be5db69cc2.png)

**Comment by singhik** [comment]
@NCIEVS @bdionne  : Have underestimated the power of '.fileprefs' to mess not only the UI make up but functionality too but the logical in me could never guage  how it  can impact search on Lucene .

Clearing them and a restart  solved the issue, hence closing the ticket .

**Comment by bdionne** [comment]
@singhik I take it removing the `.fileprefs` fixed the search? I should look at this. The indices are stored in the filesystem and the naming is dependent on the project id, which can change. The top level location is set by the user and I imagine is set as part of the build process.

If any of these change a full reindex is required, which would explain why it looks broken.

**Comment by singhik** [comment]
@bdionne : yes, deleting .fileprefs made Lucene search work for me
