### ISSUE TITLE
Merge Complex Edit Is Not Working - 3.7.0 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#519]
@bdionne @NCIEVS  : Hi, Steps To reproduce and screen prints are below : 

1. Create concept 'Test1' and add Alt-Def , create concept 'Test2' and add alt-def .
2. Perform a 'Merge' of 'Test1' and 'Test2' with Test2 being surviving concept and Test1 being Retiring concept .
3. post Merge, concept 'Test2' does not list any of the complex properties from 'Test1' <Issue> 

 

 
![image](https://user-images.githubusercontent.com/36314371/125126419-13ca3780-e0c9-11eb-9236-37963e3c1cc3.png)

![image](https://user-images.githubusercontent.com/36314371/125126434-19c01880-e0c9-11eb-88b6-ff9ca2d73ebf.png)

![image](https://user-images.githubusercontent.com/36314371/125126448-1dec3600-e0c9-11eb-97d1-ceab64eceaed.png)

![image](https://user-images.githubusercontent.com/36314371/125126461-23498080-e0c9-11eb-8fc8-78b747fdc4d6.png)

![image](https://user-images.githubusercontent.com/36314371/125126468-280e3480-e0c9-11eb-87fe-8e11ea7c2cc9.png)

**Concept Test2, does not show any merged properties of Concept Test1 , Issue :** 

![image](https://user-images.githubusercontent.com/36314371/125126498-32c8c980-e0c9-11eb-996b-b1a1fca789c1.png)

**Comment by bdionne** [comment]
@singhik I get different results, using your steps. When I create `test1` and then `test2, adding the `alt-def` props, it prompts me to switch retiring and serving as it favors the older one.

I then get rules violations when I have more than one `definition` with source `NCI`. I clean those up and save it the merge seems fine.

**Comment by bdionne** [comment]
Here are my results, where `test1` is the survivor, and you can see it has two `alt-defs`

<img width="1016" alt="Screen Shot 2021-07-09 at 3 49 20 PM" src="https://user-images.githubusercontent.com/31741/125129557-a5d43f00-e0cd-11eb-9cbf-6673d716879a.png">

<img width="1019" alt="Screen Shot 2021-07-09 at 3 49 43 PM" src="https://user-images.githubusercontent.com/31741/125129573-ac62b680-e0cd-11eb-8d65-e11f6146c4f2.png">

**Comment by singhik** [comment]
@bdionne  : For me, the Merge still shows Test1 without any properties of Test2, have tried deleting fileprefs too .
What happens when you don't reverse the order of Retiring & Surviving Concept when Editor suggests ?

**Comment by singhik** [comment]
@bdionne : Doing it again, after a complete restart and clean up, still same issue : 

Creating Test1 as below : 

![image](https://user-images.githubusercontent.com/36314371/125135161-8b529380-e0d6-11eb-8605-1f4eb3f01c4e.png)

Creating Test2 as below : 

![image](https://user-images.githubusercontent.com/36314371/125135234-a8876200-e0d6-11eb-852b-cbe9b06a7993.png)

Merge : Test2 survives & Test1 Retires 

![image](https://user-images.githubusercontent.com/36314371/125135287-bc32c880-e0d6-11eb-84bb-873036a5c5b3.png)

![image](https://user-images.githubusercontent.com/36314371/125135370-d8cf0080-e0d6-11eb-8fbd-68af25345e7e.png)

![image](https://user-images.githubusercontent.com/36314371/125135388-e1273b80-e0d6-11eb-997f-374ed6bab61a.png)


Test2 (Merged Concept, with no complex properties from Test1) ? : 

![image](https://user-images.githubusercontent.com/36314371/125135477-074cdb80-e0d7-11eb-95bb-9c9aea60fa16.png)

**Comment by bdionne** [comment]
Interesting @singhik, so you didn't see the offer to switch which one is retired? Maybe this is related to changing the format of the generated codes, we use the codes to determine which class is older.

I'll try again, using the full Thesaurus and an example in the same branch you did, maybe it's data related.

We can triage this further on Monday over Webex if needed.

**Comment by singhik** [comment]
@bdionne : Hi, i do get the offer to switch but i don't reverse the order , even when i do ,it still behaves the same .

**Comment by bdionne** [comment]
Ok, thanks @singhik , I think I see the issue, wow! talk about an edge case. The value you use for the `ALT-DEF` property you add is the same as the class name. If you change that it works. This has to do with not wanting to copy the label property but having to rely on the OWL renderer for the class name that should be identical to the label.

I'll confirm all this and review with Gilberto later at our weekly. Thanks again, nice find!

**Comment by NCIEVS** [comment]
Hi @singhik , it looks like this is probably OK.  @bdionne will fix it but it's not a showstopper for 3.7.0.  Can you re-test with different property values?  thanks!

**Comment by singhik** [comment]
@NCIEVS @bdionne : Hi, yes not a blocker @NCIEVS  , it can be parked to a later milestone push , for now i can pass my tests with amending the use case for a variant pty value .

**Comment by bdionne** [comment]
We'll fix this in 3.8.0, as this likely would never happen in production and already exists there.

**Comment by singhik** [comment]
@bdionne : I tried this today, merge fails to cumulate properties of retired concept. Attached is the document with screen prints for reference .

[Issue_519.docx](https://github.com/NCIEVS/nci-protege5/files/6994166/Issue_519.docx)

**Comment by bdionne** [comment]
hmm, this is the same weird edge case where the `alt-def` value is equals to the class name. Let me check, maybe I forgot to push that fix

**Comment by bdionne** [comment]
This one is definitely missing code, which will be in the next plugin update for `EditTab`

**Comment by singhik** [comment]
Create Concept 1 : 

![image](https://user-images.githubusercontent.com/36314371/130288166-0f2510d0-ecb0-4598-bcca-421641f3b3f7.png)


Create Concept 2 : 

![image](https://user-images.githubusercontent.com/36314371/130288195-a281fcf8-5bbd-46f4-b741-b2a159809c9e.png)


Merge the two : 

![image](https://user-images.githubusercontent.com/36314371/130288242-95842b4c-53d2-452c-b349-cb7d6457663d.png)

![image](https://user-images.githubusercontent.com/36314371/130288254-0d889b23-b03d-4242-9120-81945c611234.png)


You will get a Warning stating Only one Full_SYn is allowed, so Delete one Full_Syn from 'Test_Two' concept : 


The moment delete is clicked, the control shifts completely from 'Test_Two' Editor to the 'Retired' Concept tree of 'Test_Two_Copy'  , this is an issue as the Merge is still not complete and surviving concept 'Test_Two' is not saved . 

![image](https://user-images.githubusercontent.com/36314371/130288586-c406796e-7d11-45a0-84cb-677e619e1da2.png)

**Comment by bdionne** [comment]
We'll have to review this @singhik, I don't see this behavior as you describe above.

> You will get a Warning stating Only one Full_SYn is allowed, so Delete one Full_Syn from 'Test_Two' concept :

You can't possibly get the warning *until* you click on save, which saves any edit that occur. I do see the control shift to the retired branch as your screenshot above shows, but I see that right after I click on merge, which I think is ok. When I then click save I see the warning about `FULL_SYN`, I fix it and click save again.

On your screen it also looks ike you can still click save again, so I'm not so sure about it jumping after the delete. Perhaps it's a Mac/Windows diff.

After that it clears the screen. I'm thinking that actually we should change that last step so that it either switched to the read only panel, as we do with retire now, or goes back to the surviving class, opened in the edit panel

I'll go over this one and the retire case in my weekly on Monday with @NCIEVS. Feel free to join that call if you're available.

**Comment by bdionne** [comment]
I'm not able to accurately reproduce this in the debugger, but was able to reproduce it using the build and using Tracy's build. I made a minor fix in `EditTab` [1.3.3](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.3) which allows it to works as before and addresses the main issue of this ticket where properties aren't copied when the literal value is equal to the class name.

**Comment by singhik** [comment]
@bdionne : I also see 1.2.5 of Lucene Search Tab in your repo, do i need to get that too for 3.8.0-qa2  ?

**Comment by bdionne** [comment]
@singhik - not for this ticket, but you'll need that for the other. the `3..0-qa2` package seems to contain the older plugins, so you'll likely want to either point to my autoupdater or have @safrant promote them to the QA tier.

**Comment by singhik** [comment]
Tested on 3.8.0-qa2 build with NCI Edit Tab v 1.3.4 , works fine ,hence closed
