### ISSUE TITLE
Protege5-Tag 103- Server Administration-Json Serialization-Duplicated Save and Cancel

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#52]
Steps to reproduce:
1)  Launch protege server and client 
2)  Log into the Server.
3)  Add a user
4)  Select Access Control Policy and assign project to a user 
5)  Select JSON Serialization and you'll see duplicated Save and Cancel 
6)  When the page is minimized the duplication gets cleared and you'll see only Save and Cancel
7)  When the page is re-maximized and toggling   Access Control Policy and JSON Serialization tabs then you'll see the same duplication.
Please see attached screen shot for more details.

Regards,
Reza
![protege_jason serialization_duplicated save and cancel](https://cloud.githubusercontent.com/assets/8367102/19545429/29d8e180-9654-11e6-96c9-fd5f981b8a09.png)

**Comment by NCIEVS** [comment]
This is not reproducible.  Please test again in your environment and close it as wontfix if the issue doesn't occur anymore.  If the refresh issue continues, please make a note of the testing environment (windows/mac/linux version, hardware/VM, so on).  For now, will label as needs investigation and future release.

**Comment by rmehri** [comment]
I have retested one time and reproduced the same behavior in tag-106. But I tested again and did not see the same issue. In this case, I would consider this issue as an intermittent problem, so the ticket should remain open for further investigation. 
Test Environment: Windows 7

Thanks,
Reza

**Comment by NCIEVS** [comment]
Are you testing on windows hardware or is it running in a VM?

**Comment by rmehri** [comment]
Windows hardware (Windows Laptop)

**Comment by bdionne** [comment]
[nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
This fix has been successfully retested and verified in tag-115.  
*Note: I still consider this issue as an intermittent problem.  For now, this ticket can be closed but it will be reopened if the same behavior occurs again. 
Thanks,
Reza

**Comment by rmehri** [comment]
Hi, 
I have noticed the same issue occurs in tag-118, edittab-03.3.  Please see attached screenshot for more details. Thereby, I am reopening this ticket for the further resolution.
OS: Windows7
Local server: 8080
Login: bob
Server Admin

![server admin_duplicate save and cancel_tag-118](https://cloud.githubusercontent.com/assets/8367102/22478889/cab8a480-e7b9-11e6-8eb1-87fb9cbec02f.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
This issue has been retested using tag-0120, edittab-0.3.7 and the same behavior did not occur.  
Thanks,
Reza
