### ISSUE TITLE
Editors Lost Save Button - 3.7.0 UAT

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#520]
@bdionne @NCIEVS  : 

**Issue Description From Editors :** 

Lost Save button when adding additional Alt-Defs to concepts (C1000076 ) 

**Logs :** 

Email With Subject 'Protege Operation Error Details & Logs 07/28/2021 12:45:21'  has logs 

Issue Is Not Reproducible at QA.

**Comment by bdionne** [comment]
This is the same issue as #521 , though here we see a null pointer exception when an attempt is made to add an `ALT_DEFINITION`.

I think what's going on in both these cases is a bad jar file. I suspect the `1.2.9` plugin in GH is not correct.


[log.txt](https://github.com/NCIEVS/nci-protege5/files/6902398/Al-1.txt)

**Comment by singhik** [comment]
Regression tested on 3.8.0-qa2 build and is not reproducible ......
