### ISSUE TITLE
Classification Flagging Issues During Merge With Identical Labels - 3.7.0 UAT

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#522]
@bdionne @NCIEVS 

**Issue Description :** 

Classifier is flagging issues based on protégé misassigning retired partner of merges to role filler values when the labels are identical when Selected Curator and Reasoner>Start reasoner  .
 
C151897; C151910; C155958  are the Concepts involved .

Inferrence Results shows two are  pointed at Preexisting Condition (C54349) instead of (C54056) and one has parent Thyroid Gland Follicular Adenoma (C3684) instead of (C3502) . 

**Logs :**

Email with Subject 'Protege Operation Error Details & Logs 07/26/2021 13:07:52' has detailed logs

**Comment by bdionne** [comment]
[log.txt](https://github.com/NCIEVS/nci-protege5/files/6902362/Liz-1.txt)

**Comment by NCIEVS** [comment]
Here's the suggested error message for the classification when domains/ranges are an issue [from EHD]:

"Classification not complete. Issues with role domain and ranges need to be fixed before performing classification."
