### ISSUE TITLE
Save Button Becomes Non-Responsive 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#523]
@bdionne @NCIEVS  : 

**Steps :** 

> Open Protege as a modeler & Create a concept .
> Logout and relogin as a Manager and Retire the concept .

**Issue :** 

Save button becomes non-responsive and hangs Protege .

**Build :** 3.7.0-qa1  & NCI Edit Tab version 1.2.9.1 

**Logs :** 

**[logs.txt](https://github.com/NCIEVS/nci-protege5/files/6934559/logs.txt)** 

![image](https://user-images.githubusercontent.com/36314371/128258897-f6c9a5e6-8eba-416f-a4fa-a57851f0fe86.png)

**Comment by bdionne** [comment]
@singhik @NCIEVS - does this happen every time or did you just see it once?

There's a suspicious null pointer in the logs, but I'm not able to reproduce it using the scenario described. @singhik I need more detail. 

When you say you logged out was that using the server menu or did you close the app?

Did you log back in as manager using "open from server" or login first then do the open of the project?

At what point did it fail? Had you already clicked retire and added the editor/design notes?

I can push a fix for the null pointer, but I'd like to first establish a test case. There's nothing that indicates this has anything to do with the modeler versus the manager. Please clarify. Thanks for the help triaging this

**Comment by singhik** [comment]
@bdionne   : 

1. Server->logout
2. Server->Login   (As Manager )
3. Failed after the 'Steps' as described above 
4. Right Click->Retire   
5. Not added editor notes , it was kept as-is from default text 
6. I am also not able to reproduce it frequently, it happened a couple of times with Automation and Functional Executions in parallel (Something which did not happen earlier) .
7. Test case does not change, it is the same as described above, it may not be easily reproducible (for me too)

**Comment by bdionne** [comment]
> 1. Server->logout
> 2. Server->Login   (As Manager )

This is from the Server menu? Are you then using `File/OpenFromServer` separately to reopen the project?

> 3. Failed after the 'Steps' as described above
> 4. Right Click->Retire
> 5. Not added editor notes , it was kept as-is from default text

Ok, so you've clicked retire and accepted the default notes, and then there's no save button. I see.

> 6. I am also not able to reproduce it frequently, it happened a couple of times with Automation and Functional Executions in parallel (Something which did not happen earlier) .

Ok, thanks, maybe if I can't reproduce it I can provide you a jar with the sys outs in it that can be run thru your automation a number of times. The exception into log is during the completion phase of the retirement, so there's something there to find

**Comment by bdionne** [comment]
This should be tested again. I the `1.3.0` EditTab plugin I did fix the null pointer. I'm not sure what was causing it but it would hang the eve button

**Comment by singhik** [comment]
Signed off on 3.8.0-qa2 build
