### ISSUE TITLE
Allow manual sorting of properties in the admin GUI

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#528]
Example: complex_properties should be sorted in a specific, editor-requested order.  Currently the admin GUI automatically sorts these properties alphabetically and does not allow rearrangement.

**Comment by safrant** [comment]
From Bob in #279 "@safrant - I can look at that GUI code, perhaps there's an easy fix for that particular editing of lists, so that they aren't sorted.

We may still want to rework that GUI if it's going to be a regular part of your life. When it was built, the programmer wanted to pretend the meta project was as generic as possible, so all the stuff we wanted at NCI was pushed into this options object and the GUI for it is quite cumbersome.

Frankly, one possibly easy change would be to just let a sysadmin type user edit the json panel directly'

________________

Editing the json panel directly would work for my reported issue.  It's not my preferred fix as the GUI handles all the formatting for me but I could live with it.

We would still need to use the GUI for creating/importing new projects I think.  And Liz would still need to use the tool to administer editor privileges.

**Comment by singhik** [comment]
@bdionne  : What is the fix applied for this change ? Do we manually update the JSON serialization for each project to obtain the desired order ?

**Comment by NCIEVS** [comment]
That was the original process.  In the current fix, you change the order of the complex properties in the Admin GUI.

**Comment by singhik** [comment]
@NCIEVS  : I don't find an option to do that when logged in as an 'Admin', unless the 'Admin GUI' is another UI which i am unaware of ?

**Comment by bdionne** [comment]
@singhik All we did in this [commit here](https://github.com/NCIEVS/metaproject-admin/commit/3751662567972519) is remove the sorting that occurs when updates are made in the GUI. There is no change to the GUI. So whatever order the properties have in the config file ought to be preserved.

We did discuss reworking that GUI completely in the future as it's incredibly awkward for editing the optional properties in a project

**Comment by safrant** [comment]
@singhik To test:  Open the complex_properties listing and see if they are in alphabetical order.  You can then add a property or two and save then see if it maintains order.  It should keep things in the order that you enter them.  Previously it had been automatically sorting them alphabetically.

**Comment by NCIEVS** [comment]
Hi @safrant , but to change the order of existing properties, do you edit them?  Or maybe delete all of them and then add them?

**Comment by safrant** [comment]
I edited them but either way should work.

**Comment by singhik** [comment]
@bdionne @NCIEVS  : On discussion with Tracy , when we add a new Complex Property, it should get added to the bottom of the list as requested/desired by the Editor, but it instead goes to top per alphabetic sort ? 

![image](https://user-images.githubusercontent.com/36314371/149024900-b470d641-8f8f-4799-ac37-a8f9549235b7.png)

![image](https://user-images.githubusercontent.com/36314371/149024983-523e71b3-6784-4d97-90b1-dcd725d6b0a1.png)

![image](https://user-images.githubusercontent.com/36314371/149025166-0f21b7a3-4ebf-4c8a-92da-8122b058c606.png)

**Comment by bdionne** [comment]
It could be sorting, or it could be it's repopulating the whole list each time you add a new one and the default is to sort them. I thought dialing the sorts would be an easy workaround for this.

@NCIEVS I recommend we push this ticket into the next release or to whenever we take on reworking this GUI. It's really not very suitable for editing optional properties and need considerable work.

**Comment by NCIEVS** [comment]
@bdionne @singhik , agreed.  Leave the GUI sorting fix for when we rework this GUI.  

@singhik , I'm not sure about this, but I'm wondering, if we edit the json config file to have the correct order, will opening the GUI and just looking at the complex_properties key will result in a resort.

**Comment by singhik** [comment]
@bdionne @NCIEVS :  Hi, i did a re-creation of steps to add complex properties in Admin GUI Panel, it still shows the ones added at the end of the list, it does not them alphabetically ?

![image](https://user-images.githubusercontent.com/36314371/187520148-fbfdb78b-73f5-4027-a812-4934e835bd3a.png)

**Comment by bdionne** [comment]
@singhik This issue, and 3 others are fixed in #556, linked to above. In #556 you'll see links to the other tickets also addressed.

We decided that many of these GUI changes were not worth the effort as we'll be redoing completely this year, so for now these features are supported using scripts, see #556 for details.

**Comment by fragosog** [comment]
Because of #556, closing, but keeping with "wontfix" tag in the project so we can fish it out.
