### ISSUE TITLE
lucene search - "enter" key to start a search for parents and filler values

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#53]
The user can enter a term in the Lucene Query Search Tab value window and hit Enter to launch the search but hitting enter when searching for a filler value or parent does not launch the search.

**Comment by rmehri** [comment]
I have successfully retested this enhancement in Tag-106. QA verified. 
Test Environment: laptop -Windows 7
This ticket can be closed.

**Comment by rmehri** [comment]
I don't see "Close" link for this ticket, so I can close it.

Thanks,
Reza
