### ISSUE TITLE
Clone Of Concepts Throwing Error As "New Concept Has no code or Preferred_Name" - 3.6.0 Production 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#531]
@NCIEVS @bdionne  :  Per Editors  

"Editor cloned C179632 Anti-BCMA/Anti-CD3 Bispecific Antibody EMB-06 to create C181676 Anti-BCMA/Anti-CD3 Bispecific Antibody WVT078, when he hit save he got an error saying “C181676 should have a code property using shortform IRI instead”

"Another Editor needed to manually add a code, Preferred_Name and label to C181676 in the Entities tab to counter that error message" 

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/7139277/Logs.txt)

**Comment by NCIEVS** [comment]
Additional info from [NT]

It happened also on 3.9.0, yesterday when the ticket was created.

And the indexing progress bar does not show up when this happens.

**Comment by singhik** [comment]
Comments from Editors on 2/25/2022 on 3.9.0-dev2 code base : 

"I used the right click menu while focused on C185580 to clone a concept once I entered the new concept data (Preferred_Name and DEFINITION) into the window and hit OK I got a popup saying I had uncommitted edits. On that warning popup I hit Cancel and another error was thrown saying "New Concept Has no code or Preferred_Name" C185628 was created with the new concept data but without a code, IRI, Preferred_Name or label. " 

"C185580 is primitive and C185628 is defined  as the concepts involved " .

Logs are sent via outlook utility with email Subject : Protege Operation Error Details & Logs 02/25/2022 12:49:26
