### ISSUE TITLE
missing rdfs:range in a property on batch edit

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#532]
If a property doesn't have a declared range then on batch edit a null pointer exception is thrown.  No damage except confusion.  This is a request to output an error message indicating that the property being batch edited needs to have a range declared.

**Comment by bdionne** [comment]
`rdfs:range` missing on a property is an edge case that needs checking during validations

**Comment by singhik** [comment]
@NCIEVS  : Hi , can you give me a list of Properties that need to have 'rdfs:range' defined ?

**Comment by NCIEVS** [comment]
Hi @singhik, ah yes.  We'll need another vocab to test this, or modify one of the properties in the vocab that you are testing with.  The NCIt declares all its annotations with an rdfs:range.  This is a general issue that we hadn't examined before.  Let me know what vocab in what server you are testing with and I'll modify one of the properties.

**Comment by singhik** [comment]
@NCIEVS  : Hi, i am using 'Thesaurus-22.01b ' asProject but it does not load currently on 4.0.0-dev1 client

**Comment by singhik** [comment]
@NCIEVS  : Hi, please align if you were able to set up a Project for this Property validation on QA Server .

**Comment by NCIEVS** [comment]
Hi @singhik , I've edited the "has free acid or base form" annotation property (code A6).  Only change was to eliminate the xsd:anyURI range from the property declaration in Thesaurus-22-04b in the QA server.  I should restore it when you are done testing this ticket, so let me know.  thanks!

**Comment by bdionne** [comment]
@singhik I think this was just to catch the null pointer. I'm not aware of requirement for a message if there is no type at all.

The other ticket, #543 is the one related tp `refs:anyURI`

**Comment by singhik** [comment]
@NCIEVS  : Please clarify the requirement ,  per above you've  mentioned **'This is a request to output an error message indicating that the property being batch edited needs to have a range declared'**  . That is not implemented in this ticket, only null pointer Exception above is handled to catch the Exception and allow the happy flow of Batch Edits of such properties missing range .

**Comment by singhik** [comment]
@bdionne @NCIEVS  : Message that gets thrown for Properties with no range f.e. A6 is ' property value has invalid type.' 

Expectation from @NCIEVS  was to have the Error Verbiage be like ' Property does not have a range and needs to have a range declared' . Please confirm on the Requirement verbiage @NCIEVS  . 

![image](https://user-images.githubusercontent.com/36314371/163341451-d43b9bbc-6f9a-464c-9422-cec87a4fa73f.png)

**Comment by NCIEVS** [comment]
@bdionne @singhik , so let's go with this for the error message:

"ERROR:  record XYZ - property declaration does not have a range" 

Don't recall if it's ERROR or Error or error, but can use the same capitalization for all errors.

**Comment by bdionne** [comment]
ok, text is changed in [1.3.9](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.9)

I also changed the warning messages to use the same format as the errors
