### ISSUE TITLE
make some identifiers editable in the metaproject admin gui

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#535]
To discuss.  

Some items probably don't need to have editable identifiers, e.g. projects and maybe roles.  But operations need to match what's in the metaproject code and currently if you create an operation in the admin gui, a guid will be assigned and it won't match what the software expects.  Plus it's good to be able to fix typos.

**Comment by bdionne** [comment]
See the comment in #534. I'm not sure we want to allow these edit. There seems to be two issues to address

1. The config file for the server needs to sync with the meta project when new operations are added. But as noted in #534 these are hardcoded in the software as constants. Adding new operation generally means code changes as well. This is different from roles, which are collections of operations, which we don want to edit as they control permissions
2. There is a need to reload an existing project, discussed in #545. I think this is what prompted the need to edit the id of the project in the GUI.

**Comment by NCIEVS** [comment]
The scenario is this:  a new operation is developed in software that can only be executed by some privileged user.  The operation in software expects to find a constant that identifies that operation associated with some user role in the metaproject.  If the admin knows that a new operation needs to be added to the metaproject s/he can create it in the admin gui and then assign it to a role; however this gui-created operation will have a uuid for its identifier and it will not match the constant that the software will act on.  The extent of this request is to be able to edit that identifier so that it matches the constant that the software is looking for.  The alternative to being able to do it in the gui is to edit the servers' config json file, which involves the same kind of edits albeit a bit more complicated because of the json structure, and a deployment by the IT group.  A typo or any other issue could happen the same in the gui or while editing the json file; however, fixing a e.g. typo would also be faster in the gui.

(Yes, we discussed editing the project identifier for "2", but the vocabulary version migration is a better solution to this problem. )

**Comment by bdionne** [comment]
> The scenario is this: a new operation is developed in ....

Yea I agree, this is the scenario, but what I'm trying to convey is that this is broken, and the solution is to not give the sysadmin user the ability to edit the identifier to fix it. To me that's creating more trouble :)

If we create a new *operation* that's fundamental to OWL, that requires support in the software and code changes, then it ought to just *appear* in the GUI as a new operation, allowing the sysadmin to add it to certain roles depending on the context.

I think the problem to fix is we shouldn't allow the sysadmin to edit certain parts of the config file. They should be static and fixed/locked. If they need to be changed occasionally (arguably this is a very rare thing), we should treat the changes as a migration.

**Comment by bdionne** [comment]
> however this gui-created operation will have a uuid for its identifier and it will not match the constant that the software will act on. The extent of this request is to be able to edit that identifier so that it matches the constant that the software is looking for.

In other words, I would remove the ability to add the operation in the GUI, it's not needed for such a rare event that also will come with lots of software changes.

**Comment by NCIEVS** [comment]
The alternative is to edit the json.  We had talked about doing this in the admin gui.  Would this work for you?

**Comment by NCIEVS** [comment]
- it ought to just appear in the GUI as a new operation
Hmm, this would work for me.  But wouldn't you need to create plumbing to modify the server's json so that the operation then appears in the admin gui?  Or it appears in the gui and then gets persisted to the json?

- sysadmin to edit certain parts of the config file
But somebody has to do it.  If it can be done as per the bullet above, that would be good.  Hopefully there aren't typos when that edit happens :-)

**Comment by bdionne** [comment]
> But somebody has to do it. If it can be done as per the bullet above, that would be good.

Yes, for sure, but perhaps it should be treated as an upgrade to what is arguably a static portion of the config file. Those operations are only there so they can be added to specific roles that govern the user permissions.

I think where we need to add functionality is how the options are handled. Those are the items tied to specific apps such as `EditTab`, and are more likely to be changed over time. The current GUI is quite cumbersome

**Comment by NCIEVS** [comment]
We'll probably need to talk this out.  My preference is to make the protege sysadmin responsible for these kinds of changes without having to involve the systems group.

**Comment by bdionne** [comment]
For sure, we should review both this and future requirements. I understand the constraint imposed by the systems group, and the need to have the protege admin make necessary changes, and I think we can resolve this without exposing internal identifiers or letting the protege admin edit values that impact the software.

**Comment by bdionne** [comment]
We can make the Json text in the admin panel editable. I was thinking we might want to only allow this for a user who also can edit the server settings. This would also address #534. 

It's a little tricky for the following reason. It's designed to be read only. When other GUI operations (.eg. deleting a project) are executed, the operation is first given to the client to execute on the server. The client then pulls the new config from the server and all the admin panels receive that event and update whatever state they have. This includes the Json read only panel, it asks the client for the new config object and serializes it out to update the text field.

So we can make it editable for sysadmin users, detect edit to the text and then create a a new path through the client to push the config to the server. I think this will work. The save button will be away of these direct edits and choose the right path. Given this enables manual edits we may also want to consider a backup strategy on the server side to handle user error, maybe just a simple catch of exceptions and restart with the old config.

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi, what is the final implementation on the GUI Panel for this ticket ?

1> 'JSON Serialization' Tab is still read-only for 'sysadmin' user .
2>'Operations' Tab does not have 'Edit' or 'Remove' buttons .

Please align on the implementation done as part of this as i am unable to guage .

**Comment by bdionne** [comment]
@singhik see #556 as this is also one the tickets mentioned there

**Comment by singhik** [comment]
This ticket is intrinsically addressed via a workaround fix per  #556  . However, as the Admin GUI is not changed ,this ticket is kept open to analyze in Future, this was discussed in Team Meeting 9/15/2022 .

**Comment by fragosog** [comment]
Adding "wontfix" as a tag to fish out later when we review the info for a future admin gui.
