### ISSUE TITLE
Intermittent Lucene search failure and inability to Build Index

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#537]
reported by Liz

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/7688091/Logs.txt)

**Comment by bdionne** [comment]
fixed in [1.2.8](https://github.com/NCIEVS/lucene-search-tab/releases/tag/lucene-search-tab-1.2.8)

**Comment by singhik** [comment]
@bdionne  : What is the fix applied for this ticket ? Lucene Search failure is not reproducible

**Comment by bdionne** [comment]
@singhik 

I'm not sure what the original scenario Liz was executing, but if you look in the attached log file above you'll see she got an `IllegalStateException`. I'm not able to reliably reproduce it either but I do see it, and when it occurs search no longer works and the indexer no longer works. Fortunately the workaround is to just restart the app. 

I've inspected the code and believe this [minor change](https://github.com/NCIEVS/lucene-search-tab/commit/5e66af15f16205604) fixes it. Adding a commit here forces the delegator to flush out buffers so that the close can occur gracefully.
