### ISSUE TITLE
Protege5-Tag 102- Open Project "foo.owl" Receiving Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#54]
Steps to reproduce:
 1) Launch protege server and client 
 2) Select Open from Protégé OWL Server and login to "http://localhost:8080"
 3) Select "foo" project then try to open and you'll see error that shows 0.
![protege_open project](https://cloud.githubusercontent.com/assets/8367102/19568122/4623bd1e-96be-11e6-8fd3-6ac5b954d1eb.png)
![protege_open project](https://cloud.githubusercontent.com/assets/8367102/19568139/504f90ba-96be-11e6-9ed3-721031833392.png)

 Please see attached screen shot for more details.

Regards,
 Reza

**Comment by bdionne** [comment]
Not sure what this screen shot is showing?

**Comment by NCIEVS** [comment]
As per [#55](https://github.com/NCIEVS/nci-protege5/issues/55), this doesn't happen in the DEV server, and it might have something to do with missing properties or configuration items in "foo".  As [#55](https://github.com/NCIEVS/nci-protege5/issues/55) will remain, open, will close this ticket with duplicate label.
