### ISSUE TITLE
Ctl-X and Ctrl-V allows multiple copies that are treated like complex props

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#541]
Reported by Liz. Command keys don't work on all platforms, and selecting multiple properties fails to add them correctly

**Comment by bdionne** [comment]
Email from Liz:

> Terry had said she tried this in the Dual Edit panel, she selected 2 Concept_In_Subset from the left side concept and cut them both, then she pasted them into the concept in the right side. She said that after the paste, the two associations displayed as if they were a parent and a child. So I replicated this in two ways. 1. From C122577, I selected both Contributing_Source atoms and hit ctrl-X. I then hit Cancel to undo the edit to C122577. Then I pasted the two atoms into C84605 and they pasted as if one was the property and one was an annotation on that property (see screenshot). Then I hit Cancel to undo the edit to C84605, since it wasn't what I wanted.

**Comment by NCIEVS** [comment]
related to #189

**Comment by bdionne** [comment]
The way the code currently works it allows multiple properties to be selected and cut, but only a single property can be copied. If multiple properties are selected copy is disabled.

If multiple objects are dropped on the target, it assumes it's because a complex property is copied, which happens a lot with these dual pane operations. The first is the complex property and the rest are qualifiers.

So in the use case Liz cites the multiple properties are treated as a complex property and it's qualifiers.

We need to just clarify with the modelers what the preferred behavior is and we can likely adjust this.

**Comment by bdionne** [comment]
This is possible to support but a little complicated by nature of complex operations. When multiples are selected the assumption is the remainder are qualifiers.

We need to clarify with modelers whether this requirement is supporting a weak split or other type of dual edit.

**Comment by bdionne** [comment]
Let's just prevent modelers from selecting multiple simple properties in dual edit and general property panels.

**Comment by singhik** [comment]
@bdionne @NCIEVS : What is/are the implementation(s) of this ticket ? 
1. If it is only to not allow multiple property selections using Keyboard, that works only in 'General' Tab, 'Dual Edit' Panel still allows multiple property Selections , so Retest Failed for this Implementation .

2. What is the expected operation protocol for Keyboard  Cut and Paste in 'Dual Edit Panel' ? For me Cut and Paste in Dual Edit does not work even for a single property within the DUal Edit panel windows of 'Source' and 'Target' . Does the clipboard Cut,Paste in Dual Edit intends to cut a cut a property from Dual Edit Panel and then Paste it  in a separate Window/operation after 'Clear or Save ' of the Existing Dual Edit panel ??

This implemenation is not clear and need clear steps to detail out expected operation(s) for Clipboard Cut Paste w.r.t Dual Edits, w.r.t Simple or Complex Properties and so on .... It is not Ready for QA

**Comment by bdionne** [comment]
@singhik The cut/paste operations are a little kludgy in protege. We've discussed this on a number of occasions. In the panel which is the target, one has to select the header field before the paste operation will work.

I'll check the general props panels used for the dual edits. I thought they are shared with the regular edit but perhaps not. That's an easy fix. You should be able to test this in the general properties tab. Please try that and confirm it works for you on Windows

As mentioned above, the fix for this is:

> Let's just prevent modelers from selecting multiple simple properties in dual edit and general property panels.

**Comment by bdionne** [comment]
@singhik - yes, thanks. It's been changed in all the dual panes in version [nci-edit-tab-1.3.7](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.7), this will also address single select in the description panels (see #189)
