### ISSUE TITLE
Redundant parent check only applies to newly added parents

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#542]
When adding a parent, curator checks that the parent being added is not redundant, it does not check that existing parents are made redundant if the new parent is more specific.

From modeler:

> Terry created Blue Gene C1000003 and Green Gene C1000004 as children of Gene C16612. I edited C1000003 and made it a child of Cancer Gene C19540. Later, I edited C1000004 by adding C19540 and C1000003 as parents without removing Gene C16612. I was able to add each parent using the add or modify parent button and hit Save and I not get any warnings.

**Comment by bdionne** [comment]
Need to discuss semantics of ok/cancel with modelers as this case differs from existing curator check

**Comment by singhik** [comment]
@bdionne : This is still reproducible on Client(4.0.0-dev1) and Edit Tab (1.3.6). Attached document for reference.

**Comment by bdionne** [comment]
@singhik Do you have the curator checks enabled? If you did then the very first edit in your doc, adding cancer_gene as a parent to test_1 will cause the warning. You would see this:

<img width="1019" alt="Screen Shot 2022-04-06 at 5 24 29 PM" src="https://user-images.githubusercontent.com/31741/162074386-d719951a-c088-4fcd-848e-23dd2cf46fb7.png">

**Comment by bdionne** [comment]
@singhik - I've tested this more and it works for me, including your scenario

**Comment by singhik** [comment]
@bdionne : It still fails for me, attached document for second iteration with plugin details and curator being enabled .

**Comment by bdionne** [comment]
@singhik This new doc appears to show the same test, that works fine for me. Please check your Preferences/Reasoner/Curator and see that the `Curator Edit Checks` are enabled. Post a screenshot also so we can see.

Have you tried other Edit Checks? Are those working? If not it indicates your preferences are not right.

**Comment by bdionne** [comment]
@singhik Here's what mine look like


<img width="714" alt="Screen Shot 2022-04-11 at 1 45 08 PM" src="https://user-images.githubusercontent.com/31741/162798787-41f4ca68-f87f-4d17-b159-6e42b90d4fd8.png">
