### ISSUE TITLE
note unknown entities in logs of batch edits of associations - annotations with anyURI range

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#543]
From [EHD]:
"During UAT I ran batches that I had just run in prod. However, the new content (codes) in prod that I had as filler values in A8 Concept_In_Subset didn't exist in the UAT. However, the values (long IRIs) were added to the 5 concepts below (see screenshot, batch file and batch output file in attachment)"

The result is valid, the filler values are anyURI references, e.g. to an external entity.

Although in prod no internal reference would produce the result observed in stage, the suggested solution at this point is to proceed with the batch edit & create the property with the input IRIs and log a notice indicating that the filler value cannot be resolved to an internal entity.

**Comment by bdionne** [comment]
The log should read:

`The filler value is not an entity in this terminology`

**Comment by singhik** [comment]
@bdionne  : I do not get this verbiage which you posted i.e. 'The Filler Value is not an entity in this terminology', instead i get 'WARNING:  -- Property has anyURI type but value does not exist' . ?

**Comment by bdionne** [comment]
@singhik That can easily changed, I don't think the value above is right either. @NCIEVS has the correct verbiage in a spreadsheet

**Comment by bdionne** [comment]
Per discussion with Gilberto, this warning has been changed in version [nci-edit-tab-1.3.7](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.3.7)

**Comment by singhik** [comment]
@bdionne : Please push Nci Edit 1.3.7 to Dev-QA repository

**Comment by singhik** [comment]
@bdionne @NCIEVS  :  and the new Warning message per your discussion  is 'Property <Pty_Code> is not identifiable' ?

**Comment by bdionne** [comment]
@singhik - the plugin is pushed to the top level. Tracy normally protest it to the higher tiers, so I guess @chaozhang-nci would handle it. 

The new warning message is as above.

**Comment by chaozhang-nci** [comment]
Update Edit-Tab plugin ver to 1.3.7 for lower tier (Dev-QA)
