### ISSUE TITLE
include creation date in metadata of vocabulary project

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#544]
When rebuilding a DB, if you forget to note the identifier of the old project, and create the new project with the same name as the old project, it's difficult to figure out which one is which. This would be a request to add the creation date in the project's metadata.  The date doesn't need to be exposed in the "open project from server" dialog.  

Related to #545

**Comment by bdionne** [comment]
This feature arose when trying to upgrade and use the same project. A [proposed](https://github.com/NCIEVS/nci-protege5/issues/545#issuecomment-1096963380) solution to #545 would remove the need for this.

Alternatively we could force the name to be unique, that would be an easy check on edit.

**Comment by NCIEVS** [comment]
Agreed, not needed with the #545 functionality.

**Comment by singhik** [comment]
@chaozhang-nci  : Hi, assigning this ticket to Chao , as it is related to server side validation during build .

**Comment by chaozhang-nci** [comment]
This is closed as similar features tested with the https://github.com/NCIEVS/nci-protege5/issues/545 and https://github.com/NCIEVS/nci-protege5/issues/556.
