### ISSUE TITLE
EditTab fails when options in server config are empty

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#546]
During initialization, EditTab throws `ArrayIndexOutOfBounds` exception, which bubbles to a "0 Open Project Error" in the open project dialog.

To reproduce modify the server config for a project and set the options field to:

`options: {}`

Then open the project from the client the normal way.

**Comment by singhik** [comment]
As this requires Server config change, assigning this ticket to @chaozhang-nci ...

**Comment by chaozhang-nci** [comment]
create a new project Thesaurus-22.04b-TKt546 at QA server, with options {}. 
tested it with no issue.
![Screen Shot 2022-04-15 at 9 13 30 AM](https://user-images.githubusercontent.com/71105663/163575061-8634eadf-003f-4f7c-9cbc-00154e7f60d1.png)
