### ISSUE TITLE
Protege5-Tag 102- Server Logout Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#55]
Steps to reproduce:
 1) Launch protege server and client 
 2) Select Open from Protégé OWL Server and login to "http://localhost:8080"
 3) Select "foo" project then try to open and you'll see error that shows 0.
 4) Click Server and select logout then receiving java errors.

Please see the attached screen shots and log file for more details.

Regards,
Reza 

[Protyege-Logout..txt](https://github.com/NCIEVS/nci-protege5/files/542228/Protyege-Logout.txt)
![protege_open project-error](https://cloud.githubusercontent.com/assets/8367102/19568388/55fd8bb0-96bf-11e6-98b8-6a7e078c8560.png)
![protege_open project](https://cloud.githubusercontent.com/assets/8367102/19568404/61cd6dfc-96bf-11e6-8fcc-07395b4d4054.png)

**Comment by rmehri** [comment]
Need to test further.

**Comment by NCIEVS** [comment]
This appears to have to do with new requirements to support NCIt editing.  Maybe the local "foo" is missing a property or configuration item.  In any case the "0" is not observed in the "foo" in the DEV server.  The client's exception is on the protege/stanford side, something about bad listeners and issues disposing the workspace.  Will label it as a bug but set it for future release.

**Comment by bdionne** [comment]
needs checking in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
This fix has been successfully retested and verified using tag-115.  Please see attached snapshots for more detail. 
Thanks,
Reza

![project_foo](https://cloud.githubusercontent.com/assets/8367102/21668488/407bb94a-d2d0-11e6-8f24-a5e2d3978935.png)
![project_foo-1](https://cloud.githubusercontent.com/assets/8367102/21668494/4cf66d1e-d2d0-11e6-9e52-7b3a603fb5c7.png)
