### ISSUE TITLE
Opening a Project Throws Error on QA Server - 4.0.0-dev1 client

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#552]
@bdionne @NCIEVS  :  Steps to reproduce : 

1. Login to Protege Client at QA Server and choose a project f.e. **Thesaurus-22.04b**  , relogin a couple of times .
2. An error is thrown ,screen shot below 

![image](https://user-images.githubusercontent.com/36314371/163079204-794fcced-49c2-4bf6-9e5a-ae30f048f8bf.png)

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/8477470/Logs.txt)

**Comment by bdionne** [comment]
This is interesting, hard to say right away. If you didn't deploy the new server code it might mess up but that would happen right away.

@singhik Please clarify what `relogin` means. Did you logout using the server menu then open from server, or did you exit the app and restart

Since this is possibly an environmental issue, I'll need the following to triage it:

 * the owl source file used to build the project
 * the server config file, or at least the snippet of the config for this project
 * the snapshot and history files on then server, essentially the directory whose name is the id of the bad project.

If you could push those to the anonymous ftp site I'll be happy to debug it

**Comment by NCIEVS** [comment]
@bdionne @singhik , i logged in 4 times to this vocab yesterday w no issues.  This morning I'm getting the same error popup as above, so far ~ 4 tries too.

1. However, if I click OK, the vocab is there, and a test edit was successful.
2. The plugins in my 4.0.0-dev1 client are the same as in the [release description](https://github.com/NCIEVS/nci-protege5/releases/tag/4.0.0-dev1)
3. The config file's "options" is not empty/null, here's the top of the config for this project:

    {
      "id": "14377429-2cc0-4a3f-be72-53aefb23673e",
      "namespace": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
      "name": "Thesaurus-22.04b",
      "description": "Thesaurus-22.04b for Release 4.0.0-dev1 test",
      "owner": "chaozhangAdmin",
      "imports": [],
      "options": {
        "deprecated_child": [
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P201"
        ],
        "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97": [
. . . .

The only difference between yesterday & this morning was that I was in the office, and this morning I'm on VPN.  Can't imagine this is it, but I thought I'd mention it.

**Comment by bdionne** [comment]
@NCIEVS - 

When you login, did you bring the app up or was it a logout, followed by open from server?

Also, so the open dialog completed and went away before you saw this error dialog? There's nothing in this attached log above, can you upload the log you have where you saw this?

It's not clear to me where this exception is coming from, possibly from the server as the client never throws this. It might be coming from the dialog close if the index updating thread is hanging on to something.

**Comment by bdionne** [comment]
@singhik As above, I need information from you and Chao to further triage this. I reassign tickets to others when I am waiting on information. Please provide the information I request and then feel free to pass the ticket back to me

**Comment by singhik** [comment]
@bdionne  : I don't have anything else to share, as far as re-login goes, one can try either/or via File->Exit or CTRL+C on cmd or Server->Logout . I don't have access to QA server or an FTP to send owl file,server config file or server history  .

**Comment by NCIEVS** [comment]
@bdionne Yes, I exit protege and relaunch it for each trial.  No, the open dialog isn't going away (yesterday it was), after closing the error message the open dialog is still there & have to close it manually.  

I'm attaching the server log with entries from this morning, the only thing there is an exception after my test edit, saying that it doesn't recognize the project ID, even though the entry is the same that shows up when you open the project.

[server-log-from-AM-on-20220413.txt](https://github.com/NCIEVS/nci-protege5/files/8483053/server-log-from-AM-on-20220413.txt)

The client log doesn't show any exceptions, but here it is too.

[protege.log](https://github.com/NCIEVS/nci-protege5/files/8483103/protege.log)

**Comment by bdionne** [comment]
@singhik 

> I don't have anything else to share, as far as re-login goes, one can try either/or via File->Exit or CTRL+C on cmd or Server->Logout .

Thanks, this is good to know. As much detail as possible on these fails always helps narrow things

@NCIEVS Thanks, that's helpful. That server side error looks odd, but seems irrelevant.

As I mentioned to @singhik there is little I can do on this ticket until I have the data needed to run it locally and try to reproduce.

**Comment by NCIEVS** [comment]
@bdionne I think @chaozhang-nci needs to fetch that data.  I don't know where is the owl file that he used for the project.  @chaozhang-nci for the snapshot, you'll have to shut down the server before copying that file to a zip; probably best is to zip the entire directory for the project.  You'll also need to include server config json in the package for @bdionne and post it in the sFTP server.  Let me know if you have questions.

**Comment by bdionne** [comment]
>  No, the open dialog isn't going away (yesterday it was)

@NCIEVS sorry I meant to say the little progress bar that shows the various stages .... "retrieving snapshot" ... "initialize menus"...

Did that go away?

**Comment by NCIEVS** [comment]
@bdionne Ah, OK.  Not before the error dialog pops up.  Once you click OK on the error dialog then the progress bar goes away.  The dialog that remains open is the one that shows the available vocabs from the server.

**Comment by bdionne** [comment]
@NCIEVS By any chance did you see what stage that progress bar was at?

**Comment by bdionne** [comment]
I think the issue is some code somewhere is dereferencing an Optional instance and it's throwing a `NoSuchElement` error

This should be readily reproducible locally if I can see your project and data

**Comment by NCIEVS** [comment]
@bdionne the bar was about 90-95%.  Hopefully @chaozhang-nci can do a data package today.

**Comment by chaozhang-nci** [comment]
created data file v4.0.0-dev1-22.04b.zip and uploaded to protege FTP site.

**Comment by singhik** [comment]
From @NCIEVS  : " OK, this same vocab in the dev server is coming up without an error dialog.  In both the laptop over VPN and the office desktop.

But both laptop & desktop proteges are still showing the error dialog in the qa copy of the vocab.  Tried deleting the .fileprefs and that didn't solve it.  "

**Comment by bdionne** [comment]
@NCIEVS 

[This line here](https://github.com/NCIEVS/lucene-search-tab/blob/master/src/main/java/org/protege/editor/search/lucene/RemoveChangeSetHandler.java#L80) is the source of the `NoSuchElement` exception. The `Optional` class throws this on a `get()` if no value is present. Not sure why this is happening yet but this is the source

**Comment by bdionne** [comment]
This is fixed in [nci-edit-tab-1.4.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.4.0). It requires [lucene-search-tab-1.3.0](https://github.com/NCIEVS/lucene-search-tab/releases/tag/lucene-search-tab-1.3.0) and the protege [4.0.0-dev2](https://github.com/NCIEVS/protege/releases/tag/4.0.0-dev2) build.

This also fixes #552 and #434

**Comment by singhik** [comment]
@bdionne @NCIEVS @chaozhang-nci  : Currently failing to load on QA with 4.0.0-dev2 build and Edit Tab 1.4.0 .

![image](https://user-images.githubusercontent.com/36314371/164332533-07d64616-3864-416e-a23f-b14d14a674d6.png)
[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/8525743/Logs.txt)

**Comment by NCIEVS** [comment]
Different error, maybe related or not (we are still dealing with the cert complication), this one is in DEV.  

![image](https://user-images.githubusercontent.com/7783321/164427382-2504dc3b-b622-41c4-b884-ce79d886a895.png)

The output to the console (skipping the top of the output):

2022-04-21 05:36:49.413 [main] INFO  ProtegeApplication    
2022-04-21 05:36:55.766 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node org.protege.editor.owl.client
2022-04-21 05:36:55.766 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node org.protege.editor.owl.client
2022-04-21 05:36:55.767 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node SERVER_LOCATIONS
2022-04-21 05:36:55.767 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node SERVER_LOCATIONS
2022-04-21 05:37:09.291 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node PREFERRED_TAB_NAMES
2022-04-21 05:37:09.291 [AWT-EventQueue-0] INFO  FilePrefs    Instantiating node PREFERRED_TAB_NAMES
2022-04-21 05:37:26.844 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.844 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.847 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.847 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.847 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.847 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.848 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.848 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.848 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:37:26.848 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:38:24.802 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false
2022-04-21 05:38:24.802 [SwingWorker-pool-2-thread-1] INFO  SessionRecorder    Changes equal ignored changes? false

**Comment by bdionne** [comment]
@singhik not sure what this is, presumably you've already logged in so it's not the cert. 

The log file indicates it's failed to load the snapshot.. Perhaps it's somehow out of sync with the server? If you look at the project id you can find the directory in the client's filesystem and deleted it. This will force it to fetch the snapshot again from the server.

@NCIEVS Your error is server side for sure.

If you can't resolve this, bundle up the QA server side and config as you did before recently and I'll look at it locally.

**Comment by NCIEVS** [comment]
@bdionne I just repeated with the same client in QA and I got the same error as I saw in DEV (same popup, but no error logged to the console).  I didn't get the error that @singhik got in QA above.

**Comment by singhik** [comment]
@NCIEVS @bdionne : I can reproduce NCIEVS's error on QA server : 

![image](https://user-images.githubusercontent.com/36314371/164520058-0508c969-a049-4d33-96a9-870fb42c1190.png)

**Comment by NCIEVS** [comment]
Yes, this was working Tuesday and yesterday in the morning at least.

**Comment by chaozhang-nci** [comment]
It should work again on QA after updated QA server with certs. Please continue the tests.

**Comment by singhik** [comment]
This is not-reproducible on 4.0.0-dev2 on multiple instances of multiple logins, hence closing the ticket
