### ISSUE TITLE
Concurrent Edits Not Getting Auto Updated Unless Manual Indexing Is Done

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#554]
From Editors : Protege Client version 4.0.0 

• Which operation failed ? : 
<Editor's Input>: Indexing of new loaded content 
• Approximately what time did this failure occur ? : 
<Editor's Input>: 9:40 am 
• Description or sequence of steps followed ? : 
<Editor's Input>: Editor created a set of new terms (with different fruits in their names) in a batch load. After this load, I logged in and searched for the term Apple, I didn't get her new content in the query results until I selected Lucene > Build index 
• Concepts involved ? : 
<Editor's Input>: see attached screenshots 
• If necessary, please include the state that the concepts were in at the time of the incident, Screenshot is good if possible ? :
<Editor's Input>: primitive 
• Outcome ? : 
<Editor's Input>: Had to select Lucene > Build index but wouldn't have known to do that without her notification that she ran the batch load

![image](https://user-images.githubusercontent.com/36314371/169097211-ee28e403-07c2-47b3-b2d7-ca7b3f78b78b.png)

Logs are in the Email with Subject Line : Protege Operation Error Details & Logs 05/18/2022 09:50:04

**Comment by singhik** [comment]
Editor's Input : Sample batch files are sent via Email with Subject : "Protege Operation Error Details & Logs 05/18/2022 09:50:04"

" Yep, I believe Editor's batch load was followed by what happened in my ticket, then I did a batch edit of FULL_SYN (>1200 terms) and I think Terry did another batch load in there as well. Then I did a batch delete of ~250 FULL_SYN.
 
Another thing I noticed was after the FULL_SYN batch was that I had to reindex to find the new FULL_SYN but I wasn’t very patient and reindexed within a minute or two of the batch (this also may have coincided with Terry’s second batch load so the index was challenged). The index may take a few minutes to catch up.
 
None of this is really a showstopper, but we will need to tell the editors to reindex more our current recommendations say, so more than once a week, maybe even once a day. "

**Comment by singhik** [comment]
@NCIEVS @bdionne  :  We huddled up to do concurrent user testing today on 4.0.0-dev3 Client on QA server : 

- User1 did Batch Load with 334 Concepts on Instance1 .
- User1 logged in to Instance2 to see the changes, he was able to view & search .
- User2 saw 'Updates' counter incremented to 1 after User1's updates.
- User2 was neither able to 'Updates' the changes, nor was able to see/search User1's updates .
- Exceptions were generated everytime 'Updates' or 'Build Index' was clicked by User2 .
- Below are the logs of the Exceptions.
- User1's fileprefs counter 'SERVER_CHANGES_ALREADY_PROCESSED' had 165.
- User2's fileprefs counter 'SERVER_CHANGES_ALREADY_PROCESSED' had  164.

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/8787946/Logs.txt)

**Comment by singhik** [comment]
@NCIEVS  @bdionne : Results of concurrent Testing on  4.0.0-dev4 Client on DEV server :


- User1 connects with two instances to the database, waits until both instances have indexed the DB. And exits Instance2 to represent an offline user.
- User1 did Batch Load with 334 Concepts on Instance1 .
- User1's batch finished, the concepts were observable in tree. It took a minute for these concepts to be searchable.
- User1 logged in to Instance2 on the same machine (different filesystem) to see the changes, he was able to view in hierarchy but not in search. Instance2 required full indexing for the concepts to be searchable.
- User2 saw 'Updates' counter incremented to 1 after User1's updates.
- User2 Clicked on 'Updates' , after the local copy was updated, User2 was able to see User1's concepts in hierarchy as well as Search them , it did take a while to complete 2310 changes .
- User3 connects with a fresh instance of protege, i.e. has not seen or indexed the DB yet, unlike Instance2 of User which had already seen the DB.
- User3 sees the batch concepts, and can search them.
- User2 did updates like adding complex property, adding simple property, retire concepts at his end.
- User 1 did see 'Updates' counter incremented to 6 on his Instance1 & his Instance2, after clicking on it ,changes were updated and User1 was able to see as well as Search User2's changes & edits .
- User2 did a Batch Load , User1 clicked on 'Updates' and was able to View and Search the concepts created by User2.
- User1 did some simple property edits on Instance 1, re-logins to Instance2, was able to search the concept with the added/edited Property .
- User1 created Instance3,  which behaved exactly like User3's fresh instance.
- One exceptions was seen by User1 (instance1) but not by User2 during this process.
- One of the issue which was observed by both User1 & User2 was for the Lucene Search not navigating to the NCI Hierarchy Tree when a Searched concept is clicked, in the case of User1 likely because the indices were out of sync.

**Comment by bdionne** [comment]
@singhik What's the status of this one? It's in 4.0.0, and marked ready for QA. Is it done?

**Comment by singhik** [comment]
@bdionne : Last comments for this Ticket mentions about the Testing done . The navigation to the searched concept issue worked fine for me as individual users, i would close this ticket for now.
