### ISSUE TITLE
Add scripts to support remote get/put of server configuration

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#556]
Several issues with metaproject-admin UI have been identified are quite difficult to address in the UI due to it's design, so we decided to use shell scripts to allow [fetching](https://github.com/NCIEVS/protege/blob/master/protege-desktop/src/main/env/platform-independent/get_config.sh)  and [updating](https://github.com/NCIEVS/protege/blob/master/protege-desktop/src/main/env/platform-independent/put_config.sh) the server config file directly. Upon a successful update the server will reboot itself. This addresses the following issues:

#534 #535 #544 

The scripts have a few variables at the top that can be modified for whatever environment.

**Comment by singhik** [comment]
@chaozhang-nci  : Hi, assigning the ticket to Chao as it deals with server side execution of shell scripts for build

**Comment by bdionne** [comment]
It's your call @fragosog I'm fine either way, I don't have a strong opinion either way.

I would think the simplest, which will be more maintainable in the future, is go with what works on the OS that's most likely to be used by this script, and modify as need for other platforms when and if it ever becomes an issue.

**Comment by fragosog** [comment]
Well, these two scripts are meant to be run remotely (prod, stage), I've got linux, and @chaozhang-nci has Mac.  I can do the edits and pass them around or push them to a repo after I've tested them.

**Comment by cmoid** [comment]
ok, I'm happy to do it also if you like, but you should test it on your linux. The linux version is already there in the commented out line above.

that last phrase: `tr -d "\n"` seems redundant if you use the `-n` ?

**Comment by bdionne** [comment]
ok, I'm happy to do it also if you like, but you should test it on your linux.

The linux command is already there in the commented out line above. This last phrase:

`tr -d "\n"` looks redundant if you already have the `-n` in there. That's the part that fails on the Mac.

**Comment by chaozhang-nci** [comment]
Tested on both DEV and QA servers.

After changed to 

> AUTH=`echo ${res%?} | tr -d "\n" | openssl enc -base64 -A`

Both get/put scripts are working  as sh script on either Linux and Mac OS. 

On any terminal where can access the backend server host, modify the following parameters, get script will retrieve the server-configuration.json from the host. After modify the server-configuration.json file, put script will update the host with the revised configuration.

s#!/bin/sh
protocol=https
host={ server hostname }. // example nciws-d699-v.nci.nih.gov
port=9090
user=accountAdmin	
password=accountpassword
input/out filename

**Comment by chaozhang-nci** [comment]
Tested on both DEV and QA servers.

**Comment by chaozhang-nci** [comment]
Closed.
