### ISSUE TITLE
Improve logging on curator crashes

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#558]
When curator crashes due to bad data that leaks in ( .eg. #557), if possible log the class is being classified to enable modelers to review terminology and possibly fix

**Comment by singhik** [comment]
@bdionne @Fragosog: Hi, not sure how to insert bad data in the Thesaurus for the curator to catch post classification ? Is it a Unit Test only ticket ?

**Comment by bdionne** [comment]
> Hi, not sure how to insert bad data in the Thesaurus for the curator to catch post classification ? - @singhik 

You can disable all the curator checks and then make edits that violate these. They will then show up as inconsistencies in the inferences panel and/or will be logged

**Comment by singhik** [comment]
Fixed and Tested on 4.2.0-dev1 client
