### ISSUE TITLE
Protege-Tag-Tag103-Warning Message Displays When Selecting a Class

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#56]
Steps to reproduce:
1) Launch protege server and client 
2) Select Open from Protégé OWL Server and login to "https://nciws-d699-v.nci.nih.gov:9090" with "eric" login.  Open "ncit-owl2-v3" project.
3) Select "NCI Edit Tab" tab
4) Click owl: Thing and try to select a Class then you'll receive a warning message.

*Note: this warning message occurs almost throughout every class in this page when using "foo" project more but less in this project ncit-owl2-v3.

Please see the attached screen shots
![edit tab-warning msg-1](https://cloud.githubusercontent.com/assets/8367102/19622629/dc3e48a0-987b-11e6-995c-78d59a373cfe.png)
![edit tab-warning msg-2](https://cloud.githubusercontent.com/assets/8367102/19622633/ef5dadfe-987b-11e6-9192-ab7a08deb48d.png)

 for more details.

Regards,
Reza

**Comment by bdionne** [comment]
This is the intended behavior, classes are required to have an rdfs:label

**Comment by rmehri** [comment]
The warning messages are all over..

Regards,
Reza

**Comment by rmehri** [comment]
Hi, 
Please see attached zip file to retrieve the video clip for more details of this issue as well as the reported screen shots previously.

Thanks,
Reza
[Protege_Video_Warning MSG_Issue1.zip](https://github.com/NCIEVS/nci-protege5/files/569835/Protege_Video_Warning.MSG_Issue1.zip)
