### ISSUE TITLE
Server Failed To Commit Data - 4.1.0 Client 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#561]
@bdionne @fragoso :  Hi, Getting a server side exception error while trying to save a concept . 

![image](https://user-images.githubusercontent.com/36314371/191134769-5cc93eb5-53c4-4350-be54-6334c700611b.png)

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/9602848/Logs.txt)

**Comment by bdionne** [comment]
Is this reproducible? Does it happen on all saves or just this once? If on all saves is it a particular edit or was it just this one?

Do you have the server log? The attached log seems to be from the client and contains nothing of interest.

If it happened this once it could be a network error.

Thanks in advance for providing more information

**Comment by singhik** [comment]
@bdionne  : Hi, the logs attached were from the server end. This issue was related to the user permissions which logged in to perform edits, hence closing this ticket
