### ISSUE TITLE
UI locks when errors occur in configuration

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#566]
When edit tab initializes, and there are properties specified in the config that are missing from the terminology, sometimes the modal popup dialog that displays the missing properties hangs, displays nothing and locks the app.

This same behavior also happens at times when there are connection problems and the autoupdater tries to retrieve `HEAD`

Reported on windows. In this case we know the terminology is missing props from the config file.

**Comment by fragosog** [comment]
Possibly related to #569

**Comment by bdionne** [comment]
ready to test in [1.5.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.5.0)

**Comment by chaozhang-nci** [comment]
It was tested with some required properties missing in the project configurations. 
The protege client is still running, however, the related functionalities would not work.
After fixing missing property, all work well.
