### ISSUE TITLE
Documentation of properties for project configuration in metaproject

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#568]
As a preliminary to making some project configuration properties optional, it would be of interest to classify the current project properties according to where they are used (e.g. general business rules, merge, retirement, so on).  This is a documentation ticket to update the [appropriate table](https://github.com/NCIEVS/nci-protege5/wiki/Configuration:--server-and-project#metaproject-key-value-pairs-needed-to-configure-project) in the wiki.  

This would also help external users figure out what they need to declare for their project and in their vocabulary if they don't require all the EditTab's functionality.

**Comment by chaozhang-nci** [comment]
The wiki page about project configuration properties is very clear.
