### ISSUE TITLE
Optional project configuration properties

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#569]
Related to #568 & #486 & #566.  Although some vocabulary properties are currently absolutely required, e.g. label, PT, fullSyn, code, others are not, e.g. definition, semantic type, or are only required to support special operations (e.g. merge, retirement) that a third-party user might not do (e.g. merge, retirement - at least initially when building a vocabulary).  

This request is an enhancement so that such optional properties don't require that the appropriate key in the project configuration file (info in the [wiki](https://github.com/NCIEVS/nci-protege5/wiki/Configuration:--server-and-project#metaproject-key-value-pairs-needed-to-configure-project)) be either a) present, or alternatively, b) if present, to have a value (value empty string or null).

**Comment by bdionne** [comment]
This is handled in [1.5.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.5.0)

If any properties are missing in the server config file, edit tab will stay running and try to degrade as best it can. Some complex operations such as retirements might not work at all but the plugin will not crash.

**Comment by chaozhang-nci** [comment]
tested with empty project config or partial config json file.
The project could be viewed at edit tab.
