### ISSUE TITLE
protégé wedges when opening project

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#572]
Report from modeler:

> I logged in and opened the project. Once everything opened up I did a search for contains CFHR, I selected CFHR1 Gene from the search results but the Edit tab view was empty (see screenshot). I tried using the hierarchy to navigate to other concepts but the Edit tab view did not change.

The attached log indicates failure to initialize properties results in null pointer. This code is currently undergoing considerable refactoring so this issue may disappear on its own. 

Note: the log also shows earlier failures to to socket timeouts, network issues.

[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/11289429/Logs.txt)

**Comment by kondareddys2** [comment]
This has been verified on QA for 4.4.0 milestone release.
