### ISSUE TITLE
protege server outage

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#573]
User reports server was down on 5/1 from 10:00 - 10:30 a.m. See attached server log

User reports:

"While I was able to log in after the baseline export, other editors have had issues logging in. Some users reported seeing a message about a 502 error. So I logged out and attempted to login again but once I log in the project selection window is empty (see screenshot below). It looks like we may need to do a server restart to clear up this issue."

Log indicates some editing while server paused for squashing. Also indicates successful restart, than subsequent restart again, presumable by systems group at 10:54

[protege.log](https://github.com/NCIEVS/nci-protege5/files/11399963/protege.log)

**Comment by singhik** [comment]
Closed as is not reproduceable in 4.4.0 Milestone Release Client
