### ISSUE TITLE
versionIRI in client-server mode

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#574]
Can't set the ontology versionIRI from the GUI in client server mode.  On commit I get a "projectId is null" dialog, and on subsequent autoupdates I get the "...remote head revisionprojectId is null"

![image](https://github.com/NCIEVS/nci-protege5/assets/2165212/3f3331bd-2812-4d0f-bec8-69425aed5692)

If I clear the textbox and then click through all the autoupdate notices, I can still edit and Save classes.  But can't while the versionIRI textbox has (uncommitted) text in it as the projectId is null.

**Comment by bdionne** [comment]
I've never tried this. Does it work in protege without plugins like EditTab?

When I tried it and looked at the `uncommitted changes` it's pretty weird:

<img width="795" alt="Screenshot 2023-06-26 at 4 42 30 PM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/dd3d9bcd-326b-484b-9b8c-0be8b877d7a5">

**Comment by fragosog** [comment]
I saw the same, and then switched to copy-pasting to decrease all those keyboard actions.  I haven't tried it without the edit tab in our build.  I tried it in base protege in file mode and that worked.  If I can connect to the server, I'll try client-server in our build w/o all the tabs.

**Comment by bdionne** [comment]
I looked at that code, and it seems to have never been implemented. Interestingly other updates on that panel work fine, like editing the date. I suspect it was never done as part of the client/server work, like many things, and we added bits like dates and prefixes later.

We can easily prioritize fixing this is if it's urgent
