### ISSUE TITLE
Make EditTab configurable

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#581]
Add a new preferences panel for EditTab that enables/disables all the various complex operations. Additionally allow all the annotation properties used with these complex operations to be configurable.

The goal is to enable a modeler to start with a new terminology in the form of an owl file and then configure how EditTab is used. The results of the configuration process will be a JSON file that serves as input to the metaproject admin application. It will be used to create a new project.

**Comment by bdionne** [comment]
Here are screenshots of preferences tab for EditTab:

<img width="883" alt="Screenshot 2023-11-30 at 10 10 58 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/a484f431-6a50-43bc-a83b-020e9c86114b">
<img width="881" alt="Screenshot 2023-11-30 at 10 09 05 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/4674350f-5b54-4a12-bb6f-f69b2dcf2940">
<img width="886" alt="Screenshot 2023-11-30 at 10 07 03 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/7767c6d4-d3aa-4722-987b-108019bb96f5">
<img width="884" alt="Screenshot 2023-11-30 at 10 06 34 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/f4eb1ba9-a022-4911-a0c7-f20ed7860842">
<img width="886" alt="Screenshot 2023-11-30 at 10 06 15 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/ac25f11a-03fc-4bf8-85da-5e551508b584">
<img width="882" alt="Screenshot 2023-11-30 at 10 05 09 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/198c34a4-a908-4ca6-85bc-56df435a5e66">
<img width="885" alt="Screenshot 2023-11-30 at 10 04 51 AM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/6169032b-d01a-4605-8f82-a24ba74044de">

**Comment by bdionne** [comment]
EditTab preferences now comes up immediately. After the user is finished configuring the various operations, a JSON file containing all the options, suitable for input to the metaproject admin application is written out to the filesystem.

<img width="713" alt="Screenshot 2024-01-11 at 2 32 22 PM" src="https://github.com/NCIEVS/nci-protege5/assets/31741/90c5393c-1de8-47c2-a32c-180720eb9258">

**Comment by bdionne** [comment]
This is ready to test in the plugin tag [1.5.0](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.5.0)

This feature is still subject to more development, and is designed for use outside NCI and the Thesaurus work.

The idea is as follows, and this is a possible test scenario:

 * open an owl file in file mode
 * In the EditTab preferences, select properties for all the various complex operations. These properties should correspond to what we use today
 * specify a json file to persist to and click ok.
 * use the option json file to create a new project using admin application
 * go back to protege and open the new project from the protege server
 
An additional test is to login as a modeler once a new project is created and see that the modeler *cannot* edit the edit tab preferences

The idea is to allow managers to define which props they wish to use in complex ops, then create concurrent projects using those configurations. This helps with the curation of the modeler's work.

**Comment by chaozhang-nci** [comment]
it was tested with SmallBase owl file.
