### ISSUE TITLE
Modify protege owl client/server to better manage metaproject

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#583]
The client will no longer fetch the entire server configuration on login. Instead it will only fetch what is needed for the user to open a specific project and it's associated permissions with respect to editing.

**Comment by bdionne** [comment]
Changes to the client server and protege core are mostly internal and there is nothing explicitly to test, other than to make sure nothing is broken.

The client code no longer retrieves the entire config. The login for both protege and the meta admin app no longer have an admin checkbox, as these apps are separate.

In this first release the server side files will be the same. In the next release they will start to be broken out separately.

**Comment by singhik** [comment]
CLosed as Regression on 4.4.0 Milestone Release found no issues w.r.t Project Loading or other Functional Issues defined as per Regression Set
