### ISSUE TITLE
Namespace lost in project after editing

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#585]
When editing a project using the metaproject-admin application, the namespace field of the project gets replaced by the default.

Steps to reproduce:

 * run the metaproject-admin app
 * edit any project, making a minor edit .eg. the description field
 * save the config, which reboots the protege server
 * see the namespace field is now "foo"
 
This bug has been there since we added namespace support for imports. The field is not supported at all in the GUI, probably should be.

[fixed in meta-admin-1.0.4](https://github.com/NCIEVS/metaproject-admin/commit/da36e82482e96f50844d1ed015e545c41f606bc3)

**Comment by chaozhang-nci** [comment]
tested, not saved as foo
