### ISSUE TITLE
Retire Concept Workflow Is Not Working - 4.4.0

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#587]
**Steps to Reproduce ::**

- Create a concept class and right click to Retire .
- Post clicking on Retire, the 'Retire' Button remains disabled ,not proceeding with Retire workflow .

**Retire a concept :** 
![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/b155c683-9661-4b95-8ae1-8d6cecf46c9f)

![image](https://github.com/NCIEVS/nci-protege5/assets/36314371/18b30364-5bad-43ff-9fdf-dfdd36621d29)

Logs are attached :: 

[logs.log](https://github.com/NCIEVS/nci-protege5/files/14948978/logs.log)

**Comment by bdionne** [comment]
This is fixed in the newest EditTab plugin, [1.5.2](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.5.2)

**Comment by singhik** [comment]
Re-tested,Fixed and Passed on 4.4.0 Code base with 1.5.2 Edit Tab Plug-In.
