### ISSUE TITLE
Locking navigation pane not working correctly

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#59]
Another item. I am not sure I like that the hierarchy has (editing) next to the item being edited. The timing on this label is not intuitive. It doesn’t appear when you add a new property, or move between editing subtabs, but it does appear when you hit Save. At that point, the edits have been saved, I am not sure the reminder is necessary then. Additionally, the user can no longer navigate away from the concept being edited once they have added a property either by clicking another class in the hierarchy or by double clicking on a search result, so it is difficult to lose the concept that is being edited (the way you could in earlier snapshots).

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
The fix for this issue has been retested and verified in tag-116, Edit Tab-03.1.
Thanks,
Reza
