### ISSUE TITLE
Protege-Tag103-Edit Tab-Receive Java Error When Login to Server Toggled In and Out

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#61]
Steps to reproduce:
1) Launch protege server and client 
2) Select Open from Protégé OWL Server and login to "https://nciws-d699-v.nci.nih.gov:9090" with "eric"  login. Open "foo" project.
3) Log out from server then log back into the server.
4) Select "NCI Edit Tab" tab
5) Notice that there are no classes displayed under OWL: thing
6) Click owl: Thing and you'll receive java error. 

Please see the attached screen shots and log file for more details

Regards,
Reza
![nci edit tab_select owlthing_error](https://cloud.githubusercontent.com/assets/8367102/19823275/c70bfefa-9d35-11e6-90ba-52100de3abf6.png)
[NCI Edit Tab_Select OWLThing_Error.txt](https://github.com/NCIEVS/nci-protege5/files/559476/NCI.Edit.Tab_Select.OWLThing_Error.txt)

**Comment by rmehri** [comment]
This problem still exist.

Regards,
Reza

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
This fix has been successfully retested in tag -109. 
This issue can be closed.  

Thanks,
Reza
