### ISSUE TITLE
Protege-Tag-103-Reloading Page Causes Java Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#62]
Steps to reproduce:
1) Launch protege server and client 
2) Select Open from Protégé OWL Server and login to "https://nciws-d699-v.nci.nih.gov:9090" with "eric" login. Open "ncit-owl2-v3" project.
3) Go to Preferences/General and set the Search type to Lucene Search  
4) Go browser and click file and select Reload and the Java error occurs. 
![protege103_reload_error](https://cloud.githubusercontent.com/assets/8367102/19840121/aa54b8c4-9ec5-11e6-94d9-2bf091d8e9d5.png)
[Protege_Tag103-Reload_Error.txt](https://github.com/NCIEVS/nci-protege5/files/560750/Protege_Tag103-Reload_Error.txt)

Please see the attached screen shots and log file for more details

Regards,
Reza

**Comment by rmehri** [comment]
Issue

**Comment by bdionne** [comment]
This needs review, not sure this menu item is relevant anymore. If not it can be removed from the software

**Comment by NCIEVS** [comment]
Agreed, This works in file mode, but I don't see the use of it in production, particularly client-server (perhaps for troubleshooting under some scenarios?).  The menu item can be "hidden" or disabled.  The workaround is simple, restart protege.  Will relabel "future release" and "bug".

**Comment by rmehri** [comment]
Hi, 
The reload is still an issue when using my local and development server. 
Tag-120, Edit Tab 0.4.2
Please see attached log file for more details.

[Tag-120-Reload_Error.txt](https://github.com/NCIEVS/nci-protege5/files/778329/Tag-120-Reload_Error.txt)

Thanks,
Reza

**Comment by bdionne** [comment]
this menu will be disabled, this is not a current issue

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your feedback!  I will retest this issue in the future release when it is ready for QA. 
Reza

**Comment by NCIEVS** [comment]
Menu item has been removed.

**Comment by rmehri** [comment]
Hi, 
Yes  this has been retested and the "Reload" link  is not showing in the protege browser. 
Thanks,
Reza
