### ISSUE TITLE
Protege103-Collapsing the Hierarchy Do Not Work Properly 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#63]
Steps to reproduce:
1) Launch protege server and client 
2) Select Open from Protégé OWL Server and login to "https://nciws-d699-v.nci.nih.gov:9090" with "eric" login. Open "ncit-owl2-v3 or foo" project.
3) Expand the top hierarchy of the classes, then try to collapse them and does not work. 

Please see attached screen shot for more details. 

Regards,
Reza

![protege103-collapsing classes do not work properly](https://cloud.githubusercontent.com/assets/8367102/19840490/6d9b5426-9ecd-11e6-833f-35215e6f8c2a.png)

**Comment by NCIEVS** [comment]
@rmehri , looking at the tree, the last concept is flagged as "(retiring)" suggesting that you were in the middle of an action where you are not allowed to "go away" until you either finish it or cancel/clear out of it.  Please check again.

**Comment by rmehri** [comment]
This ticket has been successfully tested in tag 105 last week. The same issue does not exist anymore.
Thanks,
Reza
