### ISSUE TITLE
viewing large definitions is awkward

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#65]
Provide multiple rows for the definition value.  When visiting a new concept the definition is scrunched to one row.  Being able to expand that with a single click, or set a configuration to x rows per definition, would be useful.

**Comment by bdionne** [comment]
This is partially [fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106) in this next tag, needs review

**Comment by rmehri** [comment]
Can you please elaborate more on the fix details and steps for this issue? 

Thanks,
Reza

**Comment by bdionne** [comment]
Originally if a definition was too large to fit in a column, it was truncated and could not be read.

Now the definitions wrap onto multiple lines and the column is adjusted to fit

**Comment by NCIEVS** [comment]
PS  The data was not truncated, only the view of the data.

**Comment by rmehri** [comment]
Great! 
Thanks very much for all of your feedback.
Reza

**Comment by rmehri** [comment]
This issue has been successfully retested in latest Tag 107. 
This issue can be closed.
