### ISSUE TITLE
Add preferred name text and code to other tabs in edit tab

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#66]
Hi
 
Would it be possible to have the banner with the Preferred Name and Code, which appears on the General tab of the concept editing view, appear on the other tabs (Complex Properties and Description) as well.

 
Thanks,
Liz

**Comment by rmehri** [comment]
This fix has been tested and verified using tag-112.
Please see attached screen shot for more detail.
Thanks,
Reza
![preferred and code](https://cloud.githubusercontent.com/assets/8367102/21370013/ba0cbf98-c6d7-11e6-98cb-6804bdf6a3d8.png)
