### ISSUE TITLE
duplicates without "qualifiers" show up in complex property table in "by code" owl file

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#68]
This is based on our initial "by code" conversion; there might be data issues to deal with as well.  In addition, from @hahndane :  

"The duplication of Complex Properties sans qualifiers appears to only affect existing data. I added 2 FULL_SYN to Initials C25536 and they don’t appear to have duplicates. I will have to log out and log in again to see if the lack of duplication persists."

**Comment by bdionne** [comment]
pretty sure this is a conversion issue, I've reloaded the by code content from the original file and it appears to contain all these dups.

I think this has something to do with making the "term" qualifier of the complex property the value itself

**Comment by NCIEVS** [comment]
this got fixed along the way during normal refactoring.  will close
