### ISSUE TITLE
assignment of defaults to properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#69]
for instance, in the dropdown selection menus for complex property editing, highlight "NCI" for a "def source" by default.

**Comment by NCIEVS** [comment]
Agreement on creation of a new annotation property "default", asserted on the declaration of the annotation property which uses that default.  Intended for use (so far) in properties where the range of the property is an enumeration expressed in a custom datatype.

**Comment by rmehri** [comment]
I have retested this successfully. QA verified.

*Note: Please let me know if I can close this ticket since I am not the owner of this issue.
Thanks,
Reza

**Comment by NCIEVS** [comment]
NOTE, the default is stated on the datatype, not on the property.

**Comment by NCIEVS** [comment]
Yes, if it says "ready for QA" you own it and can close it when fixed.
