### ISSUE TITLE
denoting annotations as required when used to annotate property values

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#72]
Discussed & have agreed to create an annotation property "required" with datatype xsd:boolean to flag annotation properties used to annotate property values.  When "required" is asserted on the declaration, that annotation must have a value before the edit is deemed valid.

**Comment by rmehri** [comment]
Can you please provide steps to reproduce for this fix? Thanks!

**Comment by rmehri** [comment]
Hi, 
Can you please elaborate more for this fix? So I can verify the fix.  
Thanks!
Reza

**Comment by bdionne** [comment]
Complex properties have annotations on them, sometimes called qualifiers. Some of these are required and some not. The ones required have a `required` annotation on them, with a boolean value set to true.

**Comment by rmehri** [comment]
Ok, thanks.   This fix has been retested and verified.
