### ISSUE TITLE
resizing the height of table cells on a change of fonts

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#74]
Changing fonts in protege works for the text in the complex property tables, but the height of the cells doesn't change and the text can get cropped

**Comment by singhik** [comment]
@NCIEVS : Hi, The only option for changing font size i could find is via File->Preferences->Renderer Tab, but changing that Font size increases the font size of entire Protege client but not of Complex Properties ,How else to increase the Font size of Complex Property table values ?

**Comment by singhik** [comment]
@NCIEVS : Hi, I did that but it only appears to change the Font of 'Value' column of Complex Properties, other Column font remains as-is. As far as re-sizing of the column goes, the data under 'Value' column does not get cropped  ...

Original Font Size ::

![image](https://user-images.githubusercontent.com/36314371/38103875-91e4aad0-3355-11e8-8437-f33bf217ded2.png)


Increased Font Size:: Changes data only for column 'Value' and the data does not get cropped 

![image](https://user-images.githubusercontent.com/36314371/38103958-d032a83c-3355-11e8-8cb7-a2c29baf1a27.png)

![image](https://user-images.githubusercontent.com/36314371/38103971-d9f507ac-3355-11e8-9c20-e0d65993e410.png)

**Comment by singhik** [comment]
New ticket for Windows specific issue for the same is created  as https://github.com/NCIEVS/nci-protege5/issues/374

**Comment by bdionne** [comment]
Not fixable in current protege
