### ISSUE TITLE
Legacy formats for dates

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#76]
use existing format or migrate data?

**Comment by bdionne** [comment]
This is for the editors

**Comment by NCIEVS** [comment]
The current dev version of the Edit Tab uses xsd:dateTime which is more information than we need to track editing dates.

The feedback that I got was that it would be fine to use the xsd:date format (YYYY-MM-DD) vs our legacy abbreviated format (YYMMDD).  Interestingly, owl2 doesn't (explicitly?) support xsd:date.

**Comment by bdionne** [comment]
The dates are now all formatted as `ISO_LOCAL_DATE` in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)
