### ISSUE TITLE
failure to find properties in report writer & lucene export selection boxes

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#78]
When selecting the slots to export in Report Writer, DEFINITION and FULL_SYN did not come up while I was typing them in, I had to scroll the list manually to find them.  It might be related to the [cell renderer](https://github.com/protegeproject/protege/issues/565)

**Comment by NCIEVS** [comment]
PS We do have a workaround, scroll down the list

**Comment by bdionne** [comment]
Nothing specifically [fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118) in this build, however we have a new `CellRenderer` and the problem no longer occurs on `OS X`

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified using tag-118, edittab-0.3.4.  Please see attached zip file for the screen shot and the report for more detail. 
[lucene-export.zip](https://github.com/NCIEVS/nci-protege5/files/748334/lucene-export.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
This issue seems to be acting up again.

**Comment by bdionne** [comment]
This turns out to be two issues in Protege:
 - sort is case sensitive
 - the find entities method retrieves all classes

**Comment by rmehri** [comment]
Hi, 
This fix has been retested using tag 126, nci-edit tab -0.5.1. Please see attached reports and screen shot for more details. 

![reportwriter](https://cloud.githubusercontent.com/assets/8367102/24381837/78d9eec0-1320-11e7-9e84-a3eec40436a5.png)
[lucene-export-ReportWriter.xlsx](https://github.com/NCIEVS/nci-protege5/files/874052/lucene-export-ReportWriter.xlsx)
[lucene-export-1.xlsx](https://github.com/NCIEVS/nci-protege5/files/874054/lucene-export-1.xlsx)
[lucene-export-Export to CSV.zip](https://github.com/NCIEVS/nci-protege5/files/874057/lucene-export-Export.to.CSV.zip)

Thanks,
Reza
