### ISSUE TITLE
persist user set defaults for table columns

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#79]

**Comment by bdionne** [comment]
Itendra: Does this refer to the 'NCI Edit Tab->Edit->Complex Properties' Table ? Is the requirement to fix the columns so that they can not be changed/sorted ?

The user can reorder the columns in these complex property tables. The enhancement is to persist changes the user makes so that when they click and close the app and then bering it back up the settings are preserved

<img width="1016" alt="screen shot 2018-02-16 at 10 02 59 am" src="https://user-images.githubusercontent.com/31741/36313841-f62f51f4-1300-11e8-9d16-68890810ce51.png">

**Comment by singhik** [comment]
Reorder works fine for ALT_DEFINITION and FULL_SYN complex properties before and after login , but fails for DEFINITION complex property . Please find attache
[Issue 79.docx](https://github.com/NCIEVS/nci-protege5/files/1732900/Issue.79.docx)
d screen prints for reference ..

**Comment by bdionne** [comment]
Could you please enumerate the steps to reproduce what you see. This seems to work fine for me and I can't quite see in the code how it would work for all the props except `DEFINITION`. Below is a screenshot where I've reordered both `FULL_SYN` and `DEFINITION`. I then closed the app, brought it up again and see the order is maintained

<img width="1016" alt="screen shot 2018-02-17 at 10 41 11 am" src="https://user-images.githubusercontent.com/31741/36342642-4f84238c-13cf-11e8-8d16-2bf40435aff7.png">

**Comment by singhik** [comment]
Hi,
     Please find below the steps, i re-executed today and the re-order did not remain for all three complex properties (ALT_DEFINITION,FULL_SYN,DEFINITION) .

1. Navigate to 'NCI Edit Tab' for Protege Client V2.2.0 .
2. Select any class from the Tree hieararchy .
3. Navigate to 'Edit' tab on the left and re-order columns for all three Complex properties (ALT_DEFINITION,FULL_SYN and DEFINITION) .
 Expected: After re-logging the order of all the three complex properties should remain as was re-ordered before per Step 3

Actual : After re-logging, the order of all three complex properties does not remain intact per Step 3 .

before relogging ::

![image](https://user-images.githubusercontent.com/36314371/36432793-0f769fc0-1629-11e8-9ac5-5739513a523a.png)

After relogging ::

![image](https://user-images.githubusercontent.com/36314371/36432843-2b3636e4-1629-11e8-9e82-f8a2915b495d.png)

**Comment by bdionne** [comment]
@singhik - please clarify what you mean my `relogging`. Are you using the server menu to logout and then login again or are you clicking the icon in the upper right corner to completely close the window and then restart the app again?

This works fine for me, I'm wondering if it's a windows/OS X issue

**Comment by singhik** [comment]
Hi Bob, I shut down protege client and then open it again to perform re-login ....

**Comment by bdionne** [comment]
I still can reproduce this, but I suspect I know the issue and I'm adding a workaround that should work on windows. It will be in the next release

**Comment by bdionne** [comment]
Fixed in 2.2.0-beta2

**Comment by singhik** [comment]
@bdionne : Hi, Unable to re-test on 2.2.0-beta 2  due to missing plugin jar in Edit Tab ..

**Comment by bdionne** [comment]
@singhik - should be there now

**Comment by singhik** [comment]
Hi,
     Re-order of columns for Complex Properties have been QA Verified prior and post logging ...

Re-ordered Complex property columns per below ::

![image](https://user-images.githubusercontent.com/36314371/36687227-fb120416-1af6-11e8-8384-382427a28d69.png)


Checking for Re-ordered columns post relogin :: Order of columns remains as before 

![image](https://user-images.githubusercontent.com/36314371/36687244-07aba614-1af7-11e8-85cb-3f74a265b41b.png)

**Comment by singhik** [comment]
@bdionne : Hi Bob, I have noticed below w.r.t reorder of columns , need your input if this is Expected : 

When re-order of columns is done, the values of those columns do not move with Column headings, f.e. 

Before re-order ::

![image](https://user-images.githubusercontent.com/36314371/36738147-d7737616-1baa-11e8-92da-2ce1a58e1523.png)

After re-order :: Only Column heading has been changed, value does not move with Column 

![image](https://user-images.githubusercontent.com/36314371/36738239-120d5d3c-1bab-11e8-8404-c4ef097724aa.png)


However, if i re-login after shutting down , only after a relogin, the Values move corresponding to the correct Column headings ::

![image](https://user-images.githubusercontent.com/36314371/36738461-8d0811da-1bab-11e8-87c6-09efb4ae66db.png)

**Comment by bdionne** [comment]
@singhik - ha, lol, I"m amazed we all missed this. Perhaps the recent changes broke it. Anyway I can reproduce it, fix will be in the next plugin upgrade since it's in edit tab

**Comment by bdionne** [comment]
@singhik - this is fixed when you update edit tab to `0.7.8`

**Comment by singhik** [comment]
@bdionne : Hi Bob, when i launch Protege Client QA for V2.2.0 beta2 , i do not see an option to Auto-update Edit Tab to 0.7.8 ?
I still have it as 0.7.7 ...

![image](https://user-images.githubusercontent.com/36314371/36905799-4486fe36-1e02-11e8-83c7-1b190b7ed11c.png)

**Comment by bdionne** [comment]
@singhik - is that Plugin Registry the one you normally point to for QA? I usually don't push plugins to the cubit download site until production. If you point to my [autoupdater](https://raw.githubusercontent.com/bdionne/autoupdate/master/plugins.repository) it will work, though I'm not sure if that's the one you use. Tracy will know

CC: @safrant

**Comment by safrant** [comment]
Thanks.  The autoupdater address works.

**Comment by singhik** [comment]
@bdionne : Hi Bob,  The Column values move with the Column headings but the order of the columns does not remain as re-ordered after re-login . Please find below the screen prints ::

Before re-ordering ::

![image](https://user-images.githubusercontent.com/36314371/36907545-e0d82860-1e06-11e8-9188-3ce1a52cb910.png)

Re-ordering Columns ::

![image](https://user-images.githubusercontent.com/36314371/36907570-f0d0b188-1e06-11e8-9882-ea549de3a681.png)


After Re-login , Columns do not remain in the order as were re-ordered ::

![image](https://user-images.githubusercontent.com/36314371/36907628-138377d8-1e07-11e8-998c-708fea111bc2.png)

**Comment by bdionne** [comment]
@singhik - can you clarify what you mean by re-login? I think I need to see this on your machine

**Comment by singhik** [comment]
@bdionne : Hi Bob, with re-login i mean to shut down Protege Client and re-instantiate the client . 
Surely, we can connect and will show you  , will be sending a webex connect at 11:30 ,if that works for u .....

**Comment by bdionne** [comment]
that works for me

**Comment by singhik** [comment]
Hi All,
          Below are the final results for this Issue from QA ::

1. Re-order of Columns works and remains in the re-ordered setup only if Protege is shut down using 'File->Exit' and Using Windows Cancel Button (X). -----(PASS)
2. Re-order of Columns does not work when Protege is Shut down using 'Ctrl+C' in Client Console .----(FAIL)
3. Re-ordering of Columns does change Column headings as well as Column values .----(PASS)

Attached is the document with detailed screen prints of entire thread of this issue ....

[Issue 79.docx](https://github.com/NCIEVS/nci-protege5/files/1776038/Issue.79.docx)
