### ISSUE TITLE
save button needs to show confirmation dialog

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#8]
`EditTab`

**Comment by NCIEVS** [comment]
Confirmation dialog showing up after the Save action completes.  Labeling ready for QA & v1 release.

**Comment by rmehri** [comment]
Retested this fix and verified that a user should receive save confirmation after saving action. For example,
saving a new class "Class saved successfully".  This ticket can be closed. Please see attached snapshot.
Thanks,
Reza

![save_confirm](https://cloud.githubusercontent.com/assets/8367102/21087063/653d8ed6-bff0-11e6-9c9c-172c6404e256.png)
