### ISSUE TITLE
lucene search fails on exact matches

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#81]
searching over rdfs:label for "oncogene" with an exact match should return only classes with an rdfs:label that has the string "oncogene". Currently it returns all the strings that contain oncogene

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
I have used "exact match - string" and retested this fix successfully. This ticket is QA verified. 

*Note: I am not the owner of ticket, please let me now if I can close this ticket.
Thanks,
Reza

**Comment by NCIEVS** [comment]
Yes, if it's "ready for QA" you own it and can close it.  Remember to add the "fixed" label.

NOTE, the "exact" on string is truly exact & case-sensitive.  There's another [ticket](https://github.com/NCIEVS/nci-protege5/issues/91) for an enhancement for case-insensitivity.

**Comment by rmehri** [comment]
Here are some of the search examples for case -sensitive and case-insensitive strings.  that I used for "exact match-string" and "exact match-token".

Property: label
Exact match-string:
1) ACD Gene ==> 1 match 
2) AcD gene ==> 0 match
3) Agonist ==>1 match
4) agonist ==> 0 match
---------------------------
Property: label
Exact match-token:
a) ACD Gene ==> 1 match 
b) AcD gene ==> 1 match  (returns ACD Gene)
c) Agonist ==>48 matches
d) agonist ==>48 matches

*Note: based on steps b and d, the case-insensitivity for exact match token search exists 
Thanks,
Reza

**Comment by rmehri** [comment]
I don't see close option to close this ticket.
