### ISSUE TITLE
editing a class doesn't always flag "editing" in the tree widget

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#82]
Some kind of refresh/event issue, where beginning to edit a class doesn't always result in the class being flagged with "(editing)" in the tree widget.

**Comment by NCIEVS** [comment]
There is no data corruption so I will slate it for a future release.

**Comment by NCIEVS** [comment]
There might be also some interaction with the other panels in protege.  I noticed that if I do some edits in the Annotation Properties & Entities tab (which require a manual update/commit), when I go back to the NCI Edit Tab the previously selected class is flagged with "(editing)" in the tree widget.  I need to Clear changes (even though there are no changes to the class that require a Clear or Save).

**Comment by NCIEVS** [comment]
Yup, just repeated the above (except that the Save & Clear buttons are not visible - perhaps some rendering issue in linux mint like with the lucene indexing progress bar).  Until this gets fixed, we need to remember to exit Protege after fiddling with the properties.

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
The fix has been retested in tag 111 and verified that when editing a class the "Save & Clear" buttons are  visible before exiting the editing class page.
 Please see attached snapshots.

Thanks,
Reza
![class_edit-1](https://cloud.githubusercontent.com/assets/8367102/21299557/cab4b4a4-c56a-11e6-818e-2de432369439.png)
![class_edit-2](https://cloud.githubusercontent.com/assets/8367102/21299563/d99b82ae-c56a-11e6-9c4f-f15bae209169.png)
