### ISSUE TITLE
preferred name and code in a more visible location

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#83]
Would it be possible to have the banner with the Preferred Name and Code, which appears on the General tab of the concept editing view, appear on the other tabs (Complex Properties and Description) as well.

**Comment by bdionne** [comment]
see #131 also

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

The preferred name, IRI fragment identifier, and code, now appear in a separate header of the edit tab, above the other tabs

**Comment by rmehri** [comment]
This fix has been tested and verified using tag-112,NCI Edit Tab-0.23
Please see attached screen shot for more detail.

Thanks,
Reza
![preferred and code](https://cloud.githubusercontent.com/assets/8367102/21403389/934d1976-c78a-11e6-9713-e6e3276089c8.png)
