### ISSUE TITLE
failure to conduct complex edits in "by code"

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#85]
in "by code", cannot do a Complex Edit (Copy, Split, Merge). Select ComplexEdit tab, click Copy (or Split; I didn’t try Merge), drag in a concept, add new Preferred Name in popup box and click OK. Nothing happens, no errors on the console.

Note, this might have been fixed when the rdfs:label was chosen for display (and IRI only used for fallback).

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
This fix has been retested and verified the split, copy (Clone), and merge in tag-116 using project by code.
Please see attached screen shots for more details.
Thanks,
Reza

![activity_code_merge](https://cloud.githubusercontent.com/assets/8367102/21783597/16cf6cf4-d686-11e6-8046-55f7c4303b61.png)
![test_code_copy](https://cloud.githubusercontent.com/assets/8367102/21783600/1894f5c2-d686-11e6-98a7-df5bcaefe53a.png)
![test_code_split](https://cloud.githubusercontent.com/assets/8367102/21783696/7ed6a34e-d686-11e6-91d1-68875cfe459a.png)

**Comment by NCIEVS** [comment]
Need to verify that the vocabulary this was tested with was a "by code" vocabulary.

**Comment by rmehri** [comment]
This fix was retested and verified in tag 116. Please see attached screen shots for more details. 
Thanks,
Reza

![bycode-merge](https://cloud.githubusercontent.com/assets/8367102/21815664/82a127e2-d72b-11e6-96b2-16d3b2748792.png)
![bycode-split](https://cloud.githubusercontent.com/assets/8367102/21815671/84d2e564-d72b-11e6-9242-b6cbfc2bb678.png)
![bycode-clone](https://cloud.githubusercontent.com/assets/8367102/21815676/88919d80-d72b-11e6-8df0-8213aec00e64.png)
