### ISSUE TITLE
Tag 105 - Lucene Search -Stop Search Not Working

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#88]
Steps to reproduce:
1.launch server and client protege5
 2)Use Eric user and Login to "https://nciws-d699-v.nci.nih.gov:9090"
2.In Add Basic Query use the following search criteria:
 Property =rdfs:label
 Query Type =End with
 Value = "d"
3.Click Search and the search query keeps going with no result
4. Click "Stop Search" and it does not work.
 Please see attached screen shot for more details.

Regards,
![protege5_tag 105-stop search not working](https://cloud.githubusercontent.com/assets/8367102/20447714/6c96d5f6-adae-11e6-8c00-cae725ab67b8.png)
![protege5_tag 105-stop search not working-2](https://cloud.githubusercontent.com/assets/8367102/20447726/72f96fd0-adae-11e6-9106-a391dcf80dd0.png)
Reza

**Comment by NCIEVS** [comment]
Was the search run against no vocabulary?  The IRI displayed on the protege title bar doesn't match any that we have in the DEV server.

**Comment by rmehri** [comment]
Yes. This is a negative search test to see how the application response.  Also, is a use accidentally searches against no vocabulary then it should be stopped/or cleared.

**Comment by bdionne** [comment]
I see, so an additional step is to select the default ontology, which is not indexed? Kind of an edge case but I can fix this if it's readily reproducible

**Comment by bdionne** [comment]
ok, actually it does stop the search, you can see the search button become enabled again on the bottom. If you switch the ontology back to one that's indexed it works fine.

The only thing it doesn't do is clear the progress bar in the the top right. Is there other behavior you see? Is it causing the app to freeze or anything?

**Comment by NCIEVS** [comment]
Tested this item.  The client doesn't freeze and you can continue working, e.g. load a vocabulary from the server.  The "indexing" notification doesn't close, however, until you do a new search.  Will label this as a bug for a future release.  

Again, only the "indexing" notification widget is behaving inappropriately, it should stop (and hide).

**Comment by bdionne** [comment]
I spent some time on this, the issue is that the default small ontology that protege always loads up is never indexed. This causes a null pointer when you query it. This exception is swallowed in the search manager so it appears to hang. As noted if one switches back to the open ontology it's all good.

I'll revisit this swallowed exception when I consolidate the search tab/plugin/csv-export repos

**Comment by NCIEVS** [comment]
Question, should we get rid of the Stop button.  Searches are fast.

**Comment by NCIEVS** [comment]
Disable Stop button until there's an ontology loaded.

Check to see if "Stop" can be dropped.

**Comment by bdionne** [comment]
this is working fine now. The search is fast enough that it's hard to see the stop button. If you create a complex query with lots of clauses, including negated and nested clauses, you can create a query that takes a while to run. I tried stopping it several times and each time it stopped, whic you can tell by looking at the number of results returned
