### ISSUE TITLE
persist protege properties per protege instance rather than per machine

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#89]
at least in windows various protege properties get stored in the registry and make a mess when you run multiple versions of the the desktop application.

**Comment by bdionne** [comment]
ready in [revision history](https://github.com/bdionne/revision-history/releases/tag/revision-history-1.0.0). This requires the `nci-1.006` tag

**Comment by rmehri** [comment]
Hi, 
Would you have reproducible steps for this issue?  
Thanks,
Reza

**Comment by bdionne** [comment]
run two separate instances of the protege software on the same machine and see that each can be customized separately

**Comment by rmehri** [comment]
Thanks for your feedback! Retested this issue using  nci-1.006  tag.  
1) Ran two separate instances of the project software on  my local server.  Modified the Look and feel for each client separately.  No errors occurred
2) Ran Three separate instances of the project software on  my local server.  Modified the Look and feel for each client to Protégé, Window and Cross-Platform .No errors occurred
Please see attached screenshot for more details.
![issue-89-1](https://cloud.githubusercontent.com/assets/8367102/25915961/17b5f47a-3591-11e7-98c4-0e273b5c7065.png)


Thanks,
Reza
