### ISSUE TITLE
better handling of long strings

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#9]
When you add a FULL_SYN as a complex property and paste in a long string meaning to modify the string so you don’t have to copy and paste each value, it runs off the page (see attachment full_syn run off.PNG). (I pasted in PRGS; GARTF; Phosphoribosylglycinamide Formyltransferase/Phosphoribosylglycinamide Synthetase/Phosphoribosylaminoimidazole Synthetase Gene. The individual synonyms are separated by semi-colons.) There is a slider at the bottom but when you type in a string of syns and want to trim them for each entry, this set up is not ideal.

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
I don't see any .PNG attachment.  Can you please elaborate more on this issue so I can validate the fix?

Thanks,
Reza

**Comment by bdionne** [comment]
sorry I don't have the screenshot any longer.

From the description above it appears the issue relates to cutting and pasting long strings from other places into the values when creating `FULL_SYN`.

**Comment by rmehri** [comment]
Based on this issue's description and development's comment above, the fix has been retested and verified in tag 116-edit tab-0.3.1.  Please see attached screenshots for more details.
Thanks,
Reza

![adding_full_syn-1](https://cloud.githubusercontent.com/assets/8367102/21818147/b9723d98-d734-11e6-8b76-846d588337bf.png)
![adding_full_syn-2](https://cloud.githubusercontent.com/assets/8367102/21818151/bc54c0c6-d734-11e6-8954-2c5c438871c0.png)
