### ISSUE TITLE
case difference in /user/.protege directory name

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#90]
Protege creates a .protege directory in the user's home.  Lucene uses that directory to store the indices; however, lucene spells it .Protege with upper case P.  In windows it doesn't matter, but in linux the user winds up with two protege directories under /home/user/.  Minor issue and can wait until the protege config gets modified so it's [associated per instance](https://github.com/NCIEVS/nci-protege5/issues/89)  rather than system-wide.

**Comment by bdionne** [comment]
Itendra: This test needs to happen on a Linux box and would need detailed steps to reproduce duplicate directory entry creations, would checking for .protege folder in Linux box suffice ?

That sounds right, if I recall windows is not case sensitive. You could follow the same steps as in #344

**Comment by singhik** [comment]
This Test needs to be performed on a Linux machine, assigning it to Tracy Safran @safrant  ....

**Comment by safrant** [comment]
configuration allows me to place indexes wherever I wish.  Tested on Mac.
