### ISSUE TITLE
'exact match - string' is case-sensitive

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#91]
The workaround for now is trivial, begin the query string with upper case as most (if not all) of the terms in the NCIt use title case.  This is then an enhancement request for a future release.

**Comment by rmehri** [comment]
Hi,
I have retested and verified this fix using  nci-1.005, Lucene Search Tab 1.0.3 and Edit Tab -0.5.8.
Please see attached screenshots for more detail.

![issue-91-exact match-string -token-1](https://cloud.githubusercontent.com/assets/8367102/25454161/8569a492-2a99-11e7-9e9d-cc5864a64f95.png)
![issue-91-exact match-string -token-2](https://cloud.githubusercontent.com/assets/8367102/25454167/8c746f38-2a99-11e7-9297-df1ddcc9bd3c.png)

Thanks,
Reza
