### ISSUE TITLE
duplicate terms and definitions are being allowed in the complex properties tables

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#92]
Tested with both "full_syn" and "definitions", but it probably happens with other properties.  (For the definitions, I edited the time stamp to match the existing def that I was duplicating.)

**Comment by bdionne** [comment]
fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
The fix has been retested in tag 111 and verified that no duplicated  "full_syn", "definitions, are allowed.
Please see attached snapshots.

Thanks,
Reza

![alt_definition-duplicate-2](https://cloud.githubusercontent.com/assets/8367102/21299016/652f9860-c565-11e6-9c12-d8267cb1c68b.png)
![alt_definition-duplicate-1](https://cloud.githubusercontent.com/assets/8367102/21299020/71a64dc8-c565-11e6-8f25-d99871510c52.png)
![duplicate_1](https://cloud.githubusercontent.com/assets/8367102/21299024/7c96c140-c565-11e6-9516-b05873d4d1ab.png)
![duplicate-2](https://cloud.githubusercontent.com/assets/8367102/21299027/87443244-c565-11e6-8cbe-110fa68192b4.png)
