### ISSUE TITLE
duplicate NCI PT is being allowed in the complex properties panel

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#93]
The user is warned that the duplicate exists; however, the newly created duplicate "takes" and is saved.

**Comment by bdionne** [comment]
This is fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107) but there are still a couple of edge cases

**Comment by rmehri** [comment]
I have successfully retested this fix in tag-110 . This ticket can be closed. 
Please see attached snapshot for more detail. 
Thanks,
Reza

![property duplicate-1](https://cloud.githubusercontent.com/assets/8367102/21150756/1d41dbe8-c12e-11e6-9452-1dfafbe91b6f.png)
![property duplicate-2](https://cloud.githubusercontent.com/assets/8367102/21150766/2983f29c-c12e-11e6-88d6-d868eedca6ff.png)
