### ISSUE TITLE
typo in export to csv dialog

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#94]
The "Field delimiter" label shows up as "File delimiter".

**Comment by bdionne** [comment]
[good eye](https://github.com/bdionne/csv-export-plugin/commit/096680244321b841b71c8375f2570ed29c07500b)

**Comment by bdionne** [comment]
This was just a typo and is fixed in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
The fix has been retested and verified successfully in tag-107.  This issue can be closed. 

Thanks,
Reza

![export to csv file](https://cloud.githubusercontent.com/assets/8367102/20841067/79f3b5c0-b880-11e6-87b6-30117fc091a1.png)
