### ISSUE TITLE
codes created with embedded 'null' strings when the delimiter is set to null in the metaproject

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#96]
e.g code = Cnull1123null

**Comment by bdionne** [comment]
I think this was fixed [here](https://github.com/bdionne/protege-server/commit/923e8283666fd035308b)

Which tag are you running on the server?

**Comment by NCIEVS** [comment]
That's probably it, I'm running 103 on the server.  Will set up the latest server build & retest.

**Comment by NCIEVS** [comment]
Yup, upgrading the server did the trick.  Clear the bug, label as invalid, and close.
