### ISSUE TITLE
add new complex property doesn't automatically appear

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#97]
Choose a class that only has a FULL_SYN and add a definition, the new table doesn't appear until you save, navigate away from the class and then return

**Comment by YinghuaXu2** [comment]
Fixed in commit https://github.com/bdionne/nci-edit-tab/commit/d9d2f9854d2973bf7eddb2d4adb4ef6d4ba24cf7 #

**Comment by bdionne** [comment]
available in [nci-0.109](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.109)

**Comment by rmehri** [comment]
This fix has been successfully retested in tag -109.  This issue can be closed. 
Please see attached snapshot for more detail. 
Thanks,
Reza

![issue-97-tag109_fixed](https://cloud.githubusercontent.com/assets/8367102/20934497/56c02cba-bba9-11e6-8408-3fbb52acaa9a.png)
