### ISSUE TITLE
default property value on class creation might not be the same value as on class edit

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#98]
For example, on creation of a class, a full_syn needs to be added with a source of NCI and a term type (term-group) of PT.  But the term type would likely be SY when adding a new full_syn to an existing class.  If SY is made the default term type to cover the majority of the edits, then the wrong term type is added at class creation; vice-versa, if the PT is selected as default, class creation full_syns are good, but the least likely term type (PT) is then presented to the user on edits.  

For now, will set the default term type to PT, but a future enhancement might be to declare defaults to use at class creation, and declare defaults for edits on pre-existing classes.

**Comment by NCIEVS** [comment]
Feedback during dual-editing from [NT]:  "In an existing, or newly created concept, when you go to add additional Full_Syns, the ‘Adding Properties’ window defaults to ‘PT’; it would be nice if this defaulted to ‘SY’ as it does in Protégé 3."

**Comment by bdionne** [comment]
There will be two new annotations on annotation properties, `default_on_create_class` and `default_on_edit_class`

These will used both when interactive editing and for batch load/edit

**Comment by rmehri** [comment]
Hi,
 This ticket will be retested and verified when the protege QA server is ready.
 Thanks,
 Reza

**Comment by rmehri** [comment]
Hi, 
I have retested this ticket using tag 1.0082 on local and QA server s and don't see the defaulted value for term type =  ‘SY’ .  Please see attached screenshots for more details. 

Note: this ticket will retested when QA server is ready with latest tag



![qa-server -issue-98-1-adding additional full_syn](https://user-images.githubusercontent.com/8367102/29895473-37c50102-8da7-11e7-80eb-8fc81e0729d2.png)

![local server-issue-98-1-adding additional full_syn 2](https://user-images.githubusercontent.com/8367102/29895530-65a4519a-8da7-11e7-9b9f-4a1564d761e1.png)
![local server-issue-98-1-adding additional full_syn 1](https://user-images.githubusercontent.com/8367102/29895534-68c28b44-8da7-11e7-94b0-938b36f4ae31.png)
![local server-issue-98-1-adding additional full_syn_dual edits](https://user-images.githubusercontent.com/8367102/29895536-6a8702fc-8da7-11e7-8b48-a28e284d2db7.png)

**Comment by bdionne** [comment]
For this to work (see comment above), you need to set a `default_on_edit_class` annotation on the enumeration type used for the `Term Type`.

If the context is creating a new class then there needs to be a `default_on_create_class` value.

Otherwise it will fall back to the value of `default`, which in this case is `PT`, for legacy purposes

**Comment by safrant** [comment]
I am testing the creation of these properties on Dev now.  Does this look right?
![default_on](https://user-images.githubusercontent.com/2364871/29927857-87445a1e-8e35-11e7-8f3b-1009a24adc96.jpeg)

**Comment by NCIEVS** [comment]
It looks right, yes.

**Comment by safrant** [comment]
Do these new properties need to be added to the metaproject options as well?

**Comment by safrant** [comment]
OK.  Procedure I followed (will need to be done on upper tiers)

On "Annotation Properties" tab, create the two new properties.  Note:  do not give them P codes, just create them straight as http://....Thesaurus#default_on_edit_class and Thesaurus#default_on_create_class

On "Entities" tab, under datatypes, add the two new annotation properties to the following datatypes
term-group-enum  (create:PT   edit:SY)
term-source-enum  (create:NCI   edit:NCI)
def-source-enum  (create:NCI  edit:NCI)

Under "Server" click "Commit" and enter a commit comment.

Close and reopen the client.

**Comment by rmehri** [comment]
Hi, 
 This fix has been retested on QA server and local server using latest tag 1.0083 and Client-V2.1.10083.
 Please see attached screenshot and for more details.

![issue98](https://user-images.githubusercontent.com/8367102/29948045-c2b0e668-8e7a-11e7-9b7d-ab76bf0064c9.png)
![issue98-1](https://user-images.githubusercontent.com/8367102/29948047-c453b90a-8e7a-11e7-946b-700d36f53564.png)

Thanks,
Reza
